/* =====================================================================
   DESAFIO DO DIA — microaprendizagem (≈ 2 minutos)
   Cada desafio é uma situação curta de empresa com alternativas,
   a resposta explicada ("Por quê?"), um exemplo "Na prática" e a
   ferramenta relacionada (ver conteudo/problemas.js), que leva ao
   conteúdo completo.
   Campos: id, areas (do Modo Estágio), pergunta, opcoes, correta
   (índice), porque, pratica, ferramenta
   ===================================================================== */
window.DESAFIOS = [
  { id: "d01", areas: ["pcp", "producao"], ferramenta: "capacidade",
    pergunta: "Você trabalha no PCP. A demanda aumentou 20%, mas a capacidade da linha continua igual. O que você analisa primeiro?",
    opcoes: ["A carga em cada recurso comparada com a capacidade, para achar onde falta hora", "O preço de venda do produto", "Quantas pessoas faltaram no mês passado", "A cor das embalagens mais vendidas"], correta: 0,
    porque: "Antes de propor hora extra ou investimento, é preciso saber **quanto** falta e **onde**. A comparação carga × capacidade por recurso mostra o gargalo e o tamanho do déficit.",
    pratica: "Na Doces Serra, a carga da envasadora foi a 109% da capacidade; as outras etapas ficaram abaixo de 90%. Hora extra só na envasadora resolveu o pico, sem custo nas demais." },
  { id: "d02", areas: ["producao", "processos"], ferramenta: "gargalo",
    pergunta: "Uma linha tem três etapas com capacidades de 60, 45 e 70 peças/hora. Quanto a linha produz por hora?",
    opcoes: ["175 peças/h", "58 peças/h (a média)", "45 peças/h", "70 peças/h"], correta: 2,
    porque: "A capacidade da linha é a da etapa mais lenta: o **gargalo**. As outras etapas ou ficam ociosas ou acumulam estoque.",
    pratica: "Comprar uma máquina mais rápida para a etapa de 70 peças/h não aumentaria em nada a produção. O ganho está em aumentar a etapa de 45." },
  { id: "d03", areas: ["suprimentos", "logistica", "compras"], ferramenta: "curva-abc",
    pergunta: "O estoque está alto e você tem 800 itens cadastrados. Qual é o primeiro passo mais eficiente?",
    opcoes: ["Reduzir todos os itens em 20%", "Fazer a curva ABC para achar os poucos itens que concentram o valor", "Parar de comprar por um mês", "Contar todos os itens toda semana"], correta: 1,
    porque: "Poucos itens costumam concentrar a maior parte do valor. A **curva ABC** mostra onde a redução traz resultado rápido e onde vale mais controle.",
    pratica: "Em muitas empresas, cerca de 20% dos itens respondem por cerca de 80% do valor. Ajustar lote e estoque de segurança só dos itens A já libera boa parte do capital parado." },
  { id: "d04", areas: ["suprimentos", "logistica"], ferramenta: "estoque-seguranca",
    pergunta: "A demanda de um item varia muito de um dia para outro e o prazo do fornecedor é de 4 dias. O que deve crescer se você quiser menos faltas?",
    opcoes: ["O estoque de segurança", "O prazo do fornecedor", "O preço de venda", "O número de itens cadastrados"], correta: 0,
    porque: "O **estoque de segurança** protege contra a incerteza. Ele cresce com a variação da demanda (σ), com a raiz do lead time e com o nível de serviço desejado (z).",
    pratica: "σ = 20 un/dia, LT = 4 dias, 95% de serviço → ES = 1,65 × 20 × 2 = 66 unidades. Passar para 99% (z = 2,33) exigiria 93 unidades." },
  { id: "d05", areas: ["suprimentos", "compras"], ferramenta: "ponto-pedido",
    pergunta: "Consumo médio de 100 un/dia, lead time de 4 dias e estoque de segurança de 66 un. Qual é o ponto de pedido?",
    opcoes: ["100 unidades", "400 unidades", "466 unidades", "166 unidades"], correta: 2,
    porque: "**PP = d̄ × LT + ES** = 100 × 4 + 66 = 466. Quando o saldo chega a esse nível, dispara-se o pedido.",
    pratica: "Sistemas ERP costumam ter um campo de 'ponto de reposição'. Se ele está desatualizado, o sistema pede tarde (falta) ou cedo (excesso)." },
  { id: "d06", areas: ["compras", "suprimentos"], ferramenta: "lec",
    pergunta: "Se o custo de fazer um pedido aumenta (mais burocracia e frete fixo), o lote econômico tende a:",
    opcoes: ["Diminuir", "Aumentar", "Ficar igual", "Virar zero"], correta: 1,
    porque: "**Q* = √(2DS/H)**: com S maior, compensa pedir menos vezes, em lotes maiores.",
    pratica: "Reduzir o custo de pedir (pedido eletrônico, contrato guarda-chuva) é o que permite comprar em lotes menores sem aumentar o custo total." },
  { id: "d07", areas: ["producao", "processos"], ferramenta: "oee",
    pergunta: "Uma máquina tem disponibilidade de 90%, performance de 85% e qualidade de 98%. Qual é o OEE aproximado?",
    opcoes: ["91%", "75%", "85%", "98%"], correta: 1,
    porque: "**OEE = D × P × Q** = 0,90 × 0,85 × 0,98 ≈ 0,75. Os fatores se multiplicam, não se somam nem se tira a média.",
    pratica: "Nesse caso a maior perda é performance (pequenas paradas e velocidade abaixo da ideal). O plano de ação começa por aí, não pela qualidade." },
  { id: "d08", areas: ["producao", "processos"], ferramenta: "takt",
    pergunta: "O turno tem 440 minutos disponíveis e o cliente pede 480 unidades por turno. Qual é o takt time?",
    opcoes: ["55 segundos", "1,09 minuto por hora", "480 segundos", "40 segundos"], correta: 0,
    porque: "**Takt = tempo disponível ÷ demanda** = 26.400 s ÷ 480 = 55 s por unidade.",
    pratica: "Se algum posto leva 62 s por ciclo, a linha não acompanha a demanda: é preciso rebalancear tarefas ou melhorar esse posto." },
  { id: "d09", areas: ["producao", "processos"], ferramenta: "balanceamento",
    pergunta: "A soma dos tempos das tarefas é 180 s e o takt é 55 s. Qual o número mínimo de postos?",
    opcoes: ["3", "4", "5", "3,27"], correta: 1,
    porque: "**N mínimo = Σt ÷ takt** = 3,27 → arredonda **para cima**: 4 postos. Com 3, algum posto passaria do takt.",
    pratica: "Com 4 postos e ciclo de 55 s, a eficiência é 180 ÷ 220 = 81,8%; os 40 s de ociosidade por ciclo mostram onde ainda há espaço para melhorar." },
  { id: "d10", areas: ["producao"], ferramenta: "smed",
    pergunta: "No SMED, qual é o primeiro passo depois de observar a troca?",
    opcoes: ["Comprar uma máquina nova", "Separar o que é setup interno (máquina parada) do externo (máquina rodando)", "Aumentar o tamanho dos lotes", "Treinar só o supervisor"], correta: 1,
    porque: "Muitas atividades feitas com a máquina parada (buscar ferramenta, molde, material) poderiam ser feitas antes. Separar interno × externo costuma trazer o maior ganho com custo quase zero.",
    pratica: "Com um carrinho com o kit da próxima troca preparado antes da parada, uma troca de 60 min caiu para 35 min só com organização." },
  { id: "d11", areas: ["qualidade", "producao"], ferramenta: "pareto",
    pergunta: "Você tem 7 tipos de defeito e tempo para atacar só um agora. Qual ferramenta ajuda a escolher?",
    opcoes: ["Diagrama de Pareto", "Cronograma de Gantt", "Curva de aprendizagem", "Balanço patrimonial"], correta: 0,
    porque: "O **Pareto** ordena as categorias pela frequência ou custo e mostra os poucos tipos que causam a maior parte do problema.",
    pratica: "Selagem e rótulo torto somavam 78% das rejeições da embaladora. Resolver a selagem, sozinha, derrubou quase metade do refugo." },
  { id: "d12", areas: ["qualidade"], ferramenta: "cep",
    pergunta: "Um ponto na carta de controle ficou acima do limite superior de controle. O que isso indica?",
    opcoes: ["Que a peça está fora da especificação do cliente", "Provável causa especial: investigar o que mudou", "Que o limite precisa ser recalculado imediatamente", "Nada, é variação normal"], correta: 1,
    porque: "Limites de **controle** vêm do próprio processo; um ponto fora sugere **causa especial**. Isso é diferente de estar fora da **especificação**, que vem do cliente/projeto.",
    pratica: "O ponto fora coincidiu com a troca de bobina de um novo fornecedor. A causa foi encontrada porque a equipe anotou o evento na carta." },
  { id: "d13", areas: ["qualidade"], ferramenta: "capabilidade",
    pergunta: "Um processo tem Cp = 1,5 e Cpk = 0,7. O que isso significa?",
    opcoes: ["O processo é ótimo", "A variação é pequena, mas a média está deslocada do centro da tolerância", "A variação é grande demais", "Os índices estão errados: Cpk nunca é menor que Cp"], correta: 1,
    porque: "**Cp** olha só a variação (potencial). **Cpk** considera onde está a média. Cp alto e Cpk baixo = processo capaz, porém **descentrado**.",
    pratica: "Recentralizar a média (ajuste de máquina) costuma ser rápido e barato, e o Cpk sobe perto do Cp sem nenhum investimento." },
  { id: "d14", areas: ["qualidade", "processos"], ferramenta: "cinco-porques",
    pergunta: "A máquina parou porque o fusível queimou. Pelo método dos 5 porquês, qual resposta está mais perto da causa raiz?",
    opcoes: ["Trocar o fusível", "Não havia rotina de lubrificação, o rolamento travou e causou sobrecarga", "O operador estava distraído", "O fusível era de má qualidade"], correta: 1,
    porque: "Trocar o fusível trata o sintoma. Seguindo os porquês (sobrecarga → rolamento travado → falta de lubrificação → sem rotina), chega-se a uma causa que, eliminada, **impede a repetição**.",
    pratica: "Culpar uma pessoa quase nunca é causa raiz: a pergunta seguinte é 'por que o sistema permitiu o erro?'." },
  { id: "d15", areas: ["qualidade", "producao"], ferramenta: "poka-yoke",
    pergunta: "Operadores às vezes montam a tampa invertida. Qual ação é mais robusta?",
    opcoes: ["Colar um aviso 'atenção à posição da tampa'", "Treinar novamente todos", "Mudar o gabarito para que a tampa só encaixe na posição certa", "Aumentar a inspeção final"], correta: 2,
    porque: "Um **poka-yoke** torna o erro impossível ou evidente na hora. Avisos e treinamento ajudam, mas dependem de atenção humana o tempo todo.",
    pratica: "Gabaritos assimétricos, sensores de presença e balanças que travam a linha são poka-yokes baratos e muito comuns em montagem." },
  { id: "d16", areas: ["processos", "producao"], ferramenta: "vsm",
    pergunta: "No mapa do fluxo de valor, o lead time é de 12 dias e o tempo que agrega valor é de 45 minutos. O que isso mostra?",
    opcoes: ["Que o processo é eficiente", "Que o produto passa quase todo o tempo esperando em estoque ou fila", "Que é preciso contratar mais operadores", "Que a demanda está baixa"], correta: 1,
    porque: "A eficiência do ciclo (PCE) é menor que 1%: quase todo o lead time é **espera**. Reduzir estoques entre etapas encurta o lead time muito mais do que acelerar as máquinas.",
    pratica: "Criar fluxo contínuo entre corte e montagem eliminou 4 dias de estoque intermediário sem mudar nenhum tempo de operação." },
  { id: "d17", areas: ["processos"], ferramenta: "tempo-padrao",
    pergunta: "Tempo observado de 50 s, ritmo avaliado em 110% e tolerância de 15%. Qual é o tempo padrão?",
    opcoes: ["57,5 s", "≈ 63,3 s", "50 s", "55 s"], correta: 1,
    porque: "**TN = TO × FR** = 50 × 1,10 = 55 s. **TP = TN × (1 + T)** = 55 × 1,15 ≈ 63,3 s.",
    pratica: "Esquecer a tolerância gera metas impossíveis; aplicá-la duas vezes 'esconde' capacidade. Os dois erros aparecem no planejamento." },
  { id: "d18", areas: ["processos", "producao"], ferramenta: "desperdicios",
    pergunta: "O operador anda 40 metros a cada ciclo para buscar embalagens. Qual desperdício é esse?",
    opcoes: ["Superprodução", "Movimentação", "Defeito", "Superprocessamento"], correta: 1,
    porque: "Deslocamento de **pessoas** sem agregar valor é **movimentação**. (Transporte é o deslocamento de materiais.)",
    pratica: "Colocar um supermercado de embalagens ao lado da linha e abastecê-lo com rota de abastecimento eliminou cerca de 15 min por turno." },
  { id: "d19", areas: ["pcp", "producao"], ferramenta: "sequenciamento",
    pergunta: "Três ordens na mesma máquina: A (6 h, entrega em 8 h), B (2 h, entrega em 6 h), C (4 h, entrega em 15 h). Qual sequência entrega todas no prazo?",
    opcoes: ["A, B, C", "B, C, A", "B, A, C", "C, B, A"], correta: 2,
    porque: "Pela regra **EDD** (data de entrega mais cedo): B termina em 2 h, A em 8 h e C em 12 h, todas no prazo. A regra SPT (B, C, A) atrasaria a ordem A em 4 h.",
    pratica: "Não existe regra única: SPT reduz o tempo médio de fluxo; EDD reduz atrasos. Escolha pelo que o cliente valoriza." },
  { id: "d20", areas: ["pcp", "suprimentos"], ferramenta: "mrp",
    pergunta: "Precisamos de 1.000 bandejas na semana 6, temos 300 em estoque e o fornecedor leva 2 semanas. O que o MRP recomenda?",
    opcoes: ["Pedir 1.000 na semana 6", "Pedir 700 na semana 4", "Pedir 1.300 na semana 4", "Não pedir nada"], correta: 1,
    porque: "Necessidade líquida = 1.000 − 300 = 700. Liberação = semana da necessidade − lead time = semana 4.",
    pratica: "Se o estoque do sistema estiver errado (ex.: 300 no sistema e 100 na prateleira), o MRP pede errado com a mesma precisão. A acuracidade do estoque é condição do MRP." },
  { id: "d21", areas: ["pcp"], ferramenta: "previsao-demanda",
    pergunta: "A previsão de outubro era 500 caixas e a venda real foi 560. Com suavização exponencial (α = 0,2), qual a previsão de novembro?",
    opcoes: ["560", "512", "530", "500"], correta: 1,
    porque: "**Fₜ₊₁ = Fₜ + α(Aₜ − Fₜ)** = 500 + 0,2 × 60 = 512. O α define quanto a previsão reage ao último erro.",
    pratica: "α alto reage rápido (bom para mudanças reais) mas 'persegue' ruído; α baixo é estável mas demora a perceber tendências." },
  { id: "d22", areas: ["pcp", "dados"], ferramenta: "erro-previsao",
    pergunta: "A previsão errou para baixo em 10 dos últimos 12 meses. O que isso indica?",
    opcoes: ["Previsão sem problema, só variação", "Viés: o método subestima sistematicamente a demanda", "Que o MAPE é zero", "Que a demanda é aleatória"], correta: 1,
    porque: "Erros sempre do mesmo lado indicam **viés**. O MAPE mostra o tamanho do erro; o viés mostra a direção.",
    pratica: "Um viés negativo persistente costuma vir de tendência de crescimento não captada pelo método (ex.: média móvel com demanda crescendo)." },
  { id: "d23", areas: ["logistica", "compras"], ferramenta: "otif",
    pergunta: "Em 500 pedidos, 470 chegaram no prazo e completos. Qual o OTIF?",
    opcoes: ["470", "94%", "6%", "97%"], correta: 1,
    porque: "**OTIF = pedidos no prazo e completos ÷ total** = 470 ÷ 500 = 94%.",
    pratica: "Separar as falhas entre 'atrasado' e 'incompleto' aponta a causa: incompleto costuma ser estoque ou separação; atrasado, transporte ou produção." },
  { id: "d24", areas: ["logistica"], ferramenta: "armazenagem",
    pergunta: "Como posicionar os itens no armazém para reduzir o tempo de separação?",
    opcoes: ["Em ordem alfabética", "Por código do produto", "Os de maior giro mais perto da expedição e na altura da cintura", "Os mais caros mais perto da porta"], correta: 2,
    porque: "Endereçar pelo **giro** (popularidade) reduz a distância percorrida nas separações mais frequentes.",
    pratica: "Poucos itens concentram a maioria das separações; reposicioná-los reduz o tempo de picking sem nenhum investimento em equipamento." },
  { id: "d25", areas: ["logistica", "po"], ferramenta: "localizacao",
    pergunta: "Para uma primeira estimativa de onde instalar um CD, qual método usa as coordenadas dos clientes ponderadas pelos volumes?",
    opcoes: ["Centro de gravidade", "Curva ABC", "PERT", "OEE"], correta: 0,
    porque: "O **centro de gravidade** calcula X = Σ(xᵢVᵢ) ÷ ΣVᵢ e Y da mesma forma: um ponto que tende a reduzir o transporte total.",
    pratica: "O ponto calculado é um começo: depois entram estradas, terrenos disponíveis, impostos e mão de obra." },
  { id: "d26", areas: ["po"], ferramenta: "teoria-filas",
    pergunta: "Chegam 8 caminhões por hora e a doca descarrega 10 por hora. O que acontece se as chegadas subirem para 9,5 por hora?",
    opcoes: ["A espera aumenta um pouco, cerca de 19%", "A espera na fila quase quintuplica", "Nada muda", "A fila diminui"], correta: 1,
    porque: "Com ρ = λ/μ, a espera no M/M/1 é Wq = ρ ÷ (μ − λ): vai de 0,4 h (ρ = 0,8) para 1,9 h (ρ = 0,95). Perto de 100% de utilização, a fila **explode**.",
    pratica: "Por isso, recursos com chegada variável precisam de folga. Utilização de 100% não é eficiência: é fila." },
  { id: "d27", areas: ["po", "pcp"], ferramenta: "programacao-linear",
    pergunta: "Em programação linear, o que é o 'preço-sombra' de uma restrição?",
    opcoes: ["O preço de venda do produto", "Quanto a função objetivo melhora com uma unidade a mais daquele recurso", "O custo fixo da fábrica", "O preço do concorrente"], correta: 1,
    porque: "O **preço-sombra** (valor dual) mostra quanto vale uma unidade a mais do recurso, dentro da faixa de validade.",
    pratica: "Se a hora do gargalo tem preço-sombra de R$ 120 e a hora extra custa R$ 60, vale a pena fazer hora extra nesse recurso." },
  { id: "d28", areas: ["po", "projetos"], ferramenta: "arvore-decisao",
    pergunta: "Ampliar a fábrica dá +R$ 500 mil com 60% de chance ou −R$ 200 mil com 40%. Qual o valor esperado?",
    opcoes: ["R$ 300 mil", "R$ 220 mil", "R$ 150 mil", "R$ 700 mil"], correta: 1,
    porque: "**VE = Σ p × resultado** = 0,6 × 500 + 0,4 × (−200) = 300 − 80 = R$ 220 mil.",
    pratica: "O valor esperado não é tudo: se um prejuízo de R$ 200 mil quebra a empresa, a decisão também deve considerar o risco." },
  { id: "d29", areas: ["projetos"], ferramenta: "caminho-critico",
    pergunta: "O projeto está atrasado. Onde acelerar para reduzir o prazo total?",
    opcoes: ["Em qualquer atividade", "Nas atividades do caminho crítico", "Nas atividades com mais folga", "Nas atividades mais baratas"], correta: 1,
    porque: "Só o **caminho crítico** (folga zero) define o término. Acelerar atividades com folga não muda a data final.",
    pratica: "Ao comprimir o caminho crítico, outro caminho pode virar crítico: recalcule a rede após cada mudança." },
  { id: "d30", areas: ["projetos"], ferramenta: "valor-agregado",
    pergunta: "Um projeto tem EV = R$ 80 mil e AC = R$ 100 mil. O CPI é:",
    opcoes: ["1,25: abaixo do orçamento", "0,8: gastando R$ 1,25 para cada R$ 1 de trabalho entregue", "0,2", "Não dá para saber sem o PV"], correta: 1,
    porque: "**CPI = EV ÷ AC** = 0,8. Menor que 1 significa custo acima do planejado para o que foi entregue.",
    pratica: "Com orçamento (BAC) de R$ 200 mil e CPI 0,8, a estimativa no término é EAC = 200 ÷ 0,8 = R$ 250 mil, um alerta para agir já." },
  { id: "d31", areas: ["projetos"], ferramenta: "eap",
    pergunta: "O que a regra dos 100% diz sobre a EAP?",
    opcoes: ["Que o projeto deve ser 100% concluído no prazo", "Que a EAP contém todo o trabalho do projeto, e somente ele", "Que cada pacote deve ter 100 horas", "Que 100% da equipe deve aprovar a EAP"], correta: 1,
    porque: "A **regra dos 100%** garante que nada fique de fora e nada estranho entre, e é a base para controlar o escopo.",
    pratica: "Listar também o que **não** faz parte do escopo evita discussões na entrega." },
  { id: "d32", areas: ["compras", "producao"], ferramenta: "margem-contribuicao",
    pergunta: "Produto com preço de R$ 50 e custos variáveis de R$ 30. Um cliente oferece R$ 40 por um pedido extra e há capacidade ociosa. A decisão financeira de curto prazo é:",
    opcoes: ["Recusar, porque o custo total com rateio é R$ 45", "Aceitar: a margem de contribuição de R$ 10 por unidade ajuda a pagar os fixos", "Recusar sempre qualquer desconto", "Aceitar só se o preço for acima de R$ 50"], correta: 1,
    porque: "Com capacidade ociosa, os custos fixos não mudam. O que importa é a **margem de contribuição**: R$ 40 − R$ 30 = R$ 10 positivos por unidade.",
    pratica: "Cuidado: se o recurso gargalo estiver cheio, o pedido tira espaço de produtos com margem maior. Também avalie o efeito no preço dos outros clientes." },
  { id: "d33", areas: ["compras", "projetos"], ferramenta: "ponto-equilibrio",
    pergunta: "Custos fixos de R$ 40.000/mês e margem de contribuição de R$ 20 por unidade. Qual o ponto de equilíbrio?",
    opcoes: ["800 unidades", "2.000 unidades", "20.000 unidades", "R$ 40.000"], correta: 1,
    porque: "**PE = custos fixos ÷ MC unitária** = 40.000 ÷ 20 = 2.000 unidades por mês.",
    pratica: "Acima de 2.000 unidades, cada unidade adicional gera R$ 20 de lucro; abaixo, cada unidade que falta é R$ 20 de prejuízo." },
  { id: "d34", areas: ["projetos", "producao"], ferramenta: "vpl-tir",
    pergunta: "Um investimento tem VPL positivo usando a TMA da empresa. Isso significa que:",
    opcoes: ["O retorno supera a taxa mínima de atratividade", "O payback é menor que 1 ano", "A TIR é negativa", "Não há risco"], correta: 0,
    porque: "**VPL > 0** significa que os fluxos, descontados pela TMA, superam o investimento, o que equivale a dizer que a TIR é maior que a TMA (em projetos convencionais).",
    pratica: "Máquina de R$ 100 mil que economiza R$ 30 mil/ano por 5 anos, com TMA de 12%: VPL ≈ R$ 8,1 mil e TIR ≈ 15,2%." },
  { id: "d35", areas: ["producao", "processos"], ferramenta: "hierarquia-controles",
    pergunta: "Há risco de corte na lâmina da embaladora. Pela hierarquia de controles, qual medida vem antes das outras?",
    opcoes: ["Luva anticorte (EPI)", "Treinamento de segurança", "Proteção fixa com intertravamento que para a máquina ao abrir", "Placa de advertência"], correta: 2,
    porque: "Depois de eliminar e substituir, vêm os **controles de engenharia**, que não dependem do comportamento. Procedimentos e **EPI** são as últimas barreiras.",
    pratica: "O EPI continua útil como proteção adicional, mas não pode ser a única medida quando existe solução de engenharia." },
  { id: "d36", areas: ["producao", "processos"], ferramenta: "ergonomia",
    pergunta: "Ao definir o alcance máximo de peças numa bancada, qual percentil da população costuma ser usado?",
    opcoes: ["O percentil 95 (pessoas maiores)", "O percentil 5 (pessoas menores)", "A média", "Tanto faz"], correta: 1,
    porque: "Para **alcance**, projeta-se para quem tem braço menor (percentil 5): se essa pessoa alcança, quase todos alcançam. Para **espaço livre** (altura de passagem), usa-se o percentil 95.",
    pratica: "Bancadas reguláveis resolvem o problema de alturas diferentes com um custo pequeno comparado a afastamentos." },
  { id: "d37", areas: ["dados", "qualidade"], ferramenta: "teste-hipoteses",
    pergunta: "Após uma melhoria, o teste de hipóteses deu valor-p = 0,02 com α = 0,05. A conclusão é:",
    opcoes: ["Não há evidência de diferença", "Há evidência estatística de que a média mudou", "A melhoria aumentou 2%", "É preciso α maior"], correta: 1,
    porque: "Com **valor-p < α**, rejeita-se H₀ (sem diferença). O valor-p não diz o tamanho do efeito: veja também a diferença das médias e o intervalo de confiança.",
    pratica: "Resultado estatisticamente significativo mas pequeno (ex.: 0,5 s por ciclo) pode não valer o custo da mudança." },
  { id: "d38", areas: ["dados"], ferramenta: "regressao",
    pergunta: "A correlação entre horas de treinamento e produtividade é r = 0,85. O que se pode afirmar?",
    opcoes: ["O treinamento causa o aumento de produtividade", "Há forte relação linear positiva, mas correlação não prova causa", "Não há relação", "Produtividade cai com treinamento"], correta: 1,
    porque: "r = 0,85 indica relação **forte e positiva**. Causa exige mais (experimento, controle de outras variáveis): talvez os mais experientes façam mais treinamentos.",
    pratica: "Um experimento com grupo de controle (DOE) seria o caminho para provar o efeito do treinamento." },
  { id: "d39", areas: ["dados"], ferramenta: "histograma",
    pergunta: "Duas máquinas enchem pacotes com média de 500 g. A máquina A tem desvio-padrão de 2 g e a B, de 8 g. O que dizer?",
    opcoes: ["São equivalentes, pois têm a mesma média", "A máquina B é muito mais variável e tende a gerar mais pacotes fora do peso", "A máquina A é pior", "O desvio-padrão não importa"], correta: 1,
    porque: "Média igual não significa processo igual. O **desvio-padrão** mostra a dispersão: com 8 g, a B produz muito mais pacotes longe do alvo.",
    pratica: "Para não ficar abaixo do peso declarado, a B precisa trabalhar com média mais alta, e esse sobrepeso é dinheiro dado de graça." },
  { id: "d40", areas: ["dados"], ferramenta: "qualidade-dados",
    pergunta: "Na planilha de paradas aparecem 'Manutenção', 'manut.' e 'MANUTENÇÃO' como causas diferentes. Qual o melhor ajuste?",
    opcoes: ["Ignorar, é só texto", "Padronizar com lista suspensa (validação de dados) e corrigir o histórico", "Apagar essas linhas", "Criar mais uma coluna 'observação'"], correta: 1,
    porque: "Categorias inconsistentes fragmentam a análise (o Pareto fica errado). **Validação de dados** evita o problema na origem.",
    pratica: "Depois da padronização, 'manutenção' virou a primeira causa do Pareto de paradas, que antes aparecia dividida em três barras pequenas." },
  { id: "d41", areas: ["pcp", "logistica"], ferramenta: "lei-little",
    pergunta: "Há 400 pedidos em processo e a fábrica conclui 50 por dia. Qual o lead time médio?",
    opcoes: ["8 dias", "20.000 dias", "450 dias", "0,125 dia"], correta: 0,
    porque: "Pela **Lei de Little**, lead time = WIP ÷ vazão = 400 ÷ 50 = 8 dias.",
    pratica: "Limitar o WIP (kanban, CONWIP) reduz o lead time sem precisar aumentar a capacidade." },
  { id: "d42", areas: ["qualidade", "compras"], ferramenta: "amostragem-aceitacao",
    pergunta: "Plano de amostragem n = 125, c = 3. Na amostra foram encontrados 5 defeituosos. O que fazer com o lote?",
    opcoes: ["Aceitar", "Rejeitar (5 > 3)", "Aceitar metade", "Refazer a amostra até dar menos de 3"], correta: 1,
    porque: "No plano (n, c), aceita-se o lote se o número de defeituosos for **≤ c**. Com 5 > 3, o lote é rejeitado.",
    pratica: "Refazer a amostra até 'passar' invalida o plano. O certo é rejeitar, registrar e tratar com o fornecedor." }
];
