/* =====================================================================
   PROBLEMAS → FERRAMENTAS → CONTEÚDO
   Alimenta as áreas "🚨 Problemas", "🔎 Consultar" e o "Modo Estágio".
   - categorias: grupos de problemas (📦 Estoque, 🏭 Produção…)
   - problemas:  situações reais de empresa ("Tenho estoque demais"),
                 com "termos" (palavras do dia a dia usadas na busca)
                 com as ferramentas que podem ajudar, na ordem sugerida
   - ferramentas: ficha rápida (o que é, para que serve, quando usar,
                 dados necessários, fórmula, exemplo, erros comuns) e
                 "ver": lições/tópicos do app para aprofundar
                 (ids de lição do curso, ex. "m03-l2", ou de tópico da
                 grade, ex. "g-logist-l2" = 2º tópico de Logística)
   - areasEstagio: áreas do Modo Estágio e o que cada uma prioriza
   ===================================================================== */
window.PROBLEMAS = {
  categorias: [
    { id: "estoque", nome: "Estoque", icone: "📦", desc: "Excesso, falta, quanto e quando comprar" },
    { id: "producao", nome: "Produção", icone: "🏭", desc: "Capacidade, paradas, trocas e atrasos" },
    { id: "dados", nome: "Dados e indicadores", icone: "📊", desc: "Medir, comparar e provar resultados" },
    { id: "logistica", nome: "Logística", icone: "🚚", desc: "Entregas, armazém e rede de distribuição" },
    { id: "compras", nome: "Compras e suprimentos", icone: "🛒", desc: "Fornecedores, lotes e fazer × comprar" },
    { id: "qualidade", nome: "Qualidade", icone: "✅", desc: "Defeitos, reclamações e especificação" },
    { id: "processos", nome: "Processos", icone: "⏱️", desc: "Tempos, desperdícios e padronização" },
    { id: "custos", nome: "Custos", icone: "💰", desc: "Custo do produto, preço e investimentos" },
    { id: "pessoas", nome: "Pessoas", icone: "👥", desc: "Ergonomia, segurança e equipes" },
    { id: "planejamento", nome: "Planejamento", icone: "📈", desc: "Demanda, plano de produção e metas" },
    { id: "po", nome: "Pesquisa Operacional", icone: "🔬", desc: "Otimizar, filas e decisões com incerteza" },
    { id: "projetos", nome: "Projetos", icone: "💡", desc: "Prazo, custo, escopo, riscos e produto novo" }
  ],

  problemas: [
    // 📦 Estoque
    { id: "estoque-demais", termos: "estoque alto excesso sobra parado cheio capital de giro obsoleto vencido", cat: "estoque", titulo: "Tenho estoque demais",
      desc: "Depósito cheio, dinheiro parado, itens vencendo ou ficando obsoletos.",
      comecar: "Comece pela **Curva ABC** para descobrir quais poucos itens concentram o valor parado; depois veja o **giro** deles e revise lote, estoque de segurança e previsão.",
      ferramentas: ["curva-abc", "giro-estoque", "lec", "estoque-seguranca", "ponto-pedido", "previsao-demanda"] },
    { id: "falta-material", termos: "ruptura faltou acabou parada por falta sem material desabastecimento", cat: "estoque", titulo: "Falta material com frequência",
      desc: "A produção para esperando material ou o cliente fica sem produto (ruptura).",
      comecar: "Confira se existe um **ponto de pedido** com **estoque de segurança** calculado a partir da variação real da demanda e do prazo do fornecedor.",
      ferramentas: ["ponto-pedido", "estoque-seguranca", "previsao-demanda", "mrp", "curva-abc"] },
    { id: "politica-reposicao", termos: "reposicao politica estoque minimo maximo revisao periodica almoxarifado", cat: "estoque", titulo: "Não sei que regra de reposição usar em cada item",
      desc: "Uns itens são pedidos quando alguém lembra, outros todo mês na mesma quantidade, sem critério.",
      comecar: "Separe os itens pela **curva ABC** e escolha a **política de estoque**: revisão contínua para os A, mín–máx ou revisão periódica para os demais.",
      ferramentas: ["politica-estoque", "curva-abc", "ponto-pedido", "lec"] },
    { id: "quanto-comprar", termos: "tamanho do lote pedido de compra quantidade", cat: "estoque", titulo: "Não sei quanto comprar de cada vez",
      desc: "Pedidos grandes demais (estoque alto) ou pequenos demais (muitos pedidos e frete caro).",
      comecar: "O **lote econômico** equilibra o custo de pedir e o custo de manter; use-o como ponto de partida e ajuste por mínimo do fornecedor e espaço.",
      ferramentas: ["lec", "ponto-pedido", "curva-abc"] },

    // 🏭 Produção
    { id: "linha-nao-da-conta", termos: "demanda aumentou nao atende capacidade insuficiente produzir mais", cat: "producao", titulo: "A linha não dá conta da demanda",
      desc: "A demanda subiu (ou vai subir) e a produção não acompanha.",
      comecar: "Compare **carga × capacidade** e ache o **gargalo**: é a capacidade dele que limita a linha inteira. Só depois pense em hora extra ou investimento.",
      ferramentas: ["capacidade", "gargalo", "takt", "balanceamento", "oee"] },
    { id: "maquina-para", termos: "quebra parada falha maquina quebrada disponibilidade", cat: "producao", titulo: "A máquina para muito",
      desc: "Quebras, pequenas paradas e perda de velocidade derrubam a produção.",
      comecar: "Meça o **OEE** para saber se a perda é disponibilidade, performance ou qualidade; para quebras, acompanhe **MTBF e MTTR**.",
      ferramentas: ["oee", "mtbf-mttr", "tpm", "smed", "ishikawa"] },
    { id: "setup-demorado", termos: "troca de ferramenta troca de produto set-up lote grande", cat: "producao", titulo: "As trocas de produto (setup) demoram demais",
      desc: "Por causa do setup, a fábrica produz lotes enormes e demora a atender pedidos variados.",
      comecar: "Filme uma troca e aplique o **SMED**: separe o que pode ser feito com a máquina rodando (setup externo).",
      ferramentas: ["smed", "heijunka", "oee", "trabalho-padronizado"] },
    { id: "pedidos-atrasam", termos: "atraso prazo entrega atrasada cliente reclama", cat: "producao", titulo: "Os pedidos atrasam",
      desc: "Prazos prometidos não são cumpridos e o cliente reclama.",
      comecar: "Verifique primeiro se há **capacidade** para a carga prometida; depois revise a **regra de sequenciamento** e o volume de WIP (**Lei de Little**).",
      ferramentas: ["capacidade", "sequenciamento", "lei-little", "pmp", "kanban", "otif"] },

    // 📊 Dados e indicadores
    { id: "quais-indicadores", termos: "kpi metas medir desempenho", cat: "dados", titulo: "Não sei quais indicadores acompanhar",
      desc: "Muitos números, pouca decisão; ou nenhum número confiável.",
      comecar: "Parta do objetivo da área e escolha poucos **KPIs** com meta, dono e frequência; OEE e OTIF são bons pontos de partida na produção e na entrega.",
      ferramentas: ["kpi", "oee", "otif", "bsc-okr"] },
    { id: "numeros-variam", termos: "variacao instavel oscila resultado varia", cat: "dados", titulo: "Os números variam e não sei se é normal",
      desc: "Um dia o resultado é ótimo, no outro é ruim. É o processo mudando ou só variação?",
      comecar: "Olhe a distribuição (**histograma**, média e desvio-padrão) e coloque os dados numa **carta de controle (CEP)**: ela separa variação comum de causa especial.",
      ferramentas: ["histograma", "cep", "capabilidade"] },
    { id: "provar-melhoria", termos: "comparar antes depois significativo", cat: "dados", titulo: "Preciso provar que uma mudança funcionou",
      desc: "Fizemos uma melhoria, mas a diferença pode ser acaso.",
      comecar: "Compare antes × depois com um **teste de hipóteses** e mostre o **intervalo de confiança** da diferença, não só a média.",
      ferramentas: ["teste-hipoteses", "intervalo-confianca", "regressao", "histograma"] },
    { id: "dados-ruins", termos: "excel planilha erro dado errado sujo", cat: "dados", titulo: "Minha planilha tem erros ou os dados são ruins",
      desc: "Valores faltando, duplicados, digitados de formas diferentes, fórmulas quebradas.",
      comecar: "Antes de analisar, avalie a **qualidade dos dados** (completude, exatidão, consistência) e organize a planilha em formato de tabela.",
      ferramentas: ["qualidade-dados", "kpi"] },

    // 🚚 Logística
    { id: "entregas-atrasam", termos: "entrega atrasada incompleta pedido faltando", cat: "logistica", titulo: "As entregas atrasam ou chegam incompletas",
      desc: "O cliente recebe fora do prazo ou faltando itens.",
      comecar: "Meça o **OTIF** separando o que é atraso e o que é pedido incompleto; depois ataque a causa (estoque, separação ou transporte).",
      ferramentas: ["otif", "estoque-seguranca", "armazenagem", "modelo-transporte"] },
    { id: "armazem-baguncado", termos: "desorganizado bagunca separacao picking lento", cat: "logistica", titulo: "O armazém está bagunçado e demora achar as coisas",
      desc: "Separação lenta, itens perdidos, muito deslocamento.",
      comecar: "Aplique **5S** e reendereçe pelo giro (**curva ABC** de movimentação): o que sai mais fica mais perto da expedição.",
      ferramentas: ["cinco-s", "armazenagem", "curva-abc", "layout"] },
    { id: "onde-instalar", termos: "localizacao novo cd deposito", cat: "logistica", titulo: "Onde instalar um novo centro de distribuição?",
      desc: "Escolher a localização que reduz o custo de transporte até os clientes.",
      comecar: "Use o **centro de gravidade** para uma primeira localização e refine com o **modelo de transporte** e fatores qualitativos.",
      ferramentas: ["localizacao", "modelo-transporte"] },
    { id: "frete-caro", termos: "frete caro transporte custo logistico rota", cat: "logistica", titulo: "O custo de transporte está alto",
      desc: "Frete pesa no custo e as rotas parecem ineficientes.",
      comecar: "Modele quanto sai de cada origem para cada destino com o **modelo de transporte** (programação linear) e revise o tamanho dos lotes.",
      ferramentas: ["modelo-transporte", "localizacao", "lec"] },

    // 🛒 Compras e suprimentos
    { id: "fornecedor-falha", termos: "fornecedor atrasa material ruim defeito recebimento", cat: "compras", titulo: "O fornecedor atrasa ou entrega com defeito",
      desc: "Material chega fora do prazo ou fora da especificação.",
      comecar: "Meça o **OTIF do fornecedor** e inspecione lotes com **amostragem de aceitação**; enquanto não melhora, proteja-se com **estoque de segurança**.",
      ferramentas: ["otif", "amostragem-aceitacao", "estoque-seguranca", "pareto"] },
    { id: "fazer-ou-comprar", termos: "terceirizar make or buy comprar pronto", cat: "compras", titulo: "Fabricar internamente ou comprar pronto?",
      desc: "Decidir se vale a pena terceirizar um item ou trazer para dentro.",
      comecar: "Compare o **custo relevante** (variável + fixo que realmente muda) de fazer × preço de comprar; se houver investimento, calcule **VPL**.",
      ferramentas: ["margem-contribuicao", "custeio", "vpl-tir"] },
    { id: "compras-producao", termos: "materia-prima componentes necessidade", cat: "compras", titulo: "Quanto e quando comprar para a produção?",
      desc: "Itens de uma receita/estrutura de produto que precisam chegar na hora certa.",
      comecar: "Itens que dependem do plano de produção pedem **MRP**; itens de consumo independente pedem **ponto de pedido**.",
      ferramentas: ["mrp", "pmp", "lec", "ponto-pedido"] },

    // ✅ Qualidade
    { id: "muitos-defeitos", termos: "defeito refugo retrabalho perda qualidade ruim", cat: "qualidade", titulo: "Muitos defeitos e refugo",
      desc: "Peças rejeitadas, retrabalho e perda de material.",
      comecar: "Faça um **Pareto** dos defeitos e ataque o maior com **Ishikawa** e **5 porquês**; quando achar a causa, previna com **poka-yoke**.",
      ferramentas: ["pareto", "ishikawa", "cinco-porques", "poka-yoke", "cep", "pdca"] },
    { id: "reclamacao-cliente", termos: "reclamacao causa raiz nao conformidade", cat: "qualidade", titulo: "O cliente reclamou e preciso achar a causa",
      desc: "Uma reclamação séria que exige resposta e ação que não volte a acontecer.",
      comecar: "Conte a história num **A3/PDCA**: contenção imediata, causa raiz (**5 porquês**, **Ishikawa**) e ação verificada.",
      ferramentas: ["pdca", "cinco-porques", "ishikawa", "pareto"] },
    { id: "atende-especificacao", termos: "tolerancia fora de especificacao capaz", cat: "qualidade", titulo: "O processo atende à especificação?",
      desc: "Saber se o processo é capaz de produzir dentro da tolerância.",
      comecar: "Confirme que o processo está estável (**CEP**) e só então calcule **Cp e Cpk**.",
      ferramentas: ["capabilidade", "cep", "histograma"] },

    // ⏱️ Processos
    { id: "tempo-tarefa", termos: "tempo meta produtividade cronometrar", cat: "processos", titulo: "Quanto tempo uma tarefa deveria levar?",
      desc: "Definir metas justas, custear e planejar capacidade.",
      comecar: "Faça **cronoanálise** com número adequado de ciclos, aplique ritmo e tolerâncias para chegar ao **tempo padrão**.",
      ferramentas: ["tempo-padrao", "fluxograma", "curva-aprendizagem"] },
    { id: "desperdicio", termos: "perda retrabalho espera lean melhoria", cat: "processos", titulo: "Tem muito desperdício e retrabalho",
      desc: "Esperas, transporte, estoque entre etapas, gente procurando coisas.",
      comecar: "Mapeie o fluxo (**VSM**) e marque os **desperdícios**; ações rápidas costumam vir de **5S** e **trabalho padronizado**.",
      ferramentas: ["desperdicios", "vsm", "cinco-s", "trabalho-padronizado", "kanban"] },
    { id: "mapear-processo", termos: "fluxo etapas desenhar processo", cat: "processos", titulo: "Preciso mapear e entender o processo",
      desc: "Ninguém sabe ao certo todas as etapas e onde está o tempo perdido.",
      comecar: "Para uma operação, use o **fluxograma** do estudo de métodos; para o fluxo de ponta a ponta com materiais e informação, o **VSM**.",
      ferramentas: ["fluxograma", "vsm", "tempo-padrao"] },

    // 💰 Custos
    { id: "custo-real", termos: "custo do produto preco errado rateio", cat: "custos", titulo: "Não sei o custo real do produto",
      desc: "O custo usado para preço e decisões parece errado.",
      comecar: "Separe custos **diretos, indiretos, fixos e variáveis**; se os indiretos são grandes e os produtos muito diferentes, considere o **custeio ABC**.",
      ferramentas: ["custeio", "custeio-abc", "margem-contribuicao"] },
    { id: "aceitar-pedido", termos: "desconto preco pedido especial margem", cat: "custos", titulo: "Vale a pena aceitar esse pedido ou esse preço?",
      desc: "Cliente pede desconto ou um pedido especial.",
      comecar: "Olhe a **margem de contribuição**: se o preço cobre os custos variáveis e há capacidade ociosa, o pedido ajuda a pagar os fixos. Acompanhe o **ponto de equilíbrio**.",
      ferramentas: ["margem-contribuicao", "ponto-equilibrio", "gargalo"] },
    { id: "investir-maquina", termos: "investimento compra de maquina retorno viabilidade", cat: "custos", titulo: "Vale a pena investir nessa máquina?",
      desc: "Justificar um investimento com números.",
      comecar: "Monte o fluxo de caixa do investimento e calcule **VPL, TIR e payback** usando a taxa mínima de atratividade da empresa.",
      ferramentas: ["vpl-tir", "arvore-decisao"] },

    // 👥 Pessoas
    { id: "posto-cansativo", termos: "dor lesao postura cansaco ergonomico", cat: "pessoas", titulo: "Postos de trabalho cansativos ou com queixas de dor",
      desc: "Afastamentos, dores, rotatividade no posto.",
      comecar: "Avalie o posto pela **ergonomia** (NR-17): alturas, alcances, esforço, repetição e pausas.",
      ferramentas: ["ergonomia", "hierarquia-controles", "tempo-padrao"] },
    { id: "risco-acidente", termos: "acidente seguranca perigo quase acidente", cat: "pessoas", titulo: "Há risco de acidente",
      desc: "Quase acidentes, máquinas sem proteção, improvisos.",
      comecar: "Siga a **hierarquia de controles**: eliminar e substituir vêm antes de EPI.",
      ferramentas: ["hierarquia-controles", "poka-yoke", "cinco-porques"] },
    { id: "equipe-desmotivada", termos: "motivacao engajamento pessoas desanimo", cat: "pessoas", titulo: "A equipe está desmotivada",
      desc: "Baixo engajamento, faltas, pouca participação em melhorias.",
      comecar: "Diferencie fatores **higiênicos** (salário, condições) de **motivadores** (reconhecimento, autonomia) e envolva a equipe em melhorias (kaizen).",
      ferramentas: ["motivacao", "pdca", "kpi"] },
    { id: "novato-lento", termos: "treinamento novo funcionario aprendizagem", cat: "pessoas", titulo: "Funcionário novo produz bem menos",
      desc: "Quanto tempo até o novato chegar ao ritmo padrão?",
      comecar: "Use a **curva de aprendizagem** para prever o tempo por peça e planejar a capacidade no período de adaptação.",
      ferramentas: ["curva-aprendizagem", "trabalho-padronizado", "tempo-padrao"] },

    // 📈 Planejamento
    { id: "prever-demanda", termos: "previsao vendas forecast quanto vamos vender", cat: "planejamento", titulo: "Preciso prever a demanda",
      desc: "Quanto vamos vender no próximo mês ou trimestre?",
      comecar: "Olhe o histórico (tendência? sazonalidade?), escolha o método e acompanhe o **erro de previsão** (MAPE) para saber em quanto confiar.",
      ferramentas: ["previsao-demanda", "erro-previsao", "regressao"] },
    { id: "plano-meses", termos: "plano de producao sazonalidade s&op", cat: "planejamento", titulo: "Como planejar a produção dos próximos meses?",
      desc: "Equilibrar demanda, capacidade, estoque e mão de obra.",
      comecar: "Faça o **planejamento agregado (S&OP)** por família, desdobre no **plano mestre (PMP)** e confira a **capacidade**.",
      ferramentas: ["sop", "pmp", "capacidade", "mrp"] },
    { id: "manter-ou-descontinuar", termos: "portfolio produtos descontinuar investir linha mix lucro vendas caindo", cat: "planejamento", titulo: "Quais produtos manter, investir ou descontinuar?",
      desc: "Portfólio grande, alguns produtos com vendas caindo, recursos limitados para novos lançamentos.",
      comecar: "Posicione os produtos na **matriz BCG** (crescimento × participação) e confira a **margem de contribuição** de cada um antes de decidir.",
      ferramentas: ["matriz-bcg", "margem-contribuicao", "previsao-demanda"] },
    { id: "metas-estrategia", termos: "estrategia objetivos metas", cat: "planejamento", titulo: "Preciso definir metas e acompanhar a estratégia",
      desc: "Ligar o que a área faz aos objetivos da empresa.",
      comecar: "Comece por uma **SWOT** e traduza os objetivos em indicadores com **BSC ou OKR**.",
      ferramentas: ["swot", "bsc-okr", "kpi"] },

    // 🔬 Pesquisa Operacional
    { id: "mix-producao", termos: "otimizar lucro recursos limitados mix", cat: "po", titulo: "Qual o melhor mix de produção com recursos limitados?",
      desc: "Vários produtos disputam as mesmas máquinas, horas e materiais.",
      comecar: "Modele como **programação linear**: variáveis de decisão, objetivo (lucro) e restrições (recursos).",
      ferramentas: ["programacao-linear", "gargalo", "margem-contribuicao"] },
    { id: "fila-grande", termos: "fila espera atendimento demora", cat: "po", titulo: "Tem fila grande e clientes esperando",
      desc: "Atendimento, doca, manutenção ou máquina com fila crescendo.",
      comecar: "Calcule a **utilização** ρ = λ/μ: perto de 100%, a fila explode. A **teoria das filas** e a **simulação** mostram o efeito de mais atendentes.",
      ferramentas: ["teoria-filas", "simulacao", "lei-little"] },
    { id: "distribuir", termos: "distribuicao transporte fabricas clientes", cat: "po", titulo: "Qual a melhor forma de abastecer os clientes a partir das fábricas?",
      desc: "Várias origens, vários destinos, custos diferentes.",
      comecar: "É um **problema de transporte**: minimize o custo total respeitando capacidades e demandas.",
      ferramentas: ["modelo-transporte", "programacao-linear", "localizacao"] },
    { id: "decisao-incerteza", termos: "incerteza risco cenario decisao", cat: "po", titulo: "Preciso decidir sem saber o que vai acontecer",
      desc: "Ampliar ou não, lançar ou não, com cenários incertos.",
      comecar: "Monte uma **árvore de decisão** com probabilidades e resultados e compare o **valor esperado**; teste a sensibilidade com **simulação**.",
      ferramentas: ["arvore-decisao", "simulacao", "vpl-tir"] },

    // 💡 Projetos
    { id: "prazo-apertado", termos: "prazo cronograma atraso projeto", cat: "projetos", titulo: "Tenho um projeto com prazo apertado",
      desc: "Descobrir o que realmente define a data de término.",
      comecar: "Monte a rede de atividades e ache o **caminho crítico**; acelere só atividades críticas (compressão).",
      ferramentas: ["caminho-critico", "eap", "matriz-riscos"] },
    { id: "estouro-orcamento", termos: "orcamento custo projeto gasto acima", cat: "projetos", titulo: "O projeto está estourando o orçamento",
      desc: "Gasto acima do previsto e sem clareza do quanto já foi entregue.",
      comecar: "Use **valor agregado (EVM)**: CPI e SPI mostram desempenho de custo e prazo e permitem prever o custo final.",
      ferramentas: ["valor-agregado", "eap", "caminho-critico"] },
    { id: "escopo-confuso", termos: "escopo requisitos projeto crescendo", cat: "projetos", titulo: "O escopo do projeto está confuso",
      desc: "Cada um entende uma coisa; o trabalho não para de crescer.",
      comecar: "Formalize o projeto num **TAP** e decomponha as entregas numa **EAP** (regra dos 100%).",
      ferramentas: ["eap", "matriz-riscos"] },
    { id: "produto-novo", termos: "desenvolvimento lancamento produto novo", cat: "projetos", titulo: "Vamos desenvolver um produto novo",
      desc: "Traduzir o que o cliente quer em especificação e evitar falhas.",
      comecar: "Use o **QFD** para ligar requisitos do cliente às características técnicas e o **FMEA** para antecipar falhas.",
      ferramentas: ["kano", "busca-anterioridade", "qfd", "fmea", "matriz-riscos"] },
    { id: "quem-faz-o-que", termos: "responsavel papel quem aprova quem decide raci responsabilidades", cat: "projetos", titulo: "Ninguém sabe quem é responsável pelo quê",
      desc: "Tarefas paradas esperando aprovação, retrabalho porque ninguém foi consultado, gente surpresa com decisões.",
      comecar: "Monte uma **matriz RACI** sobre os pacotes da **EAP**: cada entrega com pelo menos um responsável e **um único** aprovador.",
      ferramentas: ["raci", "eap", "matriz-riscos"] },
    { id: "ideia-ja-existe", termos: "patente ideia copiar registrar inpi invencao proteger", cat: "projetos", titulo: "Minha ideia de produto já existe? Posso proteger?",
      desc: "Antes de investir no desenvolvimento, saber se já há patentes parecidas e como proteger a solução.",
      comecar: "Faça uma **busca de anterioridade** (INPI, Espacenet) por palavras-chave e código IPC e mostre no que o seu produto é diferente.",
      ferramentas: ["busca-anterioridade", "kano", "qfd"] }
  ],

  ferramentas: {
    "kano": { nome: "Modelo de Kano", icone: "😍", termos: "kano atrativo obrigatorio unidimensional satisfacao requisitos do cliente encantamento",
      oque: "Classifica os atributos de um produto pelo efeito na satisfação do cliente: obrigatório, unidimensional (desempenho), atrativo (encantamento), neutro e reverso.",
      paraque: "Decidir em que atributos investir: garantir os obrigatórios e diferenciar com os unidimensionais e atrativos.",
      quando: "Projeto informacional de um produto novo ou reformulação; priorização de funcionalidades.",
      dados: ["Lista de atributos (do questionário aberto)", "Respostas de clientes ao par funcional/disfuncional de cada atributo"],
      formulas: [],
      exemplo: "Creme para cabelo: \"não vazar\" saiu obrigatório, \"deixar sedoso\" unidimensional e \"perfume marcante\" reverso para parte dos clientes. A equipe garantiu a vedação, investiu na fórmula e suavizou o perfume.",
      erros: "Perguntar só \"você gostaria de X?\" (sem a pergunta disfuncional); ignorar que segmentos diferentes classificam diferente; investir em melhorar o que é só obrigatório.",
      ver: ["g-projprod-l8", "g-projprod-l2"] },
    "busca-anterioridade": { nome: "Busca de anterioridade (patentes)", icone: "🔎", termos: "patente busca de anterioridade inpi espacenet ipc estado da tecnica propriedade intelectual",
      oque: "Pesquisa do estado da técnica em bases de patentes e publicações para saber se uma solução já existe ou está protegida.",
      paraque: "Evitar duplicar P&D e infringir direitos de terceiros, verificar se a ideia é patenteável e encontrar alternativas técnicas.",
      quando: "No início do desenvolvimento de um produto e antes de pedir uma patente ou lançar no mercado.",
      dados: ["Palavras-chave (também em inglês)", "Código IPC da área", "Bases: INPI, Espacenet, USPTO, Patentscope, LATIPAT"],
      formulas: [],
      exemplo: "Embalagem de bombom que vira porta-joias: a busca por código IPC e palavras-chave achou 3 patentes parecidas; o relatório mostrou a diferença do produto e orientou o pedido de modelo de utilidade.",
      erros: "Buscar só em português e só no INPI; parar nas primeiras palavras-chave; esquecer que a patente é territorial (vale país a país).",
      ver: ["g-projprod-l7", "g-projprod-l4"] },
    "matriz-bcg": { nome: "Matriz BCG", icone: "🐄", termos: "bcg portfolio estrela vaca leiteira interrogacao abacaxi crescimento participacao",
      oque: "Classifica produtos ou negócios por crescimento do mercado e participação relativa: estrela, interrogação, vaca leiteira e abacaxi.",
      paraque: "Equilibrar o portfólio: decidir onde investir, o que manter gerando caixa e o que descontinuar.",
      quando: "Revisão do portfólio de produtos, planejamento estratégico, escolha de projetos de desenvolvimento.",
      dados: ["Taxa de crescimento do mercado de cada produto", "Participação de mercado relativa ao maior concorrente", "Receita ou margem (tamanho da bolha)"],
      formulas: [["Participação relativa = participação do produto ÷ participação do maior concorrente", "eixo horizontal"]],
      exemplo: "O bombom tradicional (vaca leiteira) financia o lançamento do bombom proteico (interrogação, mercado crescendo 15% ao ano). A linha de balas de goma (abacaxi) entra em avaliação de descontinuação.",
      erros: "Usar crescimento do mercado como único indicador de atratividade; descontinuar um \"abacaxi\" que ainda gera caixa ou atende clientes-chave.",
      ver: ["g-projprod-l5", "g-projprod-l4"] },
    "raci": { nome: "Matriz RACI", icone: "👥", termos: "raci responsavel aprovador consultado informado matriz de responsabilidade papeis",
      oque: "Tabela que define, para cada tarefa ou entrega, quem é Responsável (executa), Aprovador (presta contas), Consultado e Informado.",
      paraque: "Acabar com dúvidas sobre quem faz e quem decide, melhorar a comunicação e evitar retrabalho.",
      quando: "Início de projeto, implantação de processo novo, sempre que tarefas travam esperando decisão.",
      dados: ["Entregas ou pacotes da EAP", "Pessoas ou funções envolvidas"],
      formulas: [],
      exemplo: "Validar o novo molde: engenheiro de processos R, gerente industrial A, qualidade C, manutenção C, PCP I. Antes havia dois aprovadores, e a validação ficava parada.",
      erros: "Mais de um A por tarefa; tarefa sem R; consultar todo mundo em tudo; montar a matriz e não divulgar.",
      ver: ["g-gproj-l7", "g-gproj-l1"] },
    "politica-estoque": { nome: "Políticas de estoque (Q, P e mín–máx)", icone: "🔁", termos: "politica de estoque revisao periodica revisao continua minimo maximo min max posicao de estoque reposicao",
      oque: "Regras de reposição: revisão contínua (pede lote fixo no ponto de pedido), revisão periódica (pede até um nível máximo a intervalos fixos) e mín–máx (ao atingir o mínimo, repõe até o máximo).",
      paraque: "Padronizar quando e quanto repor cada item, com o esforço de controle adequado ao valor dele.",
      quando: "Almoxarifados, compras recorrentes, itens de demanda independente; revisão da política por classe ABC.",
      dados: ["Consumo médio e variação", "Lead time", "Intervalo de revisão", "Estoque físico, em trânsito e comprometido"],
      formulas: [["M = d̄ × (P + LT) + ES", "nível máximo na revisão periódica"], ["Pedido = M − posição de estoque", "quantidade a pedir"], ["Posição = físico + em trânsito − comprometido", "base das decisões"]],
      exemplo: "Revisão semanal (P = 7), LT = 3 dias, consumo de 40 un/dia e ES = 50 → M = 450. Posição na revisão = 180 → pedir 270.",
      erros: "Decidir pelo estoque físico e esquecer o que está em trânsito (pedido em dobro); usar o mesmo estoque de segurança na revisão periódica e na contínua.",
      ver: ["g-pcp1-l7", "g-logist-l2"] },
    "curva-abc": { nome: "Curva ABC", icone: "🔤", termos: "pareto de estoque classificacao abc 80/20",
      oque: "Classificação dos itens pelo valor que representam (consumo × custo). Poucos itens (classe A) concentram a maior parte do valor.",
      paraque: "Decidir onde colocar controle, atenção e negociação: rigor nos itens A, simplicidade nos C.",
      quando: "Estoque alto, muitos itens para gerenciar, definir política de compras ou endereçamento no armazém.",
      dados: ["Lista de itens", "Consumo anual de cada item", "Custo unitário"],
      formulas: [["Valor anual = consumo anual × custo unitário", "base da classificação"], ["% acumulado = Σ valor dos itens até aqui ÷ valor total", "define os cortes A, B e C"]],
      exemplo: "Numa fábrica de doces, 18 dos 120 itens (15%) somam 78% do valor em estoque: são os itens A. A equipe passa a contá-los toda semana e a renegociar lotes só com esses fornecedores.",
      erros: "Classificar só pelo preço unitário (e não pelo valor anual); nunca atualizar a curva; usar cortes fixos 80/15/5 sem olhar os dados.",
      ver: ["g-logist-l2", "g-logist-l3", "g-gqual-l2"] },
    "giro-estoque": { nome: "Giro e cobertura de estoque", icone: "🔄", termos: "giro de estoque cobertura dias de estoque",
      oque: "Giro: quantas vezes o estoque se renova no período. Cobertura: por quantos dias o estoque atual atende o consumo.",
      paraque: "Medir se há estoque parado e comparar itens, famílias e períodos.",
      quando: "Suspeita de excesso, meta de redução de capital de giro, revisão de política de estoques.",
      dados: ["Consumo (ou custo das vendas) no período", "Estoque médio no período", "Consumo médio diário"],
      formulas: [["Giro = consumo no período ÷ estoque médio", "vezes por período"], ["Cobertura (dias) = estoque médio ÷ consumo médio diário", "≈ 365 ÷ giro anual"]],
      exemplo: "Consumo anual de açúcar = 240 t; estoque médio = 40 t → giro = 6 vezes/ano; cobertura ≈ 365 ÷ 6 ≈ 61 dias. Com prazo de entrega de 7 dias, há estoque demais.",
      erros: "Misturar valores em reais com quantidades; usar o estoque do fim do mês em vez do médio; comparar giro de itens com sazonalidade diferente.",
      ver: ["g-logist-l2", "g-contab-l2"] },
    "lec": { nome: "Lote econômico (LEC)", icone: "📐", termos: "lote economico de compra eoq quantidade por pedido",
      oque: "Quantidade por pedido que minimiza a soma do custo de pedir com o custo de manter estoque.",
      paraque: "Definir quanto comprar (ou produzir) de cada vez.",
      quando: "Demanda razoavelmente estável, custos de pedido e de manutenção conhecidos.",
      dados: ["Demanda anual (D)", "Custo por pedido (S)", "Custo de manter uma unidade por ano (H)"],
      formulas: [["Q* = √(2 · D · S ÷ H)", "lote econômico"], ["Nº de pedidos por ano = D ÷ Q*", "frequência de compra"]],
      exemplo: "D = 12.000 un/ano, S = R$ 150 por pedido, H = R$ 4 por unidade/ano → Q* = √(2 × 12.000 × 150 ÷ 4) ≈ 949 un, cerca de 12 a 13 pedidos por ano.",
      erros: "Ignorar lote mínimo do fornecedor, espaço e validade; usar H sem incluir custo de capital; aplicar em demanda muito irregular.",
      ver: ["g-logist-l2", "g-pcp1-l7", "g-calc1-l3", "m03-l5"] },
    "estoque-seguranca": { nome: "Estoque de segurança", icone: "🛟", termos: "estoque de seguranca estoque minimo nivel de servico",
      oque: "Quantidade adicional mantida para reduzir o risco de falta diante da incerteza da demanda ou do prazo de reposição.",
      paraque: "Proteger o nível de serviço sem manter estoque exagerado.",
      quando: "A demanda varia, o fornecedor às vezes atrasa, ou faltas já aconteceram.",
      dados: ["Desvio-padrão da demanda diária (σd)", "Lead time de reposição (LT, em dias)", "Nível de serviço desejado (z)"],
      formulas: [["ES = z · σd · √LT", "demanda variável, lead time fixo"], ["z ≈ 1,28 (90%) · 1,65 (95%) · 2,33 (99%)", "fator do nível de serviço"]],
      exemplo: "σd = 20 un/dia, LT = 4 dias, nível de serviço 95% (z = 1,65) → ES = 1,65 × 20 × √4 = 66 unidades.",
      erros: "Usar a demanda média no lugar do desvio-padrão; esquecer a variação do lead time; pedir 99,9% de serviço para todos os itens (fica caríssimo).",
      ver: ["g-logist-l2", "m13-l8", "m03-l3"] },
    "ponto-pedido": { nome: "Ponto de pedido", icone: "🚩", termos: "ponto de pedido ponto de reposicao quando comprar",
      oque: "Nível de estoque que dispara um novo pedido, calculado para o material chegar antes de acabar.",
      paraque: "Saber quando comprar.",
      quando: "Itens de demanda independente e contínua (material de consumo, produto acabado, peças de reposição).",
      dados: ["Demanda média diária (d̄)", "Lead time (LT)", "Estoque de segurança (ES)"],
      formulas: [["PP = d̄ · LT + ES", "ponto de pedido"]],
      exemplo: "d̄ = 100 un/dia, LT = 4 dias, ES = 66 un → PP = 400 + 66 = 466 unidades. Quando o saldo chegar a 466, faz-se o pedido.",
      erros: "Não considerar pedidos já em trânsito; usar o lead time 'de catálogo' em vez do real; aplicar ponto de pedido a itens que dependem do plano de produção (esses pedem MRP).",
      ver: ["g-logist-l2"] },
    "previsao-demanda": { nome: "Previsão de demanda", icone: "🔮", termos: "previsao de demanda media movel suavizacao exponencial forecast",
      oque: "Estimativa da demanda futura a partir do histórico (médias móveis, suavização exponencial, tendência e sazonalidade) e de informações do mercado.",
      paraque: "Base de todo o planejamento: produção, compras, capacidade e estoque.",
      quando: "Planejar os próximos períodos; sempre que estoque e faltas convivem (sinal de previsão ruim).",
      dados: ["Histórico de vendas/consumo por período", "Eventos que distorcem (promoções, rupturas)", "Informações de vendas e marketing"],
      formulas: [["Média móvel = soma das n últimas demandas ÷ n", "suaviza variações"], ["Fₜ₊₁ = Fₜ + α · (Aₜ − Fₜ)", "suavização exponencial (0 < α < 1)"]],
      exemplo: "Previsão de outubro = 500 caixas; venda real = 560; α = 0,2 → previsão de novembro = 500 + 0,2 × (560 − 500) = 512 caixas.",
      erros: "Usar vendas (limitadas por falta de estoque) como se fossem demanda; ignorar sazonalidade; não medir o erro da previsão.",
      ver: ["m03-l2", "m03-l3", "g-pcp1-l1", "g-pcp1-l5"] },
    "erro-previsao": { nome: "Erro de previsão (MAPE)", icone: "🎯", termos: "mape erro percentual absoluto medio acuracidade",
      oque: "Medida de quanto a previsão erra, em média, em relação ao real.",
      paraque: "Comparar métodos, acompanhar a qualidade da previsão e dimensionar o estoque de segurança.",
      quando: "Sempre que houver uma previsão em uso.",
      dados: ["Demanda real (A) e previsão (F) de vários períodos"],
      formulas: [["MAPE = (Σ |Aₜ − Fₜ| ÷ Aₜ) ÷ n × 100%", "erro percentual médio"], ["Viés = Σ (Aₜ − Fₜ) ÷ n", "mostra se a previsão erra sempre para o mesmo lado"]],
      exemplo: "Três meses com erros de 10%, 5% e 15% → MAPE = 10%. Se o viés é positivo, a previsão está sistematicamente abaixo do real.",
      erros: "Olhar só o MAPE e ignorar o viés; comparar MAPE de itens com volumes muito diferentes; calcular com períodos em que houve ruptura.",
      ver: ["m03-l3"] },
    "mrp": { nome: "MRP", icone: "🧾", termos: "mrp planejamento das necessidades de materiais explosao lista de materiais bom",
      oque: "Cálculo das necessidades de materiais a partir do plano mestre, da lista de materiais (estrutura do produto), dos estoques e dos lead times.",
      paraque: "Saber quanto e quando comprar ou produzir cada componente.",
      quando: "Itens de demanda dependente (componentes, embalagens, matéria-prima de produtos com estrutura).",
      dados: ["Plano mestre (PMP)", "Lista de materiais (BOM)", "Estoques e recebimentos programados", "Lead times e regras de lote"],
      formulas: [["Necessidade líquida = necessidade bruta − estoque disponível − recebimentos programados", "(+ estoque de segurança, se houver)"], ["Liberação do pedido = data de necessidade − lead time", "defasagem no tempo"]],
      exemplo: "500 caixas de bombom na semana 6, 2 bandejas por caixa → necessidade bruta = 1.000 bandejas. Estoque = 300 → necessidade líquida = 700. Lead time de 2 semanas → pedir na semana 4.",
      erros: "Estrutura de produto ou estoques errados (o MRP multiplica o erro); lead times irreais; usar MRP sem checar capacidade.",
      ver: ["m03-l5", "g-pcp1-l4", "g-pcp1-l6", "g-alg1-l4"] },
    "pmp": { nome: "Plano mestre de produção (PMP)", icone: "🗓️", termos: "plano mestre de producao pmp mps disponivel para promessa atp",
      oque: "Plano de quanto produzir de cada produto final, período a período, conciliando previsão, pedidos, estoque e capacidade.",
      paraque: "Dar a base para o MRP e para prometer prazos ao cliente.",
      quando: "Planejamento de curto/médio prazo (semanas) por produto final.",
      dados: ["Previsão e pedidos em carteira", "Estoque inicial", "Tamanho de lote e capacidade"],
      formulas: [["Estoque projetado = estoque anterior + produção − máx(previsão, pedidos)", "controle do saldo"]],
      exemplo: "Estoque de 200, previsão de 300 e pedidos de 250 na semana → sem produção, o estoque ficaria −100; programa-se um lote de 400 e o saldo projetado fica 300.",
      erros: "Mudar o plano toda hora (nervosismo); programar acima da capacidade; esquecer os pedidos já firmados.",
      ver: ["m03-l4", "g-pcp1-l3"] },
    "sop": { nome: "Planejamento agregado e S&OP", icone: "🧭", termos: "sop s&op planejamento agregado vendas e operacoes chase nivelado",
      oque: "Plano por família de produtos, em horizonte de meses, que equilibra demanda, capacidade, estoque e mão de obra; o S&OP é o processo mensal que alinha vendas, operações e finanças.",
      paraque: "Decidir a estratégia: produção nivelada, acompanhar a demanda ou mista.",
      quando: "Sazonalidade, crescimento ou decisões de contratação, hora extra e estoque de antecipação.",
      dados: ["Previsão por família e mês", "Capacidade e custos (hora extra, contratação, estoque, falta)"],
      formulas: [["Custo total do plano = produção + estoque + hora extra + contratação/demissão + falta", "comparar alternativas"]],
      exemplo: "Chocolates com pico na Páscoa: produzir nivelado o ano todo e estocar é mais barato do que contratar temporários só em março? O plano agregado compara os custos.",
      erros: "Planejar por item (e não por família); não envolver vendas e finanças; ignorar capacidade de armazenagem.",
      ver: ["m03-l4", "m03-l1", "g-pcp1-l2"] },
    "capacidade": { nome: "Carga × capacidade", icone: "⚖️", termos: "capacidade carga ocupacao utilizacao eficiencia rccp crp",
      oque: "Comparação entre o trabalho necessário (carga) e o que os recursos conseguem fazer (capacidade) em cada período.",
      paraque: "Saber se o plano cabe na fábrica e onde faltará recurso.",
      quando: "Aumento de demanda, novo produto, promessa de prazo, antes de liberar o plano.",
      dados: ["Quantidades planejadas", "Tempo padrão por item e recurso", "Horas disponíveis (turnos, paradas, eficiência)"],
      formulas: [["Carga = Σ (quantidade × tempo padrão)", "horas necessárias"], ["Ocupação = carga ÷ capacidade × 100%", "acima de 100% = não cabe"]],
      exemplo: "A demanda subiu 20%: carga passa de 1.000 h para 1.200 h por mês; a capacidade efetiva é 1.100 h → ocupação de 109%. Faltam 100 h: hora extra, turno extra ou terceirização no gargalo.",
      erros: "Usar a capacidade teórica (sem paradas e eficiência); olhar a fábrica inteira em vez de cada recurso; esquecer setups.",
      ver: ["m03-l6", "g-pcp2-l1"] },
    "gargalo": { nome: "Gargalo (Teoria das Restrições)", icone: "🍾", termos: "gargalo restricao toc teoria das restricoes throughput",
      oque: "Recurso cuja capacidade é menor que a demanda sobre ele; ele limita a produção de todo o sistema.",
      paraque: "Concentrar a melhoria onde ela aumenta a saída do sistema.",
      quando: "A linha não atinge a produção necessária; há fila (estoque) na frente de uma etapa.",
      dados: ["Capacidade de cada etapa (un/h)", "Demanda", "Onde se acumula estoque"],
      formulas: [["Capacidade da linha = capacidade da etapa mais lenta", "o gargalo manda"], ["5 passos: identificar → explorar → subordinar → elevar → repetir", "método da TOC"]],
      exemplo: "Etapas com 60, 45 e 70 un/h → a linha produz 45 un/h. Uma hora perdida no gargalo é uma hora perdida da fábrica; uma hora ganha fora dele não muda nada.",
      erros: "Melhorar etapas que não são gargalo; deixar o gargalo parar no almoço ou esperando material; confundir recurso muito ocupado com gargalo.",
      ver: ["m04-l6", "g-engmet-l4", "g-contab-l3"] },
    "takt": { nome: "Takt time", icone: "🥁", termos: "takt time ritmo da demanda",
      oque: "Ritmo em que a produção precisa sair para atender a demanda: tempo disponível dividido pela demanda.",
      paraque: "Dimensionar linhas, postos e pessoas conforme o cliente.",
      quando: "Projetar ou rebalancear uma linha; mudança de demanda.",
      dados: ["Tempo disponível por turno (sem pausas)", "Demanda do cliente no mesmo período"],
      formulas: [["Takt = tempo disponível ÷ demanda", "segundos por unidade"]],
      exemplo: "Turno de 480 min − 40 min de pausas = 26.400 s; demanda de 480 ventiladores → takt = 55 s. Qualquer posto com ciclo maior que 55 s atrasa a linha.",
      erros: "Confundir takt (ritmo da demanda) com tempo de ciclo (ritmo da linha); usar o tempo total do turno sem descontar pausas.",
      ver: ["m04-l5", "g-engmet-l3"] },
    "balanceamento": { nome: "Balanceamento de linha", icone: "⚖️", termos: "balanceamento de linha postos eficiencia ociosidade",
      oque: "Distribuição das tarefas entre os postos para que cada um tenha tempo de ciclo próximo ao takt, respeitando a sequência.",
      paraque: "Usar o mínimo de postos e reduzir ociosidade e gargalos.",
      quando: "Nova linha, mudança de demanda, postos muito ociosos ou sobrecarregados.",
      dados: ["Tempo de cada tarefa", "Precedências entre tarefas", "Takt time"],
      formulas: [["N mínimo = Σt ÷ takt (arredondar para cima)", "número de postos"], ["Eficiência = Σt ÷ (N × TC)", "TC = maior tempo de posto"]],
      exemplo: "Σt = 180 s e takt = 55 s → 3,27 → 4 postos. Com TC = 55 s: eficiência = 180 ÷ (4 × 55) = 81,8%.",
      erros: "Ignorar precedências; balancear com tempos que não são padrão; esquecer a variação entre operadores.",
      ver: ["m04-l5", "g-engmet-l3"] },
    "oee": { nome: "OEE", icone: "⚙️", termos: "oee eficiencia global do equipamento disponibilidade performance qualidade",
      oque: "Eficiência global do equipamento: combina disponibilidade, performance (velocidade) e qualidade.",
      paraque: "Mostrar quanto do tempo planejado virou produção boa e onde está a perda.",
      quando: "Máquinas críticas ou gargalo, projetos de TPM, comparar turnos.",
      dados: ["Tempo planejado e tempo de paradas", "Produção e ciclo ideal", "Peças boas e refugadas"],
      formulas: [["OEE = D × P × Q", "disponibilidade × performance × qualidade"], ["D = tempo operando ÷ tempo planejado", "P = (produção × ciclo ideal) ÷ tempo operando · Q = peças boas ÷ produzidas"]],
      exemplo: "D = 90%, P = 85%, Q = 98% → OEE = 0,90 × 0,85 × 0,98 ≈ 75%. A maior perda está na performance (pequenas paradas e velocidade reduzida).",
      erros: "Comparar OEE entre máquinas diferentes como se fosse ranking; mudar o ciclo ideal para 'melhorar' o número; olhar só o OEE total sem os três fatores.",
      ver: ["m06-l7", "m14-l3", "g-gmanut-l3"] },
    "mtbf-mttr": { nome: "MTBF, MTTR e disponibilidade", icone: "🔧", termos: "mtbf mttr disponibilidade confiabilidade manutencao indicadores",
      oque: "MTBF: tempo médio entre falhas. MTTR: tempo médio para reparar. Juntos dão a disponibilidade do equipamento.",
      paraque: "Acompanhar confiabilidade e manutenibilidade e priorizar ações de manutenção.",
      quando: "Máquina quebra com frequência; definir plano de manutenção preventiva.",
      dados: ["Tempo de operação", "Número de falhas", "Tempo total de reparo"],
      formulas: [["MTBF = tempo de operação ÷ nº de falhas", "confiabilidade"], ["MTTR = tempo de reparo ÷ nº de reparos", "manutenibilidade"], ["A = MTBF ÷ (MTBF + MTTR)", "disponibilidade"]],
      exemplo: "400 h de operação, 8 falhas, 16 h de reparo → MTBF = 50 h, MTTR = 2 h, disponibilidade = 50 ÷ 52 ≈ 96,2%.",
      erros: "Contar paradas planejadas como falha; não registrar pequenas paradas; olhar só a média sem ver as causas das falhas.",
      ver: ["g-gmanut-l2", "g-estqual-l4"] },
    "tpm": { nome: "TPM (Manutenção Produtiva Total)", icone: "🛠️", termos: "tpm manutencao autonoma manutencao produtiva total pilares",
      oque: "Programa que envolve produção e manutenção para eliminar perdas dos equipamentos, com manutenção autônoma pelos operadores, planejada e melhorias focadas.",
      paraque: "Aumentar disponibilidade e OEE de forma sustentada.",
      quando: "Muitas quebras, pequenas paradas e sujeira/desgaste nas máquinas.",
      dados: ["Histórico de falhas", "OEE e perdas por tipo", "Rotinas de limpeza, inspeção e lubrificação"],
      formulas: [],
      exemplo: "Operadores passam a limpar, inspecionar e lubrificar a envasadora no início do turno (manutenção autônoma); vazamentos são detectados cedo e as quebras caem pela metade em três meses.",
      erros: "Tratar TPM como tarefa só da manutenção; começar sem treinar operadores; não medir antes e depois.",
      ver: ["m06-l7", "g-gmanut-l3"] },
    "smed": { nome: "SMED (troca rápida)", icone: "⏩", termos: "smed troca rapida setup set-up setup externo interno",
      oque: "Método para reduzir o tempo de setup separando atividades internas (máquina parada) das externas (máquina rodando), convertendo internas em externas e simplificando o restante.",
      paraque: "Trocar de produto mais vezes com lotes menores, mais flexibilidade e menos estoque.",
      quando: "Setups longos forçam lotes grandes; mix de produtos crescente.",
      dados: ["Vídeo ou registro de uma troca", "Lista de atividades e tempos"],
      formulas: [["Setup interno = só o que exige a máquina parada", "o que sobra depois do SMED"]],
      exemplo: "Troca de 60 min: 25 min eram buscar ferramentas e o molde seguinte (externo). Com kit preparado antes e engate rápido, a troca cai para 20 min.",
      erros: "Pular a separação interno × externo; não padronizar a nova troca; reduzir o setup e manter os lotes do mesmo tamanho.",
      ver: ["m06-l6"] },
    "heijunka": { nome: "Heijunka (nivelamento)", icone: "📶", termos: "heijunka nivelamento da producao mix pitch",
      oque: "Nivelamento do volume e do mix de produção ao longo do tempo, em vez de grandes lotes de cada produto.",
      paraque: "Reduzir estoque e picos de carga e atender pedidos variados todos os dias.",
      quando: "Depois de reduzir setups; demanda de vários produtos ao mesmo tempo.",
      dados: ["Demanda por produto", "Tempo de setup", "Takt/pitch"],
      formulas: [["Pitch = takt × quantidade por embalagem", "intervalo de liberação de trabalho"]],
      exemplo: "Em vez de fazer só o bombom A na segunda e só o B na terça, a linha repete todo dia a sequência A-A-B-C conforme a proporção da demanda.",
      erros: "Nivelar com setups longos (a linha para o tempo todo); nivelar sem demanda minimamente estável.",
      ver: ["m06-l6"] },
    "sequenciamento": { nome: "Regras de sequenciamento", icone: "🔢", termos: "sequenciamento programacao peps spt edd mtp data de entrega prioridade",
      oque: "Critérios para decidir a ordem das ordens de produção num recurso: PEPS (primeiro a entrar), SPT/MTP (menor tempo de processamento), EDD (data de entrega mais cedo), entre outras.",
      paraque: "Reduzir atrasos e tempo médio de fluxo.",
      quando: "Fila de ordens num recurso, prazos apertados.",
      dados: ["Ordens na fila", "Tempo de processamento de cada uma", "Data prometida"],
      formulas: [["Atraso = máx(0, término − data de entrega)", "por ordem"], ["SPT minimiza o tempo médio de fluxo · EDD minimiza o atraso máximo", "resultados clássicos (1 máquina)"]],
      exemplo: "A (6 h, entrega em 8 h), B (2 h, em 6 h), C (4 h, em 15 h). Por EDD (B, A, C) todas saem no prazo; por SPT (B, C, A) a ordem A atrasa 4 h.",
      erros: "Usar sempre a mesma regra; mudar a sequência a toda hora (troca de setups); ignorar o gargalo.",
      ver: ["m03-l7", "g-pcp2-l2"] },
    "kanban": { nome: "Kanban e produção puxada", icone: "🟨", termos: "kanban producao puxada supermercado cartao jit just in time",
      oque: "Sistema em que a etapa seguinte 'puxa' o que consumiu; cartões kanban autorizam produção ou movimentação e limitam o estoque em processo.",
      paraque: "Controlar WIP e estoque e evitar superprodução.",
      quando: "Itens de demanda repetitiva e razoavelmente estável.",
      dados: ["Demanda (D)", "Lead time de reposição (L)", "Tamanho do contêiner (C)", "Fator de segurança (α)"],
      formulas: [["N = D × L × (1 + α) ÷ C (arredondar para cima)", "número de kanbans"]],
      exemplo: "D = 100 un/h, L = 2 h, α = 10%, C = 20 un → N = 100 × 2 × 1,1 ÷ 20 = 11 cartões.",
      erros: "Kanban com demanda muito instável; cartões demais (vira estoque); não respeitar a regra de não produzir sem cartão.",
      ver: ["m06-l4", "m02-l9", "g-pcp2-l4"] },
    "lei-little": { nome: "Lei de Little", icone: "⏳", termos: "lei de little wip lead time throughput estoque em processo",
      oque: "Relação entre estoque em processo (WIP), vazão (throughput) e lead time em sistemas estáveis.",
      paraque: "Mostrar que reduzir o WIP reduz o lead time.",
      quando: "Lead time longo, muita coisa 'em andamento', prazos atrasados.",
      dados: ["WIP médio", "Vazão média (un/dia)"],
      formulas: [["WIP = vazão × lead time", "lead time = WIP ÷ vazão"]],
      exemplo: "400 pedidos em processo e vazão de 50 pedidos/dia → lead time médio = 8 dias. Limitando o WIP a 200, o lead time cai para ~4 dias com a mesma vazão.",
      erros: "Aplicar em sistema instável (a fila crescendo); confundir vazão com capacidade.",
      ver: ["m02-l9", "m03-l7", "g-po2-l2"] },
    "otif": { nome: "OTIF / nível de serviço", icone: "📬", termos: "otif on time in full nivel de servico entrega no prazo completa",
      oque: "Percentual de pedidos entregues no prazo (on time) e completos (in full).",
      paraque: "Medir a entrega do ponto de vista do cliente, para clientes e fornecedores.",
      quando: "Reclamações de atraso, avaliação de fornecedores, meta de logística.",
      dados: ["Pedidos com data prometida e data de entrega", "Quantidade pedida e entregue"],
      formulas: [["OTIF = pedidos no prazo e completos ÷ total de pedidos × 100%", "por período"]],
      exemplo: "500 pedidos no mês; 470 chegaram no prazo e completos → OTIF = 94%. Dos 30 falhos, 22 foram incompletos (problema de estoque/separação) e 8 atrasados.",
      erros: "Medir só 'no prazo' ou só 'completo'; usar a data que a empresa quer, e não a combinada com o cliente.",
      ver: ["m01-l8", "g-pcp2-l3", "g-logist-l4"] },
    "cep": { nome: "CEP (cartas de controle)", icone: "📉", termos: "cep controle estatistico do processo carta de controle xbarra r limites",
      oque: "Gráficos que acompanham uma característica ao longo do tempo com limites de controle calculados do próprio processo.",
      paraque: "Separar variação comum (do sistema) de causas especiais que precisam de ação.",
      quando: "Processos repetitivos com medições frequentes (peso, dimensão, temperatura, tempo).",
      dados: ["Subgrupos de medições ao longo do tempo (ex.: 5 peças a cada hora)"],
      formulas: [["LC = média ± 3 desvios-padrão da estatística", "ideia geral"], ["Carta X̄: LSC/LIC = X̿ ± A₂ · R̄", "A₂ = 0,577 para n = 5"]],
      exemplo: "X̿ = 50,0 g, R̄ = 0,4 g, n = 5 → limites = 50,0 ± 0,577 × 0,4 = 49,77 a 50,23 g. Um ponto fora ou sequências estranhas indicam causa especial.",
      erros: "Confundir limite de controle com especificação; ajustar a máquina a cada ponto (piora a variação); recalcular os limites com dados fora de controle.",
      ver: ["g-estqual-l1", "m13-l8"] },
    "capabilidade": { nome: "Capacidade do processo (Cp e Cpk)", icone: "🎯", termos: "cp cpk capacidade do processo capabilidade especificacao",
      oque: "Índices que comparam a variação do processo com a tolerância da especificação; o Cpk também considera se o processo está centrado.",
      paraque: "Saber se o processo consegue produzir dentro da especificação e quanto sai fora.",
      quando: "Depois que o processo está estável (sob controle).",
      dados: ["Limites de especificação (LIE e LSE)", "Média e desvio-padrão do processo"],
      formulas: [["Cp = (LSE − LIE) ÷ (6σ)", "potencial"], ["Cpk = mín(LSE − μ; μ − LIE) ÷ (3σ)", "real (considera o centro)"]],
      exemplo: "LIE = 49,7 mm, LSE = 50,3 mm, μ = 50,1 mm, σ = 0,1 mm → Cp = 1,0 e Cpk = 0,67. Centralizar a média em 50,0 já leva o Cpk a 1,0; referência comum: Cpk ≥ 1,33.",
      erros: "Calcular com processo instável; usar poucos dados; ignorar que Cp alto com Cpk baixo significa processo descentrado.",
      ver: ["g-estqual-l2", "m13-l8", "m13-l12"] },
    "histograma": { nome: "Histograma, média e desvio-padrão", icone: "📊", termos: "histograma media mediana desvio padrao estatistica descritiva variacao cv",
      oque: "Resumo dos dados: o histograma mostra a forma da distribuição; média e mediana mostram o centro; desvio-padrão e CV mostram a variação.",
      paraque: "Entender o comportamento de um processo antes de decidir.",
      quando: "Sempre que houver um conjunto de medições para analisar.",
      dados: ["Medições (pelo menos 30, idealmente)"],
      formulas: [["x̄ = Σx ÷ n", "média"], ["s = √(Σ(x − x̄)² ÷ (n − 1))", "desvio-padrão amostral"], ["CV = s ÷ x̄ × 100%", "variação relativa"]],
      exemplo: "Duas envasadoras com média de 500 g: a A tem s = 2 g e a B tem s = 8 g. Mesma média, processos muito diferentes: a B precisa de atenção.",
      erros: "Olhar só a média; usar média com outliers fortes (prefira mediana); histograma com poucas ou muitas classes.",
      ver: ["m13-l2", "m13-l3", "m13-l5", "g-estat-l1"] },
    "teste-hipoteses": { nome: "Teste de hipóteses", icone: "⚗️", termos: "teste de hipoteses valor p p-valor significancia teste t anova",
      oque: "Procedimento para decidir, com dados, se uma diferença observada é real ou pode ser acaso, controlando o risco de erro.",
      paraque: "Provar (ou não) que uma melhoria, fornecedor ou método é diferente.",
      quando: "Comparar antes × depois, dois fornecedores, duas máquinas.",
      dados: ["Amostras de cada grupo", "Nível de significância (α, ex.: 5%)"],
      formulas: [["H₀: não há diferença · H₁: há diferença", "hipóteses"], ["Se valor-p < α → rejeita H₀", "decisão"]],
      exemplo: "Tempo médio de setup caiu de 42 para 36 min após a melhoria; o teste t dá valor-p = 0,02 < 0,05 → a redução é estatisticamente significativa.",
      erros: "Achar que 'não rejeitar H₀' prova que não há diferença; testar muitas coisas até algo dar significativo; ignorar se a diferença é relevante na prática.",
      ver: ["m13-l10", "g-metest-l1", "g-metest-l2"] },
    "intervalo-confianca": { nome: "Intervalo de confiança", icone: "↔️", termos: "intervalo de confianca margem de erro amostragem",
      oque: "Faixa de valores que, com uma confiança definida (ex.: 95%), contém o valor real da população estimado a partir de uma amostra.",
      paraque: "Comunicar a incerteza de uma estimativa, e não só um número.",
      quando: "Estimar média de peso, tempo, defeitos a partir de amostras.",
      dados: ["Média e desvio-padrão da amostra", "Tamanho da amostra (n)", "Nível de confiança"],
      formulas: [["IC = x̄ ± z · σ ÷ √n", "(ou t · s ÷ √n com amostra pequena)"]],
      exemplo: "x̄ = 50,1 mm, s = 0,1 mm, n = 25 → IC 95% ≈ 50,1 ± 1,96 × 0,02 = 50,06 a 50,14 mm. O alvo de 50,0 está fora: a média está deslocada.",
      erros: "Dizer que '95% das peças estão no intervalo' (o IC é da média); usar amostra não aleatória.",
      ver: ["m13-l9", "g-estat-l4"] },
    "regressao": { nome: "Correlação e regressão", icone: "📈", termos: "correlacao regressao linear r r2 dispersao tendencia",
      oque: "Correlação mede a força da relação linear entre duas variáveis; a regressão estima uma equação (y = a + b·x) para prever uma a partir da outra.",
      paraque: "Prever (demanda, consumo, tempo) e entender relações entre variáveis.",
      quando: "Suspeita de que uma variável influencia outra; previsão com tendência.",
      dados: ["Pares de valores (x, y)", "Idealmente dezenas de observações"],
      formulas: [["ŷ = a + b · x", "reta de regressão"], ["−1 ≤ r ≤ 1 · R² = parcela da variação explicada", "correlação e ajuste"]],
      exemplo: "Energia (kWh) × toneladas produzidas: ŷ = 1.200 + 85·x, R² = 0,91. Para 40 t, prevê-se ≈ 4.600 kWh; um dia com 6.000 kWh merece investigação.",
      erros: "Concluir causa a partir de correlação; extrapolar fora da faixa dos dados; ignorar outliers.",
      ver: ["m13-l11", "g-metest-l3", "m03-l3"] },
    "pareto": { nome: "Diagrama de Pareto", icone: "📊", termos: "pareto 80/20 poucos vitais muitos triviais",
      oque: "Gráfico de barras em ordem decrescente com a curva acumulada; mostra que poucas causas respondem pela maior parte do problema.",
      paraque: "Escolher onde atacar primeiro.",
      quando: "Muitos tipos de defeito, reclamação, parada ou custo.",
      dados: ["Ocorrências (ou custo) por categoria", "Período definido"],
      formulas: [["% acumulado = Σ das categorias até aqui ÷ total", "curva acumulada"]],
      exemplo: "5 tipos de defeito na embalagem: selagem (46%) e rótulo torto (32%) somam 78%. O projeto de melhoria começa pela selagem.",
      erros: "Categorias genéricas demais ('outros' gigante); contar ocorrências quando o custo seria o critério certo; nunca refazer o Pareto após a melhoria.",
      ver: ["g-gqual-l2", "m01-l8"] },
    "ishikawa": { nome: "Diagrama de Ishikawa", icone: "🐟", termos: "ishikawa espinha de peixe causa e efeito 6m",
      oque: "Diagrama de causa e efeito (espinha de peixe) que organiza as possíveis causas de um problema, em geral pelos 6M: método, máquina, material, mão de obra, meio ambiente e medida.",
      paraque: "Levantar hipóteses de causa com a equipe sem esquecer nenhuma área.",
      quando: "Depois de definir bem o problema (o 'efeito'), antes de escolher a ação.",
      dados: ["Problema bem definido", "Equipe que conhece o processo", "Dados para verificar as causas"],
      formulas: [],
      exemplo: "Efeito: selagem falhando. Máquina: resistência desgastada; Material: filme de outro fornecedor; Método: temperatura ajustada 'no olho'; Medida: termômetro descalibrado. Cada hipótese é verificada com dados.",
      erros: "Tratar todas as ideias como causas comprovadas; efeito vago ('qualidade ruim'); parar no diagrama sem verificar.",
      ver: ["g-gqual-l2", "m06-l8"] },
    "cinco-porques": { nome: "5 porquês", icone: "❓", termos: "5 porques cinco porques causa raiz",
      oque: "Perguntar 'por quê?' repetidas vezes (cerca de cinco) a partir do problema até chegar a uma causa que, eliminada, impede a repetição.",
      paraque: "Sair do sintoma e chegar à causa raiz de forma simples.",
      quando: "Problemas com cadeia de causas relativamente linear; análise de falhas e quase acidentes.",
      dados: ["Fatos do local (gemba)", "Pessoas envolvidas no processo"],
      formulas: [],
      exemplo: "A máquina parou → fusível queimou → sobrecarga → rolamento travado → falta de lubrificação → não havia rotina de lubrificação. Ação: rotina de lubrificação (e não só trocar o fusível).",
      erros: "Parar na culpa de uma pessoa; responder com suposições em vez de fatos; forçar exatamente cinco perguntas.",
      ver: ["m06-l8", "g-segtrab-l4"] },
    "poka-yoke": { nome: "Poka-yoke", icone: "🧩", termos: "poka yoke a prova de erros dispositivo",
      oque: "Dispositivo ou método à prova de erros: impede que o erro aconteça ou o detecta imediatamente.",
      paraque: "Eliminar defeitos causados por falhas humanas previsíveis.",
      quando: "Erros repetitivos de montagem, peça invertida, etapa esquecida.",
      dados: ["Tipo de erro e onde ocorre", "Frequência"],
      formulas: [],
      exemplo: "Tampa que só encaixa numa posição (gabarito assimétrico) e balança que trava a linha se a caixa estiver com menos bombons.",
      erros: "Depender de 'mais atenção' ou treinamento como única ação; poka-yoke que o operador consegue burlar facilmente.",
      ver: ["m06-l7", "g-procfab-l4"] },
    "pdca": { nome: "PDCA e A3", icone: "🔁", termos: "pdca planejar fazer checar agir a3 kaizen melhoria continua",
      oque: "Ciclo de melhoria: Planejar (problema, causa, plano), Fazer, Checar (resultado com dados) e Agir (padronizar ou corrigir). O A3 registra esse raciocínio numa folha.",
      paraque: "Resolver problemas de forma estruturada e manter a melhoria.",
      quando: "Qualquer projeto de melhoria, reclamação de cliente, kaizen.",
      dados: ["Situação atual com números", "Meta", "Análise de causa", "Plano de ação e resultado"],
      formulas: [],
      exemplo: "A3 da selagem: situação (4% de refugo), meta (1%), causa raiz (temperatura sem padrão), ação (controle automático), checagem (0,8% em 4 semanas), padronização (instrução de trabalho).",
      erros: "Pular o 'Checar'; não padronizar (o problema volta); A3 que é só um formulário preenchido depois.",
      ver: ["m06-l8", "g-gqual-l2"] },
    "cinco-s": { nome: "5S", icone: "🧹", termos: "5s seiri seiton seiso seiketsu shitsuke organizacao",
      oque: "Método de organização do local de trabalho: utilização (Seiri), organização (Seiton), limpeza (Seiso), padronização (Seiketsu) e disciplina (Shitsuke).",
      paraque: "Reduzir procura, deslocamento, erros e acidentes; base para outras melhorias.",
      quando: "Ambiente desorganizado, tempo perdido procurando coisas, início de programa Lean.",
      dados: ["Fotos antes/depois", "Checklist de auditoria"],
      formulas: [],
      exemplo: "No almoxarifado, itens sem uso há 1 ano vão para a área de descarte, os demais ganham endereço e etiqueta, e uma auditoria mensal mantém o padrão.",
      erros: "Virar faxina de um dia; não definir padrão e auditoria; fazer sem envolver quem trabalha no local.",
      ver: ["m06-l3"] },
    "vsm": { nome: "Mapeamento do fluxo de valor (VSM)", icone: "🗺️", termos: "vsm mapeamento do fluxo de valor value stream lead time pce",
      oque: "Mapa de ponta a ponta do fluxo de materiais e informações de uma família de produtos, com tempos, estoques e lead time.",
      paraque: "Enxergar desperdícios no fluxo inteiro e desenhar o estado futuro.",
      quando: "Lead time longo, muita espera e estoque entre etapas, planejar transformação Lean.",
      dados: ["Etapas e tempos de ciclo", "Estoques entre etapas", "Demanda e fluxo de informação"],
      formulas: [["Lead time ≈ Σ dias de estoque + Σ tempos de processo", "tempo total"], ["PCE = tempo que agrega valor ÷ lead time", "eficiência do ciclo"]],
      exemplo: "Lead time de 12 dias para 45 min de trabalho que agrega valor: PCE < 1%. Os estoques entre corte e montagem são o primeiro alvo.",
      erros: "Mapear pela sala de reunião (e não no chão de fábrica); mapear todos os produtos juntos; fazer o mapa e não o plano do estado futuro.",
      ver: ["m06-l5"] },
    "desperdicios": { nome: "Os 8 desperdícios", icone: "🗑️", termos: "desperdicios muda mura muri 7 desperdicios lean",
      oque: "Atividades que consomem recursos sem agregar valor: superprodução, espera, transporte, superprocessamento, estoque, movimentação, defeitos e talento não aproveitado.",
      paraque: "Treinar o olhar para encontrar melhorias no processo.",
      quando: "Caminhada no gemba, VSM, kaizen.",
      dados: ["Observação do processo", "Tempos e distâncias"],
      formulas: [],
      exemplo: "Operador anda 40 m por ciclo para buscar embalagens (movimentação); aproximar o estoque da linha elimina 15 min por turno.",
      erros: "Achar que desperdício é só material jogado fora; atacar o sintoma (estoque) sem ver a causa (setup, variação).",
      ver: ["m06-l2", "m06-l1"] },
    "tempo-padrao": { nome: "Cronoanálise e tempo padrão", icone: "⏱️", termos: "cronoanalise tempo padrao tempo normal ritmo tolerancia cronometragem",
      oque: "Medição do tempo de uma operação (cronoanálise) ajustada pelo ritmo do operador e acrescida de tolerâncias, resultando no tempo padrão.",
      paraque: "Planejar capacidade, custear, balancear linhas e definir metas justas.",
      quando: "Método já padronizado e operador treinado.",
      dados: ["Tempos cronometrados de vários ciclos", "Avaliação de ritmo (FR)", "Tolerâncias (pessoais, fadiga, espera)"],
      formulas: [["TN = TO × FR", "tempo normal"], ["TP = TN × (1 + T)", "tempo padrão"], ["n = (z · s ÷ (Er · x̄))²", "nº de ciclos a medir"]],
      exemplo: "TO = 50 s, ritmo 110% → TN = 55 s; tolerância 15% → TP = 55 × 1,15 ≈ 63,3 s por peça.",
      erros: "Cronometrar antes de padronizar o método; medir poucos ciclos; esquecer tolerâncias ou aplicá-las duas vezes.",
      ver: ["m04-l2", "m04-l3", "g-engmet-l2"] },
    "fluxograma": { nome: "Fluxograma e estudo de métodos", icone: "🔀", termos: "fluxograma estudo de metodos mapofluxograma asme eliminar combinar",
      oque: "Registro das etapas de um processo com símbolos (operação, transporte, inspeção, espera, armazenagem) para analisar e melhorar o método.",
      paraque: "Eliminar, combinar, reordenar e simplificar etapas.",
      quando: "Antes de medir tempos; processo pouco conhecido ou com muitas etapas sem valor.",
      dados: ["Etapas observadas no local", "Distâncias e tempos aproximados"],
      formulas: [],
      exemplo: "O fluxograma do recebimento mostra 3 inspeções e 4 esperas para cada lote; eliminar uma inspeção duplicada e juntar duas movimentações reduz o tempo em 30%.",
      erros: "Desenhar o processo 'ideal' em vez do real; não questionar cada etapa (por que existe?).",
      ver: ["m04-l1", "g-engmet-l1"] },
    "trabalho-padronizado": { nome: "Trabalho padronizado", icone: "📋", termos: "trabalho padronizado instrucao de trabalho padrao operacional pop",
      oque: "Melhor forma atual de fazer a tarefa, documentada com sequência, tempo e estoque padrão, usada por todos até ser melhorada.",
      paraque: "Reduzir variação, treinar novatos e servir de base para a melhoria.",
      quando: "Resultados variam entre turnos ou pessoas; após uma melhoria (para não voltar atrás).",
      dados: ["Sequência de trabalho", "Tempos por elemento", "Takt"],
      formulas: [],
      exemplo: "Depois do SMED, a nova troca vira uma folha de trabalho padronizado com fotos; o tempo de troca deixa de variar entre 20 e 50 min.",
      erros: "Padrão escrito que ninguém segue; padrão que nunca é revisado; criar sem ouvir os operadores.",
      ver: ["m06-l3"] },
    "custeio": { nome: "Custeio por absorção × variável", icone: "🧮", termos: "custeio por absorcao custeio variavel custo direto indireto fixo variavel mod cif",
      oque: "Absorção: todos os custos de produção (inclusive fixos) vão para o produto; é o exigido na contabilidade societária/fiscal. Variável: só os custos variáveis vão para o produto e os fixos vão para o resultado do período; é o mais útil para decisões.",
      paraque: "Calcular o custo do produto e apoiar preço e decisões de mix.",
      quando: "Formar preço, analisar lucratividade de produtos, decidir fazer × comprar.",
      dados: ["Custos diretos (MP, MOD)", "Custos indiretos (CIF) e critério de rateio", "Custos fixos e variáveis"],
      formulas: [["Custo de produção = MP + MOD + CIF", "absorção"], ["Custo unitário = custo total ÷ quantidade", "com volume maior, o fixo por unidade cai"]],
      exemplo: "Bombom com MP + embalagem = R$ 3,00 e fixo rateado de R$ 1,50: pela absorção custa R$ 4,50; para decidir um pedido extra com capacidade ociosa, o custo relevante é R$ 3,00.",
      erros: "Tomar decisões de curto prazo com custo que inclui fixo rateado; ratear indiretos por um critério que não tem relação com o consumo.",
      ver: ["g-custos-l1", "g-custos-l2"] },
    "custeio-abc": { nome: "Custeio ABC (por atividades)", icone: "🏷️", termos: "custeio abc custeio baseado em atividades direcionador de custo",
      oque: "Método que atribui custos indiretos às atividades e das atividades aos produtos pelos direcionadores de custo (setups, pedidos, inspeções).",
      paraque: "Evitar distorções quando produtos consomem recursos indiretos de forma muito diferente.",
      quando: "Custos indiretos altos e grande variedade de produtos/lotes.",
      dados: ["Custo de cada atividade", "Volume do direcionador por produto"],
      formulas: [["Taxa da atividade = custo da atividade ÷ volume do direcionador", "ex.: R$ por setup"], ["Custo do produto += taxa × quantidade do direcionador que consome", "atribuição"]],
      exemplo: "Setups custam R$ 60.000/mês para 300 setups → R$ 200 por setup. Um produto de lote pequeno com 60 setups recebe R$ 12.000, muito mais do que pelo rateio por horas-máquina.",
      erros: "Detalhar atividades demais (sistema caro de manter); usar direcionadores sem relação de causa.",
      ver: ["g-custos-l3"] },
    "margem-contribuicao": { nome: "Margem de contribuição", icone: "➕", termos: "margem de contribuicao mc custos variaveis decisao de preco",
      oque: "Quanto cada unidade vendida sobra, depois dos custos e despesas variáveis, para pagar os custos fixos e gerar lucro.",
      paraque: "Decidir preço, mix, aceitar pedidos e fazer × comprar.",
      quando: "Pedido com desconto, escolha de quais produtos priorizar, análise de rentabilidade.",
      dados: ["Preço de venda", "Custos e despesas variáveis por unidade"],
      formulas: [["MC unitária = preço − custos e despesas variáveis unitários", "R$ por unidade"], ["MC por recurso escasso = MC ÷ tempo no gargalo", "prioridade quando há restrição"]],
      exemplo: "Preço R$ 50, variáveis R$ 30 → MC = R$ 20 (40%). Um pedido extra a R$ 40 ainda tem MC de R$ 10 por unidade se houver capacidade ociosa.",
      erros: "Incluir custos fixos rateados na margem; aceitar pedido com MC positiva quando o gargalo está cheio (tira espaço de produto mais rentável).",
      ver: ["g-contab-l3", "g-custos-l2"] },
    "ponto-equilibrio": { nome: "Ponto de equilíbrio", icone: "⚖️", termos: "ponto de equilibrio break even lucro zero",
      oque: "Volume de vendas em que a receita cobre exatamente os custos totais (lucro zero).",
      paraque: "Saber o mínimo a vender e avaliar riscos de mudanças de preço e custo.",
      quando: "Novo produto, mudança de preço, planejamento de vendas, abertura de negócio.",
      dados: ["Custos fixos do período", "Margem de contribuição unitária"],
      formulas: [["PE (unidades) = custos fixos ÷ MC unitária", "ponto de equilíbrio"], ["PE (R$) = custos fixos ÷ MC%", "em receita"]],
      exemplo: "Custos fixos de R$ 40.000/mês e MC de R$ 20 por unidade → PE = 2.000 unidades/mês.",
      erros: "Misturar produtos com margens diferentes sem ponderar o mix; esquecer despesas fixas de vendas e administração.",
      ver: ["g-contab-l3", "g-gempr-l4"] },
    "vpl-tir": { nome: "VPL, TIR e payback", icone: "💹", termos: "vpl valor presente liquido tir taxa interna de retorno payback tma investimento",
      oque: "Métodos para avaliar investimentos: VPL traz todos os fluxos de caixa a valor presente pela taxa mínima de atratividade (TMA); TIR é a taxa que zera o VPL; payback é o tempo para recuperar o investimento.",
      paraque: "Decidir se um investimento vale a pena e comparar alternativas.",
      quando: "Compra de máquina, automação, projeto de melhoria com investimento.",
      dados: ["Investimento inicial", "Fluxos de caixa esperados por período", "TMA da empresa", "Vida útil"],
      formulas: [["VPL = Σ FCₜ ÷ (1 + i)ᵗ − I₀", "aceitar se VPL > 0"], ["TIR: taxa em que VPL = 0", "aceitar se TIR > TMA"], ["Payback simples = investimento ÷ fluxo anual (se constante)", "tempo de retorno"]],
      exemplo: "Máquina de R$ 100.000 que economiza R$ 30.000/ano por 5 anos, TMA de 12% → VPL ≈ R$ 8.143 (> 0), TIR ≈ 15,2% (> 12%), payback simples ≈ 3,3 anos. Vale a pena.",
      erros: "Usar payback como único critério; esquecer impostos, capital de giro e valor residual; comparar projetos de tamanhos muito diferentes só pela TIR.",
      ver: ["g-engeco-l3", "g-engeco-l1", "g-engeco-l4"] },
    "ergonomia": { nome: "Ergonomia do posto (NR-17)", icone: "🪑", termos: "ergonomia nr-17 nr17 antropometria postura biomecanica aet",
      oque: "Adaptação do trabalho às pessoas: alturas, alcances, esforços, repetição, ambiente e organização do trabalho. A NR-17 exige avaliar as condições de trabalho (avaliação ergonômica preliminar e, quando necessário, Análise Ergonômica do Trabalho — AET).",
      paraque: "Prevenir lesões e fadiga e melhorar produtividade e qualidade.",
      quando: "Queixas de dor, afastamentos, novo posto, mudança de ritmo.",
      dados: ["Medidas do posto e dos trabalhadores (antropometria)", "Posturas, cargas, frequência de movimentos", "Relatos dos trabalhadores"],
      formulas: [["Projetar alcance para o percentil 5 e espaço livre para o percentil 95", "regra antropométrica usual"]],
      exemplo: "Bancada fixa a 75 cm obrigava operadores altos a curvar o tronco; com bancada regulável e peças a menos de 50 cm do corpo, as queixas de lombar caíram.",
      erros: "Projetar para a 'pessoa média'; resolver só com ginástica laboral; ignorar ritmo e pausas.",
      ver: ["g-ergo-l2", "g-ergo-l3", "g-ergo-l4"] },
    "hierarquia-controles": { nome: "Hierarquia de controles de risco", icone: "🦺", termos: "hierarquia de controles epi epc risco seguranca do trabalho",
      oque: "Ordem de preferência das medidas de segurança: eliminar o perigo, substituir, controles de engenharia (proteções, EPC), controles administrativos (procedimentos, treinamento) e, por último, EPI.",
      paraque: "Escolher a medida mais eficaz, e não só a mais fácil.",
      quando: "Após identificar um perigo ou investigar um acidente/quase acidente.",
      dados: ["Perigos identificados", "Avaliação de risco (probabilidade × severidade)"],
      formulas: [["Risco = probabilidade × severidade", "matriz de risco"]],
      exemplo: "Risco de corte na embaladora: em vez de só exigir luva (EPI), instala-se proteção com intertravamento que para a máquina ao abrir (engenharia).",
      erros: "Começar pelo EPI; confiar só em treinamento; não verificar se a medida funcionou.",
      ver: ["g-segtrab-l2", "g-segtrab-l1", "g-segtrab-l4"] },
    "motivacao": { nome: "Motivação e liderança", icone: "🤝", termos: "motivacao maslow herzberg lideranca equipes engajamento",
      oque: "Teorias que explicam o que leva as pessoas a se engajarem, como Maslow (necessidades) e Herzberg (fatores higiênicos evitam insatisfação; motivadores geram satisfação).",
      paraque: "Liderar equipes e desenhar o trabalho de forma que as pessoas se engajem.",
      quando: "Baixo engajamento, rotatividade, implantação de melhorias que dependem das pessoas.",
      dados: ["Conversas e pesquisas de clima", "Indicadores de faltas e rotatividade"],
      formulas: [],
      exemplo: "Além de corrigir o ar-condicionado (higiênico), o supervisor passa a apresentar os resultados das ideias dos operadores no quadro de gestão visual (reconhecimento): as sugestões triplicam.",
      erros: "Achar que só dinheiro motiva; cobrar resultados sem dar autonomia e retorno.",
      ver: ["g-psico-l1", "g-psico-l2"] },
    "curva-aprendizagem": { nome: "Curva de aprendizagem", icone: "📚", termos: "curva de aprendizagem wright experiencia tempo por unidade",
      oque: "Modelo em que o tempo por unidade cai a uma taxa constante toda vez que a produção acumulada dobra.",
      paraque: "Prever tempos e custos de produtos novos e de operadores em treinamento.",
      quando: "Lançamento de produto, novo operador, orçamento de lotes iniciais.",
      dados: ["Tempo da 1ª unidade (T₁)", "Taxa de aprendizagem (ex.: 80%)"],
      formulas: [["Tₙ = T₁ · nᵇ, com b = log(taxa) ÷ log 2", "tempo da n-ésima unidade"]],
      exemplo: "T₁ = 100 min, taxa de 80% → T₂ = 80, T₄ = 64, T₈ = 51,2 min.",
      erros: "Usar a mesma taxa para qualquer tarefa; esquecer que a curva estabiliza (o tempo não cai para sempre).",
      ver: ["m04-l4"] },
    "programacao-linear": { nome: "Programação linear", icone: "📏", termos: "programacao linear pl otimizacao simplex restricoes funcao objetivo preco sombra",
      oque: "Modelo matemático com variáveis de decisão, uma função objetivo (maximizar lucro ou minimizar custo) e restrições lineares (recursos).",
      paraque: "Encontrar a melhor decisão possível quando recursos são limitados: mix, mistura, transporte, escala.",
      quando: "Vários produtos disputam recursos; decisões com muitas combinações.",
      dados: ["Lucro ou custo por unidade de cada variável", "Consumo de recursos por unidade", "Disponibilidade dos recursos"],
      formulas: [["máx Z = c₁x₁ + c₂x₂ + …", "função objetivo"], ["a₁₁x₁ + a₁₂x₂ + … ≤ b₁ ;  x ≥ 0", "restrições"]],
      exemplo: "Máx Z = 3x + 5y sujeito a x ≤ 4; 2y ≤ 12; 3x + 2y ≤ 18; x, y ≥ 0 → solução ótima x = 2, y = 6, Z = 36. O preço-sombra de cada restrição mostra quanto vale 1 unidade a mais de recurso.",
      erros: "Esquecer restrições reais (demanda máxima, mínimos contratuais); usar dados imprecisos e confiar cegamente na resposta; ignorar a análise de sensibilidade.",
      ver: ["g-po1-l1", "g-po1-l2", "g-po1-l3"] },
    "teoria-filas": { nome: "Teoria das filas", icone: "🚶", termos: "teoria das filas fila m/m/1 taxa de chegada atendimento utilizacao espera",
      oque: "Modelos que relacionam a taxa de chegada (λ), a taxa de atendimento (μ) e o número de servidores com o tempo de espera e o tamanho da fila.",
      paraque: "Dimensionar atendentes, docas, máquinas e equipes de manutenção.",
      quando: "Filas crescendo, clientes esperando, recursos sobrecarregados.",
      dados: ["Taxa média de chegadas (λ)", "Taxa média de atendimento por servidor (μ)", "Número de servidores"],
      formulas: [["ρ = λ ÷ μ (precisa ser < 1)", "utilização"], ["W = 1 ÷ (μ − λ) ;  Wq = ρ ÷ (μ − λ)", "tempos no sistema e na fila (M/M/1)"], ["L = λ · W", "lei de Little"]],
      exemplo: "Chegam 8 caminhões/h e a doca descarrega 10/h → ρ = 0,8; tempo na fila Wq = 0,8 ÷ 2 = 0,4 h (24 min). Com 9,5 chegadas/h, ρ = 0,95 e a fila explode (Wq = 1,9 h).",
      erros: "Dimensionar pela média achando que 100% de utilização é eficiência; usar M/M/1 quando as chegadas não são aleatórias.",
      ver: ["g-po2-l2"] },
    "simulacao": { nome: "Simulação", icone: "🎲", termos: "simulacao monte carlo eventos discretos cenarios",
      oque: "Reprodução do sistema em computador (eventos discretos ou Monte Carlo) para testar cenários com variabilidade antes de mudar a realidade.",
      paraque: "Avaliar mudanças de layout, capacidade, regras e riscos quando fórmulas simples não bastam.",
      quando: "Sistemas com muita variabilidade e interações; investimento caro para testar na prática.",
      dados: ["Distribuições de tempos e chegadas", "Regras de operação", "Dados para validar o modelo"],
      formulas: [["Resultado = média de muitas replicações (± intervalo de confiança)", "saída de uma simulação"]],
      exemplo: "Antes de comprar uma segunda empilhadeira, simula-se o armazém por 1.000 dias com as chegadas reais: a espera média cai de 18 para 4 min, mas a utilização vai a 45%.",
      erros: "Rodar uma só replicação; não validar o modelo com a realidade; confiar em dados de entrada inventados.",
      ver: ["g-po2-l3", "m02-l5"] },
    "arvore-decisao": { nome: "Teoria da decisão (árvore e valor esperado)", icone: "🌳", termos: "arvore de decisao valor esperado decisao sob incerteza risco cenarios",
      oque: "Estrutura as alternativas, os cenários possíveis, suas probabilidades e resultados; escolhe-se, em geral, a alternativa com melhor valor esperado.",
      paraque: "Decidir com incerteza de forma transparente.",
      quando: "Expansão, lançamento, investimento com cenários de demanda.",
      dados: ["Alternativas", "Cenários e probabilidades", "Resultado de cada combinação"],
      formulas: [["VE = Σ probabilidade × resultado", "valor esperado"]],
      exemplo: "Ampliar a fábrica: 60% de chance de demanda alta (+R$ 500 mil) e 40% de baixa (−R$ 200 mil) → VE = 300 − 80 = R$ 220 mil, contra R$ 50 mil de não ampliar.",
      erros: "Probabilidades 'chutadas' sem análise de sensibilidade; ignorar a aversão ao risco (um prejuízo pode quebrar a empresa).",
      ver: ["g-po2-l4", "m02-l6"] },
    "modelo-transporte": { nome: "Modelo de transporte e designação", icone: "🚛", termos: "modelo de transporte problema de transporte designacao alocacao hungaro",
      oque: "Casos especiais de programação linear: transporte decide quanto enviar de cada origem a cada destino com custo mínimo; designação aloca tarefas a recursos um a um.",
      paraque: "Reduzir custo logístico e alocar pessoas/máquinas a tarefas.",
      quando: "Várias fábricas/CDs e vários clientes; distribuir tarefas entre equipes.",
      dados: ["Oferta de cada origem", "Demanda de cada destino", "Custo unitário de cada rota"],
      formulas: [["mín Σ cᵢⱼ · xᵢⱼ", "custo total de transporte"], ["Σⱼ xᵢⱼ ≤ oferta ᵢ ;  Σᵢ xᵢⱼ ≥ demanda ⱼ", "restrições"]],
      exemplo: "Duas fábricas abastecem três CDs; o modelo mostra que a fábrica 2 deve atender só o CD Norte e o CD Sul, reduzindo o frete mensal em 11%.",
      erros: "Ignorar capacidades dos veículos ou prazos; custos por rota desatualizados.",
      ver: ["g-po1-l4", "g-logist-l4"] },
    "localizacao": { nome: "Localização (centro de gravidade)", icone: "📍", termos: "localizacao centro de gravidade instalacoes onde instalar cd",
      oque: "Métodos para escolher onde instalar fábricas e CDs; o centro de gravidade dá uma localização inicial ponderando coordenadas pelos volumes transportados.",
      paraque: "Reduzir custos de transporte e melhorar o nível de serviço.",
      quando: "Abertura ou mudança de fábrica, CD ou loja.",
      dados: ["Coordenadas de clientes/fornecedores", "Volumes movimentados", "Fatores qualitativos (mão de obra, incentivos)"],
      formulas: [["X = Σ(xᵢ · Vᵢ) ÷ ΣVᵢ ;  Y = Σ(yᵢ · Vᵢ) ÷ ΣVᵢ", "centro de gravidade"]],
      exemplo: "Clientes em (100; 200) com 300 t, (400; 100) com 500 t e (250; 500) com 200 t → centro de gravidade em (280; 210).",
      erros: "Usar o ponto exato sem ver estradas e terrenos disponíveis; esquecer fatores qualitativos.",
      ver: ["g-planinst-l1"] },
    "layout": { nome: "Tipos de layout (arranjo físico)", icone: "🏗️", termos: "layout arranjo fisico por produto por processo celular posicional slp",
      oque: "Formas de organizar os recursos: por produto (linha), por processo (funcional), celular e posicional; o SLP ajuda a definir a proximidade entre áreas.",
      paraque: "Reduzir deslocamentos, estoques e lead time.",
      quando: "Nova fábrica, mudança de mix, muito transporte interno.",
      dados: ["Fluxo de materiais entre áreas (de-para)", "Volume e variedade de produtos", "Espaço disponível"],
      formulas: [["Custo de movimentação = Σ fluxo × distância", "comparar alternativas"]],
      exemplo: "Uma empresa com poucos produtos e alto volume troca o layout funcional por células; o transporte interno cai 60% e o lead time de 5 para 2 dias.",
      erros: "Escolher o layout sem olhar volume × variedade; ignorar expansão futura.",
      ver: ["g-planinst-l2", "g-planinst-l3", "m01-l5"] },
    "armazenagem": { nome: "Armazenagem e endereçamento", icone: "🏬", termos: "armazenagem enderecamento armazem picking peps fefo movimentacao",
      oque: "Organização do armazém: endereçamento, localização pelos giros (itens de maior saída perto da expedição), regras PEPS/FEFO e equipamentos de movimentação.",
      paraque: "Reduzir tempo de separação, erros e perdas por validade.",
      quando: "Separação lenta, erros de picking, produtos vencendo.",
      dados: ["Giro/popularidade de cada item", "Dimensões e validade", "Layout do armazém"],
      formulas: [],
      exemplo: "Os 15% de itens que respondem por 70% das separações vão para as posições próximas da expedição e na altura da cintura; o tempo médio de picking cai 25%.",
      erros: "Endereçar por ordem alfabética ou código; não seguir FEFO em itens com validade.",
      ver: ["g-logist-l3"] },
    "amostragem-aceitacao": { nome: "Amostragem de aceitação", icone: "🔍", termos: "amostragem de aceitacao plano de amostragem inspecao de recebimento nqa",
      oque: "Plano de inspeção de lotes: retira-se uma amostra de n itens e aceita-se o lote se o número de defeituosos for menor ou igual a c.",
      paraque: "Decidir sobre lotes recebidos sem inspecionar 100%.",
      quando: "Recebimento de fornecedores, inspeção final de lotes.",
      dados: ["Tamanho do lote", "Nível de qualidade aceitável (NQA)", "Norma/tabela de planos (ex.: NBR 5426)"],
      formulas: [["Plano (n, c): aceitar se defeituosos ≤ c", "regra de decisão"]],
      exemplo: "Lote de 3.000 rótulos, plano n = 125 e c = 3: encontrados 2 defeituosos → lote aceito; 5 defeituosos → lote rejeitado e devolvido.",
      erros: "Achar que amostragem garante zero defeito; usar como substituto do controle do processo do fornecedor.",
      ver: ["g-estqual-l3"] },
    "caminho-critico": { nome: "Caminho crítico (CPM) e PERT", icone: "🛣️", termos: "caminho critico cpm pert folga cronograma rede de atividades compressao",
      oque: "Rede de atividades com durações e dependências; o caminho crítico é a sequência mais longa (folga zero) e define o prazo do projeto. O PERT trata durações incertas com três estimativas.",
      paraque: "Saber o prazo, onde não pode atrasar e onde acelerar.",
      quando: "Projetos com muitas atividades dependentes; prazo apertado.",
      dados: ["Lista de atividades", "Durações", "Dependências (predecessoras)"],
      formulas: [["Folga = início mais tarde − início mais cedo", "folga zero = crítica"], ["te = (a + 4m + b) ÷ 6 ;  σ = (b − a) ÷ 6", "PERT"]],
      exemplo: "Otimista 4, mais provável 6 e pessimista 14 dias → te = (4 + 24 + 14) ÷ 6 = 7 dias, σ ≈ 1,67 dia.",
      erros: "Acelerar atividades que não são críticas; esquecer que o caminho crítico pode mudar após a compressão; ignorar recursos compartilhados.",
      ver: ["m02-l4", "m02-l5", "g-gproj-l2", "g-gproj-l8"] },
    "valor-agregado": { nome: "Valor agregado (EVM)", icone: "💵", termos: "valor agregado evm cpi spi eac earned value",
      oque: "Técnica que compara o valor planejado (PV), o valor do trabalho realizado (EV) e o custo real (AC) para medir desempenho de custo e prazo.",
      paraque: "Saber se o projeto está atrasado/acima do orçamento e prever o custo final.",
      quando: "Acompanhamento periódico de projetos com orçamento.",
      dados: ["Orçamento total (BAC)", "PV, EV e AC na data"],
      formulas: [["CPI = EV ÷ AC ;  SPI = EV ÷ PV", "< 1 = pior que o planejado"], ["EAC = BAC ÷ CPI", "estimativa no término"]],
      exemplo: "BAC = R$ 200 mil; PV = 100, EV = 80, AC = 100 (mil) → CPI = 0,8 e SPI = 0,8: atrasado e acima do custo; EAC ≈ R$ 250 mil.",
      erros: "Medir EV pelo quanto foi gasto (e não pelo que foi entregue); só olhar o AC.",
      ver: ["m02-l7", "g-gproj-l3"] },
    "eap": { nome: "TAP e EAP (escopo)", icone: "🌲", termos: "eap estrutura analitica do projeto tap termo de abertura escopo wbs",
      oque: "O TAP (termo de abertura) autoriza o projeto e define objetivo, responsável e premissas; a EAP decompõe todo o trabalho em entregas menores.",
      paraque: "Deixar claro o que está (e o que não está) no projeto e base para prazo, custo e responsabilidades.",
      quando: "Início de projeto; escopo crescendo sem controle.",
      dados: ["Objetivo e entregas esperadas", "Partes interessadas", "Restrições e premissas"],
      formulas: [["Regra dos 100%: a EAP contém todo o trabalho do projeto — e só ele", "princípio"]],
      exemplo: "Projeto 'nova linha de bombons': EAP com 1. Equipamentos, 2. Instalações, 3. Pessoas, 4. Validação; cada pacote tem dono, prazo e custo.",
      erros: "EAP com atividades em vez de entregas; não escrever o que está fora do escopo.",
      ver: ["m02-l2", "m02-l3", "g-gproj-l1", "g-gproj-l6", "g-gproj-l7"] },
    "matriz-riscos": { nome: "Matriz de riscos", icone: "⚠️", termos: "matriz de riscos probabilidade impacto gestao de riscos resposta mitigar",
      oque: "Classificação dos riscos por probabilidade e impacto para priorizar respostas: evitar, mitigar, transferir ou aceitar.",
      paraque: "Antecipar problemas e preparar respostas antes que aconteçam.",
      quando: "Planejamento e acompanhamento de projetos; mudanças no processo.",
      dados: ["Lista de riscos", "Probabilidade e impacto estimados", "Responsável por cada risco"],
      formulas: [["Exposição = probabilidade × impacto", "priorização"]],
      exemplo: "Atraso do fornecedor do equipamento: probabilidade alta, impacto alto → mitigar com multa contratual e pedido antecipado.",
      erros: "Listar riscos e nunca revisar; tratar só ameaças e esquecer oportunidades.",
      ver: ["m02-l6", "g-gproj-l4"] },
    "fmea": { nome: "FMEA", icone: "🧯", termos: "fmea analise de modos de falha e efeitos npr rpn severidade ocorrencia deteccao",
      oque: "Análise de modos de falha e seus efeitos: para cada falha potencial, avalia severidade (S), ocorrência (O) e detecção (D) e prioriza ações.",
      paraque: "Prevenir falhas em produtos e processos antes que aconteçam.",
      quando: "Projeto de produto ou processo novo, mudança relevante, falhas recorrentes.",
      dados: ["Funções e etapas", "Modos de falha, efeitos e causas", "Controles atuais"],
      formulas: [["NPR = S × O × D (cada um de 1 a 10)", "número de prioridade de risco"]],
      exemplo: "Falha 'selagem incompleta': S = 8, O = 5, D = 6 → NPR = 240; ação: sensor de temperatura com alarme (reduz O e D).",
      erros: "Priorizar só pelo NPR (severidade 10 exige ação mesmo com NPR baixo; a versão AIAG-VDA usa prioridade de ação); fazer o FMEA sozinho.",
      ver: ["g-projprod-l3", "g-gmanut-l3"] },
    "qfd": { nome: "QFD (casa da qualidade)", icone: "🏠", termos: "qfd desdobramento da funcao qualidade casa da qualidade requisitos do cliente",
      oque: "Matriz que relaciona o que o cliente quer (requisitos) com como a empresa atende (características técnicas), indicando prioridades e metas.",
      paraque: "Traduzir a voz do cliente em especificações de produto.",
      quando: "Desenvolvimento ou reformulação de produto.",
      dados: ["Requisitos do cliente e sua importância", "Características técnicas mensuráveis", "Comparação com concorrentes"],
      formulas: [["Importância técnica = Σ (importância do requisito × intensidade da relação)", "prioriza características"]],
      exemplo: "Cliente quer 'embalagem fácil de abrir' (peso 5): ligada forte à força de abertura do lacre; a meta passa a ser força entre 8 e 12 N.",
      erros: "Inventar requisitos sem ouvir o cliente; matriz tão grande que ninguém usa.",
      ver: ["g-projprod-l2", "g-projprod-l8", "g-projprod-l1"] },
    "bsc-okr": { nome: "BSC e OKR", icone: "🧭", termos: "bsc balanced scorecard okr objetivos e resultados chave metas estrategia",
      oque: "BSC organiza objetivos e indicadores em quatro perspectivas (financeira, clientes, processos internos, aprendizado e crescimento). OKR define objetivos com poucos resultados-chave mensuráveis por ciclo.",
      paraque: "Ligar a estratégia às metas das áreas e acompanhar a execução.",
      quando: "Desdobramento de metas anuais/trimestrais.",
      dados: ["Estratégia e objetivos", "Indicadores com meta e responsável"],
      formulas: [],
      exemplo: "Objetivo: 'Entregar sempre no prazo'. Resultados-chave: OTIF de 88% para 95%; lead time de 8 para 5 dias; zero ruptura nos itens A.",
      erros: "Indicadores demais; metas que não dependem da equipe; OKR virar lista de tarefas.",
      ver: ["g-gestr-l4"] },
    "swot": { nome: "Análise SWOT", icone: "🧱", termos: "swot fofa forcas fraquezas oportunidades ameacas",
      oque: "Quadro de forças e fraquezas (internas) e oportunidades e ameaças (externas).",
      paraque: "Diagnóstico para orientar estratégias.",
      quando: "Planejamento estratégico, novo negócio, projeto de TCC.",
      dados: ["Informações do mercado e concorrentes", "Capacidades e limitações internas"],
      formulas: [],
      exemplo: "Força: linha flexível; fraqueza: setup longo; oportunidade: demanda por embalagens pequenas; ameaça: novo concorrente. Estratégia: SMED para aproveitar a flexibilidade.",
      erros: "Listar sem priorizar; confundir oportunidade (externa) com força (interna); não gerar ações.",
      ver: ["g-gestr-l2", "g-projprod-l6", "g-gestr-l1"] },
    "kpi": { nome: "Indicadores (KPIs) e dashboards", icone: "📟", termos: "kpi indicadores de desempenho dashboard painel metas indicador",
      oque: "Medidas que mostram o desempenho de um processo em relação a uma meta, apresentadas em painéis simples.",
      paraque: "Acompanhar resultados, agir cedo e alinhar a equipe.",
      quando: "Gestão de rotina da área, reuniões de desempenho.",
      dados: ["Objetivo da área", "Fonte de dados confiável", "Meta, responsável e frequência"],
      formulas: [["Indicador = resultado ÷ base de comparação", "ex.: peças boas ÷ produzidas"]],
      exemplo: "Painel diário da linha com 4 indicadores: segurança (dias sem acidente), qualidade (% refugo), entrega (aderência ao plano) e custo (horas extras), cada um com meta e ação.",
      erros: "Medir o que é fácil e não o que importa; painel com 30 gráficos; indicador sem ação associada.",
      ver: ["m14-l3", "m14-l5", "g-gestr-l4"] },
    "qualidade-dados": { nome: "Qualidade de dados e planilhas", icone: "🧼", termos: "qualidade de dados planilha excel dados limpos lgpd consistencia",
      oque: "Critérios para confiar nos dados (completude, exatidão, consistência, atualidade) e boas práticas de planilha (formato de tabela, sem números digitados dentro de fórmulas, validação de dados).",
      paraque: "Evitar decisões erradas por causa de dados ruins.",
      quando: "Antes de qualquer análise; planilhas usadas por várias pessoas.",
      dados: ["Base de dados ou planilha", "Regras do negócio (valores possíveis)"],
      formulas: [["Completude = registros preenchidos ÷ total de registros", "exemplo de métrica de qualidade"]],
      exemplo: "A base de paradas tinha 'Manutenção', 'manut.' e 'MANUTENÇÃO' como causas diferentes; padronizando com lista suspensa, a manutenção passou a aparecer como a maior causa no Pareto.",
      erros: "Analisar sem limpar; sobrescrever dados originais; planilha sem controle de versão.",
      ver: ["m14-l1", "m14-l2", "g-ginf-l4"] }
  },

  // Modo Estágio: o que cada área prioriza (categorias de problema, ferramentas e módulos/disciplinas)
  areasEstagio: [
    { id: "pcp", nome: "PCP", icone: "📅", cats: ["planejamento", "producao", "estoque"], ferramentas: ["previsao-demanda", "pmp", "mrp", "capacidade", "sequenciamento", "politica-estoque"], estudo: ["m03", "g-pcp1", "g-pcp2"] },
    { id: "producao", nome: "Produção", icone: "🏭", cats: ["producao", "processos", "qualidade"], ferramentas: ["oee", "gargalo", "takt", "smed"], estudo: ["m04", "m06"] },
    { id: "qualidade", nome: "Qualidade", icone: "✅", cats: ["qualidade", "dados"], ferramentas: ["cep", "capabilidade", "pareto", "ishikawa", "fmea"], estudo: ["m13", "g-gqual", "g-estqual"] },
    { id: "logistica", nome: "Logística", icone: "🚚", cats: ["logistica", "estoque"], ferramentas: ["otif", "curva-abc", "armazenagem", "modelo-transporte"], estudo: ["g-logist", "g-planinst"] },
    { id: "suprimentos", nome: "Suprimentos", icone: "📦", cats: ["estoque", "compras", "planejamento"], ferramentas: ["ponto-pedido", "estoque-seguranca", "mrp", "curva-abc"], estudo: ["g-logist", "m03"] },
    { id: "compras", nome: "Compras", icone: "🛒", cats: ["compras", "custos", "estoque"], ferramentas: ["lec", "curva-abc", "amostragem-aceitacao", "margem-contribuicao"], estudo: ["g-logist", "g-custos"] },
    { id: "processos", nome: "Processos", icone: "⏱️", cats: ["processos", "producao", "qualidade"], ferramentas: ["vsm", "tempo-padrao", "fluxograma", "desperdicios"], estudo: ["m04", "m06"] },
    { id: "projetos", nome: "Projetos", icone: "💡", cats: ["projetos", "custos", "planejamento"], ferramentas: ["caminho-critico", "valor-agregado", "eap", "raci", "matriz-riscos"], estudo: ["m02", "g-gproj"] },
    { id: "dados", nome: "Dados", icone: "📊", cats: ["dados", "qualidade", "planejamento"], ferramentas: ["kpi", "qualidade-dados", "regressao", "histograma"], estudo: ["m14", "m13"] },
    { id: "po", nome: "Pesquisa Operacional", icone: "🔬", cats: ["po", "logistica", "planejamento"], ferramentas: ["programacao-linear", "teoria-filas", "simulacao", "modelo-transporte"], estudo: ["g-po1", "g-po2"] }
  ]
};
