/* Siglas: o app mostra o significado entre parênteses na primeira vez que a sigla aparece
   em cada texto (enunciado, alternativa, explicação, ponto do conteúdo).
   Formato: [sigla, significado, contexto?]
   - contexto (opcional): expressão regular; a sigla só é explicada se o texto também a contiver.
     Serve para siglas com mais de um sentido (ex.: VP = valor planejado em projetos,
     verdadeiro positivo em dados). Sem contexto que case, a sigla fica como está.
   - Uma mesma sigla pode ter várias linhas; vale a primeira cujo contexto casar.
   Não é explicada quando já vem com parênteses ao lado — "Plano mestre (PMP)" ou "PMP (plano mestre)" —,
   nem quando o significado entregaria a resposta da questão. */
(window.SIGLAS = [
  // Planejamento e controle da produção
  ["MRP II", "planejamento dos recursos de manufatura"],
  ["MRP", "planejamento das necessidades de materiais"],
  ["PCP", "planejamento e controle da produção"],
  ["PMP", "plano mestre de produção"],
  ["MPS", "plano mestre de produção"],
  ["S&OP", "planejamento de vendas e operações"],
  ["ERP", "sistema integrado de gestão empresarial"],
  ["ERPs", "sistemas integrados de gestão empresarial"],
  ["BOM", "lista de materiais"],
  ["CRP", "planejamento das necessidades de capacidade"],
  ["RCCP", "planejamento grosseiro de capacidade"],
  ["ATP", "disponível para promessa"],
  ["CTP", "capaz de prometer"],
  ["APS", "planejamento avançado da produção"],
  ["MES", "sistema de execução da manufatura"],
  ["WIP", "estoque em processo"],
  ["CONWIP", "estoque em processo constante"],
  ["DBR", "tambor-pulmão-corda"],
  ["DDMRP", "MRP orientado pela demanda"],
  ["MTS", "produção para estoque"],
  ["MTO", "produção sob encomenda"],
  ["ATO", "montagem sob encomenda"],
  ["ETO", "engenharia sob encomenda"],
  ["LEC", "lote econômico de compra"],
  ["LT", "lead time, o tempo de reposição"],
  ["NB", "necessidade bruta"],
  ["NL", "necessidade líquida"],
  ["RP", "recebimento programado", "NB|NL|MRP|estoque"],
  ["ES", "início mais cedo", "\\b(LS|EF|LF)\\b|folga"],
  ["ES", "estoque de segurança", "\\b(PP|LT|NB|NL)\\b|estoque|d̄|σ|z ="],
  ["EF", "término mais cedo", "\\b(ES|LS|LF)\\b"],
  ["LS", "início mais tarde", "\\b(ES|EF|LF)\\b"],
  ["LF", "término mais tarde", "\\b(ES|EF|LS)\\b"],
  ["PP", "ponto de pedido", "\\b(LT|ES)\\b|d̄|demanda|estoque|pedido"],
  ["IS", "índice sazonal", "ISM|MMC|sazon"],
  ["ISM", "índice sazonal médio"],
  ["MMC", "média móvel centrada"],
  ["MAD", "desvio absoluto médio"],
  ["DAM", "desvio absoluto médio"],
  ["MAPE", "erro percentual absoluto médio"],
  ["MSE", "erro quadrático médio"],
  ["EQM", "erro quadrático médio"],
  ["AES", "amortecimento exponencial simples"],
  ["RSFE", "soma acumulada dos erros de previsão"],
  ["SKU", "código de item em estoque"],
  ["SKUs", "códigos de item em estoque"],
  ["PEPS", "primeiro que entra, primeiro que sai"],
  ["UEPS", "último que entra, primeiro que sai"],
  ["FIFO", "primeiro a entrar, primeiro a sair"],
  ["FEFO", "primeiro que vence, primeiro que sai"],
  ["MTP", "menor tempo de processamento"],
  ["SPT", "menor tempo de processamento"],
  ["LPT", "maior tempo de processamento"],
  ["EDD", "menor data de entrega"],
  ["DD", "data de entrega", "EDD|MTP|PEPS|SPT|FIFO"],
  ["OTIF", "no prazo e completo"],
  ["VMI", "estoque gerenciado pelo fornecedor"],
  ["WMS", "sistema de gerenciamento de armazém"],
  ["RFID", "identificação por radiofrequência"],
  ["HH", "homem-hora"],
  // Produção, lean e manutenção
  ["OEE", "eficiência global do equipamento"],
  ["TPM", "manutenção produtiva total"],
  ["SMED", "troca rápida de ferramenta"],
  ["VSM", "mapeamento do fluxo de valor"],
  ["PCE", "eficiência do ciclo do processo"],
  ["EPEI", "cada peça a cada intervalo"],
  ["TPS", "Sistema Toyota de Produção"],
  ["JIT", "just in time, no momento exato"],
  ["TOC", "teoria das restrições"],
  ["MTBF", "tempo médio entre falhas"],
  ["MTTR", "tempo médio de reparo"],
  ["MTTF", "tempo médio até a falha"],
  ["RCM", "manutenção centrada em confiabilidade"],
  ["PCM", "planejamento e controle da manutenção"],
  ["TO", "tempo observado", "\\b(TN|TP)\\b"],
  ["TN", "tempo normal", "\\b(TO|TP|FR)\\b|ritmo|tolerância"],
  ["TP", "tempo padrão", "\\b(TN|TO)\\b|tolerância"],
  ["FR", "fator de ritmo", "\\b(TN|TO)\\b"],
  ["TC", "tempo de ciclo", "takt|gargalo|posto"],
  ["MTM", "medição tempo-método"],
  ["ECRS", "eliminar, combinar, reorganizar e simplificar"],
  ["SIPOC", "fornecedores, entradas, processo, saídas e clientes"],
  ["SLP", "planejamento sistemático do layout"],
  ["CLP", "controlador lógico programável"],
  ["CLPs", "controladores lógicos programáveis"],
  ["SCADA", "sistema de supervisão e aquisição de dados"],
  ["IHM", "interface homem-máquina"],
  ["CNC", "comando numérico computadorizado"],
  ["AGV", "veículo guiado automaticamente"],
  ["AGVs", "veículos guiados automaticamente"],
  ["CAD", "projeto assistido por computador"],
  // Qualidade e estatística
  ["PDCA", "planejar, fazer, checar e agir"],
  ["PDSA", "planejar, fazer, estudar e agir"],
  ["DMAIC", "definir, medir, analisar, melhorar e controlar"],
  ["CEP", "controle estatístico do processo"],
  ["FMEA", "análise dos modos de falha e seus efeitos"],
  ["DFMEA", "FMEA de projeto"],
  ["NPR", "número de prioridade de risco"],
  ["QFD", "desdobramento da função qualidade"],
  ["DPMO", "defeitos por milhão de oportunidades"],
  ["DOE", "planejamento de experimentos"],
  ["ANOVA", "análise de variância"],
  ["TQM", "gestão da qualidade total"],
  ["CCQ", "círculos de controle da qualidade"],
  ["NQA", "nível de qualidade aceitável"],
  ["AQL", "nível de qualidade aceitável"],
  ["LSE", "limite superior de especificação"],
  ["LIE", "limite inferior de especificação"],
  ["LSC", "limite superior de controle"],
  ["LIC", "limite inferior de controle"],
  ["IC", "intervalo de confiança", "%|σ|x̄|confiança|amostra|média|± "],
  ["IQR", "intervalo interquartil"],
  ["CV", "coeficiente de variação", "x̄|desvio|÷ média"],
  ["CV", "custo variável", "\\bCF\\b|\\bCT\\b"],
  ["CV", "variação de custo", "\\b(VA|CR|EV|AC)\\b"],
  ["VP", "verdadeiro positivo", "\\b(FP|FN|VN)\\b"],
  ["FP", "falso positivo", "\\b(VP|FN|VN)\\b"],
  ["FN", "falso negativo", "\\b(VP|FP|VN)\\b"],
  ["VN", "verdadeiro negativo", "\\b(VP|FP|FN)\\b"],
  // Projetos
  ["PMBOK", "guia do conhecimento em gerenciamento de projetos"],
  ["PMI", "Project Management Institute, instituto de gerenciamento de projetos"],
  ["PMO", "escritório de gerenciamento de projetos"],
  ["TAP", "termo de abertura do projeto"],
  ["EAP", "estrutura analítica do projeto"],
  ["WBS", "estrutura analítica do projeto"],
  ["EAR", "estrutura analítica de riscos"],
  ["RACI", "responsável, aprovador, consultado e informado"],
  ["PERT", "técnica de avaliação e revisão de programas"],
  ["CPM", "método do caminho crítico"],
  ["EVM", "gerenciamento do valor agregado"],
  ["EV", "valor agregado", "\\b(PV|AC|CPI|SPI|BAC|EAC)\\b|agregado"],
  ["PV", "valor planejado", "\\b(EV|AC|SPI|CPI|BAC)\\b|planejado"],
  ["AC", "custo real", "\\b(EV|PV|CPI|BAC|EAC)\\b"],
  ["BAC", "orçamento no término"],
  ["EAC", "estimativa no término"],
  ["ETC", "estimativa para terminar"],
  ["VAC", "variação no término"],
  ["CPI", "índice de desempenho de custo"],
  ["SPI", "índice de desempenho de prazo"],
  ["TCPI", "índice de desempenho para terminar"],
  ["SV", "variação de prazo", "\\b(EV|PV)\\b"],
  ["VA", "valor agregado", "\\b(CR|VP|IDC|IDP|ONT)\\b"],
  ["VP", "valor planejado", "\\b(VA|CR|IDP|ONT)\\b|planejado"],
  ["CR", "custo real", "\\b(VA|VP|IDC|ONT)\\b"],
  ["VC", "variação de custo", "\\b(VA|CR)\\b"],
  ["VPr", "variação de prazo", "\\b(VA|VP)\\b"],
  ["ONT", "orçamento no término"],
  ["ENT", "estimativa no término"],
  ["EPT", "estimativa para terminar"],
  ["VNT", "variação no término"],
  ["IDC", "índice de desempenho de custo"],
  ["IDP", "índice de desempenho de prazo"],
  ["IDCP", "índice de desempenho para terminar"],
  ["VME", "valor monetário esperado"],
  ["VMEs", "valores monetários esperados"],
  ["FAT", "teste de aceitação na fábrica do fornecedor"],
  ["SAT", "teste de aceitação no local"],
  ["MVP", "produto mínimo viável"],
  // Produto
  ["PDP", "processo de desenvolvimento de produto"],
  ["DFM", "projeto para manufatura"],
  ["DFA", "projeto para montagem"],
  ["DFMA", "projeto para manufatura e montagem"],
  ["ECV", "valor comercial esperado"],
  ["PNID", "positivo, negativo, interessante e duvidoso"],
  ["ECO", "ordem de mudança de engenharia"],
  ["ECR", "solicitação de mudança de engenharia"],
  ["PPAP", "processo de aprovação de peça de produção"],
  ["TRIZ", "teoria da solução inventiva de problemas"],
  ["SCAMPER", "substituir, combinar, adaptar, modificar, propor outro uso, eliminar e reorganizar"],
  ["ACV", "avaliação do ciclo de vida"],
  ["ICV", "inventário do ciclo de vida"],
  ["AICV", "avaliação de impacto do ciclo de vida"],
  ["INPI", "Instituto Nacional da Propriedade Industrial"],
  ["IPC", "Classificação Internacional de Patentes"],
  ["BCG", "Boston Consulting Group"],
  // Gestão, custos e estratégia
  ["SWOT", "forças, fraquezas, oportunidades e ameaças"],
  ["BSC", "painel balanceado de indicadores"],
  ["OKR", "objetivos e resultados-chave"],
  ["OKRs", "objetivos e resultados-chave"],
  ["KPI", "indicador-chave de desempenho"],
  ["KPIs", "indicadores-chave de desempenho"],
  ["SMART", "específica, mensurável, atingível, relevante e com prazo"],
  ["PESTEL", "fatores políticos, econômicos, sociais, tecnológicos, ambientais e legais"],
  ["VRIO", "valor, raridade, imitabilidade e organização"],
  ["CRM", "gestão do relacionamento com o cliente"],
  ["VPL", "valor presente líquido"],
  ["TIR", "taxa interna de retorno"],
  ["TMA", "taxa mínima de atratividade"],
  ["ROI", "retorno sobre o investimento"],
  ["CIF", "custos indiretos de fabricação"],
  ["MOD", "mão de obra direta"],
  ["CPV", "custo dos produtos vendidos"],
  ["CMV", "custo das mercadorias vendidas"],
  ["DRE", "demonstração do resultado do exercício"],
  ["TDABC", "custeio baseado em atividades e tempo"],
  ["CF", "custo fixo", "\\b(CV|CT|PE|MC|MCu)\\b|cv"],
  ["PE", "ponto de equilíbrio", "\\b(CF|MC|MCu)\\b"],
  ["MC", "margem de contribuição", "preço|variáve|\\bCF\\b|\\bPE\\b"],
  ["MCu", "margem de contribuição unitária"],
  ["MEI", "microempreendedor individual"],
  ["BPMN", "notação para modelagem de processos de negócio"],
  // Pessoas, segurança e meio ambiente
  ["NR", "Norma Regulamentadora"],
  ["NRs", "Normas Regulamentadoras"],
  ["EPI", "equipamento de proteção individual"],
  ["EPC", "equipamento de proteção coletiva"],
  ["CIPA", "Comissão Interna de Prevenção de Acidentes"],
  ["SESMT", "serviço especializado em segurança e medicina do trabalho"],
  ["PGR", "programa de gerenciamento de riscos"],
  ["GRO", "gerenciamento de riscos ocupacionais"],
  ["APR", "análise preliminar de riscos"],
  ["CAT", "comunicação de acidente de trabalho"],
  ["LOTO", "bloqueio e etiquetagem de energias"],
  ["AET", "análise ergonômica do trabalho"],
  ["LER", "lesão por esforço repetitivo"],
  ["DORT", "distúrbio osteomuscular relacionado ao trabalho"],
  ["OIT", "Organização Internacional do Trabalho"],
  ["SGA", "sistema de gestão ambiental"],
  ["SGI", "sistema de gestão integrado"],
  ["PNRS", "Política Nacional de Resíduos Sólidos"],
  ["GHG", "gases de efeito estufa"],
  // Normas, instituições e dados
  ["ISO", "Organização Internacional de Normalização"],
  ["ABNT", "Associação Brasileira de Normas Técnicas"],
  ["NBR", "norma brasileira"],
  ["INMETRO", "Instituto Nacional de Metrologia, Qualidade e Tecnologia"],
  ["ABEPRO", "Associação Brasileira de Engenharia de Produção"],
  ["LGPD", "Lei Geral de Proteção de Dados"],
  ["CLT", "Consolidação das Leis do Trabalho"],
  ["IBGE", "Instituto Brasileiro de Geografia e Estatística"],
  ["PIB", "produto interno bruto"],
  ["IPCA", "índice oficial de inflação"],
  ["SQL", "linguagem de consulta a bancos de dados"],
  ["BI", "inteligência de negócios"],
  ["IA", "inteligência artificial"],
  ["RH", "recursos humanos"],
  ["TCC", "trabalho de conclusão de curso"],
  ["EDO", "equação diferencial ordinária"],
  ["EDOs", "equações diferenciais ordinárias"],
  ["EDP", "equação diferencial parcial"],
  ["EDPs", "equações diferenciais parciais"],
  ["MRU", "movimento retilíneo uniforme"],
  ["MRUV", "movimento retilíneo uniformemente variado"]
]);
