/* =====================================================================
   GRADE CURRICULAR — 1º PERÍODO
   Formato de cada disciplina (veja app/PROJETO.md, seção 10):
   { id, codigo, nome, periodo, area, icone, creditos, prereq: [ids],
     relacionado: [módulos do curso], intro,
     topicos: [{ t, pontos: [..], formulas: [[fórmula, significado]], producao, exemplo }],
     glossario: [[termo, definição]],
     questoes: [{ t: índice do tópico, id, tipo, ... }] }
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-calc1", codigo: "GEXT-7301", nome: "Cálculo a Uma Variável", periodo: 1, area: "exatas", icone: "📈", creditos: "(5-0-0) 5 créditos",
    intro: "Cálculo é a matemática da **variação**. Na Engenharia de Produção, a **derivada** mede quanto o custo ou o lucro muda quando se produz uma unidade a mais (custo marginal) e encontra o lote ou a produção ótima; o **limite** mostra para onde tende o custo médio em grande escala; a **integral** soma o que se acumula ao longo do tempo, como produção, consumo de energia e custo total.",
    topicos: [
      { t: "Funções que modelam a produção", icone: "📐",
        pontos: [
          "**Função:** regra que associa a cada entrada (x) uma única saída f(x). Ex.: custo em função da quantidade produzida.",
          "**Custo total:** C(q) = CF + cv·q, soma do custo fixo (aluguel, salários fixos) com o variável (matéria-prima por unidade).",
          "**Receita:** R(q) = p·q; **lucro:** L(q) = R(q) − C(q).",
          "**Ponto de equilíbrio:** quantidade em que o lucro é zero (R = C).",
          "**Função potência** descreve a curva de aprendizagem: o tempo por unidade cai à medida que a produção acumulada cresce."
        ],
        formulas: [["C(q) = CF + cv·q", "CF = custo fixo; cv = custo variável por unidade; q = quantidade"], ["L(q) = p·q − (CF + cv·q)", "p = preço de venda por unidade"], ["q* = CF ÷ (p − cv)", "ponto de equilíbrio; (p − cv) é a margem de contribuição unitária"], ["T(n) = T₁ · n^b, b = log₂(taxa)", "tempo da n-ésima unidade; T₁ = tempo da 1ª unidade; taxa = 0,8 para curva de 80%"]],
        producao: "Modelar custo, receita e lucro como funções é o primeiro passo para decidir preço, volume mínimo de produção e se vale a pena abrir um turno.",
        exemplo: "Doces Serra: CF = R$ 20.000/mês, cv = R$ 6 por caixa, p = R$ 10.\nq* = 20.000 ÷ (10 − 6) = **5.000 caixas/mês**. Abaixo disso há prejuízo." },
      { t: "Limites e continuidade", icone: "🎯",
        pontos: [
          "**Limite:** valor do qual f(x) se aproxima quando x se aproxima de um ponto (ou cresce sem parar), mesmo que nunca o alcance.",
          "**Custo médio** CMe(q) = CF/q + cv: quando q → ∞, CF/q → 0 e o custo médio tende a cv (a escala dilui o fixo, mas nunca abaixo do variável).",
          "**Continuidade:** f é contínua em a se o limite existe e é igual a f(a). Funções em degrau (ex.: custo que salta ao abrir um novo turno) são descontínuas.",
          "**Assíntota:** reta da qual o gráfico se aproxima; em custos, cv é a assíntota horizontal do custo médio.",
          "O limite também define a **derivada** (próximo tópico)."
        ],
        formulas: [["lim (q→∞) (CF/q + cv) = cv", "o custo médio tende ao custo variável unitário"], ["lim (x→a) f(x) = L", "f(x) fica tão perto de L quanto se queira para x perto de a"], ["f contínua em a ⇔ lim (x→a) f(x) = f(a)", "sem saltos nem buracos no ponto a"]],
        producao: "Limites explicam **economia de escala** (até onde o custo médio pode cair), o comportamento de longo prazo da **curva de aprendizagem** e mostram onde o custo tem saltos (degraus de capacidade), que exigem análise por faixas.",
        exemplo: "CF = R$ 20.000, cv = R$ 6. CMe(1.000) = 26; CMe(10.000) = 8; CMe(100.000) = 6,20. O limite é **R$ 6**: por maior que seja a produção, a caixa não sai por menos que o custo variável." },
      { t: "Derivadas: taxas e otimização", icone: "📉",
        pontos: [
          "**Derivada** f'(x): taxa de variação instantânea; inclinação da reta tangente. Definida como lim (h→0) [f(x+h) − f(x)] ÷ h.",
          "**Regras:** (xⁿ)' = n·xⁿ⁻¹; (constante)' = 0; (f + g)' = f' + g'; (f·g)' = f'g + fg'; regra da cadeia (f(g(x)))' = f'(g(x))·g'(x).",
          "**Custo marginal:** C'(q), custo aproximado de produzir uma unidade a mais.",
          "**Otimização:** máximos e mínimos ocorrem onde f'(x) = 0 (pontos críticos); f''(x) > 0 indica mínimo e f''(x) < 0 indica máximo.",
          "**Lucro máximo:** quando receita marginal = custo marginal (L'(q) = 0)."
        ],
        formulas: [["f'(x) = lim (h→0) [f(x+h) − f(x)] ÷ h", "taxa de variação instantânea"], ["(xⁿ)' = n·xⁿ⁻¹", "regra da potência"], ["CT(Q) = (D/Q)·S + (Q/2)·H", "custo anual de pedir + estocar; D = demanda anual, S = custo por pedido, H = custo de manter 1 unidade por ano"], ["CT'(Q) = 0 ⇒ Q* = √(2DS ÷ H)", "lote econômico (LEC), encontrado pela derivada"]],
        producao: "O **lote econômico de compra** (Módulo 7) nasce de uma derivada igualada a zero. O custo marginal orienta preço e aceitação de pedidos extras; a taxa de variação mede a velocidade de queda do tempo na curva de aprendizagem.",
        exemplo: "D = 12.000 caixas/ano, S = R$ 150 por pedido, H = R$ 4 por caixa·ano.\nCT'(Q) = −DS/Q² + H/2 = 0 ⇒ Q* = √(2 × 12.000 × 150 ÷ 4) = √900.000 ≈ **949 caixas por pedido**." },
      { t: "Integrais: somando o que se acumula", icone: "∫",
        pontos: [
          "**Integral indefinida (antiderivada):** F(x) tal que F'(x) = f(x). Ex.: ∫xⁿ dx = xⁿ⁺¹ ÷ (n+1) + C.",
          "**Integral definida:** ∫ₐᵇ f(x) dx = F(b) − F(a) (Teorema Fundamental do Cálculo); é a área sob a curva, isto é, o **acumulado**.",
          "Se r(t) é a **taxa de produção** (peças/h), ∫ r(t) dt é a **produção acumulada** no período.",
          "Se C'(q) é o custo marginal, o custo total é CF + ∫₀^q C'(x) dx.",
          "**Valor médio** de f em [a, b]: (1 ÷ (b − a)) · ∫ₐᵇ f(x) dx."
        ],
        formulas: [["∫ xⁿ dx = xⁿ⁺¹ ÷ (n+1) + C (n ≠ −1)", "regra da potência para integrais"], ["∫ₐᵇ f(x) dx = F(b) − F(a)", "Teorema Fundamental do Cálculo"], ["Produção = ∫₀ᵀ r(t) dt", "r(t) = taxa de produção; T = duração"], ["Energia (kWh) = ∫ P(t) dt", "P = potência em kW; a conta de energia é uma integral"]],
        producao: "Integrais calculam produção acumulada quando o ritmo varia (partida de linha, curva de aprendizagem), **energia consumida** a partir da potência, custo total a partir do custo marginal e probabilidades como área sob curvas de densidade (Estatística, Confiabilidade).",
        exemplo: "Na partida de uma linha, a taxa cresce: r(t) = 20 + 10t peças/h, de t = 0 a 4 h.\nProdução = ∫₀⁴ (20 + 10t) dt = [20t + 5t²]₀⁴ = 80 + 80 = **160 peças**." }
    ],
    glossario: [
      ["Função", "Regra que associa cada entrada a uma única saída."], ["Limite", "Valor do qual f(x) se aproxima quando x se aproxima de um ponto."],
      ["Continuidade", "Ausência de saltos ou buracos: o limite coincide com o valor da função."], ["Assíntota", "Reta da qual o gráfico se aproxima indefinidamente."],
      ["Derivada", "Taxa de variação instantânea; inclinação da tangente."], ["Custo marginal", "C'(q): custo adicional aproximado de uma unidade a mais."],
      ["Ponto crítico", "Ponto onde f'(x) = 0 ou não existe; candidato a máximo ou mínimo."], ["Lote econômico (LEC)", "Q* = √(2DS/H): minimiza o custo de pedir + estocar."],
      ["Antiderivada", "Função F com F' = f."], ["Integral definida", "Acumulado (área) de f entre a e b."],
      ["Teorema Fundamental do Cálculo", "Liga derivada e integral: ∫ₐᵇ f = F(b) − F(a)."], ["Ponto de equilíbrio", "Quantidade em que receita = custo total."]
    ],
    questoes: [
      { t: 0, id: "g-calc1-q01", tipo: "multipla", pergunta: "Na função custo C(q) = 20.000 + 6q, o que representa o número 6?",
        opcoes: ["O custo fixo mensal", "O custo variável por unidade", "O preço de venda", "A quantidade produzida"], correta: 1,
        explicacao: "Cada unidade a mais acrescenta R$ 6 ao custo total." },
      { t: 0, id: "g-calc1-t01", tipo: "calculo",
        variaveis: { cf: { min: 10000, max: 60000, passo: 5000 }, p: { min: 12, max: 30 }, cv: { min: 4, max: 10 } },
        condicao: "p > cv + 2",
        resposta: "ceil(cf/(p-cv))", tolerancia: 0, unidade: "unidades",
        pergunta: "Custo fixo = R$ {cf}; custo variável = R$ {cv}/unidade; preço = R$ {p}. Qual o ponto de equilíbrio (arredonde para cima)?",
        resolucao: "q* = CF ÷ (p − cv) = {cf} ÷ ({p} − {cv}) = {=cf/(p-cv):2} → {=ceil(cf/(p-cv))} unidades",
        explicacao: "Abaixo do ponto de equilíbrio a operação tem prejuízo." },
      { t: 0, id: "g-calc1-q02", tipo: "vf", pergunta: "Na curva de aprendizagem de 80%, o tempo por unidade cai 20% a cada unidade produzida.",
        correta: false, explicacao: "Cai para 80% a cada DOBRO da produção acumulada (1ª → 2ª → 4ª → 8ª…)." },
      { t: 1, id: "g-calc1-q03", tipo: "multipla", pergunta: "O custo médio é CMe(q) = 20.000/q + 6. Para qual valor ele tende quando a produção cresce sem limite?",
        opcoes: ["0", "6", "20.000", "Infinito"], correta: 1,
        explicacao: "20.000/q → 0; sobra o custo variável: lim CMe = 6." },
      { t: 1, id: "g-calc1-t02", tipo: "calculo",
        variaveis: { cf: { min: 5000, max: 50000, passo: 5000 }, cv: { min: 2, max: 15 }, q: { valores: [500, 1000, 2000, 5000, 10000] } },
        resposta: "cf/q+cv", tolerancia: 0.01, unidade: "R$/unidade",
        pergunta: "CF = R$ {cf}, cv = R$ {cv}. Qual o custo médio por unidade produzindo {q} unidades? (2 casas)",
        resolucao: "CMe = {cf} ÷ {q} + {cv} = {=cf/q:2} + {cv} = {=cf/q+cv:2}",
        explicacao: "Quanto maior q, mais perto de cv (o limite)." },
      { t: 1, id: "g-calc1-q04", tipo: "caso", contexto: "O custo mensal de energia é R$ 8.000 até 10.000 peças; acima disso é preciso abrir um segundo turno e o custo fixo salta para R$ 14.000.",
        pergunta: "Como se descreve matematicamente essa função de custo em q = 10.000?",
        opcoes: ["Contínua e derivável", "Descontínua (salto), por isso deve ser analisada por faixas", "Uma assíntota", "Uma integral"], correta: 1,
        explicacao: "Custos em degrau têm saltos; decisões de volume devem comparar as faixas." },
      { t: 2, id: "g-calc1-t03", tipo: "calculo",
        variaveis: { a: { min: 1000, max: 5000, passo: 500 }, b: { min: 2, max: 10 }, c: { valores: [0.001, 0.002, 0.005, 0.01] }, q: { valores: [100, 200, 300, 500] } },
        resposta: "b+2*c*q", tolerancia: 0.01, unidade: "R$/unidade",
        pergunta: "C(q) = {a} + {b}q + {c}q². Qual o custo marginal C'(q) em q = {q}? (2 casas)",
        resolucao: "C'(q) = {b} + 2 × {c} × q\nC'({q}) = {b} + {=2*c*q:2} = {=b+2*c*q:2}",
        explicacao: "A derivada de uma constante é zero; (q²)' = 2q." },
      { t: 2, id: "g-calc1-t04", tipo: "calculo",
        variaveis: { d: { min: 6000, max: 30000, passo: 1000 }, sp: { valores: [50, 80, 100, 150, 200] }, h: { valores: [2, 2.5, 4, 5, 8] } },
        resposta: "sqrt(2*d*sp/h)", tolerancia: 1, unidade: "unidades",
        pergunta: "Demanda anual D = {d}; custo por pedido S = R$ {sp}; custo de manter H = R$ {h}/unidade·ano. Qual o lote econômico Q* (derivada do custo total igualada a zero)? (inteiro)",
        resolucao: "Q* = √(2DS ÷ H) = √(2 × {d} × {sp} ÷ {h}) = √{=2*d*sp/h:0} ≈ {=sqrt(2*d*sp/h):0}",
        explicacao: "No ótimo, custo anual de pedir = custo anual de estocar." },
      { t: 2, id: "g-calc1-q05", tipo: "multipla", pergunta: "O lucro é L(q) = −0,01q² + 40q − 5.000. Em que quantidade o lucro é máximo?",
        opcoes: ["q = 400", "q = 2.000", "q = 4.000", "q = 5.000"], correta: 1,
        explicacao: "L'(q) = −0,02q + 40 = 0 ⇒ q = 2.000. L''(q) = −0,02 < 0: é máximo." },
      { t: 2, id: "g-calc1-q06", tipo: "vf", pergunta: "Se f'(x) = 0 e f''(x) > 0, o ponto é um mínimo local.",
        correta: true, explicacao: "Concavidade para cima: a curva “sorri” e o ponto é um vale." },
      { t: 3, id: "g-calc1-t05", tipo: "calculo",
        variaveis: { a: { min: 10, max: 60, passo: 5 }, b: { min: 2, max: 20, passo: 2 }, tt: { min: 2, max: 8 } },
        resposta: "a*tt+b*tt*tt/2", tolerancia: 0.01, unidade: "peças",
        pergunta: "Na partida da linha, a taxa de produção é r(t) = {a} + {b}t peças/h. Quantas peças são produzidas de t = 0 a t = {tt} h?",
        resolucao: "∫₀^{tt} ({a} + {b}t) dt = [{a}t + {=b/2}t²]₀^{tt} = {=a*tt} + {=b*tt*tt/2} = {=a*tt+b*tt*tt/2}",
        explicacao: "A integral da taxa dá o acumulado." },
      { t: 3, id: "g-calc1-q07", tipo: "multipla", pergunta: "Uma máquina consome potência P(t) (em kW) que varia ao longo do turno. Como obter a energia consumida em kWh?",
        opcoes: ["Derivando P(t)", "Integrando P(t) ao longo do tempo", "Calculando o limite de P(t)", "Multiplicando P pelo número de peças"], correta: 1,
        explicacao: "Energia = ∫ P(t) dt: a área sob a curva de potência." },
      { t: 3, id: "g-calc1-q08", tipo: "calculo", pergunta: "Custo marginal C'(q) = 10 + 0,02q e custo fixo de R$ 1.000. Qual o custo total de produzir 100 unidades (R$)?",
        resposta: 2100, tolerancia: 0, unidade: "R$",
        resolucao: "C(100) = 1.000 + ∫₀¹⁰⁰ (10 + 0,02q) dq = 1.000 + [10q + 0,01q²]₀¹⁰⁰ = 1.000 + 1.000 + 100 = 2.100",
        explicacao: "A integral do custo marginal recupera o custo variável total." },
      { t: 3, id: "g-calc1-q09", tipo: "vf", pergunta: "O Teorema Fundamental do Cálculo diz que ∫ₐᵇ f(x) dx = F(b) − F(a), onde F é uma antiderivada de f.",
        correta: true, explicacao: "É a ponte entre derivada e integral." }
    ]
  },

  {
    id: "g-alg1", codigo: "GEXT-7501", nome: "Álgebra Linear I", periodo: 1, area: "exatas", icone: "🧮", creditos: "(2-0-0) 2 créditos",
    intro: "Álgebra linear organiza muitos números ao mesmo tempo em **vetores e matrizes** e resolve **sistemas de equações**. Na produção, ela calcula o mix de produtos que usa exatamente os recursos disponíveis, explode listas de materiais, organiza dados de várias máquinas e é a base da Pesquisa Operacional (programação linear).",
    topicos: [
      { t: "Vetores e matrizes", icone: "🔢",
        pontos: ["**Vetor:** lista ordenada de números (ex.: produção de 3 produtos = (120, 80, 50)).", "**Matriz m×n:** tabela com m linhas e n colunas; aᵢⱼ é o elemento da linha i, coluna j.", "**Soma** de matrizes: elemento a elemento (mesmas dimensões). **Multiplicação por escalar:** cada elemento vezes o número.", "**Produto de matrizes** A(m×n)·B(n×p): linha de A “vezes” coluna de B; só existe se o nº de colunas de A = nº de linhas de B. Não é comutativo (AB ≠ BA em geral).", "**Transposta** Aᵀ: troca linhas por colunas. **Identidade** I: 1 na diagonal, 0 fora."],
        formulas: [["(AB)ᵢⱼ = Σₖ aᵢₖ · bₖⱼ", "produto: linha i de A com coluna j de B"], ["A(m×n) · B(n×p) = C(m×p)", "condição de existência do produto"], ["u · v = u₁v₁ + u₂v₂ + … + uₙvₙ", "produto escalar de dois vetores"]],
        producao: "A matriz de consumo (insumo por produto) vezes o vetor de produção dá o **consumo total de cada insumo**. O produto escalar de preços × quantidades dá a receita.",
        exemplo: "Bombom ao leite usa 0,02 kg de chocolate e 0,01 kg de recheio; o amargo, 0,025 e 0,008. Produção: (1.000; 500).\nChocolate = 0,02·1.000 + 0,025·500 = **32,5 kg**; recheio = 0,01·1.000 + 0,008·500 = **14 kg**." },
      { t: "Sistemas lineares", icone: "⚖️",
        pontos: ["Um **sistema linear** tem equações do tipo a₁x₁ + a₂x₂ + … = b; na forma matricial, **Ax = b**.", "**Escalonamento (eliminação de Gauss):** operações nas linhas (trocar, multiplicar, somar múltiplos) até a forma triangular; depois substituição de trás para a frente.", "Classificação: **possível determinado** (uma solução), **possível indeterminado** (infinitas) ou **impossível** (nenhuma).", "Na produção, uma solução negativa indica que o plano pedido é **inviável** fisicamente."],
        formulas: [["A · x = b", "A = coeficientes; x = incógnitas; b = termos independentes"], ["Lᵢ ← Lᵢ − k·Lⱼ", "operação elementar de linha usada no escalonamento"]],
        producao: "Descobrir quanto produzir de cada item para usar **exatamente** as horas de máquina e a matéria-prima disponíveis; balancear massas em processos (quanto de cada ingrediente para uma mistura).",
        exemplo: "Máquina A: 2 h por lote de X e 1 h por lote de Y; 100 h disponíveis. Máquina B: 1 h de X e 3 h de Y; 150 h.\n2x + y = 100 e x + 3y = 150 ⇒ **x = 30 e y = 40 lotes**." },
      { t: "Determinantes e matriz inversa", icone: "🔄",
        pontos: ["**Determinante** det(A): número associado a uma matriz quadrada. Para 2×2: ad − bc.", "det(A) ≠ 0 ⇔ A é **invertível** ⇔ o sistema Ax = b tem solução única.", "**Inversa** A⁻¹: A·A⁻¹ = I. Então x = A⁻¹·b.", "Para 2×2: A⁻¹ = (1/det) · [d −b; −c a].", "det = 0 indica equações **dependentes** (informação repetida ou contraditória)."],
        formulas: [["det [a b; c d] = ad − bc", "determinante 2×2"], ["x = A⁻¹ · b", "solução do sistema quando A é invertível"], ["[a b; c d]⁻¹ = (1/(ad − bc)) · [d −b; −c a]", "inversa 2×2"]],
        producao: "O **modelo insumo-produto de Leontief** usa (I − A)⁻¹ para calcular quanto cada setor precisa produzir para atender à demanda final, considerando o que os setores consomem uns dos outros. A mesma lógica vale para itens intermediários fabricados internamente.",
        exemplo: "A = [2 1; 1 3] ⇒ det = 2·3 − 1·1 = **5** ≠ 0: o sistema das máquinas A e B tem solução única." },
      { t: "Matrizes na lista de materiais", icone: "🧾",
        pontos: ["A **lista de materiais (BOM)** pode ser escrita como matriz: linha = componente, coluna = produto, elemento = quantidade por unidade.", "**Necessidade de componentes = matriz BOM × vetor de produção** (explosão de um nível).", "Com vários níveis, a necessidade total considera os componentes dos componentes (produtos de matrizes ou (I − N)⁻¹).", "Planilhas usam a função MATRIZ.MULT (MMULT) para isso."],
        formulas: [["r = B · p", "r = necessidades de componentes; B = matriz da BOM; p = plano de produção"], ["Necessidade total = (I − N)⁻¹ · d", "N = matriz de uso entre itens; d = demanda externa"]],
        producao: "É exatamente o cálculo de **necessidade bruta do MRP** (Módulo 3) feito de uma vez para todos os itens, e é assim que os sistemas ERP organizam os dados.",
        exemplo: "Caixa presente usa 12 bombons e 1 embalagem; caixa mini usa 6 bombons e 1 embalagem. Plano: (200; 300).\nBombons = 12·200 + 6·300 = **4.200**; embalagens = 200 + 300 = **500**." }
    ],
    glossario: [["Vetor", "Lista ordenada de números."], ["Matriz", "Tabela retangular de números com m linhas e n colunas."], ["Matriz identidade", "Matriz quadrada com 1 na diagonal e 0 fora; neutra no produto."], ["Transposta", "Matriz obtida trocando linhas por colunas."], ["Sistema linear", "Conjunto de equações lineares; forma Ax = b."], ["Escalonamento", "Eliminação de Gauss: operações de linha até a forma triangular."], ["Determinante", "Número que indica, entre outras coisas, se a matriz é invertível."], ["Matriz inversa", "A⁻¹ tal que A·A⁻¹ = I."], ["Modelo de Leontief", "Modelo insumo-produto que usa (I − A)⁻¹ para calcular a produção necessária."], ["Explosão da BOM", "Cálculo das necessidades de componentes a partir do plano de produção."]],
    questoes: [
      { t: 0, id: "g-alg1-q01", tipo: "multipla", pergunta: "A tem dimensão 3×2 e B tem 2×4. Qual a dimensão de A·B?", opcoes: ["2×2", "3×4", "4×3", "O produto não existe"], correta: 1, explicacao: "Colunas de A (2) = linhas de B (2); o resultado tem as linhas de A e as colunas de B." },
      { t: 0, id: "g-alg1-t01", tipo: "calculo", variaveis: { c1: { valores: [0.015, 0.02, 0.025] }, c2: { valores: [0.02, 0.025, 0.03] }, q1: { min: 500, max: 3000, passo: 100 }, q2: { min: 200, max: 2000, passo: 100 } },
        resposta: "c1*q1+c2*q2", tolerancia: 0.01, unidade: "kg",
        pergunta: "O bombom A usa {c1} kg de chocolate e o B usa {c2} kg. Plano: {q1} de A e {q2} de B. Quanto chocolate é necessário (kg)? (2 casas)",
        resolucao: "{c1} × {q1} + {c2} × {q2} = {=c1*q1:2} + {=c2*q2:2} = {=c1*q1+c2*q2:2} kg", explicacao: "É um produto escalar: consumo unitário × quantidades." },
      { t: 0, id: "g-alg1-q02", tipo: "vf", pergunta: "Para quaisquer matrizes quadradas A e B, A·B = B·A.", correta: false, explicacao: "O produto de matrizes em geral não é comutativo." },
      { t: 1, id: "g-alg1-q03", tipo: "calculo", pergunta: "2x + y = 100 e x + 3y = 150. Qual o valor de y?", resposta: 40, tolerancia: 0, unidade: "lotes", resolucao: "Da 1ª: y = 100 − 2x. Na 2ª: x + 300 − 6x = 150 ⇒ x = 30; y = 40.", explicacao: "Substituição ou escalonamento dão o mesmo resultado." },
      { t: 1, id: "g-alg1-q04", tipo: "multipla", pergunta: "Ao resolver o plano de produção, o sistema deu x = −15 lotes. O que isso indica?", opcoes: ["Que se deve produzir 15 lotes", "Que o plano pedido é inviável com os recursos dados (produção negativa não existe)", "Um erro de arredondamento sem importância", "Que o sistema é indeterminado"], correta: 1, explicacao: "Matematicamente há solução, mas não é fisicamente possível." },
      { t: 1, id: "g-alg1-q05", tipo: "ligar", pergunta: "Ligue a classificação do sistema ao número de soluções:", pares: [["Possível determinado", "Uma única solução"], ["Possível indeterminado", "Infinitas soluções"], ["Impossível", "Nenhuma solução"]], explicacao: "SPD, SPI e SI." },
      { t: 2, id: "g-alg1-t02", tipo: "calculo", variaveis: { a: { min: 1, max: 9 }, b: { min: 1, max: 9 }, c: { min: 1, max: 9 }, d: { min: 1, max: 9 } },
        resposta: "a*d-b*c", tolerancia: 0, unidade: "", pergunta: "Qual o determinante da matriz [{a} {b}; {c} {d}]?", resolucao: "det = {a}·{d} − {b}·{c} = {=a*d} − {=b*c} = {=a*d-b*c}", explicacao: "Se o determinante for zero, a matriz não tem inversa." },
      { t: 2, id: "g-alg1-q06", tipo: "vf", pergunta: "Se det(A) = 0, o sistema Ax = b tem solução única.", correta: false, explicacao: "det = 0: A não é invertível; o sistema é indeterminado ou impossível." },
      { t: 2, id: "g-alg1-q07", tipo: "multipla", pergunta: "O modelo insumo-produto de Leontief usa qual expressão para calcular a produção necessária x a partir da demanda final d?", opcoes: ["x = A·d", "x = (I − A)⁻¹ · d", "x = d − A", "x = det(A) · d"], correta: 1, explicacao: "x = Ax + d ⇒ (I − A)x = d." },
      { t: 3, id: "g-alg1-t03", tipo: "calculo", variaveis: { pa: { min: 100, max: 500, passo: 50 }, pb: { min: 100, max: 500, passo: 50 }, ua: { valores: [6, 9, 12, 16, 24] }, ub: { valores: [4, 6, 8, 12] } },
        resposta: "ua*pa+ub*pb", tolerancia: 0, unidade: "bombons", pergunta: "A caixa A usa {ua} bombons e a B usa {ub}. Plano: {pa} caixas A e {pb} caixas B. Quantos bombons são necessários?",
        resolucao: "{ua} × {pa} + {ub} × {pb} = {=ua*pa+ub*pb}", explicacao: "Matriz da BOM × vetor de produção." },
      { t: 3, id: "g-alg1-q08", tipo: "multipla", pergunta: "Em planilhas, qual função faz o produto de matrizes (útil para explodir a BOM)?", opcoes: ["SOMA", "MATRIZ.MULT (MMULT)", "PROCV", "MÉDIA"], correta: 1, explicacao: "MATRIZ.MULT multiplica matrizes diretamente." },
      { t: 3, id: "g-alg1-q09", tipo: "vf", pergunta: "A necessidade bruta de componentes no MRP pode ser vista como o produto da matriz da lista de materiais pelo vetor do plano de produção.", correta: true, explicacao: "É a explosão de um nível da BOM." }
    ]
  },

  {
    id: "g-desenho", codigo: "GDES-7001", nome: "Desenho", periodo: 1, area: "engenharia", icone: "✏️", creditos: "(4-0-0) 4 créditos",
    intro: "O desenho é a **linguagem gráfica da engenharia**. O engenheiro de produção lê e faz desenhos de peças, plantas de fábrica (layout), fluxos e dispositivos; precisa entender vistas, escalas e cotas para conversar com projeto, fornecedores e chão de fábrica.",
    topicos: [
      { t: "Instrumentos, formatos e normas", icone: "📏",
        pontos: ["Desenho técnico segue **normas**: no Brasil, ABNT (NBR), alinhadas à ISO.", "**Formatos de papel** da série A: A0 (841 × 1189 mm) até A4 (210 × 297 mm); cada formato é metade do anterior.", "**Legenda** (carimbo): título, escala, unidade, autor, data, número do desenho.", "**Tipos de linha:** contínua grossa (arestas visíveis), tracejada (arestas ocultas), traço-ponto (linhas de centro e eixos de simetria), contínua fina (cotas e hachuras)."],
        formulas: [["A(n+1) = A(n) ÷ 2", "cada formato da série A tem metade da área do anterior"], ["Relação dos lados = √2", "permite ampliar/reduzir entre formatos sem distorção"]],
        producao: "Desenhos padronizados evitam erro de fabricação e retrabalho. O engenheiro de produção confere desenhos em análises de fabricação, dispositivos e layout.",
        exemplo: "Uma linha tracejada numa vista indica uma aresta que existe, mas está **escondida** atrás de outra superfície." },
      { t: "Escalas", icone: "🔍",
        pontos: ["**Escala** = tamanho no desenho : tamanho real.", "**Natural** 1:1; **redução** 1:2, 1:5, 1:10, 1:50, 1:100 (plantas); **ampliação** 2:1, 5:1 (peças pequenas).", "As **cotas** sempre indicam a medida **real**, qualquer que seja a escala.", "Plantas de fábrica costumam usar 1:50, 1:100 ou 1:200."],
        formulas: [["Medida real = medida no desenho × fator de escala", "em 1:100, 1 cm no papel = 100 cm (1 m) reais"], ["Medida no desenho = medida real ÷ fator", "para desenhar em escala de redução"]],
        producao: "Ler corretamente a escala de uma **planta baixa** é essencial para calcular áreas, distâncias de movimentação e posicionar máquinas no planejamento das instalações.",
        exemplo: "Numa planta 1:100, um corredor mede 2,5 cm no papel ⇒ **2,5 m** reais: cabe uma empilhadeira que precisa de 2,2 m?" },
      { t: "Projeções e vistas ortográficas", icone: "🧊",
        pontos: ["**Projeção ortográfica:** representa o objeto por vistas perpendiculares a planos de projeção.", "Vistas principais: **frontal**, **superior** e **lateral**.", "O Brasil usa o **1º diedro** (norma ABNT): a vista superior fica **abaixo** da frontal e a lateral esquerda fica à **direita** da frontal.", "Os EUA usam o 3º diedro; o símbolo do diedro deve aparecer na legenda.", "**Perspectiva** (isométrica, cavaleira) dá a visão 3D para facilitar a compreensão."],
        formulas: [["Isométrica: eixos a 120°", "as três direções têm a mesma redução, por isso as medidas podem ser tomadas diretamente"]],
        producao: "Ler vistas permite entender peças compradas, discutir tolerâncias com fornecedores e projetar dispositivos (gabaritos, poka-yokes) com a manutenção.",
        exemplo: "Uma peça com furo passante: na vista frontal o furo aparece como círculo; na superior, como duas linhas tracejadas." },
      { t: "Cotagem e desenho auxiliado por computador", icone: "💻",
        pontos: ["**Cota:** número que informa uma dimensão; tem linha de cota, linhas de chamada e setas.", "Cada medida é cotada **uma vez só**, na vista que melhor a mostra; evite cotar arestas ocultas.", "**CAD** (AutoCAD, SolidWorks, Fusion, FreeCAD): desenho em computador, modelos 3D e geração automática de vistas.", "**Cortes e hachuras** mostram o interior da peça."],
        formulas: [["Ø", "símbolo de diâmetro"], ["R", "símbolo de raio"]],
        producao: "Modelos CAD da fábrica permitem simular o layout, checar interferências e gerar a lista de materiais do produto (ligação com Projeto do Produto e PCP).",
        exemplo: "Ø20 H7 indica um furo de diâmetro nominal 20 mm com tolerância da classe H7 (tema de Desenho Técnico)." }
    ],
    glossario: [["Legenda (carimbo)", "Quadro com as informações do desenho: título, escala, autor, data."], ["Escala", "Razão entre a medida no desenho e a medida real."], ["Cota", "Indicação numérica de uma dimensão real."], ["Linha tracejada", "Representa arestas ocultas."], ["Linha traço-ponto", "Representa linhas de centro e eixos de simetria."], ["Projeção ortográfica", "Representação por vistas perpendiculares a planos."], ["1º diedro", "Sistema de projeção adotado no Brasil (ABNT)."], ["Perspectiva isométrica", "Vista 3D com eixos a 120°."], ["Hachura", "Linhas finas que indicam superfícies cortadas."], ["CAD", "Desenho assistido por computador."]],
    questoes: [
      { t: 0, id: "g-des-q01", tipo: "ligar", pergunta: "Ligue o tipo de linha ao uso:", pares: [["Contínua grossa", "Arestas visíveis"], ["Tracejada", "Arestas ocultas"], ["Traço-ponto", "Linhas de centro e simetria"], ["Contínua fina", "Cotas e hachuras"]], explicacao: "Tipos de linha padronizados." },
      { t: 0, id: "g-des-q02", tipo: "multipla", pergunta: "Quais as dimensões do formato A4?", opcoes: ["210 × 297 mm", "297 × 420 mm", "148 × 210 mm", "841 × 1189 mm"], correta: 0, explicacao: "A3 = 297 × 420; A5 = 148 × 210; A0 = 841 × 1189." },
      { t: 0, id: "g-des-q03", tipo: "vf", pergunta: "O formato A3 tem o dobro da área do A4.", correta: true, explicacao: "Cada formato da série A é metade do anterior." },
      { t: 1, id: "g-des-t01", tipo: "calculo", variaveis: { cm: { min: 1, max: 15, passo: 0.5 }, esc: { valores: [50, 100, 200] } }, resposta: "cm*esc/100", tolerancia: 0.01, unidade: "m",
        pergunta: "Numa planta na escala 1:{esc}, uma distância mede {cm} cm no papel. Qual a distância real (m)?", resolucao: "{cm} cm × {esc} = {=cm*esc} cm = {=cm*esc/100:2} m", explicacao: "Medida real = medida no desenho × fator de escala." },
      { t: 1, id: "g-des-q04", tipo: "vf", pergunta: "Num desenho em escala 1:2, as cotas devem indicar a metade da medida real.", correta: false, explicacao: "As cotas sempre indicam a medida real." },
      { t: 1, id: "g-des-q05", tipo: "multipla", pergunta: "Para desenhar um parafuso minúsculo de relógio, qual escala é mais adequada?", opcoes: ["1:100", "1:10", "5:1", "1:1.000"], correta: 2, explicacao: "Peças pequenas usam escala de ampliação." },
      { t: 2, id: "g-des-q06", tipo: "multipla", pergunta: "No 1º diedro (padrão ABNT), onde fica a vista superior em relação à frontal?", opcoes: ["Acima", "Abaixo", "À direita", "À esquerda"], correta: 1, explicacao: "No 1º diedro, a vista superior é desenhada abaixo da frontal." },
      { t: 2, id: "g-des-q07", tipo: "vf", pergunta: "Na perspectiva isométrica, os três eixos formam ângulos de 120° entre si.", correta: true, explicacao: "Por isso as três direções têm a mesma escala de redução." },
      { t: 2, id: "g-des-q08", tipo: "lacuna", pergunta: "O sistema de projeção adotado no Brasil é o ___ diedro.", opcoes: ["1º", "2º", "3º", "4º"], correta: 0, explicacao: "Os EUA usam o 3º diedro." },
      { t: 3, id: "g-des-q09", tipo: "multipla", pergunta: "O que significa o símbolo Ø numa cota?", opcoes: ["Raio", "Diâmetro", "Ângulo", "Profundidade"], correta: 1, explicacao: "R indica raio." },
      { t: 3, id: "g-des-q10", tipo: "vf", pergunta: "Uma mesma medida deve ser cotada em todas as vistas em que aparece, para garantir.", correta: false, explicacao: "Cada medida é cotada uma única vez; repetir gera conflito e erro." },
      { t: 3, id: "g-des-q11", tipo: "multipla", pergunta: "Para mostrar o interior de uma peça com furos internos, usa-se:", opcoes: ["Corte com hachuras", "Escala de ampliação", "Perspectiva cavaleira", "Linha de cota"], correta: 0, explicacao: "O corte expõe o interior; a hachura marca a superfície cortada." }
    ]
  },

  {
    id: "g-quimica", codigo: "GEXT-7702", nome: "Química", periodo: 1, area: "exatas", icone: "⚗️", creditos: "(2-2-0) 3 créditos",
    intro: "A química explica do que os materiais são feitos e como reagem. Na produção, ela aparece em **balanços de massa** (quanto de cada insumo), em processos químicos e alimentícios, em **corrosão** e escolha de materiais, em **tratamento de efluentes** e na segurança com produtos perigosos.",
    topicos: [
      { t: "Matéria, átomos e ligações", icone: "⚛️",
        pontos: ["**Átomo:** núcleo (prótons e nêutrons) e elétrons. O número de prótons define o elemento.", "**Tabela periódica:** organiza os elementos; metais (à esquerda) tendem a perder elétrons; não metais (à direita), a ganhar.", "**Ligações:** iônica (transferência de elétrons, ex.: NaCl), covalente (compartilhamento, ex.: H₂O) e metálica (mar de elétrons, explica condutividade dos metais).", "O tipo de ligação explica propriedades: ponto de fusão, condutividade, dureza."],
        formulas: [["n = m ÷ M", "n = quantidade de matéria (mol); m = massa (g); M = massa molar (g/mol)"], ["1 mol = 6,02 × 10²³ entidades", "constante de Avogadro"]],
        producao: "Entender ligações ajuda a escolher materiais (metais conduzem, polímeros isolam) e a prever comportamento em processos de fabricação.",
        exemplo: "Água: M = 18 g/mol. Em 900 g há n = 900 ÷ 18 = **50 mol**." },
      { t: "Reações e estequiometria", icone: "⚖️",
        pontos: ["**Reação química:** reagentes se transformam em produtos; a massa se conserva (Lavoisier).", "**Balancear** a equação: mesmo número de átomos de cada elemento dos dois lados.", "**Estequiometria:** usa as proporções em mol da equação balanceada para calcular quantidades.", "**Reagente limitante:** o que acaba primeiro e limita o produto; o outro fica em excesso.", "**Rendimento** = produto obtido ÷ produto teórico."],
        formulas: [["Σ massa dos reagentes = Σ massa dos produtos", "Lei de conservação das massas"], ["Rendimento (%) = real ÷ teórico × 100", "eficiência da reação"], ["C = n ÷ V", "concentração molar (mol/L)"]],
        producao: "Estequiometria é o **balanço de massa** de processos: quanto de cada insumo comprar, quanto de produto esperar e quanto de resíduo tratar. O rendimento é um indicador de processo.",
        exemplo: "CH₄ + 2 O₂ → CO₂ + 2 H₂O. Queimar 16 kg de metano (1 kmol) gera 44 kg de CO₂ (1 kmol): base para calcular emissões da caldeira." },
      { t: "Soluções, ácidos, bases e pH", icone: "🧪",
        pontos: ["**Solução:** soluto dissolvido em solvente; concentração em g/L, mol/L ou %.", "**Diluição:** C₁V₁ = C₂V₂ (a quantidade de soluto não muda).", "**pH** mede a acidez: 7 neutro, < 7 ácido, > 7 básico; é escala logarítmica.", "**Neutralização:** ácido + base → sal + água (usada no tratamento de efluentes)."],
        formulas: [["C₁ · V₁ = C₂ · V₂", "diluição"], ["pH = −log[H⁺]", "cada unidade de pH = 10 vezes na concentração de H⁺"]],
        producao: "Preparar soluções de limpeza (CIP em alimentos), controlar pH de efluentes antes do descarte (exigência ambiental) e de banhos de processo.",
        exemplo: "Diluir 2 L de detergente a 20% para 5%: V₂ = 20 × 2 ÷ 5 = **8 L** de solução final (acrescentar 6 L de água)." },
      { t: "Eletroquímica e corrosão", icone: "🔋",
        pontos: ["**Oxidação:** perda de elétrons; **redução:** ganho de elétrons.", "**Pilha:** reação espontânea gera corrente (baterias); **eletrólise:** corrente força uma reação (galvanoplastia).", "**Corrosão:** oxidação de metais pelo ambiente (ferrugem = óxido de ferro hidratado).", "Proteções: pintura, galvanização (zinco), **ânodo de sacrifício**, inox, controle de umidade."],
        formulas: [["Fe → Fe²⁺ + 2e⁻", "oxidação do ferro (início da corrosão)"], ["m = (M · I · t) ÷ (n · F)", "lei de Faraday: massa depositada na eletrólise; F ≈ 96.500 C/mol"]],
        producao: "Corrosão causa paradas, vazamentos e custos de manutenção; escolher material e proteção certos faz parte da gestão de ativos. Galvanoplastia é um processo de acabamento.",
        exemplo: "Estruturas de aço perto do mar recebem galvanização: o zinco oxida antes do ferro e o protege." }
    ],
    glossario: [["Mol", "Quantidade com 6,02 × 10²³ entidades."], ["Massa molar", "Massa de 1 mol de uma substância (g/mol)."], ["Estequiometria", "Cálculo das quantidades em reações a partir da equação balanceada."], ["Reagente limitante", "Reagente que se esgota primeiro e limita o produto."], ["Rendimento", "Produto real ÷ produto teórico."], ["pH", "Medida logarítmica da acidez de uma solução."], ["Oxidação", "Perda de elétrons."], ["Redução", "Ganho de elétrons."], ["Corrosão", "Deterioração de metais por reação com o ambiente."], ["Ânodo de sacrifício", "Metal mais reativo que se corrói no lugar da estrutura protegida."]],
    questoes: [
      { t: 0, id: "g-qui-t01", tipo: "calculo", variaveis: { m: { min: 90, max: 1800, passo: 18 } }, resposta: "m/18", tolerancia: 0.01, unidade: "mol", pergunta: "Quantos mols há em {m} g de água (M = 18 g/mol)?", resolucao: "n = {m} ÷ 18 = {=m/18:2} mol", explicacao: "n = m ÷ M." },
      { t: 0, id: "g-qui-q01", tipo: "ligar", pergunta: "Ligue a ligação química ao exemplo:", pares: [["Iônica", "Sal de cozinha (NaCl)"], ["Covalente", "Água (H₂O)"], ["Metálica", "Fio de cobre"]], explicacao: "O tipo de ligação explica as propriedades." },
      { t: 0, id: "g-qui-q02", tipo: "vf", pergunta: "A ligação metálica explica por que os metais conduzem bem eletricidade.", correta: true, explicacao: "Os elétrons livres (“mar de elétrons”) conduzem corrente." },
      { t: 1, id: "g-qui-q03", tipo: "multipla", pergunta: "O que é o reagente limitante?", opcoes: ["O reagente mais caro", "O reagente que acaba primeiro e limita a quantidade de produto", "O reagente em excesso", "O catalisador"], correta: 1, explicacao: "Os outros ficam sobrando." },
      { t: 1, id: "g-qui-t02", tipo: "calculo", variaveis: { teo: { min: 100, max: 1000, passo: 50 }, r: { min: 60, max: 98 } }, calc: { real: "teo*r/100" }, resposta: "real/teo*100", tolerancia: 0.1, unidade: "%",
        pergunta: "A produção teórica de um processo é {teo} kg, mas foram obtidos {real} kg. Qual o rendimento (%)?", resolucao: "{real} ÷ {teo} × 100 = {=real/teo*100:1}%", explicacao: "Rendimento baixo pode indicar perdas, reações paralelas ou condições inadequadas." },
      { t: 1, id: "g-qui-q04", tipo: "vf", pergunta: "Numa reação química, a massa total dos produtos é igual à massa total dos reagentes.", correta: true, explicacao: "Lei de Lavoisier: é a base do balanço de massa." },
      { t: 2, id: "g-qui-t03", tipo: "calculo", variaveis: { c1: { valores: [10, 20, 25, 40, 50] }, v1: { min: 1, max: 10 }, c2: { valores: [2, 4, 5] } }, resposta: "c1*v1/c2", tolerancia: 0.01, unidade: "L",
        pergunta: "Você tem {v1} L de solução a {c1}% e quer diluir para {c2}%. Qual o volume final (L)?", resolucao: "V₂ = C₁V₁ ÷ C₂ = {c1} × {v1} ÷ {c2} = {=c1*v1/c2:2} L", explicacao: "A quantidade de soluto é a mesma antes e depois." },
      { t: 2, id: "g-qui-q05", tipo: "multipla", pergunta: "Uma solução de pH 3 comparada a uma de pH 5 é:", opcoes: ["2 vezes mais ácida", "100 vezes mais ácida", "Menos ácida", "Igualmente ácida"], correta: 1, explicacao: "Escala logarítmica: 2 unidades = 10² = 100 vezes." },
      { t: 2, id: "g-qui-q06", tipo: "vf", pergunta: "Efluentes industriais muito ácidos podem ser neutralizados com uma base antes do descarte.", correta: true, explicacao: "Ácido + base → sal + água." },
      { t: 3, id: "g-qui-q07", tipo: "multipla", pergunta: "Na galvanização, o aço é revestido com zinco. Por que isso protege o aço?", opcoes: ["O zinco é mais nobre e não oxida", "O zinco oxida preferencialmente (ânodo de sacrifício), protegendo o ferro", "O zinco torna o aço magnético", "O zinco aumenta o pH"], correta: 1, explicacao: "O metal mais reativo se sacrifica." },
      { t: 3, id: "g-qui-q08", tipo: "ligar", pergunta: "Ligue o termo à definição:", pares: [["Oxidação", "Perda de elétrons"], ["Redução", "Ganho de elétrons"], ["Eletrólise", "Reação forçada por corrente elétrica"]], explicacao: "Pilha: espontânea; eletrólise: forçada." },
      { t: 3, id: "g-qui-q09", tipo: "caso", contexto: "Tubulações de aço carbono numa fábrica perto do litoral apresentam vazamentos frequentes por corrosão.", pergunta: "Qual ação é mais adequada?", opcoes: ["Aumentar a pressão da linha", "Avaliar proteção (pintura, galvanização, ânodo de sacrifício) ou material mais resistente (inox), considerando o custo do ciclo de vida", "Ignorar e trocar quando vazar", "Pintar só os pontos que vazaram"], correta: 1, explicacao: "Decisão de engenharia: proteção + custo total, não só o preço inicial." }
    ]
  },

  {
    id: "g-intadm", codigo: "GPRO-7826", nome: "Introdução à Administração", periodo: 1, area: "gestao", icone: "🏢", creditos: "(3-0-0) 3 créditos",
    intro: "Administrar é **planejar, organizar, dirigir e controlar** recursos para atingir objetivos. O engenheiro de produção é, na prática, um gestor: coordena pessoas, processos e recursos, e precisa entender as escolas da administração que moldaram as fábricas de hoje.",
    topicos: [
      { t: "Funções administrativas (PODC)", icone: "🧭",
        pontos: ["**Planejar:** definir objetivos e como alcançá-los.", "**Organizar:** distribuir tarefas, recursos e autoridade.", "**Dirigir:** liderar, motivar e comunicar.", "**Controlar:** medir resultados, comparar com o planejado e corrigir.", "As funções formam um ciclo contínuo, semelhante ao PDCA."],
        formulas: [["Eficácia = resultado alcançado ÷ resultado planejado", "fazer a coisa certa (atingir o objetivo)"], ["Eficiência = resultado ÷ recursos usados", "fazer certo, com pouco desperdício"]],
        producao: "O PCP é a aplicação direta do PODC à produção: planejar a demanda, organizar recursos, dirigir a execução e controlar o realizado.",
        exemplo: "Meta: 5.000 caixas no mês. Produziu 4.500 com 10% menos horas que o previsto: **eficiente**, mas **não eficaz**." },
      { t: "Escolas da administração", icone: "📜",
        pontos: ["**Administração Científica (Taylor):** estudo de tempos e métodos, padronização, incentivo por produção.", "**Teoria Clássica (Fayol):** funções administrativas, 14 princípios, unidade de comando, hierarquia.", "**Burocracia (Weber):** regras formais, impessoalidade, hierarquia e competência técnica.", "**Relações Humanas (Mayo, Hawthorne):** fatores sociais e psicológicos afetam a produtividade.", "**Abordagem sistêmica e contingencial:** a organização é um sistema aberto; não há uma única melhor maneira, depende do ambiente."],
        formulas: [],
        producao: "Taylor está na origem da Engenharia de Métodos (Módulo 4); as relações humanas explicam por que a participação dos operadores sustenta melhorias (Lean, Módulo 6).",
        exemplo: "Os estudos de Hawthorne (anos 1920–30) observaram que a atenção dada aos trabalhadores e as relações do grupo influenciavam o desempenho, não só as condições físicas." },
      { t: "Níveis organizacionais e tomada de decisão", icone: "🏛️",
        pontos: ["**Estratégico** (alta direção): decisões de longo prazo, toda a organização.", "**Tático** (gerências): transforma a estratégia em planos por área.", "**Operacional** (supervisão): execução do dia a dia.", "**Processo de decisão:** identificar o problema, gerar alternativas, avaliar, escolher, implementar e acompanhar.", "Decisões **programadas** (rotineiras, com regra) × **não programadas** (novas, sem regra)."],
        formulas: [],
        producao: "Os mesmos três níveis aparecem no PCP (planejamento estratégico, agregado e programação).",
        exemplo: "Construir uma nova fábrica: estratégico. Definir turnos do próximo trimestre: tático. Escalar quem opera a máquina hoje: operacional." },
      { t: "Ambiente e stakeholders", icone: "🌍",
        pontos: ["**Ambiente interno:** recursos, pessoas, cultura, processos.", "**Ambiente externo:** clientes, concorrentes, fornecedores, governo, tecnologia, economia.", "**Stakeholders (partes interessadas):** todos que afetam ou são afetados pela organização.", "**Missão, visão e valores** orientam as decisões.", "Responsabilidade social e ética fazem parte da gestão."],
        formulas: [],
        producao: "Decisões de produção afetam clientes (prazo, qualidade), trabalhadores (segurança), comunidade (meio ambiente) e acionistas (custo).",
        exemplo: "Uma nova lei ambiental (ambiente externo) obriga a fábrica a tratar efluentes: mudança de processo e de custos." }
    ],
    glossario: [["PODC", "Planejar, Organizar, Dirigir e Controlar."], ["Eficácia", "Atingir os objetivos."], ["Eficiência", "Usar bem os recursos."], ["Administração Científica", "Escola de Taylor: tempos, métodos e padronização."], ["Teoria Clássica", "Escola de Fayol: funções e princípios da administração."], ["Burocracia", "Modelo de Weber baseado em regras formais e impessoalidade."], ["Relações Humanas", "Escola que destaca fatores sociais e psicológicos (Mayo)."], ["Stakeholders", "Partes interessadas na organização."], ["Missão", "Razão de existir da organização."], ["Visão", "Onde a organização quer chegar."]],
    questoes: [
      { t: 0, id: "g-adm-q01", tipo: "ordenar", pergunta: "Ordene as funções administrativas:", itens: ["Planejar", "Organizar", "Dirigir", "Controlar"], explicacao: "PODC: forma um ciclo contínuo." },
      { t: 0, id: "g-adm-q02", tipo: "caso", contexto: "A fábrica atingiu a meta de produção, mas gastou 30% a mais de horas extras do que o previsto.", pergunta: "Como classificar o desempenho?", opcoes: ["Eficiente e eficaz", "Eficaz, mas não eficiente", "Eficiente, mas não eficaz", "Nem eficiente nem eficaz"], correta: 1, explicacao: "Atingiu o objetivo (eficaz), mas com desperdício de recursos (ineficiente)." },
      { t: 0, id: "g-adm-q03", tipo: "vf", pergunta: "Controlar é comparar o resultado com o planejado e tomar ações corretivas.", correta: true, explicacao: "Sem controle, o plano vira intenção." },
      { t: 1, id: "g-adm-q04", tipo: "ligar", pergunta: "Ligue o autor à escola:", pares: [["Taylor", "Administração Científica"], ["Fayol", "Teoria Clássica"], ["Weber", "Burocracia"], ["Elton Mayo", "Relações Humanas"]], explicacao: "Cada escola respondeu a problemas da sua época." },
      { t: 1, id: "g-adm-q05", tipo: "multipla", pergunta: "Qual foi a principal contribuição dos estudos de Hawthorne?", opcoes: ["Mostrar que só a iluminação afeta a produtividade", "Mostrar que fatores sociais e a atenção ao trabalhador influenciam o desempenho", "Criar a linha de montagem", "Criar o organograma"], correta: 1, explicacao: "Deu origem à Escola de Relações Humanas." },
      { t: 1, id: "g-adm-q06", tipo: "vf", pergunta: "A abordagem contingencial defende que existe uma única melhor forma de administrar qualquer empresa.", correta: false, explicacao: "Ela afirma que depende do ambiente e da situação." },
      { t: 2, id: "g-adm-q07", tipo: "ligar", pergunta: "Ligue a decisão ao nível:", pares: [["Abrir uma nova fábrica", "Estratégico"], ["Plano de produção do trimestre", "Tático"], ["Escala de operadores de hoje", "Operacional"]], explicacao: "Horizonte e abrangência mudam em cada nível." },
      { t: 2, id: "g-adm-q08", tipo: "ordenar", pergunta: "Ordene o processo de tomada de decisão:", itens: ["Identificar o problema", "Gerar alternativas", "Avaliar as alternativas", "Escolher e implementar", "Acompanhar os resultados"], explicacao: "Decisão estruturada reduz erros." },
      { t: 2, id: "g-adm-q09", tipo: "multipla", pergunta: "Reordenar automaticamente um item quando o estoque atinge o ponto de pedido é uma decisão:", opcoes: ["Não programada", "Programada", "Estratégica", "Aleatória"], correta: 1, explicacao: "Rotineira e com regra definida." },
      { t: 3, id: "g-adm-q10", tipo: "multipla", pergunta: "Qual destes faz parte do ambiente EXTERNO da empresa?", opcoes: ["Cultura organizacional", "Concorrentes", "Processos internos", "Equipe de manutenção"], correta: 1, explicacao: "Clientes, concorrentes, fornecedores, governo, economia e tecnologia." },
      { t: 3, id: "g-adm-q11", tipo: "vf", pergunta: "Stakeholders incluem apenas os acionistas da empresa.", correta: false, explicacao: "Incluem clientes, funcionários, fornecedores, comunidade, governo…" },
      { t: 3, id: "g-adm-q12", tipo: "ligar", pergunta: "Ligue o conceito à pergunta que ele responde:", pares: [["Missão", "Por que existimos?"], ["Visão", "Onde queremos chegar?"], ["Valores", "Como nos comportamos?"]], explicacao: "Base do planejamento estratégico." }
    ]
  },

  {
    id: "g-intep", codigo: "GPRO-7860", nome: "Introdução à Engenharia de Produção", periodo: 1, area: "producao", icone: "🏭", creditos: "(2-0-0) 2 créditos", relacionado: ["m01"],
    intro: "Apresenta a profissão: o que faz o engenheiro de produção, as **10 áreas da ABEPRO**, a visão da empresa como **sistema de produção** e os indicadores básicos de desempenho. O Módulo 1 do curso aprofunda cada ponto.",
    topicos: [
      { t: "A profissão e as áreas da ABEPRO", icone: "🎓",
        pontos: ["Engenheiro de produção projeta, melhora e gerencia **sistemas de produção** de bens e serviços (pessoas, materiais, equipamentos, informação, energia).", "A ABEPRO organiza a área em 10 subáreas: **Operações, Logística, Pesquisa Operacional, Qualidade, Produto, Organizacional, Econômica, Trabalho, Sustentabilidade e Educação**.", "Atua em indústria, serviços, logística, consultoria, bancos, saúde, governo.", "Exercício profissional: registro no **CREA** e anotação de responsabilidade técnica (ART) quando aplicável."],
        formulas: [],
        producao: "Saber as áreas ajuda a escolher estágio, optativas e o tema do projeto final.",
        exemplo: "Vagas típicas para recém-formados: analista de PCP, de processos, de qualidade, de logística, de melhoria contínua, trainee." },
      { t: "Sistema de produção", icone: "⚙️",
        pontos: ["Modelo **entrada → transformação → saída**, com realimentação (controle).", "**Recursos transformados:** materiais, informações, clientes. **Recursos de transformação:** instalações e pessoas.", "Produção de **bens** (tangíveis, estocáveis) × **serviços** (intangíveis, simultâneos ao consumo, com participação do cliente).", "Os **4 Vs**: volume, variedade, variação da demanda e visibilidade (Slack)."],
        formulas: [],
        producao: "Olhar a empresa como sistema evita otimizar uma parte e piorar o todo.",
        exemplo: "Hospital: entram pacientes (recurso transformado) e informações; médicos e equipamentos transformam; saem pacientes tratados." },
      { t: "Tipos de processo e objetivos de desempenho", icone: "🎯",
        pontos: ["Processos na manufatura: **projeto, jobbing, lotes, massa e contínuo** (do baixo volume/alta variedade ao alto volume/baixa variedade).", "Em serviços: **serviços profissionais, loja de serviços e serviços de massa**.", "**Cinco objetivos de desempenho:** qualidade, rapidez, confiabilidade, flexibilidade e custo.", "Há **trade-offs**: é difícil ser o melhor em todos ao mesmo tempo."],
        formulas: [],
        producao: "O tipo de processo define layout, PCP e tecnologia adequados.",
        exemplo: "Refinaria: processo contínuo. Gráfica de convites personalizados: jobbing/lotes pequenos." },
      { t: "Produtividade e indicadores", icone: "📊",
        pontos: ["**Produtividade** = saídas ÷ entradas.", "**Parcial** (um recurso: por hora, por kg) × **total** (todos os recursos em valor).", "**Eficiência** = real ÷ padrão (ou esperado); **eficácia** = atingir o objetivo.", "Indicador bom: fórmula clara, fonte, frequência, meta e dono."],
        formulas: [["Produtividade = saídas ÷ entradas", "ex.: peças por hora-homem"], ["Variação (%) = (novo − antigo) ÷ antigo × 100", "comparar produtividade entre períodos"]],
        producao: "Medir produtividade é o ponto de partida de qualquer melhoria.",
        exemplo: "Mês 1: 4.000 caixas com 800 h ⇒ 5 caixas/h. Mês 2: 4.400 com 800 h ⇒ 5,5 caixas/h: **+10%**." }
    ],
    glossario: [["ABEPRO", "Associação Brasileira de Engenharia de Produção."], ["Sistema de produção", "Conjunto que transforma entradas em saídas de valor."], ["Recursos transformados", "Materiais, informações ou clientes que são processados."], ["Recursos de transformação", "Instalações e pessoas que realizam a transformação."], ["4 Vs", "Volume, variedade, variação e visibilidade."], ["Objetivos de desempenho", "Qualidade, rapidez, confiabilidade, flexibilidade e custo."], ["Produtividade", "Saídas ÷ entradas."], ["CREA", "Conselho Regional de Engenharia e Agronomia."]],
    questoes: [
      { t: 0, id: "g-iep-q01", tipo: "multipla", pergunta: "Qual destas NÃO é uma das 10 áreas da Engenharia de Produção segundo a ABEPRO?", opcoes: ["Engenharia da Qualidade", "Pesquisa Operacional", "Engenharia de Petróleo", "Logística"], correta: 2, explicacao: "Petróleo é outra modalidade de engenharia." },
      { t: 0, id: "g-iep-q02", tipo: "vf", pergunta: "O engenheiro de produção pode atuar em serviços, como hospitais e bancos.", correta: true, explicacao: "Sistemas de produção incluem serviços." },
      { t: 0, id: "g-iep-q03", tipo: "lacuna", pergunta: "O registro profissional do engenheiro é feito no ___.", opcoes: ["CREA", "CRM", "OAB", "CRC"], correta: 0, explicacao: "Conselho Regional de Engenharia e Agronomia." },
      { t: 1, id: "g-iep-q04", tipo: "ordenar", pergunta: "Ordene o modelo de sistema de produção:", itens: ["Entradas", "Transformação", "Saídas", "Realimentação/controle"], explicacao: "Modelo input–transformação–output." },
      { t: 1, id: "g-iep-q05", tipo: "ligar", pergunta: "Classifique o recurso num restaurante:", pares: [["Ingredientes", "Transformado"], ["Cozinheiros", "De transformação"], ["Fogões", "De transformação"], ["Clientes com fome", "Transformado"]], explicacao: "Recursos transformados são processados; os de transformação agem sobre eles." },
      { t: 1, id: "g-iep-q06", tipo: "vf", pergunta: "Serviços podem ser estocados como os bens físicos.", correta: false, explicacao: "Serviços são, em geral, produzidos e consumidos ao mesmo tempo." },
      { t: 2, id: "g-iep-q07", tipo: "ordenar", pergunta: "Ordene os processos de manufatura do menor para o maior volume:", itens: ["Projeto", "Jobbing", "Lotes", "Massa", "Contínuo"], explicacao: "Mais volume, menos variedade." },
      { t: 2, id: "g-iep-q08", tipo: "multipla", pergunta: "Entregar sempre na data prometida corresponde a qual objetivo de desempenho?", opcoes: ["Rapidez", "Confiabilidade", "Flexibilidade", "Custo"], correta: 1, explicacao: "Rapidez é entregar em pouco tempo; confiabilidade, cumprir o prometido." },
      { t: 2, id: "g-iep-q09", tipo: "multipla", pergunta: "Uma refinaria de petróleo é um exemplo de processo:", opcoes: ["Por projeto", "Jobbing", "Contínuo", "Loja de serviços"], correta: 2, explicacao: "Alto volume, baixa variedade, fluxo ininterrupto." },
      { t: 3, id: "g-iep-t01", tipo: "calculo", variaveis: { q1: { min: 3000, max: 6000, passo: 100 }, h: { valores: [600, 800, 1000] }, g: { min: -10, max: 20 } }, condicao: "g != 0", calc: { q2: "round(q1*(1+g/100))" },
        resposta: "(q2/h - q1/h)/(q1/h)*100", tolerancia: 0.05, unidade: "%", pergunta: "Mês 1: {q1} caixas em {h} h. Mês 2: {q2} caixas nas mesmas {h} h. Qual a variação da produtividade (%)? (1 casa)",
        resolucao: "P1 = {q1} ÷ {h} = {=q1/h:2}; P2 = {q2} ÷ {h} = {=q2/h:2}\nVariação = ({=q2/h:2} − {=q1/h:2}) ÷ {=q1/h:2} × 100 = {=(q2/h-q1/h)/(q1/h)*100:1}%", explicacao: "Produtividade = saídas ÷ entradas." },
      { t: 3, id: "g-iep-q10", tipo: "vf", pergunta: "Produtividade total considera todos os recursos (mão de obra, materiais, energia, capital) em valor.", correta: true, explicacao: "A parcial considera um só recurso." },
      { t: 3, id: "g-iep-q11", tipo: "multipla", pergunta: "Qual é um bom indicador de produtividade da mão de obra?", opcoes: ["Número de funcionários", "Caixas produzidas por hora-homem", "Salário médio", "Área da fábrica"], correta: 1, explicacao: "Saída ÷ entrada do recurso." }
    ]
  }
);
