/* =====================================================================
   GRADE CURRICULAR — 2º PERÍODO (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-calc2", nome: "Cálculo a Várias Variáveis", periodo: 2, area: "exatas", icone: "🗻", prereq: ["g-calc1", "g-alg1"],
    intro: "Na vida real, a produção depende de **várias variáveis ao mesmo tempo**: capital e trabalho, preço de dois produtos, temperatura e tempo. As **derivadas parciais** medem o efeito de cada uma isoladamente; o **gradiente** e os **multiplicadores de Lagrange** encontram o melhor mix respeitando restrições (orçamento, capacidade); as **integrais duplas** somam grandezas espalhadas numa área.",
    topicos: [
      { t: "Funções de várias variáveis", icone: "🗺️",
        pontos: ["**f(x, y):** cada par (x, y) gera um valor; o gráfico é uma superfície.", "**Curvas de nível:** pontos com o mesmo valor de f (como num mapa topográfico).", "**Função de produção Cobb-Douglas:** Q = A·K^α·L^β, em que K é capital e L é trabalho.", "**Isoquanta:** curva de nível da produção, ou seja, combinações de K e L que produzem a mesma quantidade.", "Se α + β = 1, há **retornos constantes de escala**: dobrar K e L dobra Q."],
        formulas: [["Q = A · K^α · L^β", "Cobb-Douglas; A = tecnologia; α, β = elasticidades do capital e do trabalho"], ["α + β > 1 / = 1 / < 1", "retornos crescentes / constantes / decrescentes de escala"]],
        producao: "Funções de várias variáveis modelam produção, custo com vários insumos e qualidade em função de parâmetros do processo (temperatura, pressão, tempo).",
        exemplo: "Q = 10·K^0,5·L^0,5. Com K = 16 e L = 25: Q = 10 × 4 × 5 = **200 unidades**." },
      { t: "Derivadas parciais e gradiente", icone: "∂",
        pontos: ["**Derivada parcial** ∂f/∂x: deriva em x tratando as outras variáveis como constantes.", "**Produto marginal do trabalho** ∂Q/∂L: quanto a produção aumenta com uma hora a mais de trabalho, mantido o capital.", "**Gradiente** ∇f = (∂f/∂x, ∂f/∂y): aponta na direção de maior crescimento de f.", "**Regra da cadeia** para várias variáveis e **diferencial total**: df ≈ fₓ·dx + f_y·dy (estimar o efeito de pequenas mudanças simultâneas)."],
        formulas: [["∂Q/∂L = β · Q / L", "produto marginal do trabalho na Cobb-Douglas"], ["∇f = (∂f/∂x, ∂f/∂y)", "vetor gradiente"], ["Δf ≈ fₓ·Δx + f_y·Δy", "diferencial total (aproximação linear)"]],
        producao: "Derivadas parciais respondem: “se eu aumentar só a temperatura do forno, quanto muda o rendimento?”. O gradiente guia métodos de otimização numérica e de superfície de resposta (DOE).",
        exemplo: "Q = 10·K^0,5·L^0,5 com K = 16 e L = 25 (Q = 200): ∂Q/∂L = 0,5 × 200 ÷ 25 = **4 unidades por hora a mais de trabalho**." },
      { t: "Máximos, mínimos e Lagrange", icone: "⛰️",
        pontos: ["**Pontos críticos:** ∂f/∂x = 0 e ∂f/∂y = 0.", "**Teste da segunda derivada:** D = fₓₓ·f_yy − (fₓ_y)²; D > 0 e fₓₓ < 0 ⇒ máximo; D > 0 e fₓₓ > 0 ⇒ mínimo; D < 0 ⇒ ponto de sela.", "**Multiplicadores de Lagrange:** otimizar f sujeito a g = c resolvendo ∇f = λ∇g.", "λ é o **preço-sombra**: quanto o ótimo melhora com uma unidade a mais do recurso restrito.", "Com Cobb-Douglas e orçamento, o gasto ótimo em cada insumo é proporcional ao seu expoente."],
        formulas: [["∇f = λ · ∇g, g(x, y) = c", "condição de Lagrange"], ["D = fₓₓ·f_yy − (fₓ_y)²", "teste da 2ª derivada"], ["K* = (α/(α+β))·B/p_K; L* = (β/(α+β))·B/p_L", "Cobb-Douglas com orçamento B e preços p_K, p_L"]],
        producao: "Maximizar produção com orçamento limitado, minimizar custo para atingir uma meta de produção, escolher o mix de dois produtos que maximiza o lucro. O preço-sombra reaparece na Pesquisa Operacional.",
        exemplo: "Q = 10·K^0,5·L^0,5; orçamento B = R$ 1.000; p_K = R$ 10; p_L = R$ 5.\nK* = 0,5 × 1.000 ÷ 10 = **50**; L* = 0,5 × 1.000 ÷ 5 = **100**; Q* = 10 × √50 × √100 ≈ **707**." },
      { t: "Integrais duplas", icone: "🧊",
        pontos: ["**∬_R f(x, y) dA:** soma de f sobre uma região R (volume sob a superfície).", "Calcula-se como **integrais iteradas**: integra em x e depois em y (Fubini).", "Com f = 1, a integral dupla dá a **área** da região; com f = densidade, dá a **massa**.", "**Valor médio** de f na região = (1/Área) · ∬ f dA.", "Coordenadas polares ajudam em regiões circulares (dA = r dr dθ)."],
        formulas: [["∬_R f dA = ∫ₐᵇ ∫_c^d f(x, y) dy dx", "integral iterada num retângulo"], ["Massa = ∬ ρ(x, y) dA", "ρ = densidade superficial"], ["dA = r dr dθ", "elemento de área em coordenadas polares"]],
        producao: "Massa de chapas com espessura variável, demanda total de uma região com densidade populacional variável (localização de centros de distribuição), carga distribuída sobre um piso, volume de silos.",
        exemplo: "Uma chapa de 2 m × 1 m tem densidade ρ(x, y) = 3 + x kg/m². Massa = ∫₀² ∫₀¹ (3 + x) dy dx = ∫₀² (3 + x) dx = 6 + 2 = **8 kg**." }
    ],
    glossario: [["Derivada parcial", "Taxa de variação em relação a uma variável, com as outras fixas."], ["Gradiente", "Vetor das derivadas parciais; aponta para o maior crescimento."], ["Curva de nível", "Conjunto de pontos com o mesmo valor da função."], ["Isoquanta", "Combinações de insumos que dão a mesma produção."], ["Cobb-Douglas", "Função de produção Q = A·K^α·L^β."], ["Produto marginal", "Aumento da produção por unidade a mais de um insumo."], ["Ponto de sela", "Ponto crítico que não é máximo nem mínimo."], ["Multiplicador de Lagrange", "λ: taxa de melhora do ótimo por unidade a mais da restrição."], ["Preço-sombra", "Valor de uma unidade adicional de um recurso restrito."], ["Integral dupla", "Soma de uma função sobre uma região do plano."]],
    questoes: [
      { t: 0, id: "g-cal2-t01", tipo: "calculo", variaveis: { k: { valores: [4, 9, 16, 25, 36, 49] }, l: { valores: [4, 9, 16, 25, 36, 64] }, a: { valores: [2, 5, 10, 20] } },
        resposta: "a*sqrt(k)*sqrt(l)", tolerancia: 0.01, unidade: "unidades", pergunta: "Q = {a}·K^0,5·L^0,5. Qual a produção com K = {k} e L = {l}?", resolucao: "Q = {a} × √{k} × √{l} = {a} × {=sqrt(k)} × {=sqrt(l)} = {=a*sqrt(k)*sqrt(l)}", explicacao: "Expoente 0,5 = raiz quadrada." },
      { t: 0, id: "g-cal2-q01", tipo: "multipla", pergunta: "Na Cobb-Douglas Q = A·K^0,6·L^0,4, dobrar K e L faz a produção:", opcoes: ["Dobrar (retornos constantes)", "Quadruplicar", "Ficar igual", "Cair pela metade"], correta: 0, explicacao: "α + β = 1: retornos constantes de escala." },
      { t: 0, id: "g-cal2-q02", tipo: "vf", pergunta: "Uma isoquanta mostra combinações de capital e trabalho que geram a mesma produção.", correta: true, explicacao: "É a curva de nível da função de produção." },
      { t: 1, id: "g-cal2-q03", tipo: "multipla", pergunta: "Se f(x, y) = 3x²y + 5y, qual é ∂f/∂x?", opcoes: ["6xy", "3x² + 5", "6xy + 5", "3x²"], correta: 0, explicacao: "Deriva em x com y constante: 3y·2x = 6xy; 5y é constante em x." },
      { t: 1, id: "g-cal2-t02", tipo: "calculo", variaveis: { q: { min: 100, max: 800, passo: 20 }, l: { min: 10, max: 80, passo: 5 }, b: { valores: [0.3, 0.4, 0.5, 0.6, 0.7] } },
        resposta: "b*q/l", tolerancia: 0.01, unidade: "unid./h", pergunta: "Numa Cobb-Douglas com β = {b}, a produção é Q = {q} com L = {l} horas. Qual o produto marginal do trabalho ∂Q/∂L? (2 casas)", resolucao: "∂Q/∂L = β·Q/L = {b} × {q} ÷ {l} = {=b*q/l:2}", explicacao: "Quanto a produção cresce por hora a mais, com o capital fixo." },
      { t: 1, id: "g-cal2-q04", tipo: "vf", pergunta: "O gradiente de uma função aponta na direção em que ela diminui mais rapidamente.", correta: false, explicacao: "Aponta para o maior crescimento; o oposto (−∇f) é a maior diminuição." },
      { t: 2, id: "g-cal2-t03", tipo: "calculo", variaveis: { b: { min: 500, max: 5000, passo: 100 }, pk: { valores: [5, 10, 20, 25] }, al: { valores: [0.3, 0.4, 0.5, 0.6] } },
        resposta: "al*b/pk", tolerancia: 0.01, unidade: "unidades de capital", pergunta: "Q = K^{al}·L^{=1-al}, orçamento B = R$ {b}, preço do capital p_K = R$ {pk}. Pelo método de Lagrange, quanto capital K* comprar? (2 casas)", resolucao: "K* = (α/(α+β))·B/p_K = {al} × {b} ÷ {pk} = {=al*b/pk:2}", explicacao: "Com Cobb-Douglas, gasta-se no capital a fração α do orçamento." },
      { t: 2, id: "g-cal2-q05", tipo: "multipla", pergunta: "No teste da 2ª derivada, D > 0 e fₓₓ < 0 indicam:", opcoes: ["Mínimo local", "Máximo local", "Ponto de sela", "Nada se conclui"], correta: 1, explicacao: "Concavidade para baixo em todas as direções." },
      { t: 2, id: "g-cal2-q06", tipo: "multipla", pergunta: "O que o multiplicador de Lagrange λ representa numa restrição de orçamento?", opcoes: ["O preço do produto", "Quanto a produção ótima aumenta com R$ 1 a mais de orçamento", "O custo fixo", "A taxa de juros"], correta: 1, explicacao: "É o preço-sombra da restrição." },
      { t: 3, id: "g-cal2-t04", tipo: "calculo", variaveis: { a: { min: 1, max: 4 }, b: { min: 1, max: 3 }, c: { min: 1, max: 5 } },
        resposta: "c*a*b+a*a*b/2", tolerancia: 0.01, unidade: "kg", pergunta: "Uma chapa retangular de {a} m × {b} m (0 ≤ x ≤ {a}, 0 ≤ y ≤ {b}) tem densidade ρ = {c} + x kg/m². Qual a massa (kg)?", resolucao: "∫₀^{a} ∫₀^{b} ({c} + x) dy dx = {b} × [{c}x + x²/2]₀^{a} = {b} × ({=c*a} + {=a*a/2}) = {=c*a*b+a*a*b/2}", explicacao: "Massa = integral dupla da densidade." },
      { t: 3, id: "g-cal2-q07", tipo: "vf", pergunta: "A integral dupla de f(x, y) = 1 sobre uma região dá a área dessa região.", correta: true, explicacao: "Somar 1 em cada pedacinho dA dá a área." },
      { t: 3, id: "g-cal2-q08", tipo: "multipla", pergunta: "Para integrar sobre uma região circular (ex.: área de atendimento em volta de um depósito), qual troca de coordenadas simplifica?", opcoes: ["Cartesianas", "Polares, com dA = r dr dθ", "Logarítmicas", "Nenhuma"], correta: 1, explicacao: "Círculos ficam retângulos em (r, θ)." }
    ]
  },

  {
    id: "g-alg2", nome: "Álgebra Linear II", periodo: 2, area: "exatas", icone: "🧭", prereq: ["g-alg1"],
    intro: "Aprofunda a álgebra linear: espaços vetoriais, transformações, **autovalores e autovetores** e **mínimos quadrados**. Na produção, isso aparece em **cadeias de Markov** (estado de máquinas, fidelidade de clientes), em **regressão** para previsão de demanda e em técnicas de análise de dados como a **PCA**.",
    topicos: [
      { t: "Espaços vetoriais, base e dimensão", icone: "📦",
        pontos: ["**Espaço vetorial:** conjunto onde se pode somar vetores e multiplicar por escalares (ex.: ℝⁿ).", "**Combinação linear:** a₁v₁ + a₂v₂ + … + aₙvₙ.", "**Linearmente independentes (LI):** nenhum vetor é combinação dos outros.", "**Base:** conjunto LI que gera todo o espaço; **dimensão** = nº de vetores da base.", "**Posto** de uma matriz: nº de linhas (ou colunas) LI; indica quantas informações independentes existem."],
        formulas: [["a₁v₁ + … + aₙvₙ = 0 só com todos aᵢ = 0", "definição de vetores LI"], ["posto(A) + nulidade(A) = nº de colunas", "teorema do posto"]],
        producao: "Se dois indicadores de processo são combinação linear um do outro, um deles é redundante; o posto mostra quantas restrições são realmente independentes num modelo de PO.",
        exemplo: "Receitas de ração: se a receita C = 2·A + B, ela não traz informação nova: A, B e C não são LI." },
      { t: "Transformações lineares", icone: "🔀",
        pontos: ["**Transformação linear T:** T(u + v) = T(u) + T(v) e T(k·u) = k·T(u); é representada por uma matriz.", "Exemplos: rotação, escala, projeção, mudança de unidades.", "**Composição** de transformações = produto das matrizes.", "**Núcleo:** vetores levados ao zero; **imagem:** todos os resultados possíveis."],
        formulas: [["T(x) = A · x", "toda transformação linear em ℝⁿ é uma matriz"], ["(T₂ ∘ T₁)(x) = A₂ · A₁ · x", "composição"]],
        producao: "Converter produção por produto em consumo por insumo (matriz de consumo) é uma transformação linear; robôs e CAD usam matrizes de rotação e translação.",
        exemplo: "Rotação de 90° no plano: A = [0 −1; 1 0]; o ponto (2, 0) vai para (0, 2)." },
      { t: "Autovalores, autovetores e Markov", icone: "🎲",
        pontos: ["**Autovetor** v: A·v = λ·v (a matriz só “estica” v); **λ** é o autovalor.", "Autovalores: raízes de **det(A − λI) = 0** (polinômio característico).", "**Diagonalização:** A = P·D·P⁻¹ facilita calcular Aⁿ.", "**Cadeia de Markov:** probabilidades de passar de um estado a outro; a distribuição de longo prazo é o autovetor de autovalor 1.", "Para dois estados (operando/quebrada), a disponibilidade de longo prazo = r ÷ (f + r), com f = prob. de falhar e r = prob. de reparar em cada período."],
        formulas: [["A · v = λ · v", "definição de autovalor e autovetor"], ["det(A − λI) = 0", "equação característica"], ["π = π · P, Σπᵢ = 1", "distribuição estacionária de Markov"], ["π_operando = r ÷ (f + r)", "máquina com 2 estados"]],
        producao: "Markov estima **disponibilidade de máquinas** (manutenção), **participação de mercado** com clientes migrando entre marcas e estados de estoque. PCA usa autovetores da matriz de covariância para resumir muitas variáveis de processo.",
        exemplo: "Por dia, uma máquina operando quebra com prob. 0,1; quebrada, é consertada com prob. 0,6.\nπ_operando = 0,6 ÷ (0,1 + 0,6) ≈ **85,7%** do tempo operando no longo prazo." },
      { t: "Mínimos quadrados e ortogonalidade", icone: "📉",
        pontos: ["Vetores **ortogonais**: produto escalar zero (perpendiculares).", "**Projeção ortogonal:** o ponto do subespaço mais próximo de um vetor.", "Quando Ax = b não tem solução (mais equações que incógnitas, dados com ruído), busca-se x que **minimiza** ‖Ax − b‖²: **mínimos quadrados**.", "Solução pelas **equações normais**: AᵀA·x = Aᵀb.", "É a matemática por trás da **regressão linear**."],
        formulas: [["AᵀA · x̂ = Aᵀ · b", "equações normais (mínimos quadrados)"], ["proj_u(v) = (u·v ÷ u·u) · u", "projeção de v na direção de u"]],
        producao: "Ajustar a reta de tendência da demanda (Módulo 3), calibrar modelos de tempo padrão em função de variáveis (peso, distância) e ajustar curvas de aprendizagem a dados reais.",
        exemplo: "Pontos (1; 2), (2; 3), (3; 5): a reta de mínimos quadrados é y = 0,33 + 1,5x (a mesma da regressão)." }
    ],
    glossario: [["Espaço vetorial", "Conjunto com soma e multiplicação por escalar que satisfaz axiomas."], ["Linearmente independente", "Nenhum vetor é combinação linear dos outros."], ["Base", "Conjunto LI que gera o espaço."], ["Dimensão", "Número de vetores de uma base."], ["Posto", "Número de linhas/colunas LI de uma matriz."], ["Transformação linear", "Função que preserva soma e multiplicação por escalar."], ["Autovalor", "λ tal que Av = λv para algum v ≠ 0."], ["Autovetor", "Vetor não nulo que só é escalado por A."], ["Cadeia de Markov", "Processo em que a próxima etapa depende só do estado atual."], ["Mínimos quadrados", "Método que minimiza a soma dos quadrados dos erros."]],
    questoes: [
      { t: 0, id: "g-alg2-q01", tipo: "vf", pergunta: "Se um vetor é combinação linear dos outros, o conjunto é linearmente independente.", correta: false, explicacao: "É linearmente dependente." },
      { t: 0, id: "g-alg2-q02", tipo: "multipla", pergunta: "Qual a dimensão de ℝ³?", opcoes: ["1", "2", "3", "Infinita"], correta: 2, explicacao: "Base canônica: (1,0,0), (0,1,0), (0,0,1)." },
      { t: 0, id: "g-alg2-q03", tipo: "caso", contexto: "Num modelo de programação linear, a restrição 3 é exatamente a soma das restrições 1 e 2.", pergunta: "O que isso significa?", opcoes: ["A restrição 3 é redundante (as linhas não são LI)", "O modelo é impossível", "A restrição 3 é a mais importante", "O posto aumentou"], correta: 0, explicacao: "Ela não traz informação nova." },
      { t: 1, id: "g-alg2-q04", tipo: "multipla", pergunta: "A composição de duas transformações lineares corresponde a:", opcoes: ["Somar as matrizes", "Multiplicar as matrizes", "Transpor as matrizes", "Calcular o determinante"], correta: 1, explicacao: "(T₂∘T₁)(x) = A₂A₁x." },
      { t: 1, id: "g-alg2-q05", tipo: "vf", pergunta: "Toda transformação linear leva o vetor zero no vetor zero.", correta: true, explicacao: "T(0) = T(0·v) = 0·T(v) = 0." },
      { t: 1, id: "g-alg2-q06", tipo: "multipla", pergunta: "A matriz [0 −1; 1 0] aplicada ao ponto (2, 0) resulta em:", opcoes: ["(0, 2)", "(2, 0)", "(−2, 0)", "(0, −2)"], correta: 0, explicacao: "É uma rotação de 90° no sentido anti-horário." },
      { t: 2, id: "g-alg2-t01", tipo: "calculo", variaveis: { f: { valores: [0.02, 0.05, 0.08, 0.1, 0.15, 0.2] }, r: { valores: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8] } },
        resposta: "r/(f+r)*100", tolerancia: 0.05, unidade: "%", pergunta: "Por turno, uma máquina operando quebra com probabilidade {f}; quebrada, é reparada com probabilidade {r}. Qual a porcentagem do tempo operando no longo prazo? (1 casa)", resolucao: "π = r ÷ (f + r) = {r} ÷ ({f} + {r}) = {=r/(f+r)*100:1}%", explicacao: "Distribuição estacionária de uma cadeia de Markov com 2 estados." },
      { t: 2, id: "g-alg2-q07", tipo: "multipla", pergunta: "Os autovalores de A são as raízes de:", opcoes: ["det(A) = 0", "det(A − λI) = 0", "A·x = 0", "Aᵀ = A"], correta: 1, explicacao: "Polinômio característico." },
      { t: 2, id: "g-alg2-q08", tipo: "calculo", pergunta: "A = [3 0; 0 5] (diagonal). Qual o maior autovalor?", resposta: 5, tolerancia: 0, unidade: "", resolucao: "Numa matriz diagonal, os autovalores são os elementos da diagonal: 3 e 5.", explicacao: "det(A − λI) = (3 − λ)(5 − λ) = 0." },
      { t: 3, id: "g-alg2-q09", tipo: "multipla", pergunta: "Qual sistema dá a solução de mínimos quadrados de Ax ≈ b?", opcoes: ["Ax = b", "AᵀA x = Aᵀb", "A⁻¹x = b", "x = Ab"], correta: 1, explicacao: "Equações normais." },
      { t: 3, id: "g-alg2-q10", tipo: "vf", pergunta: "A regressão linear usada em previsão de demanda é uma aplicação de mínimos quadrados.", correta: true, explicacao: "Minimiza a soma dos quadrados dos erros." },
      { t: 3, id: "g-alg2-t02", tipo: "calculo", variaveis: { u1: { min: -5, max: 5 }, u2: { min: -5, max: 5 }, v1: { min: -5, max: 5 }, v2: { min: -5, max: 5 } },
        resposta: "u1*v1+u2*v2", tolerancia: 0, unidade: "", pergunta: "Qual o produto escalar de u = ({u1}, {u2}) e v = ({v1}, {v2})? (Se der zero, eles são ortogonais.)", resolucao: "u·v = {u1}×{v1} + {u2}×{v2} = {=u1*v1+u2*v2}", explicacao: "Produto escalar zero = vetores perpendiculares." }
    ]
  },

  {
    id: "g-comp", nome: "Computação", periodo: 2, area: "exatas", icone: "💻", relacionado: ["m14"],
    intro: "Programar é dar instruções precisas ao computador. O engenheiro de produção usa lógica de programação para **automatizar planilhas e relatórios**, tratar dados de produção, montar simulações e modelos de otimização (Python, VBA, SQL). O Módulo 14 aprofunda dados e analytics.",
    topicos: [
      { t: "Algoritmos e lógica", icone: "🧩",
        pontos: ["**Algoritmo:** sequência finita e precisa de passos para resolver um problema.", "Representações: **pseudocódigo** e **fluxograma** (início/fim, processo, decisão, entrada/saída).", "Três estruturas básicas: **sequência**, **decisão** (se… senão) e **repetição** (enquanto, para).", "**Operadores lógicos:** E (and), OU (or), NÃO (not); tabela-verdade.", "Bons algoritmos são corretos, claros e eficientes."],
        formulas: [["A E B é verdadeiro só se A e B forem verdadeiros", "operador lógico E"], ["A OU B é falso só se A e B forem falsos", "operador lógico OU"]],
        producao: "Regras de negócio viram algoritmos: “se o estoque ≤ ponto de pedido, então gerar ordem de compra”. É a lógica do MRP e de qualquer sistema de chão de fábrica.",
        exemplo: "SE temperatura > 32 °C E produto = chocolate ENTÃO acionar alarme; SENÃO seguir." },
      { t: "Variáveis, tipos e estruturas de dados", icone: "📦",
        pontos: ["**Variável:** nome que guarda um valor; tem **tipo**: inteiro, real (float), texto (string), lógico (booleano).", "**Listas/vetores:** sequência de valores acessados por índice (em Python começa em 0).", "**Matrizes:** listas de listas (linhas e colunas).", "**Dicionários:** pares chave → valor (ex.: código do produto → estoque).", "Escolher a estrutura certa simplifica o programa."],
        formulas: [["producao = [120, 135, 128]", "lista em Python; producao[0] = 120"], ["estoque = {\"A10\": 50, \"B20\": 12}", "dicionário: estoque[\"A10\"] = 50"]],
        producao: "Dados de produção são naturalmente listas (produção por hora), matrizes (máquina × turno) e dicionários (item → saldo).",
        exemplo: "tempos = [2.1, 1.9, 2.0, 2.2, 1.8] → média = sum(tempos)/len(tempos) = **2,0 min**." },
      { t: "Repetição, funções e depuração", icone: "🔁",
        pontos: ["**Laço para (for):** repete para cada item de uma lista ou número de vezes conhecido.", "**Laço enquanto (while):** repete enquanto uma condição for verdadeira (cuidado com laço infinito).", "**Função:** bloco reutilizável com entradas (parâmetros) e saída (return).", "**Depuração:** encontrar erros de sintaxe (o programa não roda) e de lógica (roda, mas dá resultado errado).", "Teste com casos simples, cujo resultado você conhece."],
        formulas: [["def oee(d, p, q): return d * p * q", "função em Python"], ["for x in lista: total += x", "acumulador num laço"]],
        producao: "Uma função que calcula o OEE, o takt ou o número de kanbans pode ser usada em qualquer relatório; laços percorrem milhares de registros de apontamento.",
        exemplo: "Contar quantas horas passaram de 100 peças: para cada valor da lista, se valor > 100, somar 1 no contador." },
      { t: "Ferramentas do engenheiro", icone: "🛠️",
        pontos: ["**Planilhas:** fórmulas, referências relativas/absolutas ($A$1), PROCV/PROCX, tabelas dinâmicas, Solver.", "**VBA/macros:** automatizam tarefas repetitivas no Excel.", "**Python:** pandas (tabelas), matplotlib (gráficos), bibliotecas de otimização e simulação.", "**SQL:** consulta bancos de dados de sistemas (ERP, MES).", "Boas práticas: dados brutos separados dos cálculos, nomes claros, versões."],
        formulas: [["=PROCV(valor; tabela; coluna; FALSO)", "busca exata numa tabela"], ["=$B$1*A2", "referência absoluta ($) não muda ao copiar a fórmula"]],
        producao: "Automatizar o relatório diário de produção, cruzar apontamentos com o ERP e testar cenários de planejamento sem refazer contas à mão.",
        exemplo: "Um script lê o arquivo de apontamentos do dia, calcula a produção por turno e gera o gráfico para a reunião das 8h." }
    ],
    glossario: [["Algoritmo", "Sequência finita de passos para resolver um problema."], ["Pseudocódigo", "Descrição do algoritmo em linguagem estruturada próxima da natural."], ["Variável", "Nome associado a um valor armazenado."], ["Booleano", "Tipo lógico: verdadeiro ou falso."], ["Lista", "Sequência ordenada de valores acessados por índice."], ["Dicionário", "Estrutura chave → valor."], ["Laço (loop)", "Estrutura que repete instruções."], ["Função", "Bloco reutilizável com parâmetros e retorno."], ["Depuração", "Processo de encontrar e corrigir erros."], ["Referência absoluta", "Endereço de célula fixo ao copiar a fórmula ($A$1)."]],
    questoes: [
      { t: 0, id: "g-comp-q01", tipo: "ligar", pergunta: "Ligue a estrutura ao exemplo:", pares: [["Sequência", "Ler dado, calcular, mostrar"], ["Decisão", "Se estoque ≤ mínimo, pedir"], ["Repetição", "Para cada máquina, somar a produção"]], explicacao: "As três estruturas de qualquer algoritmo." },
      { t: 0, id: "g-comp-q02", tipo: "multipla", pergunta: "A = verdadeiro e B = falso. Qual o valor de (A E B) OU (NÃO B)?", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "A E B = falso; NÃO B = verdadeiro; falso OU verdadeiro = verdadeiro." },
      { t: 0, id: "g-comp-q03", tipo: "vf", pergunta: "No fluxograma, o losango representa uma decisão.", correta: true, explicacao: "Retângulo: processo; losango: decisão; paralelogramo: entrada/saída." },
      { t: 1, id: "g-comp-q04", tipo: "multipla", pergunta: "Em Python, producao = [120, 135, 128]. Quanto vale producao[1]?", opcoes: ["120", "135", "128", "Erro"], correta: 1, explicacao: "Os índices começam em 0." },
      { t: 1, id: "g-comp-q05", tipo: "ligar", pergunta: "Ligue o dado ao tipo mais adequado:", pares: [["Quantidade de peças", "Inteiro"], ["Temperatura do forno", "Real (float)"], ["Código do produto", "Texto (string)"], ["Máquina ligada?", "Booleano"]], explicacao: "Escolher o tipo certo evita erros." },
      { t: 1, id: "g-comp-t01", tipo: "calculo", variaveis: { x: { lista: 5, min: 10, max: 50 } }, resposta: "media(x)", tolerancia: 0.01, unidade: "",
        pergunta: "lista = [{x}] (valores separados por ·). Qual o resultado de sum(lista)/len(lista)? (2 casas)", resolucao: "soma = {=soma(x)}; len = 5; média = {=media(x):2}", explicacao: "sum soma os itens; len conta os itens." },
      { t: 2, id: "g-comp-q06", tipo: "multipla", pergunta: "Qual o risco de um laço “enquanto” (while) mal construído?", opcoes: ["Rodar só uma vez", "Nunca parar (laço infinito)", "Apagar o arquivo", "Mudar o tipo da variável"], correta: 1, explicacao: "A condição precisa se tornar falsa em algum momento." },
      { t: 2, id: "g-comp-q07", tipo: "caso", contexto: "O programa de OEE roda sem erro, mas mostra 145% para uma máquina.", pergunta: "Que tipo de erro é esse e o que fazer?", opcoes: ["Erro de sintaxe; reinstalar o Python", "Erro de lógica; testar com um caso simples de resultado conhecido e revisar a fórmula e as unidades", "Não é erro", "Erro de hardware"], correta: 1, explicacao: "OEE acima de 100% indica fórmula ou dado errado (ex.: ciclo ideal em unidade diferente)." },
      { t: 2, id: "g-comp-q08", tipo: "vf", pergunta: "Funções permitem reutilizar o mesmo cálculo em vários pontos do programa.", correta: true, explicacao: "Menos repetição, menos erro." },
      { t: 3, id: "g-comp-q09", tipo: "multipla", pergunta: "Ao copiar =B1*A2 para a linha de baixo, a referência B1 deve continuar fixa. Como escrever?", opcoes: ["=B1*A2", "=$B$1*A2", "=B$1$*A2", "=FIXO(B1)*A2"], correta: 1, explicacao: "O cifrão fixa linha e coluna." },
      { t: 3, id: "g-comp-q10", tipo: "ligar", pergunta: "Ligue a ferramenta ao uso típico:", pares: [["SQL", "Consultar o banco de dados do ERP"], ["pandas (Python)", "Tratar tabelas de apontamento"], ["Tabela dinâmica", "Resumir dados na planilha"], ["Solver", "Otimizar um modelo na planilha"]], explicacao: "Cada ferramenta tem seu ponto forte." },
      { t: 3, id: "g-comp-q11", tipo: "vf", pergunta: "É boa prática misturar dados brutos e cálculos na mesma aba para facilitar.", correta: false, explicacao: "Separe dados, cálculos e relatório; fica mais auditável." }
    ]
  },

  {
    id: "g-mecbas", nome: "Mecânica Básica", periodo: 2, area: "exatas", icone: "🚚", prereq: ["g-calc1", "g-alg1"],
    intro: "Física do movimento e das forças (Física I). Na produção, explica **esteiras e transportadores**, frenagem de **empilhadeiras**, força para empurrar carrinhos (ergonomia), **potência de motores** de elevação e energia gasta em movimentação de materiais.",
    topicos: [
      { t: "Cinemática", icone: "🏃",
        pontos: ["**Posição, velocidade e aceleração:** v = dx/dt; a = dv/dt (cálculo aplicado).", "**MRU:** velocidade constante, x = x₀ + v·t.", "**MRUV:** aceleração constante, v = v₀ + a·t; x = x₀ + v₀t + a·t²/2; v² = v₀² + 2aΔx (Torricelli).", "**Queda livre:** a = g ≈ 9,8 m/s².", "Grandezas vetoriais têm módulo, direção e sentido."],
        formulas: [["x = x₀ + v·t", "MRU"], ["v = v₀ + a·t", "MRUV: velocidade"], ["v² = v₀² + 2·a·Δx", "Torricelli: sem o tempo"]],
        producao: "Velocidade de esteiras define o espaçamento entre peças e a taxa de produção; distância de frenagem de empilhadeiras define corredores e regras de segurança.",
        exemplo: "Empilhadeira a 3 m/s freia com a = −1,5 m/s²: distância = v₀² ÷ (2|a|) = 9 ÷ 3 = **3 m**." },
      { t: "Leis de Newton e atrito", icone: "🍎",
        pontos: ["**1ª lei (inércia):** sem força resultante, o corpo mantém o estado de movimento.", "**2ª lei:** F = m·a (força resultante).", "**3ª lei:** ação e reação, em corpos diferentes.", "**Peso** P = m·g; **normal** N perpendicular à superfície.", "**Atrito:** estático (até μₑN, impede o início do movimento) e cinético (μ_c·N, durante o movimento)."],
        formulas: [["F = m · a", "2ª lei de Newton"], ["P = m · g", "peso"], ["F_at = μ · N", "força de atrito"]],
        producao: "Força para empurrar carrinhos e paleteiras (limites ergonômicos), inclinação máxima de esteiras sem a caixa escorregar, fixação de cargas no transporte.",
        exemplo: "Carrinho de 200 kg, μ = 0,02: força para manter o movimento = 0,02 × 200 × 9,8 ≈ **39 N**." },
      { t: "Trabalho, energia e potência", icone: "⚡",
        pontos: ["**Trabalho** W = F·d·cos θ (joules).", "**Energia cinética** Ec = m·v²/2; **potencial gravitacional** Ep = m·g·h.", "**Conservação da energia:** sem atrito, a energia mecânica se conserva.", "**Potência** P = W ÷ t (watts); 1 cv ≈ 735,5 W.", "**Rendimento** η = potência útil ÷ potência consumida."],
        formulas: [["W = F · d · cos θ", "trabalho de uma força"], ["Ep = m · g · h", "energia potencial gravitacional"], ["P = W ÷ t = F · v", "potência"], ["η = P_útil ÷ P_consumida", "rendimento"]],
        producao: "Dimensionar motores de elevadores de carga e talhas, estimar o consumo de energia na movimentação de materiais e comparar equipamentos pelo rendimento.",
        exemplo: "Elevar 500 kg a 4 m em 10 s: P_útil = 500 × 9,8 × 4 ÷ 10 = **1.960 W**. Com η = 80%, o motor consome ≈ **2.450 W**." },
      { t: "Quantidade de movimento e rotação", icone: "🔄",
        pontos: ["**Quantidade de movimento** p = m·v; conserva-se em colisões sem força externa.", "**Impulso** I = F·Δt = Δp (para-choques e amortecedores aumentam Δt e reduzem a força).", "**Movimento circular:** v = ω·r; aceleração centrípeta a = v²/r.", "**Torque** τ = F·r·sen θ; em rotação, P = τ·ω.", "Polias e engrenagens transmitem movimento trocando velocidade por torque."],
        formulas: [["p = m · v", "quantidade de movimento"], ["F · Δt = Δp", "teorema do impulso"], ["P = τ · ω", "potência em rotação (ω em rad/s)"], ["v = ω · r", "velocidade periférica"]],
        producao: "Relação de transmissão de redutores em transportadores, velocidade periférica de ferramentas de corte e amortecimento de impactos em linhas de movimentação.",
        exemplo: "Tambor de esteira com raio 0,2 m a 30 rpm (π rad/s): v = π × 0,2 ≈ **0,63 m/s**." }
    ],
    glossario: [["MRU", "Movimento retilíneo uniforme (velocidade constante)."], ["MRUV", "Movimento com aceleração constante."], ["Força resultante", "Soma vetorial das forças sobre um corpo."], ["Atrito", "Força que se opõe ao deslizamento entre superfícies."], ["Trabalho", "Energia transferida por uma força ao longo de um deslocamento."], ["Energia cinética", "Energia do movimento: m·v²/2."], ["Potência", "Trabalho por unidade de tempo."], ["Rendimento", "Potência útil ÷ potência consumida."], ["Impulso", "Força × tempo; igual à variação da quantidade de movimento."], ["Torque", "Tendência de uma força girar um corpo."]],
    questoes: [
      { t: 0, id: "g-mec-t01", tipo: "calculo", variaveis: { v: { valores: [2, 2.5, 3, 4, 5] }, a: { valores: [1, 1.5, 2, 2.5] } }, resposta: "v*v/(2*a)", tolerancia: 0.01, unidade: "m",
        pergunta: "Uma empilhadeira a {v} m/s freia com desaceleração de {a} m/s². Qual a distância de frenagem (m)? (2 casas)", resolucao: "0 = v₀² − 2·a·d ⇒ d = {v}² ÷ (2 × {a}) = {=v*v/(2*a):2} m", explicacao: "Torricelli: dobrar a velocidade quadruplica a distância." },
      { t: 0, id: "g-mec-q01", tipo: "vf", pergunta: "Dobrando a velocidade de um veículo, a distância de frenagem (mesma desaceleração) dobra.", correta: false, explicacao: "Quadruplica: d = v²/(2a)." },
      { t: 0, id: "g-mec-q02", tipo: "multipla", pergunta: "Uma esteira anda a 0,5 m/s e as caixas saem a cada 1,2 m. Quantas caixas por minuto?", opcoes: ["25", "36", "50", "60"], correta: 0, explicacao: "0,5 m/s × 60 s = 30 m/min ÷ 1,2 m = 25 caixas/min." },
      { t: 1, id: "g-mec-t02", tipo: "calculo", variaveis: { m: { min: 50, max: 800, passo: 50 }, mu: { valores: [0.01, 0.02, 0.03, 0.05, 0.1] } }, resposta: "mu*m*9.8", tolerancia: 0.1, unidade: "N",
        pergunta: "Força para manter um carrinho de {m} kg em movimento constante, com coeficiente de atrito (rolamento) {mu}? (g = 9,8 m/s²)", resolucao: "F = μ·m·g = {mu} × {m} × 9,8 = {=mu*m*9.8:1} N", explicacao: "Velocidade constante: força aplicada = atrito." },
      { t: 1, id: "g-mec-q03", tipo: "ligar", pergunta: "Ligue a lei de Newton ao exemplo:", pares: [["1ª lei (inércia)", "A carga continua indo para a frente quando a empilhadeira freia"], ["2ª lei (F = ma)", "Mais força para acelerar um carrinho mais pesado"], ["3ª lei (ação e reação)", "Ao empurrar o carrinho, ele empurra você de volta"]], explicacao: "Por isso cargas precisam ser amarradas." },
      { t: 1, id: "g-mec-q04", tipo: "vf", pergunta: "O atrito estático máximo costuma ser maior que o atrito cinético, por isso é mais difícil começar a mover um objeto do que mantê-lo em movimento.", correta: true, explicacao: "μₑ > μ_c em geral." },
      { t: 2, id: "g-mec-t03", tipo: "calculo", variaveis: { m: { min: 100, max: 1000, passo: 50 }, h: { min: 2, max: 10 }, tt: { min: 5, max: 30, passo: 5 }, eta: { valores: [0.7, 0.75, 0.8, 0.85, 0.9] } }, resposta: "m*9.8*h/tt/eta", tolerancia: 1, unidade: "W",
        pergunta: "Uma talha eleva {m} kg a {h} m em {tt} s, com rendimento de {=eta*100}%. Qual a potência consumida pelo motor (W)? (inteiro)", resolucao: "P_útil = m·g·h ÷ t = {m} × 9,8 × {h} ÷ {tt} = {=m*9.8*h/tt:0} W\nP_consumida = {=m*9.8*h/tt:0} ÷ {eta} ≈ {=m*9.8*h/tt/eta:0} W", explicacao: "O motor precisa cobrir as perdas." },
      { t: 2, id: "g-mec-q05", tipo: "multipla", pergunta: "1 cv corresponde a aproximadamente:", opcoes: ["100 W", "735,5 W", "1.000 W", "9,8 W"], correta: 1, explicacao: "Cavalo-vapor; 1 hp ≈ 745,7 W." },
      { t: 2, id: "g-mec-q06", tipo: "vf", pergunta: "Um motor com rendimento de 85% transforma 85% da energia elétrica em trabalho útil; o resto vira principalmente calor.", correta: true, explicacao: "As perdas aquecem o motor." },
      { t: 3, id: "g-mec-q07", tipo: "multipla", pergunta: "Por que amortecedores reduzem a força do impacto de uma carga que cai?", opcoes: ["Reduzem a massa", "Aumentam o tempo do impacto (F = Δp/Δt)", "Aumentam a velocidade", "Eliminam a quantidade de movimento"], correta: 1, explicacao: "Mesma variação de p em mais tempo = menos força." },
      { t: 3, id: "g-mec-t04", tipo: "calculo", variaveis: { r: { valores: [0.1, 0.15, 0.2, 0.25, 0.3] }, rpm: { valores: [20, 30, 45, 60, 90] } }, resposta: "2*PI*rpm/60*r", tolerancia: 0.01, unidade: "m/s",
        pergunta: "O tambor de uma esteira tem raio {r} m e gira a {rpm} rpm. Qual a velocidade da esteira (m/s)? (2 casas)", resolucao: "ω = 2π × {rpm} ÷ 60 = {=2*PI*rpm/60:3} rad/s\nv = ω·r = {=2*PI*rpm/60*r:2} m/s", explicacao: "Converter rpm em rad/s: × 2π ÷ 60." },
      { t: 3, id: "g-mec-q08", tipo: "vf", pergunta: "Um redutor que diminui a rotação aumenta o torque disponível (desprezando perdas).", correta: true, explicacao: "P = τ·ω constante: ω menor ⇒ τ maior." }
    ]
  },

  {
    id: "g-human", nome: "Humanidades e Ciências Sociais", periodo: 2, area: "humanas", icone: "🌎",
    intro: "Engenharia transforma a sociedade e é transformada por ela. Esta disciplina traz conceitos das ciências sociais para entender o **trabalho**, a **tecnologia**, a **ética**, a **diversidade** e a **cidadania**, que aparecem nas decisões do engenheiro de produção sobre pessoas, processos e comunidade.",
    topicos: [
      { t: "Sociologia do trabalho", icone: "👷",
        pontos: ["**Durkheim:** divisão do trabalho e coesão social (solidariedade mecânica × orgânica).", "**Marx:** trabalho, capital e **alienação** do trabalhador em relação ao produto e ao processo.", "**Weber:** racionalização e burocracia como marcas da modernidade.", "**Taylorismo-fordismo** e depois **toyotismo**: mudanças na organização do trabalho e seus efeitos sobre os trabalhadores.", "Debates atuais: automação, plataformas digitais, trabalho remoto."],
        formulas: [],
        producao: "Mudanças de método, automação e metas afetam a vida das pessoas; entender o trabalho como fenômeno social ajuda a implantar melhorias com adesão e sem adoecimento.",
        exemplo: "Uma linha muito fragmentada pode ter alta produtividade e, ao mesmo tempo, monotonia e perda de sentido do trabalho (alienação, na leitura marxista)." },
      { t: "Ciência, tecnologia e sociedade", icone: "🔬",
        pontos: ["Tecnologia não é neutra: escolhas técnicas têm efeitos sociais, ambientais e econômicos.", "**Revoluções industriais:** mecanização, eletricidade e produção em massa, automação eletrônica e, hoje, digitalização (Indústria 4.0).", "Impactos no emprego, nas qualificações exigidas e nas desigualdades.", "Avaliação de impactos antes de implantar novas tecnologias."],
        formulas: [],
        producao: "Projetos de automação devem considerar requalificação das pessoas, segurança e impacto na comunidade, não só o retorno financeiro.",
        exemplo: "Ao automatizar a embalagem, a empresa treina operadores para funções de manutenção e controle de qualidade." },
      { t: "Ética e responsabilidade profissional", icone: "⚖️",
        pontos: ["**Ética:** reflexão sobre o que é certo; **moral:** normas aceitas por um grupo.", "O engenheiro segue o **Código de Ética Profissional** do sistema Confea/Crea.", "Dilemas: segurança × prazo, custo × qualidade, lealdade à empresa × interesse público.", "Denunciar riscos graves à vida e ao meio ambiente é dever profissional.", "Integridade: não falsificar dados, relatórios ou medições."],
        formulas: [],
        producao: "Liberar um lote fora de especificação, ocultar um acidente ou ajustar indicadores para bater meta são dilemas éticos reais do dia a dia da produção.",
        exemplo: "Um teste de segurança falhou às vésperas da entrega. A resposta ética é não liberar o produto e comunicar o risco, mesmo com custo." },
      { t: "Diversidade, cidadania e direitos humanos", icone: "🤝",
        pontos: ["**Direitos humanos** e cidadania como base da convivência democrática.", "**Relações étnico-raciais:** o racismo estrutural afeta acesso a educação, emprego e renda; a legislação brasileira criminaliza o racismo.", "**Diversidade e inclusão:** gênero, raça, pessoas com deficiência (Lei Brasileira de Inclusão, Lei 13.146/2015), gerações.", "Equipes diversas tendem a considerar mais pontos de vista na solução de problemas.", "Acessibilidade é também um requisito de projeto (produtos, postos de trabalho, instalações)."],
        formulas: [],
        producao: "Projetar postos de trabalho acessíveis, processos seletivos justos e ambientes sem assédio faz parte da gestão de pessoas e da responsabilidade social da produção.",
        exemplo: "Adaptar um posto (altura regulável, sinalização visual além da sonora) permite incluir trabalhadores com deficiência e melhora a ergonomia de todos." }
    ],
    glossario: [["Divisão do trabalho", "Especialização das tarefas entre pessoas ou grupos."], ["Alienação", "Na leitura marxista, separação do trabalhador em relação ao produto e ao processo de trabalho."], ["Racionalização", "Organização da vida social por regras, cálculo e eficiência (Weber)."], ["Toyotismo", "Modelo de organização do trabalho da Toyota: flexibilidade e trabalho em equipe."], ["Indústria 4.0", "Digitalização e integração da produção (sensores, dados, automação)."], ["Ética", "Reflexão sobre valores e o que é certo."], ["Racismo estrutural", "Desigualdades raciais reproduzidas pelas instituições e práticas sociais."], ["Acessibilidade", "Possibilidade de uso por todas as pessoas, com autonomia e segurança."]],
    questoes: [
      { t: 0, id: "g-hum-q01", tipo: "ligar", pergunta: "Ligue o autor ao conceito:", pares: [["Durkheim", "Divisão do trabalho e coesão social"], ["Marx", "Alienação do trabalho"], ["Weber", "Racionalização e burocracia"]], explicacao: "Os três clássicos da sociologia." },
      { t: 0, id: "g-hum-q02", tipo: "multipla", pergunta: "Qual característica é associada ao toyotismo em contraste com o fordismo?", opcoes: ["Tarefas mais fragmentadas e rígidas", "Trabalho em equipe e maior flexibilidade", "Estoques maiores", "Produção de um único modelo"], correta: 1, explicacao: "Multifuncionalidade e produção enxuta." },
      { t: 0, id: "g-hum-q03", tipo: "vf", pergunta: "Mudanças na organização do trabalho podem aumentar a produtividade e, ao mesmo tempo, causar efeitos negativos nos trabalhadores.", correta: true, explicacao: "Por isso ergonomia e participação são essenciais." },
      { t: 1, id: "g-hum-q04", tipo: "multipla", pergunta: "“A tecnologia não é neutra” significa que:", opcoes: ["Máquinas têm opiniões", "Escolhas técnicas têm efeitos sociais, ambientais e econômicos que devem ser considerados", "Toda tecnologia é ruim", "Tecnologia não afeta empregos"], correta: 1, explicacao: "O engenheiro avalia impactos além do técnico." },
      { t: 1, id: "g-hum-q05", tipo: "ordenar", pergunta: "Ordene as revoluções industriais:", itens: ["Mecanização a vapor", "Eletricidade e produção em massa", "Eletrônica e automação", "Digitalização (Indústria 4.0)"], explicacao: "Cada uma mudou o trabalho e a sociedade." },
      { t: 1, id: "g-hum-q06", tipo: "vf", pergunta: "Planejar a requalificação das pessoas faz parte de um bom projeto de automação.", correta: true, explicacao: "Reduz impacto social e aproveita o conhecimento." },
      { t: 2, id: "g-hum-q07", tipo: "caso", contexto: "Às vésperas de uma entrega, o teste de segurança de um lote falha. O gerente sugere liberar e “corrigir no próximo”.", pergunta: "Qual a conduta ética do engenheiro?", opcoes: ["Liberar, pois o prazo é mais importante", "Não liberar, registrar e comunicar o risco, buscando solução com a gestão e o cliente", "Alterar o resultado do teste", "Ignorar e deixar a decisão para outros"], correta: 1, explicacao: "Segurança e integridade vêm antes do prazo." },
      { t: 2, id: "g-hum-q08", tipo: "multipla", pergunta: "O código de ética que orienta o engenheiro no Brasil é do sistema:", opcoes: ["OAB", "Confea/Crea", "CFM", "CRC"], correta: 1, explicacao: "Conselho Federal de Engenharia e Agronomia e conselhos regionais." },
      { t: 2, id: "g-hum-q09", tipo: "vf", pergunta: "Ajustar um indicador para bater a meta sem melhorar o processo é uma questão ética.", correta: true, explicacao: "É falsear informação para quem decide." },
      { t: 3, id: "g-hum-q10", tipo: "multipla", pergunta: "Qual lei brasileira trata da inclusão da pessoa com deficiência?", opcoes: ["Lei 13.146/2015 (Lei Brasileira de Inclusão)", "Lei 12.305/2010", "Lei 8.666/1993", "CLT, art. 59"], correta: 0, explicacao: "A 12.305/2010 é a Política Nacional de Resíduos Sólidos." },
      { t: 3, id: "g-hum-q11", tipo: "vf", pergunta: "Acessibilidade é um requisito que pode ser considerado já no projeto de produtos, postos de trabalho e instalações.", correta: true, explicacao: "Projetar acessível desde o início custa menos que adaptar depois." },
      { t: 3, id: "g-hum-q12", tipo: "multipla", pergunta: "Qual prática reduz vieses num processo seletivo?", opcoes: ["Contratar só por indicação", "Critérios claros definidos antes, avaliação estruturada e banca diversa", "Decidir pela primeira impressão", "Não registrar os critérios"], correta: 1, explicacao: "Processos estruturados reduzem discriminação." }
    ]
  },

  {
    id: "g-metcie", nome: "Metodologia Científica", periodo: 2, area: "humanas", icone: "🔎",
    intro: "Ensina a **pesquisar e escrever** com rigor: formular problemas, escolher métodos, buscar fontes confiáveis, citar e referenciar pelas normas ABNT. É a base do **projeto final (TCC)**, de relatórios técnicos e de qualquer estudo de melhoria baseado em dados.",
    topicos: [
      { t: "Ciência e método científico", icone: "🧪",
        pontos: ["**Conhecimento científico:** sistemático, verificável, baseado em evidências e aberto à revisão.", "Etapas: **observação → problema → hipótese → teste (coleta e análise) → conclusão → comunicação**.", "**Hipótese:** resposta provisória e testável ao problema.", "**Variáveis:** independente (causa investigada), dependente (efeito medido), de controle.", "Correlação não é causalidade."],
        formulas: [],
        producao: "O PDCA e o DMAIC são aplicações do método científico à melhoria de processos: hipótese de causa, teste, medição e conclusão.",
        exemplo: "Problema: refugo alto no turno da noite. Hipótese: temperatura da câmara mais alta à noite. Teste: medir temperatura e refugo por 4 semanas." },
      { t: "Tipos de pesquisa", icone: "🗂️",
        pontos: ["Quanto à **abordagem:** quantitativa (números, estatística), qualitativa (significados, entrevistas) ou mista.", "Quanto aos **objetivos:** exploratória (conhecer o tema), descritiva (descrever características), explicativa (identificar causas).", "Quanto aos **procedimentos:** bibliográfica, documental, experimental, levantamento (survey), **estudo de caso**, **pesquisa-ação**, modelagem e simulação.", "Em Engenharia de Produção, são muito comuns estudo de caso, modelagem/simulação e pesquisa-ação."],
        formulas: [],
        producao: "Um TCC sobre redução de setup numa empresa costuma ser pesquisa-ação ou estudo de caso, com abordagem quantitativa (tempos) e qualitativa (entrevistas).",
        exemplo: "Aplicar SMED numa linha, participando da mudança e medindo antes × depois: **pesquisa-ação**." },
      { t: "Fontes, citações e referências (ABNT)", icone: "📚",
        pontos: ["Fontes confiáveis: artigos revisados por pares, livros técnicos, normas, dados oficiais. Cuidado com sites sem autoria.", "Bases de busca: Portal de Periódicos da CAPES, SciELO, Google Acadêmico, Scopus, Web of Science.", "**Citação direta** (literal, entre aspas, com página) e **indireta** (paráfrase, com autor e ano) — ABNT NBR 10520.", "**Referências** ao final, pela ABNT NBR 6023.", "**Plágio** é usar ideias ou textos de outros sem citar: é falta grave."],
        formulas: [["(SOBRENOME, ano, p. X)", "citação direta no sistema autor-data"], ["Sobrenome (ano)", "citação indireta no texto"]],
        producao: "Relatórios técnicos e laudos também precisam de fontes: norma usada, origem dos dados, referência do método.",
        exemplo: "Direta: “trecho copiado do autor” (SILVA, 2020, p. 45). Indireta: Segundo Silva (2020), o setup longo aumenta o tamanho dos lotes. (Autor e ano fictícios, só para mostrar o formato.)" },
      { t: "Estrutura do trabalho acadêmico", icone: "📝",
        pontos: ["**Elementos pré-textuais:** capa, folha de rosto, resumo, sumário.", "**Textuais:** introdução (problema, objetivos, justificativa), referencial teórico, metodologia, resultados e discussão, conclusão.", "**Pós-textuais:** referências, apêndices, anexos.", "Formatação de trabalhos acadêmicos: ABNT NBR 14724.", "**Objetivo geral** (verbo no infinitivo) e **objetivos específicos** (etapas mensuráveis)."],
        formulas: [],
        producao: "A mesma estrutura (problema → método → resultados → conclusão) serve para relatórios de projeto de melhoria e A3.",
        exemplo: "Objetivo geral: “Reduzir o tempo de setup da banhadeira”. Específicos: mapear o setup atual; separar atividades internas e externas; propor e testar melhorias; medir o resultado." }
    ],
    glossario: [["Método científico", "Procedimento sistemático de formular e testar hipóteses."], ["Hipótese", "Resposta provisória e testável ao problema."], ["Variável dependente", "Efeito medido na pesquisa."], ["Estudo de caso", "Investigação aprofundada de um ou poucos casos no seu contexto."], ["Pesquisa-ação", "Pesquisa em que o pesquisador participa da mudança que estuda."], ["Survey", "Levantamento com questionários aplicados a uma amostra."], ["Citação direta", "Transcrição literal, entre aspas, com página."], ["Citação indireta", "Paráfrase da ideia do autor, com a fonte."], ["Plágio", "Uso de obra alheia sem atribuição."], ["Revisão por pares", "Avaliação de um artigo por especialistas antes da publicação."]],
    questoes: [
      { t: 0, id: "g-met-q01", tipo: "ordenar", pergunta: "Ordene as etapas do método científico:", itens: ["Observação", "Formulação do problema", "Hipótese", "Teste (coleta e análise)", "Conclusão e comunicação"], explicacao: "É a mesma lógica do PDCA." },
      { t: 0, id: "g-met-q02", tipo: "multipla", pergunta: "No estudo “a temperatura da câmara afeta o refugo?”, qual é a variável dependente?", opcoes: ["Temperatura", "Refugo", "Turno", "Nenhuma"], correta: 1, explicacao: "É o efeito medido." },
      { t: 0, id: "g-met-q03", tipo: "vf", pergunta: "Se duas variáveis estão correlacionadas, uma necessariamente causa a outra.", correta: false, explicacao: "Pode haver uma terceira variável ou coincidência." },
      { t: 1, id: "g-met-q04", tipo: "ligar", pergunta: "Ligue o tipo de pesquisa ao exemplo:", pares: [["Estudo de caso", "Análise aprofundada do PCP de uma empresa"], ["Survey", "Questionário com 200 gestores sobre Lean"], ["Pesquisa-ação", "O pesquisador implanta o SMED e mede os resultados"], ["Bibliográfica", "Revisão de artigos sobre OEE"]], explicacao: "Procedimentos técnicos da pesquisa." },
      { t: 1, id: "g-met-q05", tipo: "multipla", pergunta: "Uma pesquisa que busca identificar CAUSAS de um fenômeno é:", opcoes: ["Exploratória", "Descritiva", "Explicativa", "Bibliográfica"], correta: 2, explicacao: "Explicativa: por que acontece." },
      { t: 1, id: "g-met-q06", tipo: "vf", pergunta: "Pesquisas qualitativas podem usar entrevistas e observação para entender significados e percepções.", correta: true, explicacao: "Complementam os dados numéricos." },
      { t: 2, id: "g-met-q07", tipo: "multipla", pergunta: "Qual norma ABNT trata das referências?", opcoes: ["NBR 6023", "NBR 10520", "NBR 14724", "NBR ISO 9001"], correta: 0, explicacao: "10520: citações; 14724: trabalhos acadêmicos." },
      { t: 2, id: "g-met-q08", tipo: "vf", pergunta: "Na citação direta, é obrigatório indicar a página de onde o trecho foi retirado.", correta: true, explicacao: "Autor, ano e página." },
      { t: 2, id: "g-met-q09", tipo: "multipla", pergunta: "Qual fonte é mais confiável para fundamentar um TCC?", opcoes: ["Vídeo sem autoria", "Artigo revisado por pares num periódico científico", "Postagem em rede social", "Resumo sem referência"], correta: 1, explicacao: "A revisão por pares filtra erros e falta de rigor." },
      { t: 3, id: "g-met-q10", tipo: "ordenar", pergunta: "Ordene os elementos textuais do trabalho acadêmico:", itens: ["Introdução", "Referencial teórico", "Metodologia", "Resultados e discussão", "Conclusão"], explicacao: "Estrutura clássica." },
      { t: 3, id: "g-met-q11", tipo: "multipla", pergunta: "Qual é um objetivo específico bem escrito?", opcoes: ["Estudar a empresa", "Mapear o processo de setup atual e medir seu tempo", "Melhorar tudo", "Fazer um trabalho bom"], correta: 1, explicacao: "Verbo no infinitivo, ação clara e mensurável." },
      { t: 3, id: "g-met-q12", tipo: "vf", pergunta: "O resumo é um elemento pós-textual.", correta: false, explicacao: "É pré-textual; referências, apêndices e anexos são pós-textuais." }
    ]
  },

  {
    id: "g-inteco", nome: "Introdução à Economia", periodo: 2, area: "gestao", icone: "💹",
    intro: "Economia estuda como pessoas, empresas e países decidem usar recursos escassos. O engenheiro de produção usa **oferta e demanda** para entender preços, **elasticidade** para prever o efeito de promoções, **custos de produção** para decidir volumes e acompanha **juros, inflação e câmbio**, que afetam investimentos e compras.",
    topicos: [
      { t: "Oferta, demanda e equilíbrio", icone: "⚖️",
        pontos: ["**Demanda:** quantidade que os consumidores querem comprar a cada preço; cai quando o preço sobe (lei da demanda).", "**Oferta:** quantidade que os produtores querem vender a cada preço; sobe com o preço.", "**Equilíbrio:** preço em que oferta = demanda.", "Deslocamentos: renda, gosto e preço de substitutos mudam a demanda; custo e tecnologia mudam a oferta.", "Preço acima do equilíbrio gera excedente (estoque); abaixo, escassez."],
        formulas: [["Qd = a − b·P", "demanda linear"], ["Qo = c + d·P", "oferta linear"], ["Qd = Qo ⇒ P* = (a − c) ÷ (b + d)", "preço de equilíbrio"]],
        producao: "Entender a demanda ajuda a planejar produção e estoque; um aumento no custo do cacau desloca a oferta de chocolate e tende a elevar o preço.",
        exemplo: "Qd = 1.000 − 20P e Qo = 200 + 20P ⇒ P* = 800 ÷ 40 = **R$ 20** e Q* = **600**." },
      { t: "Elasticidade", icone: "🪀",
        pontos: ["**Elasticidade-preço da demanda:** variação % da quantidade ÷ variação % do preço.", "|E| > 1: **elástica** (sensível ao preço); |E| < 1: **inelástica**.", "Produtos com muitos substitutos tendem a ser elásticos; essenciais, inelásticos.", "Com demanda elástica, baixar o preço **aumenta** a receita; com inelástica, **diminui**.", "Elasticidade-renda e cruzada (substitutos > 0, complementares < 0)."],
        formulas: [["E = (ΔQ/Q) ÷ (ΔP/P)", "elasticidade-preço da demanda"], ["Receita = P × Q", "o efeito de mudar o preço depende de E"]],
        producao: "Prever o efeito de uma promoção sobre o volume e planejar a produção e os estoques para o pico que ela vai gerar.",
        exemplo: "Preço cai 10% e as vendas sobem 25%: E = 25 ÷ (−10) = **−2,5** (elástica): a promoção aumenta a receita, e a fábrica precisa produzir mais." },
      { t: "Custos de produção e mercados", icone: "🏭",
        pontos: ["**Custo fixo** (não varia com a quantidade no curto prazo) e **variável**.", "**Custo marginal:** custo da unidade adicional; **custo médio:** custo total ÷ quantidade.", "**Rendimentos decrescentes:** com um fator fixo, cada unidade extra do fator variável acrescenta cada vez menos produção.", "**Economias de escala:** custo médio cai com o volume no longo prazo.", "Estruturas de mercado: concorrência perfeita, monopólio, oligopólio, concorrência monopolística."],
        formulas: [["CT = CF + CV", "custo total"], ["CMe = CT ÷ Q", "custo médio"], ["CMg = ΔCT ÷ ΔQ", "custo marginal"]],
        producao: "Decidir se aceita um pedido extra (comparar preço com o custo marginal), escolher a escala da fábrica e entender o poder de negociação de fornecedores concentrados (oligopólio).",
        exemplo: "Produzir 1.000 custa R$ 10.000; 1.100 custa R$ 10.600. CMg ≈ 600 ÷ 100 = **R$ 6 por unidade** extra." },
      { t: "Macroeconomia para o engenheiro", icone: "🌐",
        pontos: ["**PIB:** valor dos bens e serviços finais produzidos no país num período.", "**Inflação:** aumento generalizado dos preços; no Brasil, medida oficial pelo IPCA (IBGE).", "**Taxa Selic:** taxa básica de juros definida pelo Copom/Banco Central; influencia o custo do crédito e dos investimentos.", "**Câmbio:** preço da moeda estrangeira; afeta insumos importados e exportações.", "Juros altos encarecem estoques e investimentos (custo de capital)."],
        formulas: [["Crescimento real ≈ crescimento nominal − inflação", "aproximação para taxas pequenas"], ["(1 + nominal) = (1 + real) × (1 + inflação)", "relação exata (Fisher)"]],
        producao: "Câmbio alto encarece o cacau importado; juros altos aumentam o custo de manter estoque (Módulo 7) e mudam a viabilidade de investimentos (Engenharia Econômica).",
        exemplo: "Reajuste de 10% com inflação de 4%: ganho real = 1,10 ÷ 1,04 − 1 ≈ **5,8%**." }
    ],
    glossario: [["Demanda", "Quantidade desejada pelos compradores a cada preço."], ["Oferta", "Quantidade que os vendedores desejam vender a cada preço."], ["Equilíbrio de mercado", "Preço e quantidade em que oferta = demanda."], ["Elasticidade-preço", "Sensibilidade da quantidade demandada ao preço."], ["Custo marginal", "Custo de produzir uma unidade adicional."], ["Rendimentos decrescentes", "Queda do acréscimo de produção por unidade extra de um fator variável."], ["Economia de escala", "Queda do custo médio com o aumento do volume."], ["Oligopólio", "Mercado dominado por poucas empresas."], ["PIB", "Valor dos bens e serviços finais produzidos."], ["IPCA", "Índice oficial de inflação no Brasil (IBGE)."], ["Selic", "Taxa básica de juros da economia brasileira."]],
    questoes: [
      { t: 0, id: "g-eco-t01", tipo: "calculo", variaveis: { a: { min: 800, max: 2000, passo: 100 }, b: { min: 10, max: 40, passo: 5 }, c: { min: 0, max: 400, passo: 50 }, d: { min: 10, max: 40, passo: 5 } }, condicao: "a > c",
        resposta: "(a-c)/(b+d)", tolerancia: 0.01, unidade: "R$", pergunta: "Demanda Qd = {a} − {b}P; oferta Qo = {c} + {d}P. Qual o preço de equilíbrio? (2 casas)", resolucao: "{a} − {b}P = {c} + {d}P ⇒ P* = ({a} − {c}) ÷ ({b} + {d}) = {=(a-c)/(b+d):2}", explicacao: "No equilíbrio, oferta = demanda." },
      { t: 0, id: "g-eco-q01", tipo: "multipla", pergunta: "Se o preço fica ACIMA do equilíbrio, o que tende a acontecer?", opcoes: ["Escassez", "Excedente (sobra estoque)", "Nada", "A demanda aumenta"], correta: 1, explicacao: "Oferta maior que demanda." },
      { t: 0, id: "g-eco-q02", tipo: "vf", pergunta: "Um aumento no preço do cacau tende a deslocar a curva de oferta de chocolate para a esquerda (menos oferta a cada preço).", correta: true, explicacao: "Custo maior reduz a oferta." },
      { t: 1, id: "g-eco-t02", tipo: "calculo", variaveis: { dp: { valores: [-5, -10, -15, -20] }, dq: { valores: [4, 8, 12, 20, 30] } }, resposta: "dq/dp", tolerancia: 0.01, unidade: "",
        pergunta: "O preço variou {dp}% e a quantidade vendida variou +{dq}%. Qual a elasticidade-preço da demanda? (2 casas)", resolucao: "E = {dq} ÷ ({dp}) = {=dq/dp:2}", explicacao: "|E| > 1: elástica; |E| < 1: inelástica." },
      { t: 1, id: "g-eco-q03", tipo: "multipla", pergunta: "Com demanda INELÁSTICA, uma redução de preço tende a:", opcoes: ["Aumentar a receita", "Reduzir a receita", "Não mudar nada", "Zerar as vendas"], correta: 1, explicacao: "A quantidade sobe proporcionalmente menos que a queda do preço." },
      { t: 1, id: "g-eco-q04", tipo: "vf", pergunta: "Produtos com muitos substitutos tendem a ter demanda mais elástica.", correta: true, explicacao: "O consumidor troca facilmente de marca." },
      { t: 2, id: "g-eco-t03", tipo: "calculo", variaveis: { q1: { valores: [1000, 2000, 5000] }, dq: { valores: [100, 200, 500] }, c1: { min: 8000, max: 40000, passo: 1000 }, cm: { min: 3, max: 12 } }, calc: { c2: "c1+cm*dq" },
        resposta: "(c2-c1)/dq", tolerancia: 0.01, unidade: "R$/unid.", pergunta: "Produzir {q1} unidades custa R$ {c1}; produzir {=q1+dq} custa R$ {c2}. Qual o custo marginal por unidade?", resolucao: "CMg = ({c2} − {c1}) ÷ {dq} = {=(c2-c1)/dq:2}", explicacao: "Compare com o preço de um pedido extra." },
      { t: 2, id: "g-eco-q05", tipo: "multipla", pergunta: "Mantendo o número de máquinas fixo e contratando cada vez mais operadores, a produção extra por operador tende a cair. Isso é:", opcoes: ["Economia de escala", "Lei dos rendimentos decrescentes", "Elasticidade", "Inflação"], correta: 1, explicacao: "Um fator fixo limita o ganho do fator variável." },
      { t: 2, id: "g-eco-q06", tipo: "ligar", pergunta: "Ligue a estrutura de mercado ao exemplo:", pares: [["Monopólio", "Única distribuidora de água da cidade"], ["Oligopólio", "Poucos fabricantes de aço"], ["Concorrência monopolística", "Muitas marcas de chocolate diferenciadas"]], explicacao: "O número de empresas e a diferenciação mudam o poder de preço." },
      { t: 3, id: "g-eco-t04", tipo: "calculo", variaveis: { nom: { min: 5, max: 20 }, inf: { min: 2, max: 10 } }, resposta: "((1+nom/100)/(1+inf/100)-1)*100", tolerancia: 0.05, unidade: "%",
        pergunta: "Um reajuste nominal de {nom}% com inflação de {inf}% corresponde a qual ganho real (%)? (1 casa)", resolucao: "(1 + {=nom/100}) ÷ (1 + {=inf/100}) − 1 = {=((1+nom/100)/(1+inf/100)-1)*100:1}%", explicacao: "Relação de Fisher." },
      { t: 3, id: "g-eco-q07", tipo: "multipla", pergunta: "Quem define a meta da taxa Selic?", opcoes: ["IBGE", "Copom (Banco Central)", "Ministério da Economia sozinho", "Bolsa de valores"], correta: 1, explicacao: "Comitê de Política Monetária." },
      { t: 3, id: "g-eco-q08", tipo: "vf", pergunta: "Juros mais altos tornam mais caro manter estoques, pois aumentam o custo do capital parado.", correta: true, explicacao: "O custo de manter estoque inclui o custo de oportunidade do capital." }
    ]
  }
);
