/* =====================================================================
   GRADE CURRICULAR — 3º PERÍODO (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-edo", nome: "Equações Diferenciais Ordinárias", periodo: 3, area: "exatas", icone: "〰️", prereq: ["g-calc2", "g-alg2"],
    intro: "Uma **equação diferencial** relaciona uma grandeza com a sua taxa de variação. Na produção, ela modela o **resfriamento** de produtos num túnel, a **confiabilidade** de equipamentos, a concentração num **tanque de mistura**, a adoção de um **produto novo** e a **vibração** de máquinas.",
    topicos: [
      { t: "EDOs de 1ª ordem separáveis", icone: "📉",
        pontos: ["**EDO:** equação com uma função desconhecida y(t) e suas derivadas; a **ordem** é a da maior derivada.", "**Separável:** dy/dt = g(t)·h(y) ⇒ ∫ dy/h(y) = ∫ g(t) dt.", "**Crescimento/decaimento exponencial:** dy/dt = k·y ⇒ y = y₀·e^(kt).", "**Condição inicial** y(0) = y₀ fixa a constante de integração (problema de valor inicial).", "**Confiabilidade** com taxa de falhas constante λ: dR/dt = −λR ⇒ R(t) = e^(−λt)."],
        formulas: [["dy/dt = k·y ⇒ y(t) = y₀·e^(kt)", "crescimento (k > 0) ou decaimento (k < 0)"], ["R(t) = e^(−λt)", "probabilidade de o equipamento funcionar até t; λ = taxa de falhas"], ["MTTF = 1 ÷ λ", "tempo médio até a falha (λ constante)"]],
        producao: "A confiabilidade exponencial é usada em manutenção (Gestão da Manutenção, Confiabilidade) para prever a chance de uma máquina passar um turno sem falhar e dimensionar peças de reposição.",
        exemplo: "λ = 0,002 falha/h. Chance de operar 100 h sem falhar: R = e^(−0,2) ≈ **81,9%**. MTTF = 1 ÷ 0,002 = **500 h**." },
      { t: "EDOs lineares de 1ª ordem e balanços", icone: "🧊",
        pontos: ["Forma: dy/dt + p(t)·y = q(t); resolve-se com **fator integrante** μ = e^(∫p dt).", "**Lei do resfriamento de Newton:** dT/dt = −k(T − Tₐ): a temperatura se aproxima exponencialmente da do ambiente.", "**Tanque de mistura:** d(quantidade)/dt = taxa de entrada − taxa de saída (balanço de massa).", "A **constante de tempo** τ = 1/k indica a rapidez: após τ, falta 37% da diferença inicial; após 3τ, cerca de 5%."],
        formulas: [["T(t) = Tₐ + (T₀ − Tₐ)·e^(−kt)", "resfriamento de Newton"], ["dQ/dt = entrada − saída", "balanço de massa num tanque"], ["t = (1/k)·ln[(T₀ − Tₐ) ÷ (T − Tₐ)]", "tempo para atingir a temperatura T"]],
        producao: "Dimensionar o **túnel de resfriamento** do chocolate (tempo de permanência = comprimento ÷ velocidade da esteira), tanques de diluição, fornos e câmaras frias.",
        exemplo: "Bombom sai a 45 °C num túnel a 15 °C, k = 0,1/min. Após 10 min: T = 15 + 30·e^(−1) ≈ **26 °C**. Para chegar a 20 °C: t = 10·ln(30/5) ≈ **17,9 min**." },
      { t: "Modelo logístico e aplicações", icone: "🚀",
        pontos: ["**Logístico:** dP/dt = r·P·(1 − P/K): cresce quase exponencialmente no início e satura em K (capacidade/mercado).", "Solução: P(t) = K ÷ (1 + A·e^(−rt)), com A = (K − P₀)/P₀.", "O crescimento é mais rápido quando P = K/2 (ponto de inflexão).", "Usado para **adoção de produtos novos**, difusão de tecnologias e curvas S de projetos."],
        formulas: [["dP/dt = r·P·(1 − P/K)", "crescimento logístico; K = saturação"], ["P(t) = K ÷ (1 + A·e^(−rt))", "curva S"]],
        producao: "Prever a demanda de um lançamento (a produção precisa crescer junto com a adoção, sem superproduzir quando o mercado saturar) e planejar a curva de subida de uma linha nova.",
        exemplo: "Mercado potencial K = 100 mil clientes, P₀ = 1 mil, r = 0,5/mês. O pico de vendas mensais ocorre quando P = 50 mil (metade do mercado)." },
      { t: "EDOs de 2ª ordem e vibrações", icone: "📳",
        pontos: ["**Linear com coeficientes constantes:** a·y'' + b·y' + c·y = f(t); resolve-se pela equação característica a·r² + b·r + c = 0.", "**Massa-mola-amortecedor:** m·x'' + c·x' + k·x = F(t).", "**Frequência natural:** ωₙ = √(k/m); se a força externa vibrar perto dela, ocorre **ressonância** (amplitudes grandes).", "Amortecimento: subamortecido (oscila), crítico, superamortecido.", "A **transformada de Laplace** transforma EDOs em equações algébricas (usada em controle de processos)."],
        formulas: [["m·x'' + c·x' + k·x = F(t)", "sistema massa-mola-amortecedor"], ["ωₙ = √(k ÷ m); fₙ = ωₙ ÷ 2π", "frequência natural (rad/s e Hz)"], ["a·r² + b·r + c = 0", "equação característica"]],
        producao: "Evitar que motores e bombas operem perto da frequência natural da base (ressonância quebra estruturas), dimensionar **amortecedores** e entender a **análise de vibração** usada em manutenção preditiva.",
        exemplo: "Máquina de 200 kg sobre coxins com k = 80.000 N/m: ωₙ = √400 = 20 rad/s ⇒ fₙ ≈ **3,2 Hz**. Um motor girando a 190 rpm (≈ 3,2 Hz) entraria em ressonância." }
    ],
    glossario: [["EDO", "Equação com uma função de uma variável e suas derivadas."], ["Ordem", "Maior derivada presente na equação."], ["Problema de valor inicial", "EDO com condição inicial dada."], ["Separável", "EDO que pode ser escrita com y de um lado e t do outro."], ["Fator integrante", "Função que torna integrável uma EDO linear de 1ª ordem."], ["Resfriamento de Newton", "Taxa de variação da temperatura proporcional à diferença para o ambiente."], ["Constante de tempo", "τ = 1/k; tempo característico da resposta exponencial."], ["Modelo logístico", "Crescimento com saturação (curva S)."], ["Frequência natural", "Frequência em que o sistema oscila livremente."], ["Ressonância", "Aumento da amplitude quando a excitação tem frequência próxima da natural."], ["Confiabilidade", "Probabilidade de funcionar sem falhar até um tempo t."]],
    questoes: [
      { t: 0, id: "g-edo-t01", tipo: "calculo", variaveis: { lam: { valores: [0.0005, 0.001, 0.002, 0.004, 0.005] }, tt: { valores: [50, 100, 200, 300, 500] } }, resposta: "exp(-lam*tt)*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Taxa de falhas constante λ = {lam} falha/h. Qual a probabilidade (%) de a máquina operar {tt} h sem falhar? (1 casa)", resolucao: "R = e^(−λt) = e^(−{=lam*tt}) = {=exp(-lam*tt)*100:1}%", explicacao: "Vem da EDO dR/dt = −λR." },
      { t: 0, id: "g-edo-q01", tipo: "multipla", pergunta: "Qual a solução de dy/dt = 0,05·y com y(0) = 200?", opcoes: ["y = 200 + 0,05t", "y = 200·e^(0,05t)", "y = 0,05·e^(200t)", "y = 200·e^(−0,05t)"], correta: 1, explicacao: "Crescimento exponencial." },
      { t: 0, id: "g-edo-q02", tipo: "vf", pergunta: "Com taxa de falhas constante λ, o tempo médio até a falha é 1/λ.", correta: true, explicacao: "Distribuição exponencial." },
      { t: 1, id: "g-edo-t02", tipo: "calculo", variaveis: { ta: { valores: [5, 10, 15, 18] }, t0: { valores: [40, 45, 50, 60] }, k: { valores: [0.05, 0.08, 0.1, 0.15, 0.2] }, tt: { min: 5, max: 30, passo: 5 } }, resposta: "ta+(t0-ta)*exp(-k*tt)", tolerancia: 0.1, unidade: "°C",
        pergunta: "Um produto sai do forno a {t0} °C e entra num túnel a {ta} °C (k = {k}/min). Qual a temperatura após {tt} min? (1 casa)", resolucao: "T = {ta} + ({t0} − {ta})·e^(−{k}×{tt}) = {ta} + {=t0-ta} × {=exp(-k*tt):4} = {=ta+(t0-ta)*exp(-k*tt):1} °C", explicacao: "Resfriamento de Newton." },
      { t: 1, id: "g-edo-q03", tipo: "multipla", pergunta: "No tanque de mistura, o balanço dQ/dt = entrada − saída expressa:", opcoes: ["Conservação da massa", "Lei de Ohm", "Segunda lei de Newton", "Lei de Hooke"], correta: 0, explicacao: "O que acumula = o que entra − o que sai." },
      { t: 1, id: "g-edo-q04", tipo: "vf", pergunta: "Depois de 3 constantes de tempo, a diferença de temperatura inicial caiu para cerca de 5%.", correta: true, explicacao: "e^(−3) ≈ 0,05." },
      { t: 2, id: "g-edo-q05", tipo: "multipla", pergunta: "No modelo logístico, em que ponto o crescimento é mais rápido?", opcoes: ["No início", "Quando P = K/2", "Quando P = K", "Sempre igual"], correta: 1, explicacao: "Ponto de inflexão da curva S." },
      { t: 2, id: "g-edo-q06", tipo: "vf", pergunta: "O modelo logístico prevê crescimento ilimitado da demanda.", correta: false, explicacao: "Satura na capacidade K." },
      { t: 2, id: "g-edo-q07", tipo: "caso", contexto: "Um produto novo está com vendas crescendo rápido. O gerente quer triplicar a capacidade porque “as vendas vão continuar dobrando”.", pergunta: "Qual o alerta baseado no modelo logístico?", opcoes: ["Nenhum: o crescimento exponencial continua", "A adoção tende a saturar (curva S); estimar o mercado potencial antes de investir para não criar capacidade ociosa", "Reduzir a produção", "Parar de vender"], correta: 1, explicacao: "Crescimento inicial rápido não significa crescimento eterno." },
      { t: 3, id: "g-edo-t03", tipo: "calculo", variaveis: { m: { valores: [50, 100, 200, 400, 500] }, k: { valores: [20000, 50000, 80000, 100000, 200000] } }, resposta: "sqrt(k/m)/(2*PI)", tolerancia: 0.01, unidade: "Hz",
        pergunta: "Máquina de {m} kg sobre apoios com rigidez k = {k} N/m. Qual a frequência natural fₙ (Hz)? (2 casas)", resolucao: "ωₙ = √(k/m) = √({=k/m}) = {=sqrt(k/m):2} rad/s\nfₙ = ωₙ ÷ 2π = {=sqrt(k/m)/(2*PI):2} Hz", explicacao: "Evite operar perto dessa frequência (ressonância)." },
      { t: 3, id: "g-edo-q08", tipo: "multipla", pergunta: "O que acontece quando uma máquina vibra numa frequência próxima da frequência natural da sua base?", opcoes: ["A vibração some", "Ressonância: a amplitude cresce muito, com risco de dano", "A máquina desliga", "A frequência natural muda"], correta: 1, explicacao: "Por isso se usam amortecedores e se evitam essas rotações." },
      { t: 3, id: "g-edo-q09", tipo: "ligar", pergunta: "Ligue o termo da equação m·x'' + c·x' + k·x = F(t) ao significado:", pares: [["m·x''", "Inércia (massa × aceleração)"], ["c·x'", "Amortecimento"], ["k·x", "Força da mola (rigidez)"], ["F(t)", "Força externa (excitação)"]], explicacao: "Modelo clássico de vibrações." }
    ]
  },

  {
    id: "g-calcvet", nome: "Cálculo Vetorial", periodo: 3, area: "exatas", icone: "🧲", prereq: ["g-calc2"],
    intro: "Estende o cálculo a **campos vetoriais**: grandezas com direção em cada ponto, como velocidade de um fluido, forças e fluxo de calor. Na produção, aparece em **escoamento** (vazão em tubulações, ventilação), **trabalho** de forças ao longo de trajetos (robôs, AGVs) e **transferência de calor** — base de Fenômenos de Transporte.",
    topicos: [
      { t: "Curvas e movimento no espaço", icone: "🤖",
        pontos: ["**Curva parametrizada:** r(t) = (x(t), y(t), z(t)).", "**Velocidade** r'(t) e **aceleração** r''(t) são vetores.", "**Comprimento de arco:** L = ∫ |r'(t)| dt.", "**Vetor tangente unitário** e curvatura descrevem como a trajetória dobra."],
        formulas: [["v(t) = r'(t)", "velocidade vetorial"], ["L = ∫ₐᵇ |r'(t)| dt", "comprimento da trajetória"], ["|r'(t)| = √(x'² + y'² + z'²)", "rapidez (módulo da velocidade)"]],
        producao: "Programar trajetórias de robôs e AGVs, calcular a distância percorrida por veículos internos e o tempo de ciclo de movimentação.",
        exemplo: "AGV com r(t) = (3t, 4t) m, 0 ≤ t ≤ 2 s: |r'| = √(9 + 16) = 5 m/s; L = **10 m**." },
      { t: "Campos vetoriais: gradiente, divergente e rotacional", icone: "🌬️",
        pontos: ["**Campo escalar:** um número em cada ponto (temperatura). **Campo vetorial:** um vetor em cada ponto (velocidade do ar).", "**Gradiente** ∇f: direção de maior aumento do campo escalar; o calor flui no sentido de −∇T.", "**Divergente** ∇·F: “quanto sai” de um ponto (fonte > 0, sumidouro < 0).", "**Rotacional** ∇×F: tendência de girar (redemoinhos).", "Campo **conservativo:** F = ∇φ; o trabalho só depende dos pontos inicial e final."],
        formulas: [["∇·F = ∂P/∂x + ∂Q/∂y + ∂R/∂z", "divergente de F = (P, Q, R)"], ["q = −k·∇T", "lei de Fourier: fluxo de calor contra o gradiente de temperatura"], ["∇×F = 0 ⇔ F conservativo (em regiões simples)", "teste de campo conservativo"]],
        producao: "Projetar ventilação e exaustão (campos de velocidade do ar), entender a distribuição de temperatura em fornos e câmaras frias e onde há pontos quentes.",
        exemplo: "F = (x², y): ∇·F = 2x + 1. No ponto (1, 0), o divergente vale 3: sai mais do que entra (fonte)." },
      { t: "Integrais de linha e trabalho", icone: "🛤️",
        pontos: ["**Integral de linha** ∫_C F·dr: soma a componente de F ao longo da curva C.", "Se F é força, a integral de linha é o **trabalho** realizado ao longo do trajeto.", "Para F constante e trajeto reto: W = F·d (produto escalar).", "Em campo **conservativo**, o trabalho num caminho fechado é zero."],
        formulas: [["W = ∫_C F · dr", "trabalho ao longo do trajeto"], ["W = F · d (F constante, trajeto reto)", "produto escalar força × deslocamento"], ["∫_C ∇φ · dr = φ(B) − φ(A)", "teorema fundamental para integrais de linha"]],
        producao: "Estimar a energia gasta para movimentar cargas ao longo de rotas com forças variáveis (rampas, atrito diferente) e comparar layouts pela energia de transporte.",
        exemplo: "F = (2, 3) N, deslocamento de (0, 0) a (4, 1) m: W = 2·4 + 3·1 = **11 J**." },
      { t: "Fluxo e teoremas integrais", icone: "🚰",
        pontos: ["**Fluxo** de F através de uma superfície: ∬ F·n dS (ex.: vazão de fluido atravessando uma seção).", "**Teorema de Green** (plano): relaciona integral de linha na borda com integral dupla na região.", "**Teorema da divergência (Gauss):** fluxo total que sai de uma superfície fechada = integral do divergente no volume.", "**Teorema de Stokes:** circulação na borda = fluxo do rotacional pela superfície.", "Esses teoremas fundamentam as equações de conservação de massa, energia e quantidade de movimento."],
        formulas: [["Φ = ∬_S F · n dS", "fluxo através da superfície S"], ["∯ F · n dS = ∭ ∇·F dV", "teorema da divergência"], ["Q = v · A", "vazão com velocidade uniforme v perpendicular à área A"]],
        producao: "Vazão em tubulações e dutos, balanço de massa em volumes de controle (Fenômenos de Transporte) e dimensionamento de exaustores pela vazão de ar necessária.",
        exemplo: "Ar a 5 m/s atravessando um duto de 0,4 m²: Q = 5 × 0,4 = **2 m³/s** = 7.200 m³/h." }
    ],
    glossario: [["Curva parametrizada", "Curva descrita por r(t)."], ["Comprimento de arco", "Distância percorrida ao longo da curva."], ["Campo vetorial", "Associação de um vetor a cada ponto do espaço."], ["Gradiente", "Vetor que aponta para o maior aumento do campo escalar."], ["Divergente", "Medida de fonte ou sumidouro de um campo."], ["Rotacional", "Medida da tendência de rotação de um campo."], ["Campo conservativo", "Campo gradiente; trabalho independe do caminho."], ["Integral de linha", "Integral ao longo de uma curva."], ["Fluxo", "Quanto de um campo atravessa uma superfície."], ["Teorema da divergência", "Fluxo pela superfície fechada = integral do divergente no volume."]],
    questoes: [
      { t: 0, id: "g-cvet-t01", tipo: "calculo", variaveis: { a: { valores: [3, 5, 6, 8] }, b: { valores: [4, 12, 8, 6] }, tt: { min: 1, max: 6 } }, resposta: "sqrt(a*a+b*b)*tt", tolerancia: 0.01, unidade: "m",
        pergunta: "Um AGV segue r(t) = ({a}t, {b}t) m. Qual a distância percorrida de t = 0 a t = {tt} s? (2 casas)", resolucao: "|r'| = √({a}² + {b}²) = {=sqrt(a*a+b*b):2} m/s\nL = {=sqrt(a*a+b*b):2} × {tt} = {=sqrt(a*a+b*b)*tt:2} m", explicacao: "Comprimento de arco com rapidez constante." },
      { t: 0, id: "g-cvet-q01", tipo: "vf", pergunta: "A derivada do vetor posição r(t) é o vetor velocidade.", correta: true, explicacao: "E a segunda derivada é a aceleração." },
      { t: 0, id: "g-cvet-q02", tipo: "multipla", pergunta: "Como se calcula o comprimento de uma trajetória r(t) de t = a até t = b?", opcoes: ["|r(b) − r(a)|", "∫ₐᵇ |r'(t)| dt", "r'(b) − r'(a)", "∫ₐᵇ r(t) dt"], correta: 1, explicacao: "|r(b) − r(a)| é só a distância em linha reta." },
      { t: 1, id: "g-cvet-q03", tipo: "multipla", pergunta: "Qual o divergente de F = (x², y)?", opcoes: ["2x + 1", "x² + y", "2x", "0"], correta: 0, explicacao: "∂(x²)/∂x + ∂y/∂y = 2x + 1." },
      { t: 1, id: "g-cvet-q04", tipo: "vf", pergunta: "Pela lei de Fourier, o calor flui no sentido do gradiente de temperatura (do frio para o quente).", correta: false, explicacao: "Flui contra o gradiente (−∇T): do quente para o frio." },
      { t: 1, id: "g-cvet-q05", tipo: "ligar", pergunta: "Ligue o operador ao que ele mede:", pares: [["Gradiente", "Direção de maior aumento"], ["Divergente", "Fonte ou sumidouro"], ["Rotacional", "Tendência de giro"]], explicacao: "Os três operadores do cálculo vetorial." },
      { t: 2, id: "g-cvet-t02", tipo: "calculo", variaveis: { fx: { min: 1, max: 10 }, fy: { min: 1, max: 10 }, dx: { min: 1, max: 20 }, dy: { min: 0, max: 10 } }, resposta: "fx*dx+fy*dy", tolerancia: 0, unidade: "J",
        pergunta: "Força constante F = ({fx}, {fy}) N; deslocamento reto de (0, 0) a ({dx}, {dy}) m. Qual o trabalho (J)?", resolucao: "W = F·d = {fx}×{dx} + {fy}×{dy} = {=fx*dx+fy*dy} J", explicacao: "Produto escalar." },
      { t: 2, id: "g-cvet-q06", tipo: "vf", pergunta: "Num campo conservativo, o trabalho ao longo de um caminho fechado é zero.", correta: true, explicacao: "Só depende dos pontos inicial e final, que coincidem." },
      { t: 2, id: "g-cvet-q07", tipo: "multipla", pergunta: "Se F é uma força, a integral de linha ∫_C F·dr representa:", opcoes: ["A massa", "O trabalho ao longo do caminho", "A área", "A temperatura"], correta: 1, explicacao: "Soma de F·dr ao longo da curva." },
      { t: 3, id: "g-cvet-t03", tipo: "calculo", variaveis: { v: { valores: [2, 3, 4, 5, 8, 10] }, a: { valores: [0.1, 0.2, 0.25, 0.4, 0.5] } }, resposta: "v*a*3600", tolerancia: 1, unidade: "m³/h",
        pergunta: "Ar a {v} m/s atravessa perpendicularmente um duto de {a} m². Qual a vazão (m³/h)?", resolucao: "Q = v·A = {v} × {a} = {=v*a} m³/s = {=v*a*3600} m³/h", explicacao: "Fluxo de um campo uniforme através de uma área." },
      { t: 3, id: "g-cvet-q08", tipo: "multipla", pergunta: "Qual teorema relaciona o fluxo total através de uma superfície fechada com o divergente no volume interno?", opcoes: ["Green", "Stokes", "Divergência (Gauss)", "Pitágoras"], correta: 2, explicacao: "Base das equações de conservação." },
      { t: 3, id: "g-cvet-q09", tipo: "vf", pergunta: "As equações de conservação de massa e energia usadas em Fenômenos de Transporte se apoiam nos teoremas integrais do cálculo vetorial.", correta: true, explicacao: "Volume de controle + teorema da divergência." }
    ]
  },

  {
    id: "g-calcnum", nome: "Cálculo Numérico", periodo: 3, area: "exatas", icone: "🔢", prereq: ["g-calc1", "g-alg1", "g-comp"],
    intro: "Muitos problemas não têm solução exata fácil; o **cálculo numérico** encontra aproximações confiáveis com o computador. Na produção: calcular a **TIR** de um investimento (raiz de uma equação), interpolar tabelas, integrar dados medidos (energia, vazão) e simular sistemas passo a passo.",
    topicos: [
      { t: "Erros e zeros de funções", icone: "🎯",
        pontos: ["**Erro absoluto** |x − x̄| e **relativo** |x − x̄| ÷ |x|.", "Erros de **arredondamento** (representação no computador) e de **truncamento** (método interrompido).", "**Bissecção:** se f(a) e f(b) têm sinais opostos, há raiz no intervalo; divide ao meio até a precisão desejada.", "**Newton-Raphson:** xₙ₊₁ = xₙ − f(xₙ) ÷ f'(xₙ); converge rápido perto da raiz, mas pode falhar se f' ≈ 0.", "A **TIR** é a raiz da equação VPL(i) = 0."],
        formulas: [["xₙ₊₁ = xₙ − f(xₙ) ÷ f'(xₙ)", "Newton-Raphson"], ["n ≥ log₂[(b − a) ÷ ε]", "iterações da bissecção para precisão ε"], ["Erro relativo = |x − x̄| ÷ |x|", "comparar a qualidade de aproximações"]],
        producao: "Planilhas calculam a TIR (função TIR/IRR) por métodos iterativos como esses; o mesmo vale para encontrar o ponto de equilíbrio em modelos não lineares.",
        exemplo: "Investe R$ 1.000 e recebe R$ 600 em 1 e 2 anos. VPL(i) = −1.000 + 600/(1+i) + 600/(1+i)² = 0 ⇒ TIR ≈ **13,07%**." },
      { t: "Sistemas lineares numéricos", icone: "🧮",
        pontos: ["**Métodos diretos:** eliminação de Gauss (com pivoteamento para reduzir erros) e decomposição LU.", "**Métodos iterativos:** Jacobi e **Gauss-Seidel**; bons para sistemas grandes e esparsos.", "Convergência garantida se a matriz for **diagonal dominante**.", "Número de condição alto indica sistema **mal condicionado**: pequenos erros nos dados geram grandes erros na solução."],
        formulas: [["xᵢ⁽ᵏ⁺¹⁾ = (bᵢ − Σⱼ≠ᵢ aᵢⱼxⱼ) ÷ aᵢᵢ", "iteração de Jacobi/Gauss-Seidel"], ["|aᵢᵢ| > Σⱼ≠ᵢ |aᵢⱼ|", "diagonal dominante (garante convergência)"]],
        producao: "Balanços de massa e energia de plantas com muitas correntes, modelos insumo-produto e redes de distribuição geram sistemas grandes resolvidos numericamente.",
        exemplo: "4x + y = 9 e x + 3y = 7 (diagonal dominante). Partindo de (0, 0), Gauss-Seidel: x = 2,25; y = 1,58; depois x = 1,85; y = 1,72… converge para (**1,82; 1,73**)." },
      { t: "Interpolação e ajuste de curvas", icone: "📈",
        pontos: ["**Interpolação:** encontrar valores entre pontos tabelados; o polinômio passa exatamente pelos pontos.", "**Interpolação linear:** y = y₀ + (y₁ − y₀)·(x − x₀) ÷ (x₁ − x₀).", "Polinômios de Lagrange e Newton para mais pontos; graus altos podem oscilar (fenômeno de Runge).", "**Ajuste (mínimos quadrados):** a curva não passa pelos pontos, mas minimiza o erro; melhor para dados com ruído.", "**Extrapolar** (fora do intervalo) é arriscado."],
        formulas: [["y = y₀ + (y₁ − y₀)·(x − x₀) ÷ (x₁ − x₀)", "interpolação linear"], ["min Σ (yᵢ − f(xᵢ))²", "critério de mínimos quadrados"]],
        producao: "Ler tabelas técnicas (vapor, fatores de tolerância, tabelas de juros), estimar valores entre medições e ajustar curvas de aprendizagem ou de consumo.",
        exemplo: "Tabela: a 20 °C a viscosidade é 40; a 30 °C é 30. A 26 °C: 40 + (30 − 40) × 6/10 = **34**." },
      { t: "Integração numérica e EDOs", icone: "∫",
        pontos: ["**Regra dos trapézios:** aproxima a área por trapézios: (h/2)·(y₀ + 2y₁ + … + 2yₙ₋₁ + yₙ).", "**Simpson 1/3:** usa parábolas (nº par de intervalos); mais precisa: (h/3)·(y₀ + 4y₁ + 2y₂ + … + 4yₙ₋₁ + yₙ).", "Úteis quando só existem **dados medidos** e não uma fórmula.", "**Método de Euler:** yₙ₊₁ = yₙ + h·f(tₙ, yₙ); simples, erro proporcional a h.", "**Runge-Kutta** (RK4) é mais preciso e muito usado em simulação."],
        formulas: [["∫ ≈ (h/2)·[y₀ + 2(y₁ + … + yₙ₋₁) + yₙ]", "regra dos trapézios"], ["yₙ₊₁ = yₙ + h·f(tₙ, yₙ)", "método de Euler"]],
        producao: "Calcular a energia consumida a partir de medições de potência a cada hora, o volume bombeado a partir de leituras de vazão e simular estoques e filas passo a passo.",
        exemplo: "Potência medida (kW) às 0, 1, 2, 3 e 4 h: 20, 26, 30, 28, 22. Energia ≈ (1/2)·[20 + 2(26 + 30 + 28) + 22] = **105 kWh**." }
    ],
    glossario: [["Erro de arredondamento", "Diferença devida à representação finita dos números."], ["Erro de truncamento", "Diferença por interromper um processo infinito."], ["Bissecção", "Método de raízes que divide o intervalo ao meio."], ["Newton-Raphson", "Método de raízes que usa a reta tangente."], ["TIR", "Taxa que zera o VPL; raiz de uma equação."], ["Gauss-Seidel", "Método iterativo para sistemas lineares."], ["Diagonal dominante", "Elemento da diagonal maior que a soma dos outros da linha."], ["Interpolação", "Estimativa de valores entre pontos conhecidos."], ["Regra dos trapézios", "Integração numérica por trapézios."], ["Método de Euler", "Solução numérica de EDO passo a passo."]],
    questoes: [
      { t: 0, id: "g-cnum-q01", tipo: "multipla", pergunta: "Qual a fórmula de iteração de Newton-Raphson?", opcoes: ["xₙ₊₁ = xₙ − f(xₙ)/f'(xₙ)", "xₙ₊₁ = (a + b)/2", "xₙ₊₁ = xₙ + h·f", "xₙ₊₁ = f(xₙ)"], correta: 0, explicacao: "Usa a tangente para estimar onde a função cruza o zero." },
      { t: 0, id: "g-cnum-t01", tipo: "calculo", variaveis: { l: { valores: [1, 2, 4, 5, 10] }, e: { valores: [0.01, 0.001, 0.0001] } }, resposta: "ceil(log(l/e)/log(2))", tolerancia: 0, unidade: "iterações",
        pergunta: "Intervalo inicial de comprimento {l} e precisão desejada ε = {e}. Quantas iterações da bissecção, no mínimo?", resolucao: "n ≥ log₂({l} ÷ {e}) = {=log(l/e)/log(2):2} → {=ceil(log(l/e)/log(2))}", explicacao: "Cada iteração divide o intervalo por 2." },
      { t: 0, id: "g-cnum-q02", tipo: "vf", pergunta: "A TIR de um investimento é a raiz da equação VPL(i) = 0, normalmente encontrada por método iterativo.", correta: true, explicacao: "Planilhas usam métodos numéricos para isso." },
      { t: 1, id: "g-cnum-q03", tipo: "multipla", pergunta: "Qual condição garante a convergência de Gauss-Seidel?", opcoes: ["Matriz simétrica qualquer", "Matriz diagonal dominante", "Determinante zero", "Matriz com zeros na diagonal"], correta: 1, explicacao: "|aᵢᵢ| maior que a soma dos outros na linha." },
      { t: 1, id: "g-cnum-q04", tipo: "vf", pergunta: "Um sistema mal condicionado é aquele em que pequenos erros nos dados podem causar grandes erros na solução.", correta: true, explicacao: "Número de condição alto." },
      { t: 1, id: "g-cnum-q05", tipo: "multipla", pergunta: "Para sistemas muito grandes e esparsos (muitos zeros), costuma-se preferir:", opcoes: ["Métodos iterativos", "Regra de Cramer", "Calcular a inversa à mão", "Nenhum método funciona"], correta: 0, explicacao: "Economizam memória e tempo." },
      { t: 2, id: "g-cnum-t02", tipo: "calculo", variaveis: { x0: { valores: [10, 20, 30] }, dxx: { valores: [10, 20] }, y0: { min: 30, max: 80, passo: 2 }, y1: { min: 10, max: 60, passo: 2 }, fr: { valores: [0.2, 0.25, 0.4, 0.5, 0.6, 0.75] } }, calc: { x1: "x0+dxx", x: "x0+fr*dxx" },
        resposta: "y0+(y1-y0)*(x-x0)/(x1-x0)", tolerancia: 0.01, unidade: "", pergunta: "Tabela: x = {x0} → y = {y0}; x = {x1} → y = {y1}. Interpolando linearmente, quanto vale y em x = {x}? (2 casas)",
        resolucao: "y = {y0} + ({y1} − {y0}) × ({x} − {x0}) ÷ ({x1} − {x0}) = {=y0+(y1-y0)*(x-x0)/(x1-x0):2}", explicacao: "Reta entre os dois pontos." },
      { t: 2, id: "g-cnum-q06", tipo: "vf", pergunta: "Para dados com muito ruído de medição, é melhor ajustar uma curva por mínimos quadrados do que forçar um polinômio a passar por todos os pontos.", correta: true, explicacao: "Polinômios de grau alto oscilam e seguem o ruído." },
      { t: 2, id: "g-cnum-q07", tipo: "multipla", pergunta: "Qual o principal risco de extrapolar (usar o modelo fora do intervalo dos dados)?", opcoes: ["Nenhum", "O comportamento real pode ser diferente fora da faixa observada", "O computador trava", "A interpolação fica exata"], correta: 1, explicacao: "O modelo só foi validado dentro da faixa." },
      { t: 3, id: "g-cnum-t03", tipo: "calculo", variaveis: { y: { lista: 5, min: 10, max: 40 } }, resposta: "0.5*(y[0]+2*(y[1]+y[2]+y[3])+y[4])", tolerancia: 0.01, unidade: "kWh",
        pergunta: "Potência medida (kW) a cada 1 h, de 0 a 4 h: {y}. Pela regra dos trapézios, qual a energia consumida (kWh)?", resolucao: "E ≈ (1/2) × [{=y[0]} + 2×({=y[1]} + {=y[2]} + {=y[3]}) + {=y[4]}] = {=0.5*(y[0]+2*(y[1]+y[2]+y[3])+y[4]):2} kWh", explicacao: "Integração numérica de dados medidos." },
      { t: 3, id: "g-cnum-q08", tipo: "calculo", pergunta: "dy/dt = 0,1·y, y(0) = 100, passo h = 1. Qual y(1) pelo método de Euler?", resposta: 110, tolerancia: 0, unidade: "", resolucao: "y₁ = 100 + 1 × 0,1 × 100 = 110 (valor exato: 100·e^0,1 ≈ 110,5)", explicacao: "Euler subestima um pouco o crescimento exponencial." },
      { t: 3, id: "g-cnum-q09", tipo: "multipla", pergunta: "Entre trapézios e Simpson 1/3, para a mesma quantidade de pontos (funções suaves), qual costuma ser mais precisa?", opcoes: ["Trapézios", "Simpson 1/3", "São sempre iguais", "Nenhuma funciona"], correta: 1, explicacao: "Simpson usa parábolas em vez de retas." }
    ]
  },

  {
    id: "g-mecger", nome: "Mecânica Geral", periodo: 3, area: "engenharia", icone: "🏗️", prereq: ["g-alg2", "g-mecbas"],
    intro: "Estuda **forças em equilíbrio** (estática). O engenheiro de produção usa esses conceitos para entender cargas em **porta-paletes**, **içamento** com cabos e cintas, **estabilidade de empilhadeiras** (centro de gravidade da carga) e reações em vigas e estruturas do layout.",
    topicos: [
      { t: "Forças, resultante e momento", icone: "➡️",
        pontos: ["Força é um **vetor**: decompõe-se em componentes Fₓ = F·cos θ e F_y = F·sen θ.", "**Resultante:** soma vetorial das forças.", "**Momento (torque)** de uma força em relação a um ponto: M = F·d (d = distância perpendicular, braço de alavanca).", "**Binário:** duas forças iguais, opostas e paralelas; produzem só rotação.", "Sinal: anti-horário positivo (convenção comum)."],
        formulas: [["Fₓ = F·cos θ; F_y = F·sen θ", "componentes da força"], ["M = F · d", "momento; d = braço (perpendicular)"], ["R = √(ΣFₓ² + ΣF_y²)", "módulo da resultante"]],
        producao: "Braço de alavanca explica por que ferramentas longas reduzem esforço e por que cargas longe do corpo sobrecarregam a coluna (ergonomia).",
        exemplo: "Chave de 0,3 m com 100 N: M = 100 × 0,3 = **30 N·m**. Com 0,5 m, bastam 60 N." },
      { t: "Equilíbrio de partícula e içamento", icone: "🪝",
        pontos: ["**Equilíbrio de partícula:** ΣFₓ = 0 e ΣF_y = 0.", "**Diagrama de corpo livre (DCL):** desenhe todas as forças sobre o corpo isolado.", "Em içamento com dois cabos simétricos: T = P ÷ (2·sen α), com α = ângulo do cabo com a **horizontal**.", "Quanto **menor** o ângulo com a horizontal, **maior** a tração nos cabos (por isso se evitam ângulos abertos).", "Todo acessório de içamento tem **carga máxima de trabalho** (CMT) informada pelo fabricante."],
        formulas: [["ΣFₓ = 0; ΣF_y = 0", "equilíbrio de partícula"], ["T = P ÷ (2·sen α)", "tração em cada perna de uma lingada simétrica"]],
        producao: "Segurança no içamento de moldes, máquinas e bobinas: escolher cintas e cabos adequados e respeitar ângulos mínimos (tema também de segurança do trabalho, NR-11/NR-12).",
        exemplo: "Carga de 1.000 kgf com duas pernas a 60° da horizontal: T = 1.000 ÷ (2 × 0,866) ≈ **577 kgf** cada. A 30°: T = 1.000 ÷ (2 × 0,5) = **1.000 kgf** cada!" },
      { t: "Equilíbrio de corpo rígido e reações de apoio", icone: "🌉",
        pontos: ["**Corpo rígido em equilíbrio:** ΣFₓ = 0, ΣF_y = 0 e **ΣM = 0**.", "**Apoios:** simples/rolete (1 reação), articulação (2 reações), engaste (2 reações + momento).", "**Viga bi-apoiada** com carga concentrada: tome momentos num apoio para achar a reação do outro.", "**Carga distribuída** q (N/m) equivale a uma força q·L no centro do trecho.", "**Treliças:** barras só com tração ou compressão; métodos dos nós e das seções."],
        formulas: [["ΣM_A = 0 ⇒ R_B = P·a ÷ L", "reação no apoio B (carga P a uma distância a de A, vão L)"], ["R_A = P − R_B", "equilíbrio vertical"], ["Carga distribuída: F = q·L no centro", "força equivalente"]],
        producao: "Verificar a carga em vigas de porta-paletes e mezaninos, reações em bases de máquinas e posicionar cargas em pontes rolantes.",
        exemplo: "Viga de 4 m com 1.000 N a 1 m do apoio A: R_B = 1.000 × 1 ÷ 4 = **250 N**; R_A = **750 N**." },
      { t: "Centro de gravidade e estabilidade", icone: "🎯",
        pontos: ["**Centro de gravidade (CG):** ponto de aplicação do peso total; x̄ = Σ(mᵢ·xᵢ) ÷ Σmᵢ.", "Um corpo apoiado **tomba** quando o CG sai da base de apoio.", "**Empilhadeira:** funciona como alavanca apoiada no eixo dianteiro; a capacidade nominal vale para um **centro de carga** definido (ex.: 500 mm).", "Carga com CG mais afastado reduz a capacidade real (momento maior).", "**Atrito** e ângulo de rampa também influenciam a estabilidade."],
        formulas: [["x̄ = Σ(mᵢ·xᵢ) ÷ Σmᵢ", "coordenada do centro de gravidade"], ["Capacidade real ≈ capacidade nominal × (c_nominal ÷ c_real)", "aproximação pelo equilíbrio de momentos no eixo dianteiro"]],
        producao: "Paletização estável (produtos mais pesados embaixo), limites de carga de empilhadeiras e porta-paletes, arrumação de cargas em caminhões.",
        exemplo: "Empilhadeira de 2.000 kg com centro de carga de 500 mm. Uma carga com CG a 800 mm: capacidade ≈ 2.000 × 500 ÷ 800 = **1.250 kg** (consulte sempre a placa do fabricante)." }
    ],
    glossario: [["Resultante", "Soma vetorial das forças."], ["Momento", "Tendência de giro: força × braço."], ["Binário", "Par de forças iguais e opostas que produz rotação pura."], ["Diagrama de corpo livre", "Desenho do corpo isolado com todas as forças."], ["Equilíbrio", "Resultante e momento resultante nulos."], ["Reação de apoio", "Força exercida pelo apoio sobre a estrutura."], ["Engaste", "Apoio que impede translação e rotação."], ["Treliça", "Estrutura de barras que trabalham a tração ou compressão."], ["Centro de gravidade", "Ponto de aplicação do peso total."], ["Centro de carga", "Distância de referência do CG da carga para a capacidade da empilhadeira."]],
    questoes: [
      { t: 0, id: "g-mger-t01", tipo: "calculo", variaveis: { f: { min: 50, max: 300, passo: 10 }, d: { valores: [0.2, 0.25, 0.3, 0.4, 0.5] } }, resposta: "f*d", tolerancia: 0.01, unidade: "N·m", pergunta: "Uma força de {f} N é aplicada perpendicularmente a {d} m do eixo. Qual o momento (N·m)?", resolucao: "M = {f} × {d} = {=f*d:2} N·m", explicacao: "Braço maior = mais momento com a mesma força." },
      { t: 0, id: "g-mger-q01", tipo: "multipla", pergunta: "Uma força de 100 N faz 30° com a horizontal. Qual sua componente vertical?", opcoes: ["86,6 N", "50 N", "100 N", "30 N"], correta: 1, explicacao: "F·sen 30° = 100 × 0,5 = 50 N." },
      { t: 0, id: "g-mger-q02", tipo: "vf", pergunta: "O braço de alavanca é a distância perpendicular entre a linha de ação da força e o ponto de referência.", correta: true, explicacao: "Por isso o ângulo importa." },
      { t: 1, id: "g-mger-t02", tipo: "calculo", variaveis: { p: { min: 500, max: 5000, passo: 100 }, al: { valores: [30, 45, 60, 75] } }, resposta: "p/(2*sin(al*PI/180))", tolerancia: 1, unidade: "kgf",
        pergunta: "Carga de {p} kgf içada por duas pernas simétricas, cada uma a {al}° da horizontal. Qual a tração em cada perna (kgf)? (inteiro)", resolucao: "T = P ÷ (2·sen {al}°) = {p} ÷ (2 × {=sin(al*PI/180):3}) ≈ {=p/(2*sin(al*PI/180)):0} kgf", explicacao: "Ângulos pequenos com a horizontal aumentam muito a tração." },
      { t: 1, id: "g-mger-q03", tipo: "vf", pergunta: "Numa lingada de duas pernas, quanto menor o ângulo entre o cabo e a horizontal, menor a tração no cabo.", correta: false, explicacao: "É o contrário: a tração aumenta." },
      { t: 1, id: "g-mger-q04", tipo: "multipla", pergunta: "Qual o primeiro passo para resolver um problema de equilíbrio?", opcoes: ["Calcular a resultante no chute", "Desenhar o diagrama de corpo livre", "Escolher o material", "Medir o tempo"], correta: 1, explicacao: "Isolar o corpo e desenhar todas as forças." },
      { t: 2, id: "g-mger-t03", tipo: "calculo", variaveis: { p: { min: 500, max: 5000, passo: 100 }, l: { valores: [2, 3, 4, 5, 6] }, fr: { valores: [0.25, 0.4, 0.5, 0.6, 0.75] } }, calc: { a: "fr*l" }, resposta: "p*a/l", tolerancia: 0.01, unidade: "N",
        pergunta: "Viga bi-apoiada de {l} m com carga de {p} N a {a} m do apoio A. Qual a reação no apoio B (N)?", resolucao: "ΣM_A = 0: R_B × {l} = {p} × {a} ⇒ R_B = {=p*a/l:2} N (R_A = {=p-p*a/l:2} N)", explicacao: "Momentos em relação ao apoio A." },
      { t: 2, id: "g-mger-q05", tipo: "ligar", pergunta: "Ligue o apoio às reações que ele oferece (plano):", pares: [["Rolete (apoio simples)", "1 força perpendicular"], ["Articulação (pino)", "2 forças"], ["Engaste", "2 forças e 1 momento"]], explicacao: "Quanto mais restrições, mais reações." },
      { t: 2, id: "g-mger-q06", tipo: "multipla", pergunta: "Uma carga distribuída de 500 N/m ao longo de 4 m equivale a:", opcoes: ["500 N no início", "2.000 N no meio do trecho", "125 N no fim", "2.000 N no início"], correta: 1, explicacao: "F = q·L aplicada no centro." },
      { t: 3, id: "g-mger-t04", tipo: "calculo", variaveis: { cap: { valores: [1500, 2000, 2500, 3000] }, cn: { valores: [500, 600] }, cr: { valores: [700, 800, 900, 1000] } }, resposta: "cap*cn/cr", tolerancia: 1, unidade: "kg",
        pergunta: "Empilhadeira de {cap} kg com centro de carga nominal de {cn} mm. A carga tem CG a {cr} mm. Estimativa da capacidade real (kg)? (inteiro)", resolucao: "≈ {cap} × {cn} ÷ {cr} = {=cap*cn/cr:0} kg", explicacao: "Aproximação por momentos; o valor oficial está na placa de capacidade." },
      { t: 3, id: "g-mger-q07", tipo: "vf", pergunta: "Um corpo tomba quando a vertical que passa pelo seu centro de gravidade sai da base de apoio.", correta: true, explicacao: "O peso passa a gerar momento de tombamento." },
      { t: 3, id: "g-mger-q08", tipo: "multipla", pergunta: "Numa paletização estável, onde ficam os produtos mais pesados?", opcoes: ["No topo", "Embaixo, baixando o centro de gravidade", "Num canto", "Tanto faz"], correta: 1, explicacao: "CG mais baixo = mais estabilidade." }
    ]
  },

  {
    id: "g-eletbas", nome: "Eletricidade Básica", periodo: 3, area: "exatas", icone: "💡", prereq: ["g-calc2", "g-mecbas"],
    intro: "A energia elétrica move a fábrica. O engenheiro de produção usa eletricidade para estimar o **consumo e o custo de energia**, entender **fator de potência** e multas na conta, dimensionar cargas e conversar com a manutenção elétrica com segurança (**NR-10**).",
    topicos: [
      { t: "Grandezas elétricas e Lei de Ohm", icone: "🔌",
        pontos: ["**Carga** (coulomb), **corrente** I (ampère) = fluxo de carga, **tensão** V (volt) = diferença de potencial.", "**Resistência** R (ohm) opõe-se à corrente; depende do material, do comprimento e da seção: R = ρ·L ÷ A.", "**Lei de Ohm:** V = R·I.", "**Potência:** P = V·I = R·I² = V²/R (watts).", "Condutores mais finos ou longos esquentam mais (efeito Joule)."],
        formulas: [["V = R · I", "Lei de Ohm"], ["P = V · I", "potência elétrica"], ["R = ρ · L ÷ A", "resistência de um condutor"]],
        producao: "Entender por que cabos subdimensionados aquecem (risco de incêndio), ler dados de placa de motores e estimar correntes de equipamentos.",
        exemplo: "Resistência de forno de 20 Ω em 220 V: I = 220 ÷ 20 = **11 A**; P = 220 × 11 = **2.420 W**." },
      { t: "Circuitos série e paralelo", icone: "🔗",
        pontos: ["**Série:** mesma corrente; R_eq = R₁ + R₂ + …; se um componente abre, tudo para.", "**Paralelo:** mesma tensão; 1/R_eq = 1/R₁ + 1/R₂ + …; cada ramo funciona de forma independente.", "Instalações prediais e industriais ligam cargas em **paralelo**.", "**Leis de Kirchhoff:** soma das correntes num nó = 0; soma das tensões numa malha = 0."],
        formulas: [["R_eq(série) = R₁ + R₂ + …", "resistência equivalente em série"], ["1/R_eq(paralelo) = 1/R₁ + 1/R₂ + …", "em paralelo"], ["ΣI(nó) = 0; ΣV(malha) = 0", "Leis de Kirchhoff"]],
        producao: "Entender por que uma máquina desligada não derruba as outras (paralelo) e como circuitos de segurança em série (botões de emergência) param tudo se qualquer um for acionado.",
        exemplo: "Dois resistores de 10 Ω: em série = **20 Ω**; em paralelo = **5 Ω**." },
      { t: "Energia, conta de luz e fator de potência", icone: "🧾",
        pontos: ["**Energia** (kWh) = potência (kW) × tempo (h); é o que a concessionária cobra.", "Consumidores industriais podem pagar também **demanda** (kW contratados) e ter tarifas por horário (ponta e fora de ponta).", "Em corrente alternada com motores, há **potência ativa** (P, kW, realiza trabalho), **reativa** (Q, kvar) e **aparente** (S, kVA).", "**Fator de potência** FP = P ÷ S = cos φ. No Brasil, a regulação da ANEEL cobra excedente de reativo quando o FP fica abaixo de **0,92**.", "Correção do FP com **bancos de capacitores**."],
        formulas: [["E (kWh) = P (kW) × t (h)", "energia consumida"], ["S² = P² + Q²; FP = P ÷ S", "triângulo de potências"], ["Custo = E × tarifa", "custo da energia"]],
        producao: "Reduzir o custo de energia deslocando cargas do horário de ponta, corrigindo o fator de potência e desligando equipamentos ociosos; energia é custo de produção relevante.",
        exemplo: "Motor de 7,5 kW, 16 h/dia, 22 dias: E = 7,5 × 16 × 22 = **2.640 kWh**; a R$ 0,80/kWh = **R$ 2.112/mês**." },
      { t: "Corrente alternada, trifásico e segurança", icone: "⚠️",
        pontos: ["**Corrente alternada (CA):** no Brasil, frequência de **60 Hz**; tensões típicas 127/220 V (residencial) e 220/380 V ou mais (industrial).", "**Sistema trifásico:** três fases defasadas de 120°; potência P = √3·V_L·I_L·FP.", "**Choque elétrico:** o perigo depende da corrente que passa pelo corpo, do caminho e do tempo.", "**NR-10:** segurança em instalações e serviços em eletricidade; exige trabalhadores qualificados, habilitados e autorizados e medidas como desenergização e bloqueio.", "**Bloqueio e etiquetagem** (LOTO) antes de manutenção."],
        formulas: [["P = √3 · V_L · I_L · FP", "potência ativa trifásica"], ["V_rms = V_pico ÷ √2", "valor eficaz de uma senoide"]],
        producao: "Estimar a corrente de motores trifásicos, planejar paradas de manutenção com bloqueio de energia e garantir que só pessoas autorizadas atuem em painéis.",
        exemplo: "Motor trifásico de 15 kW, 380 V, FP 0,85: I = 15.000 ÷ (1,732 × 380 × 0,85) ≈ **26,8 A**." }
    ],
    glossario: [["Corrente", "Fluxo de carga elétrica (A)."], ["Tensão", "Diferença de potencial elétrico (V)."], ["Resistência", "Oposição à passagem de corrente (Ω)."], ["Lei de Ohm", "V = R·I."], ["Potência ativa", "Parcela que realiza trabalho (W, kW)."], ["Potência reativa", "Parcela associada a campos magnéticos e elétricos (var)."], ["Fator de potência", "P ÷ S; mede o aproveitamento da energia."], ["kWh", "Unidade de energia: 1 kW durante 1 hora."], ["Sistema trifásico", "Três tensões senoidais defasadas de 120°."], ["NR-10", "Norma regulamentadora de segurança em eletricidade."], ["LOTO", "Bloqueio e etiquetagem de fontes de energia."]],
    questoes: [
      { t: 0, id: "g-elet-t01", tipo: "calculo", variaveis: { v: { valores: [127, 220, 380] }, r: { valores: [10, 20, 22, 40, 50, 100] } }, resposta: "v*v/r", tolerancia: 0.5, unidade: "W",
        pergunta: "Uma resistência de {r} Ω é ligada em {v} V. Qual a potência dissipada (W)? (inteiro)", resolucao: "I = {v} ÷ {r} = {=v/r:2} A; P = V·I = {=v*v/r:0} W", explicacao: "P = V²/R." },
      { t: 0, id: "g-elet-q01", tipo: "vf", pergunta: "Um cabo mais fino e mais longo tem maior resistência e tende a aquecer mais com a mesma corrente.", correta: true, explicacao: "R = ρL/A; perdas R·I²." },
      { t: 0, id: "g-elet-q02", tipo: "ligar", pergunta: "Ligue a grandeza à unidade:", pares: [["Corrente", "Ampère (A)"], ["Tensão", "Volt (V)"], ["Resistência", "Ohm (Ω)"], ["Potência", "Watt (W)"]], explicacao: "Unidades do SI." },
      { t: 1, id: "g-elet-t02", tipo: "calculo", variaveis: { r1: { valores: [4, 6, 10, 12, 20] }, r2: { valores: [4, 5, 10, 15, 30] } }, resposta: "r1*r2/(r1+r2)", tolerancia: 0.01, unidade: "Ω",
        pergunta: "Qual a resistência equivalente de {r1} Ω e {r2} Ω em paralelo? (2 casas)", resolucao: "R_eq = {r1}×{r2} ÷ ({r1} + {r2}) = {=r1*r2/(r1+r2):2} Ω", explicacao: "Em paralelo, a equivalente é menor que a menor resistência." },
      { t: 1, id: "g-elet-q03", tipo: "multipla", pergunta: "Por que as máquinas de uma fábrica são ligadas em paralelo?", opcoes: ["Para dividir a tensão", "Para cada uma receber a mesma tensão e funcionar independentemente", "Para economizar cabo", "Porque é obrigatório usar série"], correta: 1, explicacao: "Em série, desligar uma pararia as outras." },
      { t: 1, id: "g-elet-q04", tipo: "vf", pergunta: "Botões de emergência costumam ser ligados em série no circuito de comando para que qualquer um deles interrompa o funcionamento.", correta: true, explicacao: "Abrir qualquer contato da série interrompe o circuito." },
      { t: 2, id: "g-elet-t03", tipo: "calculo", variaveis: { p: { valores: [3, 5.5, 7.5, 11, 15, 22] }, h: { valores: [8, 16, 24] }, d: { valores: [20, 22, 26, 30] }, tar: { valores: [0.6, 0.7, 0.8, 0.9] } }, resposta: "p*h*d*tar", tolerancia: 0.5, unidade: "R$",
        pergunta: "Motor de {p} kW funcionando {h} h/dia durante {d} dias, tarifa R$ {tar}/kWh. Custo mensal de energia (R$)? (inteiro)", resolucao: "E = {p} × {h} × {d} = {=p*h*d} kWh; custo = {=p*h*d} × {tar} = R$ {=p*h*d*tar:0}", explicacao: "Energia = potência × tempo." },
      { t: 2, id: "g-elet-q05", tipo: "multipla", pergunta: "P = 80 kW e S = 100 kVA. Qual o fator de potência?", opcoes: ["0,80", "1,25", "0,92", "0,60"], correta: 0, explicacao: "FP = P ÷ S = 0,8: abaixo de 0,92, sujeito a cobrança de excedente de reativo." },
      { t: 2, id: "g-elet-q06", tipo: "multipla", pergunta: "Qual solução é usada para corrigir o baixo fator de potência de uma fábrica com muitos motores?", opcoes: ["Bancos de capacitores", "Aumentar a tensão", "Trocar lâmpadas", "Desligar o aterramento"], correta: 0, explicacao: "Os capacitores fornecem a potência reativa localmente." },
      { t: 3, id: "g-elet-t04", tipo: "calculo", variaveis: { p: { valores: [5, 7.5, 11, 15, 22, 30] }, v: { valores: [220, 380, 440] }, fp: { valores: [0.8, 0.85, 0.9] } }, resposta: "p*1000/(sqrt(3)*v*fp)", tolerancia: 0.1, unidade: "A",
        pergunta: "Motor trifásico de {p} kW, {v} V, FP = {fp}. Qual a corrente de linha (A)? (1 casa)", resolucao: "I = P ÷ (√3·V·FP) = {=p*1000} ÷ (1,732 × {v} × {fp}) = {=p*1000/(sqrt(3)*v*fp):1} A", explicacao: "Desprezando o rendimento do motor." },
      { t: 3, id: "g-elet-q07", tipo: "vf", pergunta: "Pela NR-10, qualquer trabalhador pode abrir um painel energizado se usar luvas.", correta: false, explicacao: "Só profissionais qualificados/habilitados, capacitados e autorizados, com medidas de controle." },
      { t: 3, id: "g-elet-q08", tipo: "ordenar", pergunta: "Ordene a sequência básica de desenergização para manutenção:", itens: ["Seccionar (desligar)", "Impedir a reenergização (bloqueio e etiqueta)", "Constatar a ausência de tensão", "Instalar aterramento temporário", "Proteger elementos energizados próximos", "Sinalizar"], explicacao: "Sequência prevista na NR-10 para considerar a instalação desenergizada." }
    ]
  },

  {
    id: "g-estat", nome: "Estatística", periodo: 3, area: "exatas", icone: "📊", prereq: ["g-calc1"], relacionado: ["m13"],
    intro: "Estatística transforma dados em decisão. Na produção, descreve a **variabilidade** dos processos, calcula **probabilidades** de defeito e de falha e estima parâmetros com **amostras**. O Módulo 13 do curso aprofunda os temas com muitos exercícios.",
    topicos: [
      { t: "Estatística descritiva", icone: "📋",
        pontos: ["**Média, mediana e moda** resumem o centro dos dados; a mediana resiste a valores extremos.", "**Amplitude, variância e desvio-padrão** medem a dispersão.", "**Coeficiente de variação** CV = s ÷ x̄ compara a variabilidade de grandezas diferentes.", "Gráficos: histograma, boxplot, gráfico de linha (dados no tempo), Pareto."],
        formulas: [["x̄ = Σxᵢ ÷ n", "média"], ["s = √[Σ(xᵢ − x̄)² ÷ (n − 1)]", "desvio-padrão amostral"], ["CV = s ÷ x̄ × 100%", "coeficiente de variação"]],
        producao: "O desvio-padrão do peso das caixas indica se o processo está consistente; o CV compara a variabilidade de linhas diferentes.",
        exemplo: "Pesos: 248, 250, 252 g ⇒ x̄ = 250 g; s = 2 g; CV = **0,8%**." },
      { t: "Probabilidade", icone: "🎲",
        pontos: ["P(A) entre 0 e 1. **Complemento:** P(não A) = 1 − P(A).", "**Adição:** P(A ou B) = P(A) + P(B) − P(A e B).", "**Independência:** P(A e B) = P(A)·P(B).", "**Condicional:** P(A|B) = P(A e B) ÷ P(B); **Bayes** atualiza probabilidades com nova informação.", "Sistemas em **série** funcionam se todos funcionam: R = R₁·R₂·…"],
        formulas: [["P(A e B) = P(A)·P(B) (independentes)", "regra do produto"], ["P(A|B) = P(A e B) ÷ P(B)", "probabilidade condicional"], ["R_série = R₁ · R₂ · … · Rₙ", "confiabilidade de componentes em série"]],
        producao: "Probabilidade de um lote passar pela inspeção, confiabilidade de linhas com várias máquinas em série e chance de falta de material.",
        exemplo: "Linha com 3 máquinas em série, cada uma com 95% de disponibilidade: R = 0,95³ ≈ **85,7%**." },
      { t: "Distribuições de probabilidade", icone: "🔔",
        pontos: ["**Binomial:** nº de sucessos em n tentativas independentes com probabilidade p (ex.: defeituosos num lote).", "**Poisson:** nº de eventos num intervalo com taxa λ (ex.: chegadas, quebras por mês).", "**Normal:** simétrica, em forma de sino; padroniza-se com Z = (x − μ) ÷ σ.", "**Exponencial:** tempo entre eventos com taxa constante (ligação com confiabilidade)."],
        formulas: [["P(X = k) = C(n,k)·pᵏ·(1 − p)ⁿ⁻ᵏ", "binomial"], ["P(X = k) = e^(−λ)·λᵏ ÷ k!", "Poisson"], ["Z = (x − μ) ÷ σ", "padronização da normal"]],
        producao: "Planos de amostragem (binomial), dimensionamento de equipes de manutenção (Poisson), porcentagem de itens fora da especificação (normal).",
        exemplo: "Lote de 10 peças com 5% de defeituosas: P(nenhuma defeituosa) = 0,95¹⁰ ≈ **59,9%**." },
      { t: "Amostragem e intervalo de confiança", icone: "🎯",
        pontos: ["**População** × **amostra**; amostragem aleatória reduz vieses.", "**Teorema Central do Limite:** a média amostral tende à normal, com erro-padrão σ ÷ √n.", "**Intervalo de confiança** (95%): x̄ ± 1,96·σ/√n (σ conhecido ou n grande).", "Tamanho de amostra para estimar a média com erro E: n = (z·σ ÷ E)²."],
        formulas: [["IC = x̄ ± z · σ ÷ √n", "intervalo de confiança para a média"], ["n = (z · σ ÷ E)²", "tamanho de amostra"]],
        producao: "Estimar o peso médio do lote sem pesar tudo, definir quantas cronometragens fazer (Módulo 4) e quantas unidades inspecionar.",
        exemplo: "x̄ = 250 g, σ = 4 g, n = 64: IC 95% = 250 ± 1,96 × 4 ÷ 8 = 250 ± **0,98 g**." }
    ],
    glossario: [["Média", "Soma dos valores ÷ quantidade."], ["Mediana", "Valor central dos dados ordenados."], ["Desvio-padrão", "Medida da dispersão em torno da média."], ["Coeficiente de variação", "Desvio-padrão relativo à média."], ["Eventos independentes", "A ocorrência de um não altera a probabilidade do outro."], ["Distribuição binomial", "Nº de sucessos em n tentativas com probabilidade p."], ["Distribuição de Poisson", "Nº de eventos num intervalo com taxa λ."], ["Distribuição normal", "Distribuição simétrica em forma de sino."], ["Erro-padrão", "Desvio-padrão da média amostral: σ/√n."], ["Intervalo de confiança", "Faixa que contém o parâmetro com a confiança declarada."]],
    questoes: [
      { t: 0, id: "g-est-t01", tipo: "calculo", variaveis: { x: { lista: 5, min: 240, max: 260 } }, resposta: "desvio(x)", tolerancia: 0.01, unidade: "g",
        pergunta: "Pesos de 5 caixas (g): {x}. Qual o desvio-padrão amostral? (2 casas)", resolucao: "x̄ = {=media(x):2}; s = {=desvio(x):2} g", explicacao: "Divide por n − 1 na amostra." },
      { t: 0, id: "g-est-q01", tipo: "multipla", pergunta: "Qual medida de tendência central é menos afetada por valores extremos?", opcoes: ["Média", "Mediana", "Amplitude", "Variância"], correta: 1, explicacao: "A mediana depende da posição, não do valor dos extremos." },
      { t: 0, id: "g-est-q02", tipo: "vf", pergunta: "O coeficiente de variação permite comparar a variabilidade de grandezas com unidades diferentes.", correta: true, explicacao: "É adimensional (%)." },
      { t: 1, id: "g-est-t02", tipo: "calculo", variaveis: { r: { valores: [0.9, 0.92, 0.95, 0.97, 0.98, 0.99] }, n: { min: 2, max: 6 } }, resposta: "pow(r,n)*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Uma linha tem {n} máquinas em série, cada uma com confiabilidade {r}. Qual a confiabilidade da linha (%)? (1 casa)", resolucao: "R = {r}^{n} = {=pow(r,n)*100:1}%", explicacao: "Em série, todas precisam funcionar." },
      { t: 1, id: "g-est-q03", tipo: "multipla", pergunta: "P(A) = 0,3. Qual P(não A)?", opcoes: ["0,3", "0,7", "1,3", "0"], correta: 1, explicacao: "Complemento: 1 − 0,3." },
      { t: 1, id: "g-est-q04", tipo: "vf", pergunta: "Se A e B são independentes, P(A e B) = P(A) + P(B).", correta: false, explicacao: "É o produto: P(A)·P(B)." },
      { t: 2, id: "g-est-t03", tipo: "calculo", variaveis: { n: { valores: [5, 10, 20] }, p: { valores: [0.01, 0.02, 0.05, 0.1] } }, resposta: "pow(1-p,n)*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Amostra de {n} peças de um processo com {=p*100}% de defeituosas. Probabilidade (%) de não encontrar nenhuma defeituosa? (1 casa)", resolucao: "P(X = 0) = (1 − {p})^{n} = {=pow(1-p,n)*100:1}%", explicacao: "Binomial com k = 0." },
      { t: 2, id: "g-est-q05", tipo: "ligar", pergunta: "Ligue a distribuição ao exemplo:", pares: [["Binomial", "Defeituosas numa amostra de 20"], ["Poisson", "Quebras de máquina por mês"], ["Normal", "Peso de caixas envasadas"], ["Exponencial", "Tempo até a próxima falha"]], explicacao: "Cada distribuição modela um tipo de fenômeno." },
      { t: 2, id: "g-est-q06", tipo: "multipla", pergunta: "Um peso de 256 g numa normal com μ = 250 g e σ = 3 g tem Z igual a:", opcoes: ["1", "2", "3", "6"], correta: 1, explicacao: "Z = (256 − 250) ÷ 3 = 2." },
      { t: 3, id: "g-est-t04", tipo: "calculo", variaveis: { s: { valores: [2, 3, 4, 5, 6] }, n: { valores: [16, 25, 36, 49, 64, 100] } }, resposta: "1.96*s/sqrt(n)", tolerancia: 0.01, unidade: "g",
        pergunta: "σ = {s} g e n = {n}. Qual a margem de erro do intervalo de 95% para a média (±)? (2 casas)", resolucao: "E = 1,96 × {s} ÷ √{n} = 1,96 × {s} ÷ {=sqrt(n)} = {=1.96*s/sqrt(n):2} g", explicacao: "Quadruplicar n reduz a margem pela metade." },
      { t: 3, id: "g-est-q07", tipo: "vf", pergunta: "Pelo Teorema Central do Limite, a média de amostras grandes tende a ter distribuição aproximadamente normal.", correta: true, explicacao: "Base dos intervalos de confiança e das cartas de controle." },
      { t: 3, id: "g-est-q08", tipo: "multipla", pergunta: "Para reduzir pela metade a margem de erro de uma estimativa, o tamanho da amostra deve ser:", opcoes: ["Dobrado", "Multiplicado por 4", "Reduzido à metade", "Mantido"], correta: 1, explicacao: "E ∝ 1/√n." }
    ]
  },

  {
    id: "g-engmet", nome: "Engenharia de Métodos", periodo: 3, area: "producao", icone: "⏱️", relacionado: ["m04"],
    intro: "Como fazer melhor e quanto tempo leva: **estudo de métodos**, **cronoanálise**, **tempo padrão**, **takt time** e **balanceamento de linha**. É a disciplina que mais conversa com o Módulo 4 do curso (em 3 níveis, com muito mais exercícios).",
    topicos: [
      { t: "Estudo de métodos", icone: "🔍",
        pontos: ["Primeiro melhorar o **método**, depois medir o tempo.", "**Fluxograma de processo:** operação, transporte, inspeção, espera e armazenagem.", "**ECRS:** Eliminar, Combinar, Rearranjar, Simplificar.", "**Economia de movimentos:** ferramentas no ponto de uso, movimentos simultâneos e simétricos, alcance adequado."],
        formulas: [["% que agrega valor = tempo de operação ÷ tempo total × 100", "leitura do fluxograma"]],
        producao: "Melhorias de método aumentam a produtividade sem investimento e reduzem esforço físico.",
        exemplo: "Posto onde o operador anda 8 m por ciclo para buscar caixas: um abastecedor por gravidade ao lado elimina o deslocamento." },
      { t: "Cronoanálise e tempo padrão", icone: "⏲️",
        pontos: ["Dividir a operação em **elementos**, cronometrar vários ciclos e calcular o **tempo observado (TO)**.", "**Tempo normal** TN = TO × fator de ritmo.", "**Tempo padrão** TP = TN × (1 + tolerâncias) — tolerâncias pessoais, de fadiga e esperas inevitáveis.", "Número de ciclos: n = (z·s ÷ (Er·x̄))².", "Cronometrar sempre com transparência para o operador."],
        formulas: [["TN = TO × FR", "tempo normal"], ["TP = TN × (1 + T)", "tempo padrão (tolerância sobre o TN)"], ["n = (z·s ÷ (Er·x̄))²", "número de ciclos a medir"]],
        producao: "O tempo padrão alimenta custo, capacidade, PCP e balanceamento.",
        exemplo: "TO = 2,0 min, ritmo 110%, tolerância 15%: TN = 2,2 min; TP = 2,2 × 1,15 = **2,53 min**." },
      { t: "Takt time e balanceamento de linha", icone: "⚖️",
        pontos: ["**Takt time** = tempo disponível ÷ demanda: o ritmo exigido pelo cliente.", "**Tempo de ciclo** da linha = maior tempo entre os postos (o gargalo).", "**Nº mínimo de postos** = ⌈Σt ÷ takt⌉.", "**Eficiência do balanceamento** = Σt ÷ (N × TC).", "Respeitar a **precedência** das tarefas."],
        formulas: [["Takt = tempo disponível ÷ demanda", "ritmo do cliente"], ["N_mín = ⌈Σt ÷ takt⌉", "limite inferior de postos"], ["Eficiência = Σt ÷ (N × TC)", "aproveitamento da linha"]],
        producao: "Dimensionar quantas pessoas e postos uma linha precisa para atender a demanda.",
        exemplo: "27.000 s disponíveis, demanda de 600 caixas: takt = **45 s**. Σt = 130 s ⇒ N_mín = ⌈2,89⌉ = **3 postos**." },
      { t: "Gargalos e melhoria", icone: "🍾",
        pontos: ["O **gargalo** é o recurso que limita a saída do sistema.", "Uma hora perdida no gargalo é uma hora perdida no sistema inteiro.", "**Teoria das Restrições (TOC):** identificar, explorar, subordinar, elevar e repetir.", "Melhorar fora do gargalo não aumenta a produção."],
        formulas: [["Produção máxima = tempo disponível ÷ TC do gargalo", "capacidade da linha"]],
        producao: "Priorizar melhorias e investimentos onde realmente aumentam a produção.",
        exemplo: "Postos de 35, 40, 30 e 25 s: gargalo = 40 s; produção máxima = 27.000 ÷ 40 = **675 caixas/turno**." }
    ],
    glossario: [["ECRS", "Eliminar, Combinar, Rearranjar, Simplificar."], ["Cronoanálise", "Medição de tempos de uma operação padronizada."], ["Fator de ritmo", "Avaliação da velocidade do operador (100% = normal)."], ["Tempo padrão", "Tempo normal com tolerâncias."], ["Takt time", "Tempo disponível ÷ demanda."], ["Tempo de ciclo", "Ritmo real da linha, dado pelo posto mais lento."], ["Balanceamento", "Distribuição das tarefas entre postos."], ["Gargalo", "Recurso que limita a saída do sistema."], ["TOC", "Teoria das Restrições (Goldratt)."]],
    questoes: [
      { t: 0, id: "g-emet-q01", tipo: "ordenar", pergunta: "Ordene as perguntas do ECRS:", itens: ["Eliminar", "Combinar", "Rearranjar", "Simplificar"], explicacao: "Eliminar primeiro." },
      { t: 0, id: "g-emet-q02", tipo: "vf", pergunta: "Deve-se medir o tempo antes de melhorar o método.", correta: false, explicacao: "Medir um método ruim é padronizar desperdício." },
      { t: 0, id: "g-emet-q03", tipo: "multipla", pergunta: "No fluxograma de processo, qual atividade normalmente agrega valor?", opcoes: ["Transporte", "Operação", "Espera", "Armazenagem"], correta: 1, explicacao: "A operação transforma o produto." },
      { t: 1, id: "g-emet-t01", tipo: "calculo", variaveis: { to: { min: 1.5, max: 4, passo: 0.1 }, fr: { valores: [90, 95, 100, 105, 110, 115] }, tol: { valores: [10, 12, 15, 18, 20] } }, resposta: "to*fr/100*(1+tol/100)", tolerancia: 0.01, unidade: "min",
        pergunta: "TO = {to} min, ritmo {fr}%, tolerância {tol}% sobre o TN. Qual o tempo padrão (min)? (2 casas)", resolucao: "TN = {to} × {=fr/100} = {=to*fr/100:3}\nTP = TN × {=1+tol/100} = {=to*fr/100*(1+tol/100):2} min", explicacao: "TO → TN → TP." },
      { t: 1, id: "g-emet-q04", tipo: "vf", pergunta: "Um fator de ritmo de 110% indica um operador mais rápido que o normal, e o tempo normal fica maior que o observado.", correta: true, explicacao: "TN = TO × 1,10." },
      { t: 1, id: "g-emet-q05", tipo: "multipla", pergunta: "Qual destes NÃO é um tipo de tolerância no tempo padrão?", opcoes: ["Necessidades pessoais", "Fadiga", "Esperas inevitáveis", "Lucro da empresa"], correta: 3, explicacao: "Tolerâncias cobrem necessidades e esperas do trabalho." },
      { t: 2, id: "g-emet-t02", tipo: "calculo", variaveis: { disp: { valores: [25200, 27000, 28800] }, dem: { min: 300, max: 900, passo: 20 } }, resposta: "disp/dem", tolerancia: 0.01, unidade: "s",
        pergunta: "Tempo disponível = {disp} s por turno; demanda = {dem} unidades. Qual o takt time (s)? (2 casas)", resolucao: "Takt = {disp} ÷ {dem} = {=disp/dem:2} s", explicacao: "Ritmo exigido pelo cliente." },
      { t: 2, id: "g-emet-q06", tipo: "multipla", pergunta: "Σt = 130 s e takt = 45 s. Qual o número mínimo teórico de postos?", opcoes: ["2", "3", "4", "5"], correta: 1, explicacao: "130 ÷ 45 = 2,89 → 3." },
      { t: 2, id: "g-emet-q07", tipo: "vf", pergunta: "O tempo de ciclo da linha é dado pelo posto com o maior tempo.", correta: true, explicacao: "A linha anda no ritmo do mais lento." },
      { t: 3, id: "g-emet-q08", tipo: "ordenar", pergunta: "Ordene os 5 passos da Teoria das Restrições:", itens: ["Identificar a restrição", "Explorar a restrição", "Subordinar o resto", "Elevar a restrição", "Repetir"], explicacao: "Goldratt, A Meta." },
      { t: 3, id: "g-emet-q09", tipo: "multipla", pergunta: "Postos com 35, 40, 30 e 25 s. Reduzir o posto de 30 s para 20 s aumenta a produção?", opcoes: ["Sim, muito", "Não: o gargalo continua sendo o de 40 s", "Sim, 10%", "Depende do takt"], correta: 1, explicacao: "Melhorar fora do gargalo não aumenta a saída." },
      { t: 3, id: "g-emet-t03", tipo: "calculo", variaveis: { disp: { valores: [25200, 27000, 28800] }, tc: { min: 30, max: 60 } }, resposta: "floor(disp/tc)", tolerancia: 0, unidade: "unidades",
        pergunta: "O gargalo tem tempo de ciclo de {tc} s e há {disp} s disponíveis no turno. Qual a produção máxima?", resolucao: "{disp} ÷ {tc} = {=disp/tc:2} → {=floor(disp/tc)} unidades", explicacao: "O gargalo define a capacidade." }
    ]
  }
);
