/* =====================================================================
   GRADE CURRICULAR — 4º PERÍODO (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-edp", nome: "Equações Diferenciais Parciais", periodo: 4, area: "exatas", icone: "🌡️", prereq: ["g-edo"],
    intro: "Quando uma grandeza varia no **tempo e no espaço** ao mesmo tempo, surge uma EDP. Na produção, ela descreve como o **calor se espalha** numa placa de chocolate, numa peça em tratamento térmico ou na parede de uma câmara fria, como substâncias se **difundem** (secagem, contaminação) e como **ondas** percorrem cabos e estruturas. É a base das simulações por computador.",
    topicos: [
      { t: "O que são EDPs e classificação", icone: "🗂️",
        pontos: ["**EDP:** envolve derivadas parciais de uma função de várias variáveis, ex.: u(x, t).", "**Parabólica** — equação do calor/difusão: evolução no tempo que “suaviza”.", "**Hiperbólica** — equação da onda: propagação com velocidade finita.", "**Elíptica** — equação de Laplace: regime permanente (não muda mais com o tempo).", "Precisam de **condições iniciais** (estado em t = 0) e **de contorno** (o que acontece nas bordas)."],
        formulas: [["∂u/∂t = α · ∂²u/∂x²", "equação do calor (1D); α = difusividade térmica"], ["∂²u/∂t² = c² · ∂²u/∂x²", "equação da onda; c = velocidade de propagação"], ["∂²u/∂x² + ∂²u/∂y² = 0", "equação de Laplace (regime permanente)"]],
        producao: "Saber qual equação descreve o fenômeno ajuda a escolher o método de cálculo ou a simulação (CAE) adequada para fornos, túneis, estruturas e tubulações.",
        exemplo: "Temperatura numa barra aquecida numa ponta, variando ao longo do comprimento e do tempo: equação do **calor**." },
      { t: "Equação do calor e difusão", icone: "🔥",
        pontos: ["**α = k ÷ (ρ·c):** difusividade térmica (condutividade ÷ capacidade térmica volumétrica).", "O calor flui do quente para o frio e as diferenças de temperatura se **suavizam** com o tempo.", "**Tempo característico** de difusão numa espessura L: t ≈ L² ÷ α — dobrar a espessura **quadruplica** o tempo.", "A mesma equação vale para **difusão de massa** (lei de Fick), com D no lugar de α.", "**Condições de contorno:** temperatura imposta (Dirichlet), fluxo imposto (Neumann), convecção com o ar."],
        formulas: [["α = k ÷ (ρ · c)", "difusividade térmica (m²/s)"], ["t ≈ L² ÷ α", "ordem de grandeza do tempo de aquecimento/resfriamento"], ["J = −D · ∂C/∂x", "lei de Fick (difusão de massa)"]],
        producao: "Dimensionar o **tempo de resfriamento** de produtos de espessuras diferentes, o tempo de forno em tratamento térmico, secagem de alimentos e madeira, e o isolamento de câmaras frias.",
        exemplo: "Alimentos têm α da ordem de 1 × 10⁻⁷ m²/s. Uma barra de chocolate resfriada pelos dois lados, com meia espessura L = 5 mm: t ≈ (0,005)² ÷ 10⁻⁷ = **250 s**. Com o dobro da espessura, ≈ 1.000 s." },
      { t: "Separação de variáveis e séries de Fourier", icone: "〽️",
        pontos: ["**Separação de variáveis:** supõe u(x, t) = X(x)·T(t) e transforma a EDP em EDOs.", "A solução é uma soma de modos: senos/cossenos em x multiplicados por exponenciais em t.", "**Série de Fourier:** representa uma função periódica como soma de senos e cossenos.", "Na equação do calor, os modos de maior frequência decaem mais rápido (por isso o perfil se suaviza).", "Na equação da onda, os modos são as **frequências naturais** (harmônicos) de cabos e barras."],
        formulas: [["u(x, t) = Σ Bₙ · sen(nπx/L) · e^(−α(nπ/L)²t)", "solução do calor numa barra com extremidades a 0"], ["f(x) = a₀/2 + Σ [aₙcos(nx) + bₙsen(nx)]", "série de Fourier"], ["fₙ = n·c ÷ (2L)", "frequências naturais de uma corda/cabo de comprimento L"]],
        producao: "A decomposição em frequências (Fourier) é a base da **análise de vibração** em manutenção preditiva: cada defeito (desbalanceamento, rolamento) aparece numa frequência característica.",
        exemplo: "No espectro de vibração de um motor a 1.800 rpm (30 Hz), um pico em 30 Hz sugere desbalanceamento; picos em outras frequências podem indicar defeitos de rolamento." },
      { t: "Solução numérica: diferenças finitas", icone: "🖥️",
        pontos: ["Divide-se o espaço em pontos (Δx) e o tempo em passos (Δt).", "Derivadas viram diferenças: ∂²u/∂x² ≈ (uᵢ₊₁ − 2uᵢ + uᵢ₋₁) ÷ Δx².", "**Método explícito:** uᵢⁿ⁺¹ = uᵢⁿ + r·(uᵢ₊₁ⁿ − 2uᵢⁿ + uᵢ₋₁ⁿ), com r = αΔt/Δx².", "**Estabilidade:** no esquema explícito da equação do calor, é preciso r ≤ 1/2; senão a solução “explode”.", "Softwares de elementos finitos (FEM) e volumes finitos (CFD) resolvem problemas 2D/3D complexos."],
        formulas: [["uᵢⁿ⁺¹ = uᵢⁿ + r·(uᵢ₊₁ⁿ − 2uᵢⁿ + uᵢ₋₁ⁿ)", "esquema explícito do calor"], ["r = α·Δt ÷ Δx² ≤ 1/2", "condição de estabilidade"]],
        producao: "Simular a distribuição de temperatura num forno ou num produto antes de construir, reduzindo testes caros; entender os limites e os erros de simulações encomendadas.",
        exemplo: "Pontos a 20, 60 e 20 °C, r = 0,25: o ponto central vai para 60 + 0,25 × (20 − 120 + 20) = **40 °C** no passo seguinte." }
    ],
    glossario: [["EDP", "Equação com derivadas parciais de uma função de várias variáveis."], ["Equação do calor", "EDP parabólica que descreve difusão de calor."], ["Equação da onda", "EDP hiperbólica de propagação de ondas."], ["Equação de Laplace", "EDP elíptica do regime permanente."], ["Difusividade térmica", "α = k/(ρc): rapidez com que a temperatura se espalha."], ["Condição de contorno", "O que se impõe nas bordas do domínio."], ["Separação de variáveis", "Técnica que escreve a solução como produto de funções de uma variável."], ["Série de Fourier", "Soma de senos e cossenos que representa uma função."], ["Diferenças finitas", "Aproximação das derivadas por diferenças numa malha."], ["Estabilidade numérica", "Propriedade de o método não amplificar erros."]],
    questoes: [
      { t: 0, id: "g-edp-q01", tipo: "ligar", pergunta: "Ligue a equação ao fenômeno:", pares: [["Equação do calor", "Resfriamento de uma placa ao longo do tempo"], ["Equação da onda", "Vibração de um cabo tensionado"], ["Equação de Laplace", "Temperatura em regime permanente numa parede"]], explicacao: "Parabólica, hiperbólica e elíptica." },
      { t: 0, id: "g-edp-q02", tipo: "vf", pergunta: "Para resolver a equação do calor numa barra, é preciso conhecer a temperatura inicial e as condições nas extremidades.", correta: true, explicacao: "Condições iniciais e de contorno." },
      { t: 0, id: "g-edp-q03", tipo: "multipla", pergunta: "A equação de Laplace descreve situações:", opcoes: ["Que mudam rapidamente no tempo", "Em regime permanente (sem variação no tempo)", "De vibração", "Aleatórias"], correta: 1, explicacao: "Não há derivada no tempo." },
      { t: 1, id: "g-edp-t01", tipo: "calculo", variaveis: { lmm: { valores: [2, 3, 4, 5, 8, 10] }, a: { valores: [1, 1.2, 1.5] } }, resposta: "pow(lmm/1000,2)/(a*1e-7)", tolerancia: 1, unidade: "s",
        pergunta: "Produto com difusividade α = {a} × 10⁻⁷ m²/s e meia espessura L = {lmm} mm. Ordem de grandeza do tempo de resfriamento t ≈ L²/α (s)? (inteiro)", resolucao: "t ≈ ({=lmm/1000})² ÷ ({a} × 10⁻⁷) ≈ {=pow(lmm/1000,2)/(a*1e-7):0} s", explicacao: "O tempo cresce com o quadrado da espessura." },
      { t: 1, id: "g-edp-q04", tipo: "multipla", pergunta: "Dobrando a espessura de um produto, o tempo de resfriamento (difusão) tende a:", opcoes: ["Dobrar", "Quadruplicar", "Ficar igual", "Cair pela metade"], correta: 1, explicacao: "t ∝ L²." },
      { t: 1, id: "g-edp-q05", tipo: "vf", pergunta: "A lei de Fick da difusão de massa tem a mesma forma matemática da equação do calor.", correta: true, explicacao: "Troca-se α pela difusividade mássica D." },
      { t: 2, id: "g-edp-q06", tipo: "multipla", pergunta: "Na solução da equação do calor por séries, os modos de alta frequência:", opcoes: ["Crescem com o tempo", "Decaem mais rápido, suavizando o perfil", "Não mudam", "Viram ondas"], correta: 1, explicacao: "O fator e^(−α(nπ/L)²t) decai mais rápido para n grande." },
      { t: 2, id: "g-edp-t02", tipo: "calculo", variaveis: { l: { valores: [0.5, 1, 1.5, 2, 3] }, c: { valores: [100, 150, 200, 300] }, n: { min: 1, max: 3 } }, resposta: "n*c/(2*l)", tolerancia: 0.01, unidade: "Hz",
        pergunta: "Num cabo de {l} m em que as ondas se propagam a {c} m/s (extremidades fixas), qual a frequência do modo n = {n} (Hz)? (2 casas)", resolucao: "fₙ = n·c ÷ (2L) = {n} × {c} ÷ (2 × {l}) = {=n*c/(2*l):2} Hz", explicacao: "Frequências naturais da equação da onda." },
      { t: 2, id: "g-edp-q07", tipo: "vf", pergunta: "A análise de vibração em manutenção preditiva usa a decomposição do sinal em frequências (Fourier).", correta: true, explicacao: "Cada defeito aparece em frequências características." },
      { t: 3, id: "g-edp-t03", tipo: "calculo", variaveis: { ue: { min: 10, max: 40, passo: 5 }, uc: { min: 50, max: 100, passo: 5 }, ud: { min: 10, max: 40, passo: 5 }, r: { valores: [0.1, 0.2, 0.25, 0.4, 0.5] } }, resposta: "uc+r*(ud-2*uc+ue)", tolerancia: 0.01, unidade: "°C",
        pergunta: "Esquema explícito: pontos vizinhos a {ue} °C e {ud} °C e ponto central a {uc} °C; r = {r}. Qual a temperatura do ponto central no próximo passo? (2 casas)", resolucao: "u = {uc} + {r} × ({ud} − 2×{uc} + {ue}) = {=uc+r*(ud-2*uc+ue):2} °C", explicacao: "O ponto quente perde calor para os vizinhos." },
      { t: 3, id: "g-edp-q08", tipo: "multipla", pergunta: "No esquema explícito da equação do calor, qual condição garante estabilidade?", opcoes: ["r ≤ 1/2", "r ≥ 2", "Δt grande", "Nenhuma"], correta: 0, explicacao: "r = αΔt/Δx² ≤ 0,5." },
      { t: 3, id: "g-edp-q09", tipo: "vf", pergunta: "Reduzir Δx pela metade no esquema explícito permite manter o mesmo Δt sem perder estabilidade.", correta: false, explicacao: "r = αΔt/Δx² quadruplica; é preciso reduzir Δt para 1/4." }
    ]
  },

  {
    id: "g-destec", nome: "Desenho Técnico I", periodo: 4, area: "engenharia", icone: "📐", prereq: ["g-desenho"],
    intro: "Aprofunda o desenho para **fabricação**: cortes, cotagem funcional, **tolerâncias dimensionais e geométricas**, rugosidade, roscas e **desenho de conjunto com lista de peças**. O engenheiro de produção usa isso para analisar a fabricabilidade, conversar com fornecedores e montar a estrutura de produto (BOM).",
    topicos: [
      { t: "Cortes, seções e vistas auxiliares", icone: "🔪",
        pontos: ["**Corte total, meio corte e corte parcial** mostram o interior da peça.", "**Hachuras** indicam as superfícies cortadas; o padrão pode indicar o material.", "**Seção:** mostra só a superfície cortada (ex.: perfil de um eixo).", "**Vista auxiliar:** mostra em verdadeira grandeza uma face inclinada.", "**Vista em detalhe:** amplia uma região pequena."],
        formulas: [],
        producao: "Entender cortes evita erros na fabricação de peças com furos internos, canais e rebaixos.",
        exemplo: "Uma polia com cubo e rasgo de chaveta é mostrada em meio corte: metade externa, metade interna na mesma vista." },
      { t: "Tolerâncias dimensionais e ajustes", icone: "🎯",
        pontos: ["Nenhuma peça sai com a medida exata: a **tolerância** é a variação permitida (limite máximo − limite mínimo).", "**Sistema ISO de tolerâncias:** letras (posição: H para furo-base, h para eixo-base) e números (grau/IT: quanto menor, mais apertado).", "**Ajustes:** com **folga** (sempre folga), **incerto** (pode folgar ou interferir) e com **interferência** (montagem forçada).", "Tolerância mais apertada = processo mais caro (mais precisão, mais inspeção, mais refugo)."],
        formulas: [["Tolerância = Lmáx − Lmín", "variação permitida"], ["Folga máx = furo máx − eixo mín", "no ajuste"], ["Folga mín = furo mín − eixo máx", "negativa = interferência"]],
        producao: "Especificar tolerâncias adequadas é decisão de custo: apertada demais encarece; folgada demais gera falhas de montagem. É a base da capacidade de processo (Cp, Cpk).",
        exemplo: "Furo Ø20 H7 (20,000 a 20,021) com eixo Ø20 g6 (19,980 a 19,993): folga máx = 20,021 − 19,980 = **0,041 mm**; folga mín = 20,000 − 19,993 = **0,007 mm** ⇒ ajuste com folga." },
      { t: "Tolerâncias geométricas e rugosidade", icone: "🔘",
        pontos: ["**Tolerâncias geométricas** (GD&T): forma (retilineidade, planeza, circularidade, cilindricidade), orientação (paralelismo, perpendicularidade), posição (localização, concentricidade) e batimento.", "São indicadas em quadros de controle com símbolo, valor e **referências (datums)**.", "**Rugosidade** (ex.: Ra em µm) descreve o acabamento da superfície.", "Acabamento mais fino exige processos mais caros (retífica, polimento)."],
        formulas: [["Ra = média dos desvios absolutos do perfil", "rugosidade média (µm)"]],
        producao: "Definir o acabamento e a geometria necessários para a função evita retrabalho e processos caros sem necessidade.",
        exemplo: "Um eixo que gira num mancal precisa de circularidade e Ra baixos; a face de uma tampa que só encosta pode ter acabamento mais grosseiro." },
      { t: "Elementos de máquinas e desenho de conjunto", icone: "🔩",
        pontos: ["**Roscas:** designação ex. M10 × 1,5 (métrica, diâmetro 10 mm, passo 1,5 mm).", "Representação simplificada de parafusos, porcas, molas, engrenagens e rolamentos.", "**Desenho de conjunto:** mostra como as peças se montam, com **números de posição**.", "**Lista de peças:** item, descrição, quantidade, material, referência — é a origem da **BOM** usada no PCP e no MRP.", "Desenhos de detalhe de cada peça fabricada completam o conjunto."],
        formulas: [["M d × p", "rosca métrica: d = diâmetro nominal (mm); p = passo (mm)"]],
        producao: "A lista de peças do desenho de conjunto é a base da estrutura de produto no ERP; erros nela viram faltas de material e montagens erradas.",
        exemplo: "Conjunto “suporte do rolo”: pos. 1 base (1), pos. 2 eixo (1), pos. 3 rolamento 6204 (2), pos. 4 parafuso M8 × 20 (4)." }
    ],
    glossario: [["Corte", "Representação imaginária da peça cortada para mostrar o interior."], ["Vista auxiliar", "Vista que mostra uma face inclinada em verdadeira grandeza."], ["Tolerância", "Variação permitida de uma dimensão."], ["Ajuste com folga", "O eixo é sempre menor que o furo."], ["Ajuste com interferência", "O eixo é sempre maior que o furo."], ["Ajuste incerto", "Pode haver folga ou interferência."], ["GD&T", "Dimensionamento e tolerâncias geométricas."], ["Datum", "Referência para tolerâncias geométricas."], ["Rugosidade (Ra)", "Medida do acabamento da superfície."], ["Lista de peças", "Tabela do desenho de conjunto; origem da BOM."]],
    questoes: [
      { t: 0, id: "g-dtec-q01", tipo: "multipla", pergunta: "Para mostrar metade externa e metade interna de uma peça simétrica numa mesma vista, usa-se:", opcoes: ["Corte total", "Meio corte", "Vista auxiliar", "Perspectiva"], correta: 1, explicacao: "Meio corte aproveita a simetria." },
      { t: 0, id: "g-dtec-q02", tipo: "vf", pergunta: "A vista auxiliar é usada para mostrar em verdadeira grandeza uma face inclinada.", correta: true, explicacao: "Nas vistas principais ela apareceria deformada." },
      { t: 0, id: "g-dtec-q03", tipo: "multipla", pergunta: "O que as hachuras indicam num corte?", opcoes: ["Arestas ocultas", "Superfícies cortadas", "Linhas de centro", "Cotas"], correta: 1, explicacao: "Marcam onde o plano de corte atravessa o material." },
      { t: 1, id: "g-dtec-t01", tipo: "calculo", variaveis: { fmin: { valores: [20, 25, 30, 40] }, tf: { valores: [0.021, 0.025, 0.03] }, ei: { valores: [0.007, 0.009, 0.01, 0.02] }, te: { valores: [0.013, 0.016, 0.019] } },
        resposta: "(fmin+tf)-(fmin-ei-te)", tolerancia: 0.0005, unidade: "mm", pergunta: "Furo: {fmin},000 a {=fmin+tf:3} mm. Eixo: {=fmin-ei-te:3} a {=fmin-ei:3} mm. Qual a folga máxima (mm)? (3 casas)",
        resolucao: "Folga máx = furo máx − eixo mín = {=fmin+tf:3} − {=fmin-ei-te:3} = {=(fmin+tf)-(fmin-ei-te):3} mm", explicacao: "Folga mínima = {=ei:3} mm (positiva ⇒ ajuste com folga)." },
      { t: 1, id: "g-dtec-q04", tipo: "ligar", pergunta: "Ligue o ajuste à situação:", pares: [["Com folga", "Eixo sempre menor que o furo"], ["Com interferência", "Eixo sempre maior (montagem forçada)"], ["Incerto", "Pode folgar ou interferir"]], explicacao: "Escolhido conforme a função." },
      { t: 1, id: "g-dtec-q05", tipo: "vf", pergunta: "Apertar tolerâncias além do necessário aumenta o custo de fabricação e de inspeção.", correta: true, explicacao: "Exige processos mais precisos e gera mais refugo." },
      { t: 2, id: "g-dtec-q06", tipo: "ligar", pergunta: "Ligue a tolerância geométrica ao grupo:", pares: [["Planeza", "Forma"], ["Perpendicularidade", "Orientação"], ["Localização", "Posição"], ["Batimento radial", "Batimento"]], explicacao: "Grupos de tolerâncias geométricas." },
      { t: 2, id: "g-dtec-q07", tipo: "multipla", pergunta: "Qual processo costuma dar o melhor acabamento (menor Ra)?", opcoes: ["Fundição em areia", "Retífica", "Oxicorte", "Serra"], correta: 1, explicacao: "Retífica e polimento dão acabamentos finos." },
      { t: 2, id: "g-dtec-q08", tipo: "vf", pergunta: "Todas as superfícies de uma peça devem ter o acabamento mais fino possível, por segurança.", correta: false, explicacao: "Especifique conforme a função; acabamento fino desnecessário encarece." },
      { t: 3, id: "g-dtec-q09", tipo: "multipla", pergunta: "O que significa M10 × 1,5?", opcoes: ["Rosca métrica de 10 mm de diâmetro e passo 1,5 mm", "10 parafusos de 1,5 mm", "Rosca de 1,5 polegada", "Material nº 10"], correta: 0, explicacao: "Designação de rosca métrica." },
      { t: 3, id: "g-dtec-q10", tipo: "vf", pergunta: "A lista de peças do desenho de conjunto é a origem da estrutura de produto (BOM) usada no MRP.", correta: true, explicacao: "Erros nela viram faltas de material." },
      { t: 3, id: "g-dtec-q11", tipo: "multipla", pergunta: "No desenho de conjunto, os números de posição servem para:", opcoes: ["Indicar a escala", "Relacionar cada peça do desenho com a linha da lista de peças", "Numerar as folhas", "Indicar tolerâncias"], correta: 1, explicacao: "Ligam o desenho à lista." }
    ]
  },

  {
    id: "g-fister", nome: "Física Térmica", periodo: 4, area: "exatas", icone: "♨️", prereq: ["g-mecbas"],
    intro: "Calor e energia térmica estão em toda fábrica: **caldeiras**, fornos, câmaras frias, **dilatação** de tubulações e trilhos, **refrigeração** e o custo de energia para aquecer e resfriar. A termodinâmica mostra também os **limites de rendimento** de máquinas térmicas.",
    topicos: [
      { t: "Temperatura, calor e dilatação", icone: "🌡️",
        pontos: ["**Temperatura:** medida da agitação térmica; escalas Celsius, Kelvin (K = °C + 273,15) e Fahrenheit.", "**Calor:** energia em trânsito devido à diferença de temperatura.", "**Dilatação linear:** ΔL = α·L₀·ΔT; superficial (2α) e volumétrica (3α, aproximações).", "Estruturas longas precisam de **juntas de dilatação** e liras em tubulações de vapor."],
        formulas: [["ΔL = α · L₀ · ΔT", "dilatação linear; α = coeficiente de dilatação (1/°C)"], ["T(K) = T(°C) + 273,15", "conversão para Kelvin"]],
        producao: "Tubulações de vapor, trilhos de pontes rolantes e estruturas metálicas expostas ao sol precisam absorver a dilatação; ajustes por interferência usam aquecimento para montar.",
        exemplo: "Tubo de aço (α ≈ 12 × 10⁻⁶/°C) de 50 m aquecido de 20 para 180 °C: ΔL = 12 × 10⁻⁶ × 50 × 160 ≈ **0,096 m (9,6 cm)**." },
      { t: "Calorimetria e mudanças de fase", icone: "🧊",
        pontos: ["**Calor sensível:** muda a temperatura: Q = m·c·ΔT.", "**Calor latente:** muda o estado sem mudar a temperatura: Q = m·L.", "Água: c ≈ 4,18 kJ/(kg·°C); calor latente de vaporização ≈ 2.257 kJ/kg (a 100 °C, 1 atm); de fusão ≈ 334 kJ/kg.", "1 kWh = 3.600 kJ (converter para estimar custo de energia).", "**Capacidade térmica** C = m·c."],
        formulas: [["Q = m · c · ΔT", "calor sensível"], ["Q = m · L", "calor latente"], ["1 kWh = 3.600 kJ", "conversão de energia"]],
        producao: "Estimar a energia (e o custo) para aquecer água de processo, derreter chocolate, congelar produtos ou produzir vapor.",
        exemplo: "Aquecer 500 kg de água de 20 para 80 °C: Q = 500 × 4,18 × 60 = 125.400 kJ ≈ **34,8 kWh**." },
      { t: "Transferência de calor", icone: "🔥",
        pontos: ["**Condução:** através de sólidos; lei de Fourier q = k·A·ΔT ÷ L.", "**Convecção:** por fluidos em movimento; q = h·A·ΔT.", "**Radiação:** por ondas eletromagnéticas; q = ε·σ·A·T⁴ (T em kelvin).", "**Isolamento térmico:** materiais de baixa condutividade k reduzem perdas.", "Resistências térmicas em série se somam (paredes com várias camadas)."],
        formulas: [["q = k · A · ΔT ÷ L", "condução (W)"], ["q = h · A · ΔT", "convecção (W)"], ["q = ε · σ · A · T⁴", "radiação; σ = 5,67 × 10⁻⁸ W/(m²·K⁴)"]],
        producao: "Isolar tubulações de vapor e câmaras frias, projetar trocadores de calor e reduzir perdas de energia em fornos são ganhos diretos de custo.",
        exemplo: "Parede de câmara fria: k = 0,03 W/(m·K), 10 cm, 50 m², ΔT = 30 °C: q = 0,03 × 50 × 30 ÷ 0,1 = **450 W** de calor entrando." },
      { t: "Termodinâmica: leis e máquinas térmicas", icone: "⚙️",
        pontos: ["**1ª lei:** conservação da energia: ΔU = Q − W.", "**2ª lei:** o calor flui espontaneamente do quente para o frio; nenhuma máquina converte todo o calor em trabalho.", "**Rendimento de uma máquina térmica:** η = W ÷ Q_q; limite de **Carnot**: η = 1 − T_f ÷ T_q (em kelvin).", "**Refrigeradores e bombas de calor:** COP = calor retirado ÷ trabalho.", "Caldeiras, turbinas, compressores e ciclos de refrigeração aplicam essas leis."],
        formulas: [["ΔU = Q − W", "1ª lei"], ["η_Carnot = 1 − T_f ÷ T_q", "rendimento máximo teórico (kelvin)"], ["COP = Q_f ÷ W", "coeficiente de desempenho de refrigeração"]],
        producao: "Avaliar eficiência de caldeiras, compressores e sistemas de refrigeração; recuperar calor de processos (cogeração) para reduzir custo.",
        exemplo: "Entre 500 K e 300 K, nenhuma máquina térmica passa de η = 1 − 300/500 = **40%**." }
    ],
    glossario: [["Calor", "Energia transferida por diferença de temperatura."], ["Dilatação térmica", "Variação de dimensões com a temperatura."], ["Calor específico", "Energia para elevar 1 kg em 1 °C."], ["Calor latente", "Energia de mudança de fase sem variação de temperatura."], ["Condução", "Transferência de calor através de um meio sólido."], ["Convecção", "Transferência de calor por um fluido em movimento."], ["Radiação térmica", "Transferência por ondas eletromagnéticas."], ["1ª lei da termodinâmica", "Conservação da energia."], ["Ciclo de Carnot", "Ciclo ideal de rendimento máximo entre duas temperaturas."], ["COP", "Coeficiente de desempenho de refrigeradores e bombas de calor."]],
    questoes: [
      { t: 0, id: "g-fter-t01", tipo: "calculo", variaveis: { l: { valores: [10, 20, 30, 50, 80, 100] }, dt: { min: 40, max: 200, passo: 10 } }, resposta: "12e-6*l*dt*1000", tolerancia: 0.1, unidade: "mm",
        pergunta: "Tubo de aço (α = 12 × 10⁻⁶/°C) de {l} m aquecido em {dt} °C. Quanto ele dilata (mm)? (1 casa)", resolucao: "ΔL = 12 × 10⁻⁶ × {l} × {dt} = {=12e-6*l*dt:4} m = {=12e-6*l*dt*1000:1} mm", explicacao: "Tubulações longas precisam de liras ou juntas de dilatação." },
      { t: 0, id: "g-fter-q01", tipo: "multipla", pergunta: "25 °C correspondem a quantos kelvin?", opcoes: ["25 K", "248,15 K", "298,15 K", "77 K"], correta: 2, explicacao: "K = °C + 273,15." },
      { t: 0, id: "g-fter-q02", tipo: "vf", pergunta: "Calor e temperatura são a mesma coisa.", correta: false, explicacao: "Temperatura é estado; calor é energia em trânsito." },
      { t: 1, id: "g-fter-t02", tipo: "calculo", variaveis: { m: { min: 100, max: 2000, passo: 100 }, ti: { valores: [15, 20, 25] }, tf: { valores: [60, 70, 80, 90] } }, resposta: "m*4.18*(tf-ti)/3600", tolerancia: 0.1, unidade: "kWh",
        pergunta: "Energia para aquecer {m} kg de água de {ti} °C para {tf} °C (c = 4,18 kJ/kg·°C), em kWh? (1 casa)", resolucao: "Q = {m} × 4,18 × {=tf-ti} = {=m*4.18*(tf-ti):0} kJ ÷ 3.600 = {=m*4.18*(tf-ti)/3600:1} kWh", explicacao: "Multiplique pela tarifa para ter o custo." },
      { t: 1, id: "g-fter-q03", tipo: "multipla", pergunta: "Durante a fusão do gelo a 0 °C, fornecendo calor, a temperatura:", opcoes: ["Sobe", "Fica constante até todo o gelo derreter", "Cai", "Oscila"], correta: 1, explicacao: "O calor vai para a mudança de fase (latente)." },
      { t: 1, id: "g-fter-q04", tipo: "vf", pergunta: "1 kWh equivale a 3.600 kJ.", correta: true, explicacao: "1 kW × 3.600 s = 3.600 kJ." },
      { t: 2, id: "g-fter-t03", tipo: "calculo", variaveis: { k: { valores: [0.025, 0.03, 0.04] }, a: { min: 20, max: 200, passo: 10 }, dt: { valores: [20, 25, 30, 40] }, e: { valores: [0.05, 0.1, 0.15, 0.2] } }, resposta: "k*a*dt/e", tolerancia: 0.5, unidade: "W",
        pergunta: "Parede isolada: k = {k} W/(m·K), espessura {e} m, área {a} m², diferença de temperatura {dt} °C. Qual o fluxo de calor (W)? (inteiro)", resolucao: "q = k·A·ΔT ÷ L = {k} × {a} × {dt} ÷ {e} = {=k*a*dt/e:0} W", explicacao: "Dobrar a espessura do isolante reduz o fluxo pela metade." },
      { t: 2, id: "g-fter-q05", tipo: "ligar", pergunta: "Ligue o mecanismo ao exemplo:", pares: [["Condução", "Calor atravessando a parede da câmara fria"], ["Convecção", "Ar do ventilador resfriando o bombom"], ["Radiação", "Calor do forno sentido à distância"]], explicacao: "Os três mecanismos de transferência de calor." },
      { t: 2, id: "g-fter-q06", tipo: "vf", pergunta: "Na radiação, a potência emitida é proporcional à quarta potência da temperatura absoluta.", correta: true, explicacao: "Lei de Stefan-Boltzmann." },
      { t: 3, id: "g-fter-t04", tipo: "calculo", variaveis: { tq: { valores: [400, 500, 600, 800] }, tf: { valores: [290, 300, 310] } }, resposta: "(1-tf/tq)*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Máquina térmica entre {tq} K e {tf} K. Qual o rendimento máximo teórico de Carnot (%)? (1 casa)", resolucao: "η = 1 − {tf} ÷ {tq} = {=(1-tf/tq)*100:1}%", explicacao: "Máquinas reais ficam abaixo desse limite." },
      { t: 3, id: "g-fter-q07", tipo: "multipla", pergunta: "O que a 2ª lei da termodinâmica afirma, entre outras coisas?", opcoes: ["A energia pode ser criada", "Nenhuma máquina converte todo o calor recebido em trabalho", "O calor flui do frio para o quente sozinho", "O rendimento pode passar de 100%"], correta: 1, explicacao: "Sempre há rejeição de calor para uma fonte fria." },
      { t: 3, id: "g-fter-q08", tipo: "vf", pergunta: "Um refrigerador com COP = 3 retira 3 kJ de calor para cada 1 kJ de trabalho consumido.", correta: true, explicacao: "COP pode ser maior que 1 (não é rendimento)." }
    ]
  },

  {
    id: "g-resmat", nome: "Resistência dos Materiais III", periodo: 4, area: "engenharia", icone: "🧱", prereq: ["g-mecger"],
    intro: "Estuda como peças e estruturas **resistem e se deformam** sob cargas: tensão, deformação, flexão, cisalhamento, torção e flambagem. O engenheiro de produção usa esses conceitos para avaliar **prateleiras, mezaninos, dispositivos e eixos**, entender especificações e coeficientes de segurança e dialogar com a engenharia de projeto.",
    topicos: [
      { t: "Tensão, deformação e Lei de Hooke", icone: "📏",
        pontos: ["**Tensão normal** σ = F ÷ A (Pa ou MPa = N/mm²).", "**Deformação** ε = ΔL ÷ L₀ (adimensional).", "**Lei de Hooke** (regime elástico): σ = E·ε; E é o **módulo de elasticidade** (aço ≈ 200 GPa; alumínio ≈ 70 GPa).", "**Diagrama tensão-deformação:** limite elástico, **escoamento** (σ_e), resistência máxima (σ_r) e ruptura.", "Materiais **dúcteis** deformam bastante antes de romper; **frágeis** rompem quase sem aviso."],
        formulas: [["σ = F ÷ A", "tensão normal"], ["ε = ΔL ÷ L₀", "deformação"], ["σ = E · ε ⇒ ΔL = F·L₀ ÷ (A·E)", "Lei de Hooke"]],
        producao: "Verificar tirantes, correntes, parafusos e hastes de dispositivos; entender por que um material dúctil “avisa” antes de romper (importante para segurança).",
        exemplo: "Barra de aço com 100 mm², carga de 10 kN: σ = 10.000 ÷ 100 = **100 MPa**. Com 2 m: ΔL = 100 × 2.000 ÷ 200.000 = **1 mm**." },
      { t: "Coeficiente de segurança e cisalhamento", icone: "🛡️",
        pontos: ["**Tensão admissível** σ_adm = σ_e ÷ CS (coeficiente de segurança > 1).", "O CS cobre incertezas de carga, material, fabricação e modelo; normas indicam valores mínimos por aplicação.", "**Cisalhamento:** τ = V ÷ A (pinos, parafusos, rebites, soldas).", "Pino em **cisalhamento duplo** divide a força entre duas seções: τ = V ÷ (2A)."],
        formulas: [["σ_adm = σ_e ÷ CS", "tensão admissível"], ["τ = V ÷ A", "tensão de cisalhamento média"], ["CS = σ_e ÷ σ_atuante", "coeficiente de segurança da peça"]],
        producao: "Dimensionar pinos de dispositivos e ganchos, verificar se uma peça improvisada (ex.: suporte soldado) é segura antes de liberar o uso.",
        exemplo: "Aço com σ_e = 250 MPa e CS = 2: σ_adm = **125 MPa**. Um pino de 10 mm (A ≈ 78,5 mm²) em cisalhamento simples com 5 kN: τ ≈ **63,7 MPa**." },
      { t: "Flexão de vigas", icone: "🌉",
        pontos: ["Cargas transversais geram **esforço cortante** e **momento fletor** ao longo da viga.", "Viga bi-apoiada com carga central P: momento máximo M = P·L ÷ 4 (no meio).", "**Tensão de flexão:** σ = M·c ÷ I (máxima nas fibras mais afastadas da linha neutra).", "Seção retangular: I = b·h³ ÷ 12 — **dobrar a altura** aumenta a rigidez 8 vezes.", "**Flecha** (deslocamento) limita o uso mesmo sem ruptura (prateleiras “embarrigando”)."],
        formulas: [["σ = M · c ÷ I", "tensão de flexão; c = distância à linha neutra"], ["I = b · h³ ÷ 12", "momento de inércia da seção retangular"], ["M_máx = P·L ÷ 4", "viga bi-apoiada com carga no centro"], ["flecha = P·L³ ÷ (48·E·I)", "flecha no centro (mesmo caso)"]],
        producao: "Carga admissível de vigas de porta-paletes e prateleiras, perfis de mezaninos e bancadas; posicionar perfis “em pé” (maior h) aumenta muito a resistência.",
        exemplo: "Tábua 20 × 2 cm: deitada, I = 20 × 2³ ÷ 12 ≈ 13,3 cm⁴; em pé, I = 2 × 20³ ÷ 12 ≈ **1.333 cm⁴** (100 vezes mais rígida)." },
      { t: "Torção e flambagem", icone: "🌀",
        pontos: ["**Torção** em eixos: τ = T·r ÷ J; para eixo maciço, J = π·d⁴ ÷ 32.", "Relação potência-torque: P = T·ω (motor e eixo).", "**Flambagem:** colunas esbeltas comprimidas perdem estabilidade antes de atingir a tensão de escoamento.", "**Carga crítica de Euler:** P_cr = π²·E·I ÷ (K·L)² — dobrar o comprimento reduz a carga crítica a 1/4.", "O tipo de apoio nas extremidades muda o fator K."],
        formulas: [["τ = T · r ÷ J; J = π·d⁴ ÷ 32", "torção em eixo maciço"], ["P = T · ω", "potência transmitida pelo eixo"], ["P_cr = π²·E·I ÷ (K·L)²", "carga crítica de flambagem (Euler)"]],
        producao: "Eixos de transportadores e redutores (torção), colunas de mezaninos e montantes de porta-paletes (flambagem): um montante amassado por empilhadeira perde muita capacidade.",
        exemplo: "Motor de 5 kW a 1.750 rpm (≈ 183 rad/s): torque T = 5.000 ÷ 183 ≈ **27,3 N·m**." }
    ],
    glossario: [["Tensão normal", "Força perpendicular por unidade de área."], ["Deformação", "Variação relativa de comprimento."], ["Módulo de elasticidade", "Rigidez do material no regime elástico (E)."], ["Escoamento", "Início da deformação plástica permanente."], ["Coeficiente de segurança", "Razão entre resistência e solicitação."], ["Cisalhamento", "Tensão tangencial ao plano da seção."], ["Momento fletor", "Esforço interno que flexiona a viga."], ["Momento de inércia", "Propriedade geométrica que mede a resistência da seção à flexão."], ["Flecha", "Deslocamento transversal da viga."], ["Flambagem", "Instabilidade de peças esbeltas comprimidas."]],
    questoes: [
      { t: 0, id: "g-rmat-t01", tipo: "calculo", variaveis: { f: { min: 5, max: 50, passo: 5 }, a: { valores: [50, 78.5, 100, 150, 200] } }, resposta: "f*1000/a", tolerancia: 0.1, unidade: "MPa",
        pergunta: "Uma barra com seção de {a} mm² suporta {f} kN de tração. Qual a tensão normal (MPa)? (1 casa)", resolucao: "σ = {f} × 1.000 N ÷ {a} mm² = {=f*1000/a:1} MPa", explicacao: "1 MPa = 1 N/mm²." },
      { t: 0, id: "g-rmat-q01", tipo: "vf", pergunta: "Materiais dúcteis costumam deformar visivelmente antes de romper, o que dá aviso de falha.", correta: true, explicacao: "Frágeis rompem quase sem deformação." },
      { t: 0, id: "g-rmat-q02", tipo: "multipla", pergunta: "O módulo de elasticidade do aço é aproximadamente:", opcoes: ["2 GPa", "70 GPa", "200 GPa", "2.000 GPa"], correta: 2, explicacao: "O alumínio tem cerca de 70 GPa." },
      { t: 1, id: "g-rmat-t02", tipo: "calculo", variaveis: { se: { valores: [235, 250, 275, 350] }, cs: { valores: [1.5, 2, 2.5, 3] } }, resposta: "se/cs", tolerancia: 0.1, unidade: "MPa",
        pergunta: "Material com tensão de escoamento de {se} MPa e coeficiente de segurança {cs}. Qual a tensão admissível (MPa)? (1 casa)", resolucao: "σ_adm = {se} ÷ {cs} = {=se/cs:1} MPa", explicacao: "O CS cobre incertezas." },
      { t: 1, id: "g-rmat-q03", tipo: "multipla", pergunta: "Um pino em cisalhamento duplo, comparado ao simples com a mesma carga, tem tensão:", opcoes: ["O dobro", "A metade", "Igual", "Zero"], correta: 1, explicacao: "Duas seções dividem a força." },
      { t: 1, id: "g-rmat-q04", tipo: "vf", pergunta: "Um coeficiente de segurança menor que 1 indica que a peça é segura.", correta: false, explicacao: "CS < 1: a solicitação supera a resistência." },
      { t: 2, id: "g-rmat-t03", tipo: "calculo", variaveis: { b: { valores: [2, 3, 4, 5] }, h: { valores: [5, 8, 10, 12, 15, 20] } }, resposta: "b*pow(h,3)/12", tolerancia: 0.01, unidade: "cm⁴",
        pergunta: "Qual o momento de inércia de uma seção retangular com base b = {b} cm e altura h = {h} cm? (2 casas)", resolucao: "I = b·h³ ÷ 12 = {b} × {h}³ ÷ 12 = {=b*pow(h,3)/12:2} cm⁴", explicacao: "A altura entra ao cubo." },
      { t: 2, id: "g-rmat-q05", tipo: "multipla", pergunta: "Para aumentar muito a rigidez de uma prateleira de madeira sem trocar o material, o mais eficaz é:", opcoes: ["Aumentar a largura", "Aumentar a altura (espessura) da seção ou usar o perfil “em pé”", "Pintar", "Diminuir o comprimento dos parafusos"], correta: 1, explicacao: "I = b·h³/12." },
      { t: 2, id: "g-rmat-t04", tipo: "calculo", variaveis: { p: { min: 1, max: 20 }, l: { valores: [1, 1.5, 2, 2.5, 3, 4] } }, resposta: "p*l/4", tolerancia: 0.01, unidade: "kN·m",
        pergunta: "Viga bi-apoiada de {l} m com carga concentrada de {p} kN no centro. Qual o momento fletor máximo (kN·m)? (2 casas)", resolucao: "M = P·L ÷ 4 = {p} × {l} ÷ 4 = {=p*l/4:2} kN·m", explicacao: "Ocorre no meio do vão." },
      { t: 3, id: "g-rmat-t05", tipo: "calculo", variaveis: { p: { valores: [2.2, 3.7, 5.5, 7.5, 11, 15] }, rpm: { valores: [900, 1150, 1750, 3500] } }, resposta: "p*1000/(2*PI*rpm/60)", tolerancia: 0.1, unidade: "N·m",
        pergunta: "Motor de {p} kW a {rpm} rpm. Qual o torque no eixo (N·m)? (1 casa)", resolucao: "ω = 2π × {rpm} ÷ 60 = {=2*PI*rpm/60:1} rad/s\nT = P ÷ ω = {=p*1000} ÷ {=2*PI*rpm/60:1} = {=p*1000/(2*PI*rpm/60):1} N·m", explicacao: "Mesma potência com menos rotação = mais torque." },
      { t: 3, id: "g-rmat-q06", tipo: "multipla", pergunta: "Se o comprimento de uma coluna dobra (mesma seção e apoios), a carga crítica de flambagem:", opcoes: ["Dobra", "Cai pela metade", "Cai para 1/4", "Não muda"], correta: 2, explicacao: "P_cr ∝ 1/L²." },
      { t: 3, id: "g-rmat-q07", tipo: "vf", pergunta: "Um montante de porta-paletes amassado por uma batida de empilhadeira pode perder muita capacidade de carga por flambagem.", correta: true, explicacao: "Defeitos geométricos reduzem a resistência à flambagem; inspecione e substitua." }
    ]
  },

  {
    id: "g-eletron", nome: "Eletricidade/Eletrônica", periodo: 4, area: "engenharia", icone: "🔋", prereq: ["g-eletbas"],
    intro: "Aplica a eletricidade à fábrica: **motores elétricos**, formas de **partida e acionamento** (incluindo inversores de frequência, que economizam energia), componentes eletrônicos, **sensores** e **CLPs** que automatizam máquinas e linhas.",
    topicos: [
      { t: "Motores elétricos", icone: "⚙️",
        pontos: ["O **motor de indução trifásico** é o mais usado na indústria: robusto, barato, pouca manutenção.", "**Rotação síncrona:** n_s = 120·f ÷ p (f = frequência; p = nº de polos).", "O rotor gira um pouco abaixo da síncrona: **escorregamento** s = (n_s − n) ÷ n_s.", "**Placa do motor:** potência, tensão, corrente, rotação, rendimento, fator de potência, fator de serviço, grau de proteção (IP).", "Motores de **alto rendimento** reduzem o custo de energia ao longo da vida útil."],
        formulas: [["n_s = 120 · f ÷ p", "rotação síncrona (rpm)"], ["s = (n_s − n) ÷ n_s", "escorregamento"], ["η = P_mecânica ÷ P_elétrica", "rendimento do motor"]],
        producao: "Escolher motores com potência adequada (motor superdimensionado trabalha com baixo rendimento e baixo FP) e ler dados de placa para a manutenção.",
        exemplo: "Motor de 4 polos em 60 Hz: n_s = 120 × 60 ÷ 4 = **1.800 rpm**; girando a 1.750 rpm, s ≈ **2,8%**." },
      { t: "Partida e acionamento", icone: "🚦",
        pontos: ["**Partida direta:** simples, mas a corrente de partida pode ser várias vezes a nominal.", "**Estrela-triângulo:** reduz a corrente de partida (motores que partem com pouca carga).", "**Soft-starter:** partida e parada suaves por controle eletrônico da tensão.", "**Inversor de frequência:** varia a frequência e, portanto, a velocidade do motor.", "Em bombas e ventiladores, a potência varia com o **cubo da rotação** (leis de afinidade): reduzir 20% da velocidade reduz ~49% da potência."],
        formulas: [["P₂ ÷ P₁ = (n₂ ÷ n₁)³", "lei de afinidade (bombas e ventiladores)"], ["Q₂ ÷ Q₁ = n₂ ÷ n₁", "vazão proporcional à rotação"]],
        producao: "Trocar o controle de vazão por válvula estrangulada por um **inversor** é uma das ações de eficiência energética de maior retorno; soft-starters reduzem choques mecânicos em esteiras.",
        exemplo: "Ventilador de 20 kW reduzido a 80% da rotação: P ≈ 20 × 0,8³ = **10,2 kW**." },
      { t: "Eletrônica básica", icone: "🔌",
        pontos: ["**Diodo:** conduz em um só sentido; usado em **retificadores** (CA → CC).", "**Transistor:** funciona como **chave** ou amplificador; base de toda a eletrônica digital.", "**Relé e contator:** chaves acionadas eletricamente (baixa potência comandando alta potência).", "**Sinais analógicos** (contínuos, ex.: 4–20 mA) × **digitais** (0/1).", "Fontes, conversores e eletrônica de potência (inversores) usam esses componentes."],
        formulas: [["Sinal 4–20 mA: valor = mín + (I − 4) ÷ 16 × (máx − mín)", "conversão do sinal padrão de instrumentação"]],
        producao: "Entender o painel de uma máquina: contatores, relés, fontes e sinais de sensores; diagnosticar falhas simples com a manutenção.",
        exemplo: "Transmissor de temperatura 0–200 °C em 4–20 mA marcando 12 mA: T = (12 − 4) ÷ 16 × 200 = **100 °C**." },
      { t: "Sensores, CLP e automação", icone: "🤖",
        pontos: ["**Sensores:** indutivos (metal), capacitivos (quase qualquer material), fotoelétricos, de temperatura (termopar, PT100), pressão, nível, encoders (posição/velocidade).", "**Atuadores:** motores, cilindros pneumáticos, válvulas.", "**CLP** (controlador lógico programável): lê entradas, executa o programa (ex.: **ladder**) e aciona saídas, num ciclo de varredura.", "**Supervisório (SCADA/IHM):** interface para operação e coleta de dados.", "Segurança de máquinas (NR-12): sensores e circuitos de segurança específicos."],
        formulas: [["Ciclo do CLP: ler entradas → executar programa → atualizar saídas", "varredura (scan)"]],
        producao: "Automação reduz variabilidade e esforço; os dados do CLP alimentam OEE, rastreabilidade e Indústria 4.0 (Módulo 14).",
        exemplo: "Esteira: sensor fotoelétrico detecta a caixa → CLP para a esteira → cilindro empurra a caixa para o palete → esteira volta a andar." }
    ],
    glossario: [["Motor de indução", "Motor CA em que o campo girante induz corrente no rotor."], ["Rotação síncrona", "Velocidade do campo girante: 120f/p."], ["Escorregamento", "Diferença relativa entre rotação síncrona e real."], ["Inversor de frequência", "Equipamento que varia a velocidade do motor pela frequência."], ["Soft-starter", "Dispositivo de partida suave."], ["Leis de afinidade", "Relações entre rotação, vazão e potência em bombas/ventiladores."], ["Diodo", "Componente que conduz num só sentido."], ["Transistor", "Componente que atua como chave ou amplificador."], ["Contator", "Chave eletromagnética para cargas de potência."], ["CLP", "Controlador lógico programável."], ["Ladder", "Linguagem de programação de CLP em forma de diagrama de contatos."]],
    questoes: [
      { t: 0, id: "g-eltr-t01", tipo: "calculo", variaveis: { p: { valores: [2, 4, 6, 8] }, f: { valores: [50, 60] } }, resposta: "120*f/p", tolerancia: 0, unidade: "rpm",
        pergunta: "Qual a rotação síncrona de um motor de {p} polos alimentado em {f} Hz?", resolucao: "n_s = 120 × {f} ÷ {p} = {=120*f/p} rpm", explicacao: "O motor real gira um pouco abaixo (escorregamento)." },
      { t: 0, id: "g-eltr-q01", tipo: "vf", pergunta: "Um motor muito superdimensionado para a carga tende a operar com rendimento e fator de potência mais baixos.", correta: true, explicacao: "Motores rendem melhor perto da carga nominal." },
      { t: 0, id: "g-eltr-q02", tipo: "multipla", pergunta: "Qual o tipo de motor mais usado na indústria?", opcoes: ["Motor de passo", "Motor de indução trifásico", "Motor de corrente contínua", "Motor a vapor"], correta: 1, explicacao: "Robusto, barato e de baixa manutenção." },
      { t: 1, id: "g-eltr-t02", tipo: "calculo", variaveis: { p: { valores: [10, 15, 20, 30, 45] }, fr: { valores: [0.6, 0.7, 0.75, 0.8, 0.9] } }, resposta: "p*pow(fr,3)", tolerancia: 0.1, unidade: "kW",
        pergunta: "Bomba de {p} kW passa a operar com {=fr*100}% da rotação (inversor). Potência aproximada pela lei de afinidade (kW)? (1 casa)", resolucao: "P₂ = {p} × {fr}³ = {=p*pow(fr,3):1} kW", explicacao: "Potência ∝ rotação ao cubo." },
      { t: 1, id: "g-eltr-q03", tipo: "multipla", pergunta: "Qual equipamento permite variar a velocidade de um motor de indução?", opcoes: ["Contator", "Inversor de frequência", "Disjuntor", "Fusível"], correta: 1, explicacao: "Variando a frequência, varia a rotação." },
      { t: 1, id: "g-eltr-q04", tipo: "vf", pergunta: "A partida direta de um motor de indução pode gerar corrente várias vezes maior que a nominal.", correta: true, explicacao: "Por isso existem partidas suaves e estrela-triângulo." },
      { t: 2, id: "g-eltr-t03", tipo: "calculo", variaveis: { i: { min: 5, max: 19 }, vmax: { valores: [100, 150, 200, 300, 500] } }, resposta: "(i-4)/16*vmax", tolerancia: 0.1, unidade: "",
        pergunta: "Um transmissor de 0 a {vmax} (unidade de engenharia) em 4–20 mA está enviando {i} mA. Qual o valor medido? (1 casa)", resolucao: "valor = ({i} − 4) ÷ 16 × {vmax} = {=(i-4)/16*vmax:1}", explicacao: "4 mA = zero; 20 mA = fundo de escala." },
      { t: 2, id: "g-eltr-q05", tipo: "multipla", pergunta: "Qual componente transforma corrente alternada em contínua?", opcoes: ["Transistor como amplificador", "Retificador com diodos", "Contator", "Resistor"], correta: 1, explicacao: "Diodos conduzem num só sentido." },
      { t: 2, id: "g-eltr-q06", tipo: "vf", pergunta: "O sinal 4–20 mA usa 4 mA como zero para permitir detectar fio rompido (0 mA).", correta: true, explicacao: "Zero “vivo” facilita o diagnóstico." },
      { t: 3, id: "g-eltr-q07", tipo: "ligar", pergunta: "Ligue o sensor ao que ele detecta melhor:", pares: [["Indutivo", "Peças metálicas próximas"], ["Fotoelétrico", "Passagem de caixas na esteira"], ["PT100", "Temperatura"], ["Encoder", "Posição e velocidade de eixos"]], explicacao: "Escolha pelo material e pela grandeza." },
      { t: 3, id: "g-eltr-q08", tipo: "ordenar", pergunta: "Ordene o ciclo de varredura do CLP:", itens: ["Ler as entradas", "Executar o programa", "Atualizar as saídas"], explicacao: "Repete continuamente, em milissegundos." },
      { t: 3, id: "g-eltr-q09", tipo: "multipla", pergunta: "Qual norma regulamentadora trata da segurança em máquinas e equipamentos?", opcoes: ["NR-10", "NR-12", "NR-17", "NR-35"], correta: 1, explicacao: "NR-10: eletricidade; NR-17: ergonomia; NR-35: trabalho em altura." }
    ]
  },

  {
    id: "g-metest", nome: "Métodos Estatísticos", periodo: 4, area: "exatas", icone: "🧪", prereq: ["g-edo", "g-estat"], relacionado: ["m13"],
    intro: "Ferramentas para **decidir com dados**: testar se uma melhoria funcionou, comparar máquinas e fornecedores, modelar relações com **regressão** e planejar **experimentos (DOE)** para descobrir quais fatores do processo importam. É a base estatística do Seis Sigma.",
    topicos: [
      { t: "Testes de hipóteses", icone: "⚖️",
        pontos: ["**H₀** (hipótese nula: não há efeito/diferença) × **H₁** (alternativa).", "**Nível de significância α** (ex.: 5%): risco aceito de rejeitar H₀ verdadeira (**erro tipo I**).", "**Erro tipo II (β):** não rejeitar H₀ falsa; **poder** = 1 − β.", "**p-valor:** probabilidade de observar um resultado tão extremo se H₀ fosse verdadeira; se p < α, rejeita-se H₀.", "Significância estatística ≠ importância prática."],
        formulas: [["Z = (x̄ − μ₀) ÷ (σ/√n)", "teste para a média com σ conhecido"], ["t = (x̄ − μ₀) ÷ (s/√n)", "teste t com n − 1 graus de liberdade"], ["p < α ⇒ rejeita H₀", "regra de decisão"]],
        producao: "Verificar se o peso médio das caixas está no alvo, se uma mudança de método reduziu o tempo e se um novo fornecedor mudou a qualidade.",
        exemplo: "Alvo 250 g; amostra n = 36, x̄ = 251,2 g, σ = 3 g: Z = 1,2 ÷ 0,5 = **2,4** > 1,96 ⇒ rejeita H₀ (média fora do alvo a 5%)." },
      { t: "Comparação de grupos e ANOVA", icone: "📊",
        pontos: ["**Teste t para duas amostras independentes:** compara médias de dois grupos (ex.: máquina A × B).", "**Teste t pareado:** mesmos itens antes e depois (ex.: tempo antes × depois do treinamento).", "**ANOVA:** compara três ou mais médias ao mesmo tempo, pela razão F entre variação entre grupos e dentro dos grupos.", "Pressupostos: independência, normalidade aproximada e variâncias semelhantes.", "Comparar muitos pares com testes t separados aumenta o erro tipo I; por isso a ANOVA."],
        formulas: [["F = QM_entre ÷ QM_dentro", "estatística da ANOVA"], ["t = d̄ ÷ (s_d/√n)", "teste t pareado (d = diferenças)"]],
        producao: "Comparar três turnos, quatro fornecedores ou cinco receitas; avaliar treinamentos e melhorias com dados antes/depois.",
        exemplo: "Três fornecedores de cacau com rendimentos médios 92%, 93% e 88%: a ANOVA indica se a diferença é real ou pode ser acaso." },
      { t: "Correlação e regressão", icone: "📈",
        pontos: ["**Correlação r** (−1 a 1): força e sentido da relação linear.", "**Regressão linear:** ŷ = a + b·x, por mínimos quadrados.", "**R²:** fração da variação de y explicada pelo modelo.", "Analisar **resíduos**: devem ser aleatórios, sem padrão.", "**Regressão múltipla:** vários x ao mesmo tempo; cuidado com correlação entre os x (multicolinearidade)."],
        formulas: [["b = Σ(x − x̄)(y − ȳ) ÷ Σ(x − x̄)²", "inclinação"], ["a = ȳ − b·x̄", "intercepto"], ["R² = 1 − SQ_res ÷ SQ_total", "coeficiente de determinação"]],
        producao: "Modelar o tempo de setup em função do número de ferramentas, o consumo de energia em função da produção e a demanda em função do preço.",
        exemplo: "Energia (kWh) = 1.200 + 0,8 × caixas produzidas, R² = 0,86: cada caixa a mais consome ≈ 0,8 kWh; 86% da variação é explicada pela produção." },
      { t: "Planejamento de experimentos (DOE)", icone: "🧫",
        pontos: ["**DOE:** variar fatores de forma planejada para descobrir seus efeitos com poucos ensaios.", "**Fatorial 2ᵏ:** k fatores, cada um em dois níveis (−/+); 2² = 4 ensaios, 2³ = 8.", "**Efeito principal** de A = média com A no nível + menos média com A no nível −.", "**Interação:** o efeito de um fator depende do nível do outro.", "Princípios: **aleatorização**, **replicação** e **blocagem**. Mudar um fator de cada vez desperdiça ensaios e não detecta interações."],
        formulas: [["Efeito(A) = ȳ(A+) − ȳ(A−)", "efeito principal"], ["Nº de ensaios = 2ᵏ", "fatorial completo com k fatores"]],
        producao: "Descobrir a combinação de temperatura, tempo e velocidade que maximiza o rendimento ou minimiza defeitos, com poucos testes (fase Analisar/Melhorar do DMAIC).",
        exemplo: "Temperatura (A) e tempo (B), rendimento: (−,−) 80; (+,−) 90; (−,+) 82; (+,+) 96. Efeito de A = (90 + 96)/2 − (80 + 82)/2 = **12 pontos**." }
    ],
    glossario: [["Hipótese nula", "Afirmação de ausência de efeito ou diferença."], ["Erro tipo I", "Rejeitar H₀ quando ela é verdadeira (α)."], ["Erro tipo II", "Não rejeitar H₀ quando ela é falsa (β)."], ["p-valor", "Probabilidade de um resultado tão extremo se H₀ for verdadeira."], ["Teste t pareado", "Compara medidas antes e depois nos mesmos itens."], ["ANOVA", "Análise de variância; compara várias médias."], ["Correlação", "Medida da relação linear entre duas variáveis."], ["R²", "Fração da variação explicada pelo modelo."], ["DOE", "Planejamento de experimentos."], ["Interação", "Quando o efeito de um fator depende do nível de outro."]],
    questoes: [
      { t: 0, id: "g-mest-t01", tipo: "calculo", variaveis: { mu: { valores: [250, 500, 1000] }, dx: { valores: [-2, -1.5, -1, 0.5, 1, 1.5, 2] }, s: { valores: [2, 3, 4, 5] }, n: { valores: [16, 25, 36, 64] } }, resposta: "dx/(s/sqrt(n))", tolerancia: 0.01, unidade: "",
        pergunta: "Alvo μ₀ = {mu} g; amostra n = {n}, média {=mu+dx} g, σ = {s} g. Qual o valor de Z? (2 casas)", resolucao: "Z = ({=mu+dx} − {mu}) ÷ ({s}/√{n}) = {dx} ÷ {=s/sqrt(n):3} = {=dx/(s/sqrt(n)):2}", explicacao: "Se |Z| > 1,96, rejeita-se H₀ a 5% (bilateral)." },
      { t: 0, id: "g-mest-q01", tipo: "multipla", pergunta: "O p-valor de um teste deu 0,003 com α = 0,05. A decisão é:", opcoes: ["Não rejeitar H₀", "Rejeitar H₀", "Aumentar α", "Repetir até dar maior"], correta: 1, explicacao: "p < α." },
      { t: 0, id: "g-mest-q02", tipo: "ligar", pergunta: "Ligue o erro à definição:", pares: [["Erro tipo I", "Rejeitar H₀ verdadeira"], ["Erro tipo II", "Não rejeitar H₀ falsa"], ["Poder do teste", "Probabilidade de detectar um efeito real"]], explicacao: "α, β e 1 − β." },
      { t: 1, id: "g-mest-q03", tipo: "multipla", pergunta: "Você mediu o tempo de montagem das mesmas 15 pessoas antes e depois de um treinamento. Qual teste usar?", opcoes: ["t para amostras independentes", "t pareado", "ANOVA com 15 grupos", "Nenhum"], correta: 1, explicacao: "As medidas são das mesmas pessoas." },
      { t: 1, id: "g-mest-q04", tipo: "vf", pergunta: "Para comparar as médias de quatro fornecedores, a ANOVA é preferível a fazer vários testes t entre pares.", correta: true, explicacao: "Evita inflar o erro tipo I." },
      { t: 1, id: "g-mest-t02", tipo: "calculo", variaveis: { qe: { min: 20, max: 200, passo: 5 }, qd: { min: 5, max: 40 } }, resposta: "qe/qd", tolerancia: 0.01, unidade: "",
        pergunta: "Numa ANOVA, o quadrado médio entre grupos é {qe} e dentro dos grupos é {qd}. Qual a estatística F? (2 casas)", resolucao: "F = {qe} ÷ {qd} = {=qe/qd:2}", explicacao: "F grande sugere diferença entre as médias (compare com o F crítico)." },
      { t: 2, id: "g-mest-t03", tipo: "calculo", variaveis: { a: { min: 500, max: 2000, passo: 100 }, b: { valores: [0.5, 0.6, 0.8, 1, 1.2] }, x: { min: 1000, max: 8000, passo: 500 } }, resposta: "a+b*x", tolerancia: 0.01, unidade: "kWh",
        pergunta: "Modelo: energia = {a} + {b} × caixas. Qual a energia prevista para {x} caixas (kWh)?", resolucao: "{a} + {b} × {x} = {=a+b*x} kWh", explicacao: "Use o modelo só dentro da faixa observada." },
      { t: 2, id: "g-mest-q05", tipo: "multipla", pergunta: "Uma regressão com R² = 0,86 indica que:", opcoes: ["86% dos pontos estão sobre a reta", "86% da variação de y é explicada pelo modelo", "A correlação é 0,86", "O erro é 14 unidades"], correta: 1, explicacao: "r seria √0,86 ≈ 0,93." },
      { t: 2, id: "g-mest-q06", tipo: "vf", pergunta: "Se os resíduos da regressão mostram um padrão em forma de curva, o modelo linear pode não ser adequado.", correta: true, explicacao: "Resíduos devem parecer aleatórios." },
      { t: 3, id: "g-mest-t04", tipo: "calculo", variaveis: { y1: { min: 70, max: 85 }, y2: { min: 80, max: 95 }, y3: { min: 70, max: 88 }, y4: { min: 85, max: 99 } }, resposta: "(y2+y4)/2-(y1+y3)/2", tolerancia: 0.01, unidade: "pontos",
        pergunta: "Fatorial 2²: (A−,B−) = {y1}; (A+,B−) = {y2}; (A−,B+) = {y3}; (A+,B+) = {y4}. Qual o efeito principal de A? (2 casas)", resolucao: "Efeito(A) = ({y2} + {y4})/2 − ({y1} + {y3})/2 = {=(y2+y4)/2:2} − {=(y1+y3)/2:2} = {=(y2+y4)/2-(y1+y3)/2:2}", explicacao: "Média no nível + menos média no nível −." },
      { t: 3, id: "g-mest-q07", tipo: "multipla", pergunta: "Quantos ensaios tem um fatorial completo 2³ (sem réplicas)?", opcoes: ["3", "6", "8", "9"], correta: 2, explicacao: "2³ = 8." },
      { t: 3, id: "g-mest-q08", tipo: "vf", pergunta: "Mudar um fator de cada vez é a forma mais eficiente de descobrir interações entre fatores.", correta: false, explicacao: "Não detecta interações; o DOE fatorial detecta." }
    ]
  }
);
