/* =====================================================================
   GRADE CURRICULAR — 5º PERÍODO (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-cienamb", codigo: "GEXT-7201", nome: "Ciências do Ambiente", periodo: 5, area: "engenharia", icone: "🌱", creditos: "(2-0-0) 2 créditos", prereq: ["g-quimica"],
    intro: "Toda produção retira recursos da natureza e devolve resíduos, efluentes e emissões. Esta disciplina dá a base científica — ecossistemas, ciclos, poluição, clima e legislação — para o engenheiro de produção **reduzir impactos**, cumprir a lei e enxergar oportunidades (menos desperdício de água, energia e material).",
    topicos: [
      { t: "Ecossistemas e ciclos", icone: "♻️",
        pontos: ["**Ecossistema:** seres vivos + meio físico, ligados por fluxos de **energia** (em uma direção) e **matéria** (em ciclos).", "**Ciclos biogeoquímicos:** água, carbono, nitrogênio, fósforo.", "**Capacidade de suporte:** o ambiente tem limite para absorver resíduos e fornecer recursos.", "**Serviços ecossistêmicos:** água limpa, polinização, regulação do clima, matérias-primas.", "Indústria como sistema: analogia da **ecologia industrial** (resíduo de um processo = insumo de outro)."],
        formulas: [["Entrada = saída + acúmulo", "balanço de massa aplicado a recursos e poluentes"]],
        producao: "Pensar a fábrica em ciclos (água de reúso, subprodutos vendidos, embalagens retornáveis) reduz custo e impacto.",
        exemplo: "A casca de cacau descartada por uma fábrica de chocolate pode virar insumo para ração ou adubo em outra empresa (simbiose industrial)." },
      { t: "Poluição do ar, da água e do solo", icone: "🏭",
        pontos: ["**Ar:** material particulado, óxidos de enxofre e nitrogênio, monóxido de carbono, compostos orgânicos voláteis.", "**Água:** matéria orgânica (medida pela **DBO**), nutrientes (eutrofização), metais, óleos, temperatura.", "**Solo:** resíduos mal dispostos, vazamentos de combustíveis e químicos.", "**DBO** (demanda bioquímica de oxigênio): oxigênio consumido por microrganismos para degradar a matéria orgânica; quanto maior, mais poluente.", "Controle: tratar **na fonte** é mais barato que remediar."],
        formulas: [["Carga = concentração × vazão", "ex.: kg de DBO por dia lançados"], ["Eficiência de remoção = (entrada − saída) ÷ entrada", "desempenho de uma estação de tratamento"]],
        producao: "Efluentes de lavagem (CIP) em indústrias de alimentos têm alta DBO; reduzir perdas de produto na lavagem reduz a carga e o custo de tratamento.",
        exemplo: "Efluente com DBO de 2.000 mg/L e vazão de 50 m³/dia: carga = 2 kg/m³ × 50 = **100 kg de DBO/dia**." },
      { t: "Energia e mudanças climáticas", icone: "🌡️",
        pontos: ["**Efeito estufa:** gases (CO₂, CH₄, N₂O…) retêm calor; o aumento da concentração pela atividade humana aquece o planeta.", "**CO₂ equivalente (CO₂e):** soma das emissões ponderadas pelo potencial de aquecimento de cada gás.", "Fontes na indústria: combustíveis, eletricidade, processos, transporte, resíduos.", "**Inventário de emissões** (ex.: GHG Protocol): escopo 1 (diretas), escopo 2 (energia comprada), escopo 3 (cadeia).", "Redução: eficiência energética, fontes renováveis, logística otimizada."],
        formulas: [["Emissão = atividade × fator de emissão", "ex.: litros de diesel × kg CO₂ por litro"], ["CO₂e = Σ massa do gás × potencial de aquecimento (GWP)", "soma ponderada dos gases"]],
        producao: "Clientes e investidores pedem inventário de emissões; eficiência energética reduz custo e emissões ao mesmo tempo.",
        exemplo: "Frota interna consome 1.000 L de diesel/mês. Com fator aproximado de 2,6 kg CO₂/L: **≈ 2,6 t CO₂/mês** (escopo 1)." },
      { t: "Legislação e licenciamento", icone: "📜",
        pontos: ["**Política Nacional do Meio Ambiente** (Lei 6.938/1981): instrumentos como licenciamento e avaliação de impactos.", "**Licenciamento ambiental:** licença prévia (LP), de instalação (LI) e de operação (LO).", "**CONAMA** e órgãos estaduais definem padrões (ex.: lançamento de efluentes).", "**Lei de Crimes Ambientais** (Lei 9.605/1998) prevê sanções para pessoas físicas e jurídicas.", "**Política Nacional de Resíduos Sólidos** (Lei 12.305/2010): hierarquia de resíduos e logística reversa."],
        formulas: [],
        producao: "Ampliar a fábrica ou instalar um novo processo pode exigir renovar ou alterar a licença; operar sem licença é crime ambiental.",
        exemplo: "Antes de instalar uma nova caldeira, a empresa consulta o órgão ambiental sobre a necessidade de licença e os limites de emissão." }
    ],
    glossario: [["Ecossistema", "Conjunto de seres vivos e meio físico interagindo."], ["Ciclo biogeoquímico", "Circulação de um elemento entre seres vivos e ambiente."], ["Ecologia industrial", "Visão da indústria como ecossistema, com troca de materiais e energia."], ["DBO", "Demanda bioquímica de oxigênio: medida de matéria orgânica na água."], ["Eutrofização", "Excesso de nutrientes que provoca crescimento de algas e falta de oxigênio."], ["CO₂ equivalente", "Emissões de gases expressas em CO₂ pelo potencial de aquecimento."], ["Escopo 1, 2 e 3", "Classificação das emissões: diretas, energia comprada e cadeia de valor."], ["Licenciamento ambiental", "Processo de autorização de atividades potencialmente poluidoras (LP, LI, LO)."], ["Logística reversa", "Retorno de produtos e embalagens após o consumo."]],
    questoes: [
      { t: 0, id: "g-camb-q01", tipo: "vf", pergunta: "Nos ecossistemas, a energia flui em uma direção, enquanto a matéria circula em ciclos.", correta: true, explicacao: "A energia se dissipa como calor; a matéria é reciclada." },
      { t: 0, id: "g-camb-q02", tipo: "multipla", pergunta: "Usar o resíduo de uma empresa como matéria-prima de outra é exemplo de:", opcoes: ["Eutrofização", "Simbiose industrial (ecologia industrial)", "Efeito estufa", "Licença prévia"], correta: 1, explicacao: "Fecha ciclos de materiais." },
      { t: 0, id: "g-camb-q03", tipo: "ligar", pergunta: "Ligue o ciclo a um exemplo de interferência industrial:", pares: [["Carbono", "Queima de combustíveis fósseis"], ["Água", "Captação e lançamento de efluentes"], ["Nitrogênio/fósforo", "Nutrientes em efluentes causando eutrofização"]], explicacao: "A indústria altera vários ciclos." },
      { t: 1, id: "g-camb-t01", tipo: "calculo", variaveis: { dbo: { min: 500, max: 5000, passo: 100 }, q: { min: 10, max: 200, passo: 10 } }, resposta: "dbo/1000*q", tolerancia: 0.01, unidade: "kg/dia",
        pergunta: "Efluente com DBO de {dbo} mg/L e vazão de {q} m³/dia. Qual a carga de DBO (kg/dia)?", resolucao: "{dbo} mg/L = {=dbo/1000} kg/m³\nCarga = {=dbo/1000} × {q} = {=dbo/1000*q:2} kg/dia", explicacao: "Carga = concentração × vazão." },
      { t: 1, id: "g-camb-q04", tipo: "multipla", pergunta: "Uma DBO alta no efluente indica:", opcoes: ["Muito oxigênio dissolvido", "Muita matéria orgânica biodegradável", "Água potável", "Presença de metais"], correta: 1, explicacao: "Microrganismos consumirão muito oxigênio ao degradá-la." },
      { t: 1, id: "g-camb-t02", tipo: "calculo", variaveis: { ent: { min: 1000, max: 4000, passo: 100 }, ef: { min: 70, max: 98 } }, calc: { sai: "round(ent*(1-ef/100))" }, resposta: "(ent-sai)/ent*100", tolerancia: 0.1, unidade: "%",
        pergunta: "A estação de tratamento recebe DBO de {ent} mg/L e lança {sai} mg/L. Qual a eficiência de remoção (%)? (1 casa)", resolucao: "({ent} − {sai}) ÷ {ent} × 100 = {=(ent-sai)/ent*100:1}%", explicacao: "Compare com a exigência legal do órgão ambiental." },
      { t: 2, id: "g-camb-t03", tipo: "calculo", variaveis: { l: { min: 500, max: 5000, passo: 100 }, fe: { valores: [2.6, 2.7] } }, resposta: "l*fe/1000", tolerancia: 0.01, unidade: "t CO₂",
        pergunta: "Consumo de {l} L de diesel no mês, com fator de emissão aproximado de {fe} kg CO₂/L. Quantas toneladas de CO₂? (2 casas)", resolucao: "{l} × {fe} = {=l*fe} kg = {=l*fe/1000:2} t CO₂", explicacao: "Emissão = atividade × fator de emissão." },
      { t: 2, id: "g-camb-q05", tipo: "ligar", pergunta: "Ligue a fonte ao escopo do GHG Protocol:", pares: [["Caldeira da própria fábrica", "Escopo 1"], ["Eletricidade comprada da concessionária", "Escopo 2"], ["Transporte feito por fornecedores", "Escopo 3"]], explicacao: "Diretas, energia comprada e cadeia de valor." },
      { t: 2, id: "g-camb-q06", tipo: "vf", pergunta: "Ações de eficiência energética reduzem ao mesmo tempo custo e emissões.", correta: true, explicacao: "Menos energia consumida = menos emissões associadas." },
      { t: 3, id: "g-camb-q07", tipo: "ordenar", pergunta: "Ordene as licenças do licenciamento ambiental:", itens: ["Licença Prévia (LP)", "Licença de Instalação (LI)", "Licença de Operação (LO)"], explicacao: "Planejar, construir e operar." },
      { t: 3, id: "g-camb-q08", tipo: "multipla", pergunta: "Qual lei institui a Política Nacional de Resíduos Sólidos?", opcoes: ["Lei 6.938/1981", "Lei 9.605/1998", "Lei 12.305/2010", "Lei 13.709/2018"], correta: 2, explicacao: "6.938: PNMA; 9.605: crimes ambientais; 13.709: LGPD." },
      { t: 3, id: "g-camb-q09", tipo: "vf", pergunta: "A Lei de Crimes Ambientais pode responsabilizar tanto pessoas físicas quanto a empresa (pessoa jurídica).", correta: true, explicacao: "Lei 9.605/1998." }
    ]
  },

  {
    id: "g-ondas", codigo: "GEXT-7004", nome: "Ondas", periodo: 5, area: "exatas", icone: "🔊", creditos: "(2-2-0) 3 créditos", prereq: ["g-eletbas", "g-fister"],
    intro: "Oscilações e ondas aparecem na fábrica como **vibração de máquinas**, **ruído** (que afeta a saúde e é regulado pela NR-15), **ultrassom** para inspeção e medição e **luz** (iluminação dos postos). Esta disciplina dá a base física para entender e medir esses fenômenos.",
    topicos: [
      { t: "Oscilações (MHS)", icone: "⏱️",
        pontos: ["**Movimento harmônico simples:** x(t) = A·cos(ωt + φ).", "**Período** T (s), **frequência** f = 1/T (Hz), **frequência angular** ω = 2πf.", "Massa-mola: ω = √(k/m); pêndulo simples: ω = √(g/L).", "Oscilações **amortecidas** perdem energia; **forçadas** podem entrar em **ressonância**.", "Em máquinas, a vibração é medida em deslocamento, velocidade (mm/s) ou aceleração."],
        formulas: [["x(t) = A · cos(ωt + φ)", "MHS"], ["f = 1 ÷ T; ω = 2π·f", "frequência e frequência angular"], ["ω = √(k ÷ m)", "sistema massa-mola"]],
        producao: "A **análise de vibração** (manutenção preditiva) acompanha a amplitude e as frequências das máquinas para detectar desbalanceamento, desalinhamento e falhas de rolamento antes da quebra.",
        exemplo: "Motor a 1.800 rpm = 30 rotações/s ⇒ vibração de desbalanceamento em **30 Hz** (1× a rotação)." },
      { t: "Ondas mecânicas", icone: "🌊",
        pontos: ["**Onda:** transporta energia sem transportar matéria.", "**Transversais** (cordas) e **longitudinais** (som).", "**v = λ·f** (velocidade = comprimento de onda × frequência).", "Fenômenos: reflexão, refração, difração, **interferência** e ondas estacionárias.", "**Ultrassom** (> 20 kHz): ensaios não destrutivos (trincas, espessura), medição de nível e limpeza."],
        formulas: [["v = λ · f", "relação fundamental das ondas"], ["d = v · t ÷ 2", "distância por eco (ida e volta)"]],
        producao: "Ultrassom mede a **espessura de paredes** de tanques e tubulações (corrosão) sem desmontar e detecta trincas em soldas; sensores ultrassônicos medem nível em silos.",
        exemplo: "Som no ar ≈ 340 m/s. Sensor ultrassônico recebe o eco em 10 ms: distância = 340 × 0,010 ÷ 2 = **1,7 m** até o produto no silo." },
      { t: "Som, ruído e NR-15", icone: "🎧",
        pontos: ["**Nível de intensidade sonora:** β = 10·log(I/I₀) em decibéis (dB); escala **logarítmica**.", "Dobrar a intensidade (ex.: duas máquinas iguais) soma **+3 dB**.", "Medições ocupacionais usam a curva de ponderação **A** — dB(A).", "**NR-15, Anexo 1:** limite de tolerância de **85 dB(A) para 8 horas**; a cada aumento de 5 dB, o tempo máximo cai pela metade (90 dB(A): 4 h).", "**Dose:** D = Σ Cᵢ/Tᵢ; D > 1 ultrapassa o limite. Controle: na fonte, na trajetória (enclausuramento) e, por último, protetor auricular."],
        formulas: [["β = 10 · log(I ÷ I₀)", "nível sonoro em dB"], ["L_total = 10·log(Σ 10^(Lᵢ/10))", "soma de níveis de várias fontes"], ["D = Σ (Cᵢ ÷ Tᵢ)", "dose de ruído; C = tempo exposto, T = tempo permitido"]],
        producao: "Mapear o ruído da fábrica, reduzir na fonte (manutenção, enclausuramento) e controlar a exposição para prevenir perda auditiva, que é doença ocupacional.",
        exemplo: "Operador fica 4 h a 90 dB(A) (permitido 4 h) e 4 h a 85 dB(A) (permitido 8 h): D = 4/4 + 4/8 = **1,5** → acima do limite." },
      { t: "Ondas eletromagnéticas e luz", icone: "💡",
        pontos: ["Ondas eletromagnéticas não precisam de meio: rádio, micro-ondas, infravermelho, luz visível, UV, raios X.", "No vácuo, c ≈ 3 × 10⁸ m/s; c = λ·f.", "**Iluminância** (lux) = fluxo luminoso (lúmen) ÷ área; níveis mínimos por tarefa são definidos em norma (ABNT NBR ISO/CIE 8995-1), referenciada pela ergonomia (NR-17).", "Aplicações: **termografia** (infravermelho) na manutenção, leitores ópticos, fibras ópticas, RFID.", "Radiações ionizantes (raios X) exigem proteção específica."],
        formulas: [["c = λ · f", "ondas eletromagnéticas no vácuo"], ["E = Φ ÷ A", "iluminância (lux) = lúmens ÷ m²"]],
        producao: "Iluminação adequada reduz erros de inspeção e acidentes; a **termografia** detecta pontos quentes em painéis elétricos e mancais antes da falha.",
        exemplo: "Luminárias somando 12.000 lm úteis numa bancada de 20 m²: E ≈ 12.000 ÷ 20 = **600 lux**." }
    ],
    glossario: [["MHS", "Movimento harmônico simples."], ["Período", "Tempo de uma oscilação completa."], ["Frequência", "Número de oscilações por segundo (Hz)."], ["Ressonância", "Aumento de amplitude quando a excitação coincide com a frequência natural."], ["Comprimento de onda", "Distância entre dois pontos equivalentes consecutivos da onda."], ["Ultrassom", "Som acima de 20 kHz, usado em inspeção e medição."], ["Decibel", "Unidade logarítmica de nível sonoro."], ["dB(A)", "Nível sonoro com ponderação A, próxima da audição humana."], ["Dose de ruído", "Soma das frações de exposição em relação aos tempos permitidos."], ["Iluminância", "Fluxo luminoso por unidade de área (lux)."], ["Termografia", "Imagem por infravermelho que mostra temperaturas."]],
    questoes: [
      { t: 0, id: "g-ond-t01", tipo: "calculo", variaveis: { rpm: { valores: [900, 1200, 1500, 1800, 3000, 3600] } }, resposta: "rpm/60", tolerancia: 0, unidade: "Hz",
        pergunta: "Um motor gira a {rpm} rpm. Em que frequência (Hz) aparece a vibração de desbalanceamento (1× a rotação)?", resolucao: "{rpm} ÷ 60 = {=rpm/60} Hz", explicacao: "rpm ÷ 60 = rotações por segundo." },
      { t: 0, id: "g-ond-q01", tipo: "multipla", pergunta: "Um sistema oscila com período de 0,05 s. Qual a frequência?", opcoes: ["5 Hz", "20 Hz", "50 Hz", "0,05 Hz"], correta: 1, explicacao: "f = 1/T = 20 Hz." },
      { t: 0, id: "g-ond-q02", tipo: "vf", pergunta: "A análise de vibração permite detectar defeitos de rolamento antes da quebra.", correta: true, explicacao: "É uma técnica de manutenção preditiva." },
      { t: 1, id: "g-ond-t02", tipo: "calculo", variaveis: { ms: { min: 2, max: 40, passo: 2 } }, resposta: "340*ms/1000/2", tolerancia: 0.01, unidade: "m",
        pergunta: "Um sensor ultrassônico (som a 340 m/s) recebe o eco {ms} ms após emitir o pulso. Qual a distância até o objeto (m)? (2 casas)", resolucao: "d = 340 × {=ms/1000} ÷ 2 = {=340*ms/1000/2:2} m", explicacao: "Divide por 2: ida e volta." },
      { t: 1, id: "g-ond-q03", tipo: "multipla", pergunta: "O som é uma onda:", opcoes: ["Eletromagnética transversal", "Mecânica longitudinal", "Que não precisa de meio", "Luminosa"], correta: 1, explicacao: "Compressões e rarefações do meio." },
      { t: 1, id: "g-ond-q04", tipo: "vf", pergunta: "O ultrassom pode medir a espessura da parede de um tanque sem esvaziá-lo nem cortá-lo.", correta: true, explicacao: "Ensaio não destrutivo." },
      { t: 2, id: "g-ond-t03", tipo: "calculo", variaveis: { l: { valores: [80, 82, 85, 88, 90, 92] }, n: { valores: [2, 4, 8] } }, resposta: "l+10*log10(n)", tolerancia: 0.1, unidade: "dB",
        pergunta: "{n} máquinas iguais, cada uma com {l} dB(A) no ponto de medição. Qual o nível total? (1 casa)", resolucao: "L = {l} + 10·log({n}) = {l} + {=10*log10(n):1} = {=l+10*log10(n):1} dB(A)", explicacao: "Dobrar as fontes soma cerca de 3 dB." },
      { t: 2, id: "g-ond-q05", tipo: "multipla", pergunta: "Pela NR-15 (Anexo 1), qual o limite de tolerância para 8 horas de exposição?", opcoes: ["70 dB(A)", "80 dB(A)", "85 dB(A)", "95 dB(A)"], correta: 2, explicacao: "A 90 dB(A), o máximo é 4 h." },
      { t: 2, id: "g-ond-t04", tipo: "calculo", variaveis: { c1: { valores: [2, 3, 4] }, c2: { valores: [2, 3, 4] } }, resposta: "c1/4+c2/8", tolerancia: 0.01, unidade: "",
        pergunta: "Um operador fica {c1} h a 90 dB(A) (permitido 4 h) e {c2} h a 85 dB(A) (permitido 8 h). Qual a dose? (2 casas)", resolucao: "D = {c1}/4 + {c2}/8 = {=c1/4+c2/8:2}", explicacao: "D > 1: exposição acima do limite." },
      { t: 3, id: "g-ond-q06", tipo: "multipla", pergunta: "Qual técnica usa radiação infravermelha para achar pontos quentes em painéis elétricos?", opcoes: ["Ultrassom", "Termografia", "Raio X", "Líquido penetrante"], correta: 1, explicacao: "Mostra a temperatura das superfícies." },
      { t: 3, id: "g-ond-t05", tipo: "calculo", variaveis: { lm: { min: 4000, max: 30000, passo: 1000 }, a: { min: 10, max: 60, passo: 5 } }, resposta: "lm/a", tolerancia: 0.1, unidade: "lux",
        pergunta: "Luminárias fornecem {lm} lm úteis sobre uma área de {a} m². Qual a iluminância média (lux)? (1 casa)", resolucao: "E = {lm} ÷ {a} = {=lm/a:1} lux", explicacao: "Compare com o nível recomendado para a tarefa." },
      { t: 3, id: "g-ond-q07", tipo: "vf", pergunta: "Ondas eletromagnéticas, como a luz, precisam de um meio material para se propagar.", correta: false, explicacao: "Propagam-se até no vácuo." }
    ]
  },

  {
    id: "g-fentran", codigo: "GMEC-7007", nome: "Fenômenos de Transporte", periodo: 5, area: "engenharia", icone: "🚰", creditos: "(2-2-0) 3 créditos", prereq: ["g-fister"],
    intro: "Estuda o transporte de **quantidade de movimento (fluidos), calor e massa**. Na produção: dimensionar **bombas e tubulações**, reduzir **perdas de carga**, controlar **vazamentos de ar comprimido** (energia cara), ventilação e processos de aquecimento e resfriamento.",
    topicos: [
      { t: "Propriedades e estática dos fluidos", icone: "💧",
        pontos: ["**Massa específica** ρ (kg/m³); água ≈ 1.000 kg/m³.", "**Viscosidade** μ: resistência ao escoamento (mel > água).", "**Pressão** P = F/A; 1 bar = 10⁵ Pa ≈ 1 atm.", "**Lei de Stevin:** P = P₀ + ρ·g·h (a pressão cresce com a profundidade).", "**Pressão manométrica** (relativa à atmosfera) × **absoluta**."],
        formulas: [["P = P₀ + ρ · g · h", "pressão hidrostática"], ["1 bar = 100.000 Pa", "conversão de unidades"], ["Empuxo = ρ_fluido · g · V_imerso", "princípio de Arquimedes"]],
        producao: "Pressão no fundo de tanques e reservatórios (espessura da parede, sensores de nível por pressão), manômetros de processo.",
        exemplo: "Tanque com 4 m de água: P manométrica no fundo = 1.000 × 9,81 × 4 ≈ **39,2 kPa (0,39 bar)**." },
      { t: "Continuidade e Bernoulli", icone: "➡️",
        pontos: ["**Vazão volumétrica** Q = v·A (m³/s).", "**Continuidade** (incompressível): v₁A₁ = v₂A₂ — onde o tubo afina, a velocidade aumenta.", "**Bernoulli** (sem perdas): P + ρv²/2 + ρgz = constante ao longo de uma linha de corrente.", "Aplicações: medidores de vazão (Venturi, placa de orifício), sifões, bicos."],
        formulas: [["Q = v · A", "vazão"], ["v₁ · A₁ = v₂ · A₂", "continuidade"], ["P₁ + ρv₁²/2 + ρgz₁ = P₂ + ρv₂²/2 + ρgz₂", "equação de Bernoulli"]],
        producao: "Dimensionar diâmetros de tubulações para a vazão desejada sem velocidades excessivas (ruído, desgaste, perda de carga).",
        exemplo: "Água a 1 m/s num tubo de 100 mm passa para 50 mm: a área cai para 1/4, então v₂ = **4 m/s**." },
      { t: "Perda de carga e bombas", icone: "⛽",
        pontos: ["O escoamento real perde energia por atrito: **perda de carga**.", "**Número de Reynolds** Re = ρvD/μ: laminar (Re < ~2.300) ou turbulento (Re > ~4.000).", "**Darcy-Weisbach:** h_f = f·(L/D)·v²/(2g); perdas localizadas em curvas e válvulas.", "**Potência da bomba:** P = ρ·g·Q·H ÷ η (H = altura manométrica total).", "Cavitação: bolhas de vapor que danificam a bomba (pressão na sucção baixa demais)."],
        formulas: [["Re = ρ · v · D ÷ μ", "número de Reynolds"], ["h_f = f · (L/D) · v² ÷ (2g)", "perda de carga distribuída (Darcy-Weisbach)"], ["P = ρ · g · Q · H ÷ η", "potência consumida pela bomba"]],
        producao: "Escolher bombas pela curva do sistema, reduzir perdas (tubos maiores, menos curvas) para economizar energia, evitar cavitação.",
        exemplo: "Q = 10 L/s (0,01 m³/s), H = 30 m, η = 70%: P = 1.000 × 9,81 × 0,01 × 30 ÷ 0,7 ≈ **4,2 kW**." },
      { t: "Ar comprimido, ventilação e transferência de calor e massa", icone: "🌬️",
        pontos: ["**Ar comprimido** é uma das formas mais caras de energia na fábrica: vazamentos desperdiçam energia 24 h por dia.", "Vazão por um furo cresce com a área (o quadrado do diâmetro) e com a pressão.", "**Ventilação:** vazão de ar = volume do ambiente × trocas por hora.", "**Transferência de calor** (condução, convecção, radiação) e **de massa** (difusão, secagem) seguem leis análogas: fluxo = coeficiente × área × diferença.", "Trocadores de calor recuperam energia de correntes quentes."],
        formulas: [["Q_ar = V_ambiente × trocas/h", "vazão de ventilação (m³/h)"], ["Energia perdida = potência equivalente do vazamento × horas", "custo de vazamentos"], ["q = h · A · ΔT", "convecção (analogia com transferência de massa)"]],
        producao: "Programas de caça a vazamentos de ar comprimido, desligar compressores fora de turno, dimensionar exaustores e recuperar calor de compressores e caldeiras.",
        exemplo: "Galpão de 2.000 m³ que precisa de 6 trocas/h: vazão = **12.000 m³/h** de ar." }
    ],
    glossario: [["Massa específica", "Massa por unidade de volume (ρ)."], ["Viscosidade", "Resistência de um fluido ao escoamento."], ["Pressão manométrica", "Pressão medida em relação à atmosférica."], ["Vazão", "Volume de fluido por unidade de tempo."], ["Equação da continuidade", "Conservação da massa: v₁A₁ = v₂A₂."], ["Bernoulli", "Conservação de energia num escoamento ideal."], ["Número de Reynolds", "Razão entre forças de inércia e viscosas; indica laminar ou turbulento."], ["Perda de carga", "Energia perdida por atrito no escoamento."], ["Altura manométrica", "Energia por unidade de peso que a bomba fornece (m)."], ["Cavitação", "Formação e colapso de bolhas de vapor que danificam bombas."]],
    questoes: [
      { t: 0, id: "g-fen-t01", tipo: "calculo", variaveis: { h: { min: 1, max: 15, passo: 0.5 }, rho: { valores: [800, 1000, 1030, 1200] } }, resposta: "rho*9.81*h/1000", tolerancia: 0.1, unidade: "kPa",
        pergunta: "Tanque com {h} m de líquido de massa específica {rho} kg/m³. Pressão manométrica no fundo (kPa)? (1 casa)", resolucao: "P = ρ·g·h = {rho} × 9,81 × {h} = {=rho*9.81*h:0} Pa = {=rho*9.81*h/1000:1} kPa", explicacao: "Não depende do formato do tanque, só da altura." },
      { t: 0, id: "g-fen-q01", tipo: "vf", pergunta: "A pressão no fundo de um tanque depende da altura do líquido, e não do volume total do tanque.", correta: true, explicacao: "Lei de Stevin." },
      { t: 0, id: "g-fen-q02", tipo: "multipla", pergunta: "1 bar equivale a aproximadamente:", opcoes: ["1 Pa", "100 kPa", "10 kPa", "1 MPa"], correta: 1, explicacao: "10⁵ Pa ≈ 1 atm." },
      { t: 1, id: "g-fen-t02", tipo: "calculo", variaveis: { v1: { valores: [0.5, 1, 1.5, 2] }, d1: { valores: [100, 150, 200] }, d2: { valores: [40, 50, 75] } }, resposta: "v1*pow(d1/d2,2)", tolerancia: 0.01, unidade: "m/s",
        pergunta: "Água a {v1} m/s num tubo de {d1} mm passa para um tubo de {d2} mm. Qual a nova velocidade (m/s)? (2 casas)", resolucao: "v₂ = v₁ × (D₁/D₂)² = {v1} × ({d1}/{d2})² = {=v1*pow(d1/d2,2):2} m/s", explicacao: "A área cai com o quadrado do diâmetro." },
      { t: 1, id: "g-fen-q03", tipo: "multipla", pergunta: "Segundo Bernoulli, num estrangulamento horizontal onde a velocidade aumenta, a pressão:", opcoes: ["Aumenta", "Diminui", "Não muda", "Zera"], correta: 1, explicacao: "Princípio do medidor Venturi." },
      { t: 1, id: "g-fen-q04", tipo: "vf", pergunta: "A equação da continuidade é uma expressão da conservação da massa.", correta: true, explicacao: "O que entra sai (fluido incompressível)." },
      { t: 2, id: "g-fen-t03", tipo: "calculo", variaveis: { q: { valores: [5, 10, 15, 20, 30] }, h: { min: 10, max: 60, passo: 5 }, eta: { valores: [0.6, 0.65, 0.7, 0.75, 0.8] } }, resposta: "1000*9.81*q/1000*h/eta/1000", tolerancia: 0.05, unidade: "kW",
        pergunta: "Bomba de água: vazão {q} L/s, altura manométrica {h} m, rendimento {=eta*100}%. Potência consumida (kW)? (2 casas)", resolucao: "P = 1.000 × 9,81 × {=q/1000} × {h} ÷ {eta} = {=1000*9.81*q/1000*h/eta:0} W ≈ {=1000*9.81*q/1000*h/eta/1000:2} kW", explicacao: "P = ρ·g·Q·H/η." },
      { t: 2, id: "g-fen-t04", tipo: "calculo", variaveis: { v: { valores: [0.5, 1, 1.5, 2] }, dmm: { valores: [25, 50, 100] } }, resposta: "1000*v*dmm/1000/0.001", tolerancia: 1, unidade: "",
        pergunta: "Água (ρ = 1.000 kg/m³, μ = 0,001 Pa·s) a {v} m/s num tubo de {dmm} mm. Qual o número de Reynolds? (inteiro)", resolucao: "Re = ρ·v·D ÷ μ = 1.000 × {v} × {=dmm/1000} ÷ 0,001 = {=1000*v*dmm/1000/0.001:0}", explicacao: "Re > ~4.000: turbulento (caso comum em água industrial)." },
      { t: 2, id: "g-fen-q05", tipo: "multipla", pergunta: "O que é cavitação numa bomba?", opcoes: ["Excesso de vazão", "Formação e colapso de bolhas de vapor por pressão baixa na sucção, danificando o rotor", "Entrada de ar por vedação", "Aquecimento do motor"], correta: 1, explicacao: "Causa ruído, vibração e erosão." },
      { t: 3, id: "g-fen-t05", tipo: "calculo", variaveis: { vol: { min: 500, max: 10000, passo: 500 }, tr: { valores: [2, 4, 6, 8, 10, 12] } }, resposta: "vol*tr", tolerancia: 0, unidade: "m³/h",
        pergunta: "Um galpão de {vol} m³ precisa de {tr} trocas de ar por hora. Qual a vazão de ventilação (m³/h)?", resolucao: "{vol} × {tr} = {=vol*tr} m³/h", explicacao: "Dimensiona exaustores e insufladores." },
      { t: 3, id: "g-fen-q06", tipo: "vf", pergunta: "Vazamentos de ar comprimido são um desperdício pequeno, pois o ar é de graça.", correta: false, explicacao: "Comprimir o ar consome muita energia elétrica; vazamentos são caros." },
      { t: 3, id: "g-fen-q07", tipo: "multipla", pergunta: "Qual ação costuma ter bom retorno na eficiência do ar comprimido?", opcoes: ["Aumentar a pressão da rede", "Programa de detecção e correção de vazamentos", "Usar ar comprimido para limpar o chão", "Deixar compressores ligados no fim de semana"], correta: 1, explicacao: "Vazamentos consomem energia continuamente." }
    ]
  },

  {
    id: "g-ginf", codigo: "GPRO-7804", nome: "Gestão da Informação I", periodo: 5, area: "producao", icone: "🗄️", creditos: "(3-0-0) 3 créditos", prereq: ["g-intadm"], relacionado: ["m14"],
    intro: "Decisões boas precisam de **informação certa, no tempo certo**. A disciplina trata de dados e informação, **sistemas de informação** (ERP, MES, WMS, BI), **bancos de dados**, qualidade de dados, **LGPD** e segurança da informação. O Módulo 14 aprofunda a parte de dados e analytics.",
    topicos: [
      { t: "Dados, informação e conhecimento", icone: "🔺",
        pontos: ["**Dado:** registro bruto (ex.: 1.240). **Informação:** dado com contexto (1.240 caixas produzidas no turno A). **Conhecimento:** capacidade de usar a informação para agir.", "Qualidade da informação: **precisão, completude, atualidade, consistência, relevância**.", "**Conhecimento tácito** (na cabeça das pessoas) × **explícito** (documentado).", "Gestão do conhecimento: transformar tácito em explícito (procedimentos, lições aprendidas)."],
        formulas: [],
        producao: "Apontamentos de produção errados ou atrasados geram decisões erradas no PCP; padrões e lições aprendidas preservam o conhecimento dos operadores experientes.",
        exemplo: "“Máquina 3 parou 42 min por falta de material no turno B” é informação acionável; “42” sozinho é só um dado." },
      { t: "Sistemas de informação na empresa", icone: "🖥️",
        pontos: ["**Transacionais (TPS):** registram operações do dia a dia (vendas, apontamentos).", "**ERP:** integra finanças, compras, vendas, estoques, produção (MRP) numa base única.", "**MES:** gestão da execução no chão de fábrica (ordens, apontamentos, rastreabilidade, OEE).", "**WMS** (armazém), **TMS** (transporte), **CRM** (clientes), **SCM** (cadeia).", "**BI e sistemas de apoio à decisão:** painéis e análises a partir dos dados integrados."],
        formulas: [],
        producao: "O engenheiro de produção participa da implantação de ERP e MES, define processos, parâmetros (lead times, lotes, roteiros) e indicadores.",
        exemplo: "Pedido de venda no ERP → MRP gera ordens → MES registra a execução → WMS controla a expedição → BI mostra o OTIF." },
      { t: "Bancos de dados", icone: "🧱",
        pontos: ["**Banco de dados relacional:** dados em **tabelas** com linhas (registros) e colunas (atributos).", "**Chave primária:** identifica cada registro de forma única; **chave estrangeira:** liga tabelas.", "**Normalização:** evita repetição e inconsistência (cada fato em um lugar só).", "**SQL:** linguagem de consulta: SELECT, WHERE, JOIN, GROUP BY.", "Planilhas não substituem bancos de dados para dados grandes, compartilhados e críticos."],
        formulas: [["SELECT maquina, SUM(qtd) FROM producao GROUP BY maquina", "produção total por máquina"], ["… JOIN produtos ON producao.cod = produtos.cod", "cruzar tabelas pela chave"]],
        producao: "Consultar o banco do ERP/MES para análises que os relatórios prontos não oferecem (paradas por motivo, refugo por lote).",
        exemplo: "Tabela Produtos (cod, nome) e Produção (data, cod, qtd): o JOIN pelo campo cod mostra o nome do produto em cada apontamento." },
      { t: "Qualidade de dados, LGPD e segurança", icone: "🔐",
        pontos: ["**Qualidade de dados:** “lixo entra, lixo sai”; acuracidade de estoques e cadastros é pré-requisito para o MRP.", "**LGPD** (Lei 13.709/2018): tratamento de **dados pessoais** exige base legal (ex.: consentimento, obrigação legal, execução de contrato), finalidade definida e segurança; há direitos do titular.", "**Segurança da informação:** confidencialidade, integridade e disponibilidade (tríade **CID**).", "Boas práticas: controle de acesso, backups, atualizações, treinamento contra golpes (phishing).", "**Governança de dados:** donos dos dados, padrões e responsabilidades."],
        formulas: [["Acuracidade (%) = registros corretos ÷ registros verificados × 100", "indicador de qualidade de dados"]],
        producao: "Dados de funcionários (ponto, saúde ocupacional) são pessoais e sensíveis; dados de produção e receitas são segredos industriais: ambos exigem controle de acesso.",
        exemplo: "Inventário rotativo: 470 de 500 itens conferidos batem com o sistema ⇒ acuracidade = **94%**." }
    ],
    glossario: [["Dado", "Registro bruto, sem contexto."], ["Informação", "Dado organizado com contexto e significado."], ["Conhecimento tácito", "Saber prático difícil de documentar."], ["ERP", "Sistema integrado de gestão empresarial."], ["MES", "Sistema de execução da manufatura."], ["WMS", "Sistema de gestão de armazém."], ["Banco de dados relacional", "Dados organizados em tabelas relacionadas."], ["Chave primária", "Campo que identifica unicamente cada registro."], ["SQL", "Linguagem de consulta a bancos de dados."], ["LGPD", "Lei Geral de Proteção de Dados Pessoais (Lei 13.709/2018)."], ["Tríade CID", "Confidencialidade, integridade e disponibilidade."]],
    questoes: [
      { t: 0, id: "g-ginf-q01", tipo: "ligar", pergunta: "Classifique:", pares: [["“1.240”", "Dado"], ["“1.240 caixas no turno A, 5% abaixo da meta”", "Informação"], ["Saber que a queda vem da troca de sabor e como evitá-la", "Conhecimento"]], explicacao: "Dado → informação → conhecimento." },
      { t: 0, id: "g-ginf-q02", tipo: "vf", pergunta: "Registrar lições aprendidas e procedimentos ajuda a transformar conhecimento tácito em explícito.", correta: true, explicacao: "Preserva o saber quando as pessoas mudam de função." },
      { t: 0, id: "g-ginf-q03", tipo: "multipla", pergunta: "Um relatório de produção que chega com uma semana de atraso falha principalmente em qual atributo da informação?", opcoes: ["Precisão", "Atualidade (tempestividade)", "Completude", "Relevância"], correta: 1, explicacao: "Informação atrasada não permite agir a tempo." },
      { t: 1, id: "g-ginf-q04", tipo: "ligar", pergunta: "Ligue o sistema à função:", pares: [["ERP", "Integra finanças, compras, vendas e produção"], ["MES", "Controla a execução no chão de fábrica"], ["WMS", "Gerencia endereços e movimentos no armazém"], ["BI", "Painéis e análises para decisão"]], explicacao: "Cada sistema cobre uma parte." },
      { t: 1, id: "g-ginf-q05", tipo: "multipla", pergunta: "Em qual sistema o MRP normalmente roda?", opcoes: ["CRM", "ERP", "Planilha pessoal", "SCADA"], correta: 1, explicacao: "O MRP é um módulo do ERP." },
      { t: 1, id: "g-ginf-q06", tipo: "vf", pergunta: "Implantar um ERP é apenas instalar um software; os processos da empresa não mudam.", correta: false, explicacao: "Exige rever processos, cadastros e responsabilidades." },
      { t: 2, id: "g-ginf-q07", tipo: "multipla", pergunta: "Qual comando SQL agrupa a produção por máquina para somar as quantidades?", opcoes: ["ORDER BY", "GROUP BY", "DELETE", "CREATE"], correta: 1, explicacao: "Com SUM(qtd)." },
      { t: 2, id: "g-ginf-q08", tipo: "multipla", pergunta: "Para que serve a chave estrangeira numa tabela?", opcoes: ["Criptografar os dados", "Ligar registros a outra tabela", "Ordenar os registros", "Apagar duplicados"], correta: 1, explicacao: "Ex.: o código do produto na tabela de produção." },
      { t: 2, id: "g-ginf-q09", tipo: "vf", pergunta: "A normalização de um banco de dados busca evitar repetição e inconsistência dos dados.", correta: true, explicacao: "Cada fato em um só lugar." },
      { t: 3, id: "g-ginf-t01", tipo: "calculo", variaveis: { tot: { valores: [200, 300, 400, 500] }, ok: { min: 80, max: 99 } }, calc: { cor: "round(tot*ok/100)" }, resposta: "cor/tot*100", tolerancia: 0.05, unidade: "%",
        pergunta: "No inventário rotativo, {cor} de {tot} itens conferidos batem com o sistema. Qual a acuracidade (%)? (1 casa)", resolucao: "{cor} ÷ {tot} × 100 = {=cor/tot*100:1}%", explicacao: "Baixa acuracidade compromete o MRP." },
      { t: 3, id: "g-ginf-q10", tipo: "multipla", pergunta: "Qual lei trata da proteção de dados pessoais no Brasil?", opcoes: ["Lei 13.709/2018 (LGPD)", "Lei 12.305/2010", "Lei 6.938/1981", "Lei 8.213/1991"], correta: 0, explicacao: "LGPD." },
      { t: 3, id: "g-ginf-q11", tipo: "ligar", pergunta: "Ligue o pilar da segurança da informação ao exemplo de falha:", pares: [["Confidencialidade", "Receita do produto vazada para concorrente"], ["Integridade", "Apontamento alterado indevidamente"], ["Disponibilidade", "Sistema fora do ar parando a expedição"]], explicacao: "Tríade CID." }
    ]
  },

  {
    id: "g-tecmat", codigo: "GMEC-7308", nome: "Tecnologia dos Materiais", periodo: 5, area: "engenharia", icone: "🔩", creditos: "(2-0-0) 2 créditos", prereq: ["g-quimica"],
    intro: "Conhecer os materiais — metais, polímeros, cerâmicos e compósitos — permite **escolher o material certo** para produtos, embalagens, ferramentas e instalações, entender **ensaios** e **tratamentos térmicos** e prever o comportamento em serviço. É a base de Processos de Fabricação.",
    topicos: [
      { t: "Classes de materiais e propriedades", icone: "🧪",
        pontos: ["**Metais:** bons condutores, dúcteis, tenazes; ex.: aço, alumínio, cobre.", "**Polímeros:** leves, isolantes, fáceis de moldar; ex.: PE, PP, PET, PVC.", "**Cerâmicos:** duros, resistentes ao calor e à corrosão, frágeis; ex.: alumina, vidro, porcelana.", "**Compósitos:** combinam materiais (ex.: fibra de vidro + resina, concreto).", "Propriedades: **mecânicas** (resistência, dureza, tenacidade), **térmicas**, **elétricas**, **químicas** (corrosão) e custo/processabilidade."],
        formulas: [["Resistência específica = σ ÷ ρ", "resistência por unidade de massa (importante em transporte)"]],
        producao: "Escolher materiais de embalagem, peças de reposição, revestimentos e ferramentas pelo equilíbrio entre desempenho, custo, processo de fabricação e reciclabilidade.",
        exemplo: "Bandeja de bombom: PET (transparente, rígido, reciclável) × PP (mais flexível, suporta mais calor). A escolha depende da função e do processo de moldagem." },
      { t: "Ensaios de materiais", icone: "🔬",
        pontos: ["**Tração:** curva tensão-deformação; limite de escoamento, resistência máxima, alongamento.", "**Dureza:** resistência à penetração — Brinell (HB), Rockwell (HRC, HRB), Vickers (HV).", "**Impacto (Charpy):** energia absorvida; mede a **tenacidade** (e a transição dúctil-frágil em baixas temperaturas).", "**Fadiga:** falha sob cargas repetidas abaixo do escoamento.", "**Ensaios não destrutivos:** ultrassom, líquido penetrante, partículas magnéticas, raio X."],
        formulas: [["Alongamento (%) = (L_f − L₀) ÷ L₀ × 100", "ductilidade no ensaio de tração"]],
        producao: "Receber materiais com certificado de ensaio, especificar dureza de ferramentas e engrenagens, investigar falhas por fadiga em eixos de máquinas.",
        exemplo: "Corpo de prova de 50 mm que rompe com 61 mm: alongamento = **22%** (material dúctil)." },
      { t: "Aços, ferros fundidos e tratamentos térmicos", icone: "🔥",
        pontos: ["Ligas ferro-carbono: **aços** (até cerca de 2,1% C) e **ferros fundidos** (acima disso).", "Mais carbono: mais dureza e resistência, menos ductilidade e soldabilidade.", "**Aços inoxidáveis:** com cromo (≥ ~10,5%), resistentes à corrosão — usados em indústria de alimentos.", "**Tratamentos térmicos:** **recozimento** (amolece, alivia tensões), **normalização**, **têmpera** (endurece por resfriamento rápido) e **revenimento** (reduz a fragilidade após a têmpera).", "Tratamentos superficiais: cementação, nitretação (superfície dura, núcleo tenaz)."],
        formulas: [],
        producao: "Especificar aço inox em contato com alimentos, pedir peças temperadas e revenidas para desgaste (facas, engrenagens) e entender prazos e custos desses processos.",
        exemplo: "Faca de corte de massa: aço temperado (dureza, fio) e revenido (menos frágil, não lasca)." },
      { t: "Polímeros, cerâmicos e seleção de materiais", icone: "♻️",
        pontos: ["**Termoplásticos:** amolecem com o calor e podem ser remoldados/reciclados (PE, PP, PET).", "**Termofixos:** curam de forma irreversível (epóxi, baquelite); não se refundem.", "**Elastômeros:** grande deformação elástica (borrachas, vedações).", "**Seleção de materiais:** listar requisitos (função, ambiente, carga), filtrar candidatos, ranquear por índices de desempenho e custo, considerar o ciclo de vida.", "Reciclabilidade e símbolos de identificação dos plásticos (1 PET, 2 PEAD, 5 PP…)."],
        formulas: [["Custo por desempenho = custo ÷ propriedade requerida", "comparação simples entre candidatos"]],
        producao: "Escolher vedações compatíveis com o produto e a temperatura, trocar materiais para reduzir custo ou peso e atender exigências de reciclagem.",
        exemplo: "Vedação de uma bomba de chocolate a 50 °C: elastômero compatível com gordura e temperatura, aprovado para contato com alimentos." }
    ],
    glossario: [["Ductilidade", "Capacidade de deformar plasticamente antes de romper."], ["Tenacidade", "Capacidade de absorver energia até a fratura."], ["Dureza", "Resistência à penetração ou ao risco."], ["Fadiga", "Falha sob cargas cíclicas abaixo do escoamento."], ["Aço inoxidável", "Aço com cromo suficiente para resistir à corrosão."], ["Têmpera", "Resfriamento rápido que endurece o aço."], ["Revenimento", "Reaquecimento após a têmpera para reduzir a fragilidade."], ["Recozimento", "Tratamento que amolece e alivia tensões."], ["Termoplástico", "Polímero que amolece com o calor e pode ser remoldado."], ["Termofixo", "Polímero que cura irreversivelmente."], ["Compósito", "Material formado por dois ou mais constituintes."]],
    questoes: [
      { t: 0, id: "g-tmat-q01", tipo: "ligar", pergunta: "Ligue a classe de material ao exemplo:", pares: [["Metal", "Alumínio"], ["Polímero", "Polipropileno (PP)"], ["Cerâmico", "Alumina"], ["Compósito", "Fibra de vidro com resina"]], explicacao: "Quatro grandes classes." },
      { t: 0, id: "g-tmat-q02", tipo: "multipla", pergunta: "Qual classe de material costuma ser dura, resistente ao calor, mas frágil?", opcoes: ["Metais", "Polímeros", "Cerâmicos", "Elastômeros"], correta: 2, explicacao: "Rompe com pouca deformação." },
      { t: 0, id: "g-tmat-q03", tipo: "vf", pergunta: "Na escolha de um material, custo e processo de fabricação são tão importantes quanto as propriedades mecânicas.", correta: true, explicacao: "Seleção é um equilíbrio de requisitos." },
      { t: 1, id: "g-tmat-t01", tipo: "calculo", variaveis: { l0: { valores: [25, 50, 100] }, al: { min: 2, max: 40 } }, calc: { lf: "l0*(1+al/100)" }, resposta: "(lf-l0)/l0*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Um corpo de prova com {l0} mm de comprimento útil rompe com {lf} mm. Qual o alongamento (%)? (1 casa)", resolucao: "({lf} − {l0}) ÷ {l0} × 100 = {=(lf-l0)/l0*100:1}%", explicacao: "Alongamento alto indica material dúctil." },
      { t: 1, id: "g-tmat-q04", tipo: "ligar", pergunta: "Ligue o ensaio à propriedade:", pares: [["Tração", "Resistência e ductilidade"], ["Dureza Rockwell", "Resistência à penetração"], ["Charpy", "Tenacidade ao impacto"], ["Ultrassom", "Defeitos internos sem destruir"]], explicacao: "Cada ensaio mede uma coisa." },
      { t: 1, id: "g-tmat-q05", tipo: "vf", pergunta: "Uma peça pode falhar por fadiga mesmo com cargas abaixo do limite de escoamento, se elas se repetirem muitas vezes.", correta: true, explicacao: "Trincas crescem a cada ciclo." },
      { t: 2, id: "g-tmat-q06", tipo: "multipla", pergunta: "Qual o limite aproximado de carbono que separa aços de ferros fundidos?", opcoes: ["0,2%", "2,1%", "10%", "25%"], correta: 1, explicacao: "Acima de ~2,1% C: ferro fundido." },
      { t: 2, id: "g-tmat-q07", tipo: "ordenar", pergunta: "Ordene o tratamento para uma faca dura e não frágil:", itens: ["Aquecer para austenitizar", "Temperar (resfriamento rápido)", "Revenir (reaquecer moderadamente)"], explicacao: "Têmpera endurece; revenimento reduz a fragilidade." },
      { t: 2, id: "g-tmat-q08", tipo: "multipla", pergunta: "Qual material é mais indicado para equipamentos em contato com alimentos, pela resistência à corrosão e à limpeza?", opcoes: ["Aço carbono comum sem proteção", "Aço inoxidável", "Ferro fundido cinzento", "Cobre"], correta: 1, explicacao: "O cromo forma uma camada passiva protetora." },
      { t: 3, id: "g-tmat-q09", tipo: "ligar", pergunta: "Ligue o tipo de polímero à característica:", pares: [["Termoplástico", "Pode ser refundido e reciclado mecanicamente"], ["Termofixo", "Cura de forma irreversível"], ["Elastômero", "Grande deformação elástica (vedações)"]], explicacao: "Comportamento com o calor e a deformação." },
      { t: 3, id: "g-tmat-q10", tipo: "vf", pergunta: "O símbolo de reciclagem com o número 1 identifica o PET.", correta: true, explicacao: "2 = PEAD, 3 = PVC, 4 = PEBD, 5 = PP, 6 = PS." },
      { t: 3, id: "g-tmat-q11", tipo: "ordenar", pergunta: "Ordene as etapas de seleção de materiais:", itens: ["Definir requisitos da função", "Filtrar candidatos que atendem aos limites", "Ranquear por desempenho e custo", "Verificar processo, disponibilidade e ciclo de vida"], explicacao: "Do requisito à escolha." }
    ]
  },

  {
    id: "g-estqual", codigo: "GPRO-7502", nome: "Estatística da Qualidade e Confiabilidade", periodo: 5, area: "producao", icone: "📉", creditos: "(3-0-0) 3 créditos", prereq: ["g-metest"],
    intro: "Aplica a estatística ao controle da qualidade e da confiabilidade: **controle estatístico de processo (CEP)**, **capacidade de processo (Cp, Cpk)**, **amostragem de aceitação** e **confiabilidade** de equipamentos (MTBF, MTTR, disponibilidade). É o coração da Engenharia da Qualidade e da Manutenção.",
    topicos: [
      { t: "Controle estatístico de processo (CEP)", icone: "📈",
        pontos: ["Toda saída varia. **Causas comuns:** variação natural do processo. **Causas especiais:** eventos identificáveis (ferramenta quebrada, lote ruim).", "**Carta de controle:** linha central e limites de controle (em geral ±3σ da estatística plotada).", "Cartas para **variáveis** (X̄-R, X̄-S, individuais) e para **atributos** (p, np, c, u).", "Sinais de fora de controle: ponto fora dos limites, sequências (ex.: vários pontos seguidos do mesmo lado), tendências.", "**Limites de controle** (voz do processo) ≠ **limites de especificação** (voz do cliente)."],
        formulas: [["LSC = X̿ + A₂·R̄; LIC = X̿ − A₂·R̄", "carta X̄ (A₂ = 0,577 para n = 5)"], ["LSC_R = D₄·R̄; LIC_R = D₃·R̄", "carta R (n = 5: D₄ = 2,114; D₃ = 0)"], ["p̄ ± 3·√(p̄(1 − p̄)/n)", "limites da carta p"]],
        producao: "Monitorar o peso das caixas, a temperatura do forno ou a fração de defeituosos para agir quando surgir uma causa especial, sem “mexer” no processo por causa de variação normal.",
        exemplo: "X̿ = 250 g, R̄ = 5 g, n = 5: LSC = 250 + 0,577 × 5 ≈ **252,9 g**; LIC ≈ **247,1 g**." },
      { t: "Capacidade de processo", icone: "🎯",
        pontos: ["Só faz sentido avaliar capacidade com o processo **sob controle**.", "**Cp** = (LSE − LIE) ÷ 6σ: compara a largura da especificação com a variação natural (ignora a centralização).", "**Cpk** = mín[(LSE − μ) ÷ 3σ; (μ − LIE) ÷ 3σ]: considera a centralização.", "Referências usuais: Cpk ≥ 1,33 costuma ser exigido por clientes; valores < 1 indicam produção de itens fora da especificação.", "Cp alto e Cpk baixo: processo com pouca variação, mas **descentralizado** (ajustar a média)."],
        formulas: [["Cp = (LSE − LIE) ÷ (6σ)", "capacidade potencial"], ["Cpk = mín[(LSE − μ)/(3σ); (μ − LIE)/(3σ)]", "capacidade real"]],
        producao: "Decidir se um processo atende o cliente, onde investir (reduzir variação × centralizar) e aprovar novos equipamentos ou fornecedores.",
        exemplo: "Especificação 245–255 g, μ = 251 g, σ = 1,2 g: Cp = 10 ÷ 7,2 ≈ **1,39**; Cpk = (255 − 251) ÷ 3,6 ≈ **1,11** → centralizar a média melhora muito." },
      { t: "Amostragem de aceitação", icone: "📦",
        pontos: ["Inspecionar uma **amostra** do lote para decidir aceitar ou rejeitar.", "Plano simples: tamanho de amostra n e número de aceitação c (aceita se defeituosos ≤ c).", "**NQA (AQL):** nível de qualidade aceitável; normas como ABNT NBR 5426 trazem tabelas de planos.", "**Curva característica de operação (CO):** probabilidade de aceitar o lote em função da fração defeituosa real.", "Risco do produtor (rejeitar lote bom) e risco do consumidor (aceitar lote ruim)."],
        formulas: [["P_aceitar = Σ (k = 0 até c) C(n,k)·pᵏ·(1 − p)ⁿ⁻ᵏ", "probabilidade de aceitação (binomial)"]],
        producao: "Recebimento de embalagens e matérias-primas; amostragem é um meio-termo entre não inspecionar e inspecionar 100%. O ideal é desenvolver fornecedores para dispensar a inspeção.",
        exemplo: "Plano n = 20, c = 0, lote com 5% de defeituosos: P_aceitar = 0,95²⁰ ≈ **35,8%**." },
      { t: "Confiabilidade", icone: "🛠️",
        pontos: ["**Confiabilidade** R(t): probabilidade de funcionar sem falhar até t.", "**MTBF** (tempo médio entre falhas) e **MTTR** (tempo médio para reparar).", "**Disponibilidade** A = MTBF ÷ (MTBF + MTTR).", "**Curva da banheira:** mortalidade infantil (falhas precoces), vida útil (taxa constante) e desgaste.", "**Weibull:** parâmetro de forma β < 1 (falhas precoces), = 1 (aleatórias, exponencial), > 1 (desgaste).", "Sistemas: **série** R = ΠRᵢ; **paralelo (redundância)** R = 1 − Π(1 − Rᵢ)."],
        formulas: [["A = MTBF ÷ (MTBF + MTTR)", "disponibilidade"], ["R_série = Π Rᵢ", "todos precisam funcionar"], ["R_paralelo = 1 − Π(1 − Rᵢ)", "basta um funcionar"], ["R(t) = e^(−(t/η)^β)", "Weibull"]],
        producao: "Planejar manutenção preventiva (só faz sentido com desgaste, β > 1), decidir redundâncias (bomba reserva) e acompanhar MTBF/MTTR como indicadores.",
        exemplo: "MTBF = 200 h e MTTR = 4 h: A = 200 ÷ 204 ≈ **98%**. Duas bombas em paralelo, cada uma com R = 0,9: R = 1 − 0,1² = **0,99**." }
    ],
    glossario: [["Causa comum", "Variação natural e inerente ao processo."], ["Causa especial", "Variação por evento identificável e corrigível."], ["Carta de controle", "Gráfico com limites para monitorar a estabilidade do processo."], ["Limites de controle", "Faixa natural do processo (normalmente ±3σ)."], ["Limites de especificação", "Faixa exigida pelo cliente ou projeto."], ["Cp", "Capacidade potencial do processo."], ["Cpk", "Capacidade considerando a centralização."], ["NQA (AQL)", "Nível de qualidade aceitável num plano de amostragem."], ["Curva CO", "Probabilidade de aceitar o lote × qualidade do lote."], ["MTBF", "Tempo médio entre falhas."], ["MTTR", "Tempo médio para reparo."], ["Curva da banheira", "Taxa de falhas ao longo da vida do equipamento."]],
    questoes: [
      { t: 0, id: "g-eqc-t01", tipo: "calculo", variaveis: { xb: { valores: [100, 250, 500] }, r: { min: 2, max: 12 } }, resposta: "xb+0.577*r", tolerancia: 0.01, unidade: "",
        pergunta: "Carta X̄-R com n = 5 (A₂ = 0,577): X̿ = {xb} e R̄ = {r}. Qual o limite superior de controle da carta X̄? (2 casas)", resolucao: "LSC = {xb} + 0,577 × {r} = {=xb+0.577*r:2}", explicacao: "LIC = {=xb-0.577*r:2}." },
      { t: 0, id: "g-eqc-q01", tipo: "vf", pergunta: "Limites de controle e limites de especificação são a mesma coisa.", correta: false, explicacao: "Controle = voz do processo; especificação = voz do cliente." },
      { t: 0, id: "g-eqc-q02", tipo: "caso", contexto: "O operador ajusta a máquina a cada ponto da carta que fica um pouco acima ou abaixo da média, mesmo dentro dos limites.", pergunta: "Qual o problema?", opcoes: ["Nenhum: ajustar sempre é bom", "Ele está reagindo à variação comum (sobreajuste), o que tende a aumentar a variação", "A carta está errada", "Os limites devem ser ignorados"], correta: 1, explicacao: "Só se age diante de sinais de causa especial." },
      { t: 1, id: "g-eqc-t02", tipo: "calculo", variaveis: { lie: { valores: [245, 490, 95] }, larg: { valores: [10, 20] }, sg: { valores: [1, 1.2, 1.5, 2] }, desl: { valores: [0, 0.5, 1, 1.5, -1] } }, calc: { lse: "lie+larg", mu: "lie+larg/2+desl" },
        resposta: "min((lse-mu)/(3*sg),(mu-lie)/(3*sg))", tolerancia: 0.01, unidade: "", pergunta: "Especificação {lie} a {lse}; média μ = {mu}; σ = {sg}. Qual o Cpk? (2 casas)",
        resolucao: "(LSE − μ)/3σ = {=(lse-mu)/(3*sg):3}; (μ − LIE)/3σ = {=(mu-lie)/(3*sg):3}\nCpk = menor = {=min((lse-mu)/(3*sg),(mu-lie)/(3*sg)):2} (Cp = {=larg/(6*sg):2})", explicacao: "Cpk < Cp indica processo descentralizado." },
      { t: 1, id: "g-eqc-q03", tipo: "multipla", pergunta: "Um processo tem Cp = 2,0 e Cpk = 0,8. O que fazer primeiro?", opcoes: ["Reduzir a variação", "Centralizar a média", "Comprar outra máquina", "Nada"], correta: 1, explicacao: "A variação é pequena; o problema é a média deslocada." },
      { t: 1, id: "g-eqc-q04", tipo: "vf", pergunta: "Faz sentido calcular a capacidade de um processo que está fora de controle estatístico.", correta: false, explicacao: "Sem estabilidade, o resultado não prevê o futuro." },
      { t: 2, id: "g-eqc-t03", tipo: "calculo", variaveis: { n: { valores: [10, 13, 20, 32, 50] }, p: { valores: [0.01, 0.02, 0.05, 0.1] } }, resposta: "pow(1-p,n)*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Plano de amostragem com n = {n} e c = 0. Se o lote tem {=p*100}% de defeituosos, qual a probabilidade de aceitá-lo (%)? (1 casa)", resolucao: "P = (1 − {p})^{n} = {=pow(1-p,n)*100:1}%", explicacao: "É um ponto da curva CO." },
      { t: 2, id: "g-eqc-q05", tipo: "ligar", pergunta: "Ligue o risco ao significado:", pares: [["Risco do produtor", "Rejeitar um lote bom"], ["Risco do consumidor", "Aceitar um lote ruim"]], explicacao: "Todo plano de amostragem tem os dois riscos." },
      { t: 2, id: "g-eqc-q06", tipo: "vf", pergunta: "O ideal de longo prazo é desenvolver fornecedores capazes para reduzir a necessidade de inspeção de recebimento.", correta: true, explicacao: "Qualidade na fonte." },
      { t: 3, id: "g-eqc-t04", tipo: "calculo", variaveis: { mtbf: { valores: [50, 100, 200, 400, 800] }, mttr: { valores: [1, 2, 4, 8, 12] } }, resposta: "mtbf/(mtbf+mttr)*100", tolerancia: 0.05, unidade: "%",
        pergunta: "MTBF = {mtbf} h e MTTR = {mttr} h. Qual a disponibilidade (%)? (1 casa)", resolucao: "A = {mtbf} ÷ ({mtbf} + {mttr}) = {=mtbf/(mtbf+mttr)*100:1}%", explicacao: "Melhorar exige falhar menos (MTBF) ou reparar mais rápido (MTTR)." },
      { t: 3, id: "g-eqc-t05", tipo: "calculo", variaveis: { r: { valores: [0.8, 0.85, 0.9, 0.95] }, n: { valores: [2, 3] } }, resposta: "(1-pow(1-r,n))*100", tolerancia: 0.01, unidade: "%",
        pergunta: "{n} bombas em paralelo (redundância), cada uma com confiabilidade {r}. Qual a confiabilidade do conjunto (%)? (2 casas)", resolucao: "R = 1 − (1 − {r})^{n} = {=(1-pow(1-r,n))*100:2}%", explicacao: "Basta uma funcionar." },
      { t: 3, id: "g-eqc-q07", tipo: "multipla", pergunta: "Na distribuição de Weibull, β > 1 indica:", opcoes: ["Falhas precoces (mortalidade infantil)", "Falhas aleatórias", "Falhas por desgaste — manutenção preventiva por tempo pode ajudar", "Nenhuma falha"], correta: 2, explicacao: "A taxa de falhas cresce com o tempo." }
    ]
  },

  {
    id: "g-segtrab", codigo: "GPRO-7810", nome: "Fundamentos de Engenharia de Segurança", periodo: 5, area: "producao", icone: "🦺", creditos: "(3-0-0) 3 créditos",
    intro: "Segurança não é custo nem burocracia: é condição para produzir. O engenheiro de produção identifica **perigos e riscos**, aplica a **hierarquia de controles**, conhece as principais **Normas Regulamentadoras (NRs)**, investiga acidentes e acompanha **indicadores** de segurança.",
    topicos: [
      { t: "Conceitos: perigo, risco e acidente", icone: "⚠️",
        pontos: ["**Perigo:** fonte com potencial de causar dano (máquina com partes móveis, produto químico).", "**Risco:** combinação da **probabilidade** de o dano ocorrer com a **severidade**.", "**Acidente de trabalho:** ocorre pelo exercício do trabalho e provoca lesão, perturbação funcional ou doença (Lei 8.213/1991); inclui o acidente de trajeto e as doenças ocupacionais.", "**Incidente (quase acidente):** evento que poderia ter causado dano.", "**Pirâmide de Bird** (1969): para cada acidente grave, muitos acidentes leves e centenas de incidentes — tratar os incidentes previne os graves."],
        formulas: [["Risco = probabilidade × severidade", "matriz de risco"], ["TF = nº de acidentes × 1.000.000 ÷ HHT", "taxa de frequência (ABNT NBR 14280); HHT = horas-homem trabalhadas"], ["TG = dias perdidos (+ debitados) × 1.000.000 ÷ HHT", "taxa de gravidade"]],
        producao: "Registrar e analisar quase acidentes, comparar setores pela taxa de frequência e priorizar ações pela matriz de risco.",
        exemplo: "4 acidentes com afastamento em 800.000 HHT: TF = 4 × 10⁶ ÷ 800.000 = **5,0**." },
      { t: "Hierarquia de controles e EPI", icone: "🔺",
        pontos: ["Ordem de preferência: **1. Eliminação** → **2. Substituição** → **3. Controles de engenharia** (proteções, enclausuramento, ventilação) → **4. Controles administrativos** (procedimentos, sinalização, treinamento, rodízio) → **5. EPI**.", "**EPI** é a última barreira, não a primeira: depende do uso correto o tempo todo.", "**NR-6:** o EPI precisa ter **Certificado de Aprovação (CA)**; a empresa fornece gratuitamente, treina e exige o uso.", "**EPC** (equipamento de proteção coletiva) protege todos sem depender do comportamento individual."],
        formulas: [],
        producao: "Ao encontrar um risco, perguntar primeiro “dá para eliminar?” e “dá para proteger na máquina?” antes de “qual EPI usar?”.",
        exemplo: "Ruído alto: eliminar (máquina mais silenciosa) → enclausurar → reduzir o tempo de exposição → protetor auricular como complemento." },
      { t: "Normas Regulamentadoras essenciais", icone: "📘",
        pontos: ["**NR-1:** disposições gerais e **Gerenciamento de Riscos Ocupacionais (GRO)**, com o **PGR** (inventário de riscos + plano de ação).", "**NR-4:** SESMT (serviço especializado em segurança e medicina do trabalho). **NR-5:** CIPA — Comissão Interna de Prevenção de Acidentes e de Assédio.", "**NR-6:** EPI. **NR-10:** eletricidade. **NR-11:** transporte e movimentação de materiais. **NR-12:** máquinas e equipamentos.", "**NR-15:** atividades insalubres. **NR-17:** ergonomia. **NR-23:** proteção contra incêndios.", "**NR-33:** espaços confinados. **NR-35:** trabalho em altura (acima de 2 m do nível inferior, com risco de queda)."],
        formulas: [],
        producao: "Projetos de layout, compra de máquinas, novas atividades e mudanças de processo precisam considerar as NRs aplicáveis desde o início (é mais barato que adaptar depois).",
        exemplo: "Comprar uma máquina usada sem as proteções exigidas pela NR-12 gera custo de adequação e risco de interdição." },
      { t: "Análise de riscos e investigação de acidentes", icone: "🔎",
        pontos: ["**APR** (análise preliminar de riscos): lista perigos, causas, consequências, classificação e medidas.", "**Matriz de risco:** probabilidade × severidade define prioridade (baixo, médio, alto).", "**Investigação de acidentes:** buscar **causas** (não culpados): árvore de causas, 5 porquês, Ishikawa.", "**CAT** (comunicação de acidente de trabalho): deve ser emitida até o 1º dia útil seguinte; em caso de morte, imediatamente (Lei 8.213/1991).", "Permissão de trabalho e bloqueio de energia (LOTO) para atividades críticas."],
        formulas: [["Prioridade = P × S (ex.: escalas de 1 a 5)", "pontuação na matriz de risco"]],
        producao: "Toda mudança de processo passa por análise de risco; todo acidente vira aprendizado com ações que atacam a causa (não só “mais atenção”).",
        exemplo: "Corte na mão ao limpar a faca da máquina ligada: causa ligada ao processo (limpeza sem bloqueio de energia) → ação: procedimento com LOTO e ferramenta de limpeza que evita contato com a lâmina." }
    ],
    glossario: [["Perigo", "Fonte com potencial de causar dano."], ["Risco", "Combinação de probabilidade e severidade de um dano."], ["Incidente", "Evento que poderia ter causado dano (quase acidente)."], ["Pirâmide de Bird", "Relação entre incidentes, acidentes leves e graves."], ["Hierarquia de controles", "Eliminação, substituição, engenharia, administrativos e EPI."], ["EPI", "Equipamento de proteção individual (NR-6)."], ["EPC", "Equipamento de proteção coletiva."], ["PGR", "Programa de Gerenciamento de Riscos (NR-1)."], ["CIPA", "Comissão Interna de Prevenção de Acidentes e de Assédio (NR-5)."], ["APR", "Análise preliminar de riscos."], ["CAT", "Comunicação de acidente de trabalho."], ["Taxa de frequência", "Acidentes por milhão de horas-homem trabalhadas."]],
    questoes: [
      { t: 0, id: "g-seg-t01", tipo: "calculo", variaveis: { n: { min: 1, max: 12 }, hht: { valores: [400000, 500000, 800000, 1000000, 1500000] } }, resposta: "n*1000000/hht", tolerancia: 0.01, unidade: "",
        pergunta: "{n} acidentes com afastamento em {hht} horas-homem trabalhadas. Qual a taxa de frequência? (2 casas)", resolucao: "TF = {n} × 1.000.000 ÷ {hht} = {=n*1000000/hht:2}", explicacao: "Permite comparar empresas e setores de tamanhos diferentes." },
      { t: 0, id: "g-seg-q01", tipo: "ligar", pergunta: "Ligue o conceito ao exemplo:", pares: [["Perigo", "Lâmina afiada da máquina de corte"], ["Risco", "Chance de corte grave ao limpar a máquina ligada"], ["Incidente", "A luva prendeu na lâmina, mas ninguém se feriu"]], explicacao: "Perigo é a fonte; risco é probabilidade × severidade." },
      { t: 0, id: "g-seg-q02", tipo: "vf", pergunta: "Pela lógica da pirâmide de Bird, tratar os quase acidentes ajuda a prevenir os acidentes graves.", correta: true, explicacao: "As causas costumam ser as mesmas." },
      { t: 1, id: "g-seg-q03", tipo: "ordenar", pergunta: "Ordene a hierarquia de controles, da mais eficaz para a menos eficaz:", itens: ["Eliminação", "Substituição", "Controles de engenharia", "Controles administrativos", "EPI"], explicacao: "EPI é a última barreira." },
      { t: 1, id: "g-seg-q04", tipo: "multipla", pergunta: "Qual é um controle de engenharia?", opcoes: ["Treinamento", "Proteção fixa com intertravamento na máquina", "Protetor auricular", "Cartaz de alerta"], correta: 1, explicacao: "Age na fonte, sem depender do comportamento." },
      { t: 1, id: "g-seg-q05", tipo: "vf", pergunta: "Pela NR-6, o EPI deve ter Certificado de Aprovação (CA) e ser fornecido gratuitamente pela empresa.", correta: true, explicacao: "E a empresa deve treinar e exigir o uso." },
      { t: 2, id: "g-seg-q06", tipo: "ligar", pergunta: "Ligue a NR ao tema:", pares: [["NR-10", "Eletricidade"], ["NR-12", "Máquinas e equipamentos"], ["NR-17", "Ergonomia"], ["NR-35", "Trabalho em altura"]], explicacao: "Principais NRs da indústria." },
      { t: 2, id: "g-seg-q07", tipo: "multipla", pergunta: "O Programa de Gerenciamento de Riscos (PGR) está previsto em qual NR?", opcoes: ["NR-1", "NR-6", "NR-15", "NR-23"], correta: 0, explicacao: "Gerenciamento de Riscos Ocupacionais (GRO)." },
      { t: 2, id: "g-seg-q08", tipo: "vf", pergunta: "Pela NR-35, é considerado trabalho em altura a atividade executada acima de 2 m do nível inferior, onde haja risco de queda.", correta: true, explicacao: "Exige capacitação, análise de risco e sistemas de proteção." },
      { t: 3, id: "g-seg-t02", tipo: "calculo", variaveis: { p: { min: 1, max: 5 }, s: { min: 1, max: 5 } }, resposta: "p*s", tolerancia: 0, unidade: "pontos",
        pergunta: "Na matriz de risco (1 a 5), um perigo tem probabilidade {p} e severidade {s}. Qual a pontuação de risco?", resolucao: "Risco = {p} × {s} = {=p*s}", explicacao: "Pontuações altas têm prioridade de ação." },
      { t: 3, id: "g-seg-q09", tipo: "caso", contexto: "Após um acidente, o relatório conclui: “causa: falta de atenção do operador; ação: orientar o operador”.", pergunta: "Qual a crítica a essa investigação?", opcoes: ["Está completa", "Parou na culpa individual; deve buscar as causas no processo (por que o sistema permitiu o erro) e propor ações de engenharia e procedimento", "Deveria demitir o operador", "Deveria só trocar o EPI"], correta: 1, explicacao: "Investigação busca causas, não culpados." },
      { t: 3, id: "g-seg-q10", tipo: "multipla", pergunta: "Qual o prazo para emitir a CAT em caso de acidente sem morte?", opcoes: ["Até 30 dias", "Até o 1º dia útil seguinte ao da ocorrência", "Só se houver afastamento longo", "Não é obrigatória"], correta: 1, explicacao: "Em caso de morte, a comunicação é imediata." }
    ]
  }
);
