/* =====================================================================
   GRADE CURRICULAR — 8º PERÍODO (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-pcp1", codigo: "GPRO-7805", nome: "Planejamento e Controle da Produção I", periodo: 8, area: "producao", icone: "🗓️", creditos: "(4-0-0) 4 créditos", prereq: ["g-po1", "g-planinst", "g-custos"], relacionado: ["m03"],
    intro: "A primeira parte do PCP: **prever a demanda**, fazer o **planejamento agregado** (S&OP), montar o **plano mestre (PMP)** e calcular materiais com o **MRP**. O Módulo 3 do curso aprofunda cada tópico em 3 níveis, com muitos exercícios.",
    topicos: [
      { t: "Previsão de demanda", icone: "🔮",
        pontos: ["Métodos **qualitativos** (Delphi, especialistas) e **quantitativos** (séries temporais, causais).", "**Média móvel**, **suavização exponencial** Fₜ₊₁ = Fₜ + α(Aₜ − Fₜ), **regressão** para tendência, **índices sazonais**.", "Erro: **MAD**, **MAPE**, **MSE**; viés pelo **sinal de rastreamento** (Σ erros ÷ MAD).", "Toda previsão erra: meça e revise."],
        formulas: [["Fₜ₊₁ = Fₜ + α·(Aₜ − Fₜ)", "suavização exponencial"], ["MAD = Σ|eₜ| ÷ n", "desvio absoluto médio"], ["TS = Σeₜ ÷ MAD", "sinal de rastreamento"]],
        producao: "A previsão alimenta o S&OP, o PMP, as compras e o dimensionamento de estoques de segurança.",
        exemplo: "F = 47, A = 50, α = 0,3 ⇒ próxima previsão = 47 + 0,3 × 3 = **47,9**." },
      { t: "Planejamento agregado e S&OP", icone: "📋",
        pontos: ["Plano por **família de produtos** e por **mês**: produção, pessoas, horas extras, estoques.", "Estratégias: **acompanhar a demanda (chase)**, **nivelar (level)** ou **mista**.", "Custos: contratação, demissão, hora extra, ociosidade, estoque, falta, subcontratação.", "**S&OP:** processo mensal que integra vendas, operações, compras e finanças num plano único."],
        formulas: [["Produção nivelada = demanda total ÷ nº de períodos", "estratégia level"], ["Eₜ = Eₜ₋₁ + Pₜ − Dₜ", "estoque ao fim do período"]],
        producao: "Decidir como atravessar picos sazonais (Páscoa, Natal) com o menor custo total.",
        exemplo: "Demanda 800, 1.000, 1.200, 1.000 ⇒ nível de **1.000/mês**; estoques finais 200, 200, 0, 0." },
      { t: "Plano mestre de produção (PMP)", icone: "🗂️",
        pontos: ["Quanto de **cada produto final** em **cada semana**.", "Estoque projetado = anterior + PMP − max(previsão, pedidos).", "**ATP (disponível para promessa):** quanto ainda pode ser prometido a novos pedidos.", "Zonas **congelada, semicongelada e livre**.", "Verificação grosseira de capacidade (**RCCP**)."],
        formulas: [["Eₜ = Eₜ₋₁ + PMPₜ − máx(Prevₜ, Pedₜ)", "estoque projetado"], ["ATP = PMP (+ estoque inicial no 1º período) − pedidos até o próximo PMP", "disponível para promessa"]],
        producao: "O PMP é a ponte entre o plano agregado e o MRP; o ATP ajuda vendas a prometer prazos realistas.",
        exemplo: "PMP de 100 na semana 2; pedidos: 30 (s2) e 20 (s3); próximo PMP na s4 ⇒ ATP = **50**." },
      { t: "MRP", icone: "🧮",
        pontos: ["**Lista de materiais (BOM):** estrutura do produto.", "Demanda **dependente** é calculada, não prevista.", "**Necessidade líquida** = bruta − estoque − recebimentos programados (+ estoque de segurança).", "Recebimento planejado conforme a regra de lote; **liberação** recuada do **lead time**.", "MRP II e ERP; premissas de capacidade infinita e lead time fixo."],
        formulas: [["NB = quantidade do pai × quantidade por unidade", "necessidade bruta"], ["NL = máx(0; NB − estoque − RP + ES)", "necessidade líquida"]],
        producao: "Calcular o que comprar e fabricar, quanto e quando, para cumprir o PMP.",
        exemplo: "NB = 2.400; estoque 400; RP 500 ⇒ NL = **1.500**; com lead time de 1 semana, liberar na semana anterior." }
    ],
    glossario: [["Suavização exponencial", "Previsão que corrige uma fração α do erro."], ["MAD", "Desvio absoluto médio."], ["Sinal de rastreamento", "Σ erros ÷ MAD; detecta viés."], ["Planejamento agregado", "Plano por família e por mês."], ["S&OP", "Planejamento integrado de vendas e operações."], ["PMP", "Plano mestre de produção."], ["ATP", "Quantidade disponível para promessa."], ["BOM", "Lista de materiais."], ["Necessidade líquida", "Necessidade bruta menos estoque e recebimentos programados."], ["Lead time", "Tempo entre liberar a ordem e receber o item."]],
    questoes: [
      { t: 0, id: "g-pcp1-t01", tipo: "calculo", variaveis: { f: { min: 100, max: 400, passo: 10 }, dif: { min: -40, max: 40, passo: 5 }, a: { valores: [0.1, 0.2, 0.3, 0.4] } }, condicao: "dif != 0", calc: { r: "f+dif" }, resposta: "f+a*(r-f)", tolerancia: 0.01, unidade: "unidades",
        pergunta: "Previsão = {f}; demanda real = {r}; α = {a}. Qual a próxima previsão? (2 casas)", resolucao: "{f} + {a} × ({r} − {f}) = {=f+a*(r-f):2}", explicacao: "Suavização exponencial simples." },
      { t: 0, id: "g-pcp1-q01", tipo: "multipla", pergunta: "O sinal de rastreamento está em +6. Isso indica:", opcoes: ["Previsão sem viés", "Previsão sistematicamente abaixo da demanda real", "Previsão sistematicamente acima", "MAD negativo"], correta: 1, explicacao: "Soma dos erros (real − previsto) positiva e grande." },
      { t: 0, id: "g-pcp1-q02", tipo: "vf", pergunta: "O MAPE permite comparar a acurácia de previsão de itens com volumes muito diferentes.", correta: true, explicacao: "É um erro relativo (%)." },
      { t: 1, id: "g-pcp1-q03", tipo: "ligar", pergunta: "Ligue a estratégia agregada à característica:", pares: [["Acompanhar (chase)", "Produção varia com a demanda"], ["Nivelar (level)", "Produção constante; estoque absorve"], ["Mista", "Combina variação de produção e estoque"]], explicacao: "Escolha pelo custo total e restrições." },
      { t: 1, id: "g-pcp1-t02", tipo: "calculo", variaveis: { d1: { min: 600, max: 1400, passo: 100 }, d2: { min: 600, max: 1400, passo: 100 }, d3: { min: 600, max: 1400, passo: 100 }, d4: { min: 600, max: 1400, passo: 100 } }, condicao: "(d1+d2+d3+d4) % 4 == 0",
        resposta: "(d1+d2+d3+d4)/4", tolerancia: 0, unidade: "unidades/mês", pergunta: "Demanda: {d1}, {d2}, {d3}, {d4}. Qual a produção mensal no plano nivelado?", resolucao: "({d1} + {d2} + {d3} + {d4}) ÷ 4 = {=(d1+d2+d3+d4)/4}", explicacao: "Verifique se o estoque não fica negativo." },
      { t: 1, id: "g-pcp1-q04", tipo: "multipla", pergunta: "Qual o principal objetivo do S&OP?", opcoes: ["Programar a máquina", "Chegar a um plano único entre as áreas", "Calcular a BOM", "Definir preços"], correta: 1, explicacao: "Integração mensal por família." },
      { t: 2, id: "g-pcp1-t03", tipo: "calculo", variaveis: { e0: { min: 20, max: 120, passo: 5 }, pmp: { valores: [0, 100, 150] }, pv: { min: 30, max: 80, passo: 5 }, pd: { min: 20, max: 90, passo: 5 } }, condicao: "e0 + pmp - max(pv, pd) >= 0", resposta: "e0+pmp-max(pv,pd)", tolerancia: 0, unidade: "unidades",
        pergunta: "Estoque inicial {e0}; PMP {pmp}; previsão {pv}; pedidos firmes {pd}. Estoque projetado ao fim da semana?", resolucao: "{e0} + {pmp} − máx({pv}; {pd}) = {=e0+pmp-max(pv,pd)}", explicacao: "Usa o maior entre previsão e pedidos." },
      { t: 2, id: "g-pcp1-q05", tipo: "vf", pergunta: "No cálculo do ATP, descontam-se apenas os pedidos firmes, não a previsão.", correta: true, explicacao: "ATP mostra o que ainda pode ser prometido." },
      { t: 2, id: "g-pcp1-q06", tipo: "ordenar", pergunta: "Ordene as zonas do PMP da mais próxima para a mais distante:", itens: ["Congelada", "Semicongelada", "Livre"], explicacao: "Quanto mais perto, mais caro mudar." },
      { t: 3, id: "g-pcp1-t04", tipo: "calculo", variaveis: { nb: { min: 800, max: 3000, passo: 100 }, est: { min: 0, max: 600, passo: 50 }, rp: { valores: [0, 200, 300, 500] } }, condicao: "nb - est - rp > 0", resposta: "nb-est-rp", tolerancia: 0, unidade: "unidades",
        pergunta: "NB = {nb}; estoque = {est}; recebimento programado = {rp}; sem estoque de segurança. Qual a necessidade líquida?", resolucao: "{nb} − {est} − {rp} = {=nb-est-rp}", explicacao: "Desconte o que tem e o que já vem." },
      { t: 3, id: "g-pcp1-q07", tipo: "multipla", pergunta: "Um componente precisa chegar na semana 7 e tem lead time de 3 semanas. Quando liberar a ordem?", opcoes: ["Semana 4", "Semana 7", "Semana 10", "Semana 3"], correta: 0, explicacao: "7 − 3 = 4." },
      { t: 3, id: "g-pcp1-q08", tipo: "vf", pergunta: "O MRP clássico verifica automaticamente se há capacidade de máquina para as ordens que gera.", correta: false, explicacao: "Supõe capacidade infinita; o CRP (MRP II) faz a verificação." }
    ]
  },

  {
    id: "g-gempr", codigo: "GPRO-7815", nome: "Gestão Empreendedora", periodo: 8, area: "gestao", icone: "🚀", creditos: "(1-2-0) 2 créditos",
    intro: "Empreender é identificar oportunidades e transformá-las em negócios — dentro de uma empresa (intraempreendedorismo) ou abrindo a sua. A disciplina trata de **oportunidade e validação**, **modelo de negócio (Canvas)**, **plano de negócios e viabilidade** e **formalização** no Brasil.",
    topicos: [
      { t: "Empreendedorismo e oportunidades", icone: "💡",
        pontos: ["**Empreendedor:** identifica oportunidades, assume riscos calculados e mobiliza recursos.", "**Intraempreendedorismo:** empreender dentro da organização (novos produtos, processos, negócios).", "Fontes de oportunidade: problemas de clientes, mudanças tecnológicas, regulatórias e demográficas, ineficiências.", "Oportunidade ≠ ideia: precisa de **clientes dispostos a pagar** e de um modelo viável.", "Empreendedorismo por **oportunidade** × por **necessidade**."],
        formulas: [],
        producao: "Engenheiros de produção empreendem em consultoria, logística, automação, alimentos, software de gestão — e dentro das empresas, liderando novos projetos.",
        exemplo: "Uma engenheira percebe que pequenas confeitarias perdem muito produto por falta de previsão de demanda e cria um serviço simples de planejamento por assinatura." },
      { t: "Validação: lean startup e MVP", icone: "🧪",
        pontos: ["**Lean startup:** ciclo **construir → medir → aprender** para reduzir incerteza rápido e barato.", "**MVP (produto mínimo viável):** a versão mais simples que permite testar a hipótese principal com clientes reais.", "Testar hipóteses: problema existe? clientes pagariam? quanto? por qual canal?", "**Pivotar:** mudar a estratégia quando os dados mostram que a hipótese estava errada.", "Métricas acionáveis (conversão, retenção) em vez de métricas de vaidade (curtidas)."],
        formulas: [["Taxa de conversão = clientes que compraram ÷ clientes abordados", "métrica de validação"]],
        producao: "O mesmo raciocínio de PDCA e de piloto antes de padronizar: testar pequeno, medir e decidir.",
        exemplo: "Antes de construir o software, a engenheira oferece o serviço com uma planilha para 10 confeitarias: 4 pagam ⇒ conversão de **40%**, sinal de demanda." },
      { t: "Modelo de negócio — Business Model Canvas", icone: "🧩",
        pontos: ["**Canvas (Osterwalder e Pigneur):** 9 blocos numa página.", "**Segmentos de clientes**, **proposta de valor**, **canais**, **relacionamento com clientes**, **fontes de receita**.", "**Recursos-chave**, **atividades-chave**, **parcerias-chave**, **estrutura de custos**.", "Ajuda a enxergar a lógica do negócio e testar alternativas rapidamente.", "Proposta de valor responde: que dor resolvo ou que ganho gero para esse cliente?"],
        formulas: [],
        producao: "Atividades-chave e recursos-chave são, muitas vezes, operações: o engenheiro de produção desenha como entregar a proposta de valor com custo viável.",
        exemplo: "Proposta de valor: “reduzir desperdício de doces em 30%”; segmento: confeitarias pequenas; receita: assinatura mensal; atividade-chave: previsão e plano de produção semanal." },
      { t: "Plano de negócios, viabilidade e formalização", icone: "📑",
        pontos: ["**Plano de negócios:** mercado, concorrência, marketing, operações, equipe e finanças.", "Viabilidade: **investimento inicial**, **capital de giro**, **ponto de equilíbrio**, **VPL/TIR/payback**.", "Formalização no Brasil (LC 123/2006): **MEI**, **ME** (receita bruta anual até R$ 360 mil) e **EPP** (até R$ 4,8 milhões); **Simples Nacional** como regime tributário simplificado — confira sempre os limites vigentes.", "Fontes de recursos: capital próprio, empréstimos, investidores-anjo, editais de fomento.", "Riscos e cenários: pessimista, realista, otimista."],
        formulas: [["PE = custos fixos ÷ margem de contribuição unitária", "ponto de equilíbrio"], ["Capital de giro ≈ custos do ciclo operacional (estoques + prazo a receber − prazo a pagar)", "necessidade de caixa para operar"]],
        producao: "Operações definem boa parte dos custos e do capital de giro (estoques, prazos): um bom desenho operacional viabiliza o negócio.",
        exemplo: "Custos fixos de R$ 6.000/mês e margem de R$ 300 por cliente assinante ⇒ equilíbrio com **20 assinantes**." }
    ],
    glossario: [["Empreendedorismo", "Identificar e explorar oportunidades criando valor."], ["Intraempreendedorismo", "Empreender dentro de uma organização existente."], ["Lean startup", "Abordagem de validar hipóteses de negócio rapidamente."], ["MVP", "Produto mínimo viável para testar hipóteses."], ["Pivotar", "Mudar a estratégia com base no aprendizado."], ["Business Model Canvas", "Quadro de 9 blocos que descreve o modelo de negócio."], ["Proposta de valor", "Benefício que o negócio oferece ao cliente."], ["Capital de giro", "Recursos para financiar a operação do dia a dia."], ["MEI", "Microempreendedor individual."], ["Simples Nacional", "Regime tributário simplificado para micro e pequenas empresas."]],
    questoes: [
      { t: 0, id: "g-gemp-q01", tipo: "vf", pergunta: "Intraempreendedorismo é empreender dentro de uma empresa existente, por exemplo liderando um novo produto ou processo.", correta: true, explicacao: "Engenheiros de produção fazem isso com frequência." },
      { t: 0, id: "g-gemp-q02", tipo: "multipla", pergunta: "O que diferencia uma oportunidade de uma simples ideia?", opcoes: ["Ser original", "Ter clientes com um problema real dispostos a pagar e um modelo viável", "Ser tecnológica", "Ser cara"], correta: 1, explicacao: "Mercado + viabilidade." },
      { t: 0, id: "g-gemp-q03", tipo: "multipla", pergunta: "Qual é uma fonte típica de oportunidades?", opcoes: ["Problemas recorrentes de clientes e ineficiências de mercado", "Copiar o concorrente sem mudar nada", "Evitar clientes", "Aumentar preços sem motivo"], correta: 0, explicacao: "Dores e mudanças geram oportunidades." },
      { t: 1, id: "g-gemp-q04", tipo: "ordenar", pergunta: "Ordene o ciclo da lean startup:", itens: ["Construir", "Medir", "Aprender"], explicacao: "E repetir, pivotando se preciso." },
      { t: 1, id: "g-gemp-t01", tipo: "calculo", variaveis: { ab: { valores: [20, 30, 40, 50, 80, 100] }, cp: { min: 5, max: 40 } }, calc: { c: "round(ab*cp/100)" }, resposta: "c/ab*100", tolerancia: 0.1, unidade: "%",
        pergunta: "No teste do MVP, {c} de {ab} clientes abordados compraram. Qual a taxa de conversão (%)? (1 casa)", resolucao: "{c} ÷ {ab} × 100 = {=c/ab*100:1}%", explicacao: "Métrica acionável de validação." },
      { t: 1, id: "g-gemp-q05", tipo: "vf", pergunta: "O MVP deve ser o produto completo, com todas as funcionalidades, para não decepcionar o cliente.", correta: false, explicacao: "É o mínimo necessário para testar a hipótese principal." },
      { t: 2, id: "g-gemp-q06", tipo: "multipla", pergunta: "Quantos blocos tem o Business Model Canvas?", opcoes: ["4", "6", "9", "12"], correta: 2, explicacao: "Segmentos, proposta de valor, canais, relacionamento, receitas, recursos, atividades, parcerias e custos." },
      { t: 2, id: "g-gemp-q07", tipo: "ligar", pergunta: "Ligue o bloco do Canvas ao exemplo:", pares: [["Proposta de valor", "Reduzir o desperdício de doces em 30%"], ["Segmento de clientes", "Confeitarias pequenas"], ["Fontes de receita", "Assinatura mensal"], ["Atividade-chave", "Elaborar o plano de produção semanal"]], explicacao: "Lógica do negócio numa página." },
      { t: 2, id: "g-gemp-q08", tipo: "vf", pergunta: "No Canvas, a estrutura de custos decorre principalmente dos recursos, atividades e parcerias-chave.", correta: true, explicacao: "O lado esquerdo do quadro gera os custos." },
      { t: 3, id: "g-gemp-t02", tipo: "calculo", variaveis: { cf: { min: 3000, max: 20000, passo: 500 }, mc: { min: 100, max: 800, passo: 50 } }, resposta: "ceil(cf/mc)", tolerancia: 0, unidade: "clientes",
        pergunta: "Custos fixos de R$ {cf}/mês e margem de contribuição de R$ {mc} por cliente. Quantos clientes para atingir o equilíbrio?", resolucao: "{cf} ÷ {mc} = {=cf/mc:2} → {=ceil(cf/mc)}", explicacao: "Arredonde para cima." },
      { t: 3, id: "g-gemp-q09", tipo: "multipla", pergunta: "Qual o limite de receita bruta anual da Microempresa (ME) pela LC 123/2006 (valor vigente na última atualização do conteúdo)?", opcoes: ["R$ 81 mil", "R$ 360 mil", "R$ 4,8 milhões", "Sem limite"], correta: 1, explicacao: "EPP: até R$ 4,8 milhões. Confira sempre os valores vigentes." },
      { t: 3, id: "g-gemp-q10", tipo: "vf", pergunta: "Um negócio lucrativo no papel pode falhar por falta de capital de giro.", correta: true, explicacao: "Estoques e prazos a receber consomem caixa." }
    ]
  },

  {
    id: "g-projprod", codigo: "GPRO-7204", nome: "Projeto do Produto", periodo: 8, area: "producao", icone: "📦", creditos: "(3-0-0) 3 créditos", prereq: ["g-ergo"],
    intro: "Do problema do cliente ao produto na linha: o **processo de desenvolvimento de produto (PDP)**, a tradução da voz do cliente (**QFD**), o projeto para **fabricação e montagem (DFM/DFA)**, a análise de riscos (**FMEA**), o **ciclo de vida** e a proteção da propriedade intelectual.",
    topicos: [
      { t: "Processo de desenvolvimento de produto", icone: "🛤️",
        pontos: ["Fases (modelo de referência de Rozenfeld et al.): **planejamento**, **projeto informacional** (requisitos), **conceitual** (soluções), **detalhado**, **preparação da produção** e **lançamento**; depois, acompanhamento e descontinuação.", "**Stage-gate** (Cooper): etapas separadas por portões de decisão (seguir, parar, rever).", "**Funil de desenvolvimento:** muitas ideias entram, poucas viram produto.", "**Engenharia simultânea:** projeto, manufatura, qualidade, compras e marketing trabalham juntos desde o início.", "Grande parte do custo do produto é definida nas fases iniciais do projeto."],
        formulas: [],
        producao: "Envolver a produção cedo evita produtos difíceis de fabricar, retrabalho de projeto e atrasos de lançamento.",
        exemplo: "Novo bombom recheado: a engenharia de produção participa desde o conceito para garantir que a banhadeira e a embalagem atuais consigam processá-lo." },
      { t: "QFD e requisitos", icone: "🏠",
        pontos: ["**Voz do cliente → requisitos técnicos:** o QFD organiza essa tradução.", "**Casa da qualidade:** requisitos do cliente (e pesos) × características de engenharia (com metas), matriz de relações (forte, média, fraca), telhado de correlações e comparação com concorrentes.", "**Importância técnica** = Σ (peso do requisito × intensidade da relação).", "**Kano:** requisitos obrigatórios, de desempenho e de encantamento."],
        formulas: [["Importância técnica = Σ (peso do cliente × relação)", "priorização das características (ex.: relações 9, 3, 1)"]],
        producao: "Priorizar em quais características investir (ex.: resistência da embalagem × custo do material) com base no que o cliente valoriza.",
        exemplo: "Requisitos: “não amassar” (peso 5) e “fácil de abrir” (peso 3). A característica “espessura da caixa” tem relação 9 e 1: importância = 5×9 + 3×1 = **48**." },
      { t: "DFM, DFA e FMEA", icone: "🔧",
        pontos: ["**DFM (projeto para manufatura):** peças fáceis de fabricar com os processos disponíveis, tolerâncias realistas, materiais padronizados.", "**DFA (projeto para montagem):** menos peças, encaixes em vez de parafusos, montagem numa só direção, peças simétricas ou claramente assimétricas (poka-yoke).", "**Padronização e modularidade:** reutilizar componentes e módulos entre produtos (ligação com ATO).", "**FMEA de produto (DFMEA):** modos de falha, efeitos, causas; S, O, D e NPR para priorizar ações."],
        formulas: [["NPR = S × O × D", "priorização no FMEA"], ["Eficiência de montagem (Boothroyd) ≈ 3 s × nº mínimo teórico de peças ÷ tempo total de montagem", "índice de DFA"]],
        producao: "Menos peças significa menos compras, estoque, montagem e defeitos; o engenheiro de produção é voz ativa no DFM/DFA.",
        exemplo: "Tampa com 4 parafusos → tampa com encaixe por pressão: elimina 4 peças e cerca de 20 s de montagem por unidade." },
      { t: "Ciclo de vida e propriedade intelectual", icone: "📈",
        pontos: ["**Ciclo de vida do produto:** introdução, crescimento, maturidade e declínio; volume, custos e estratégia mudam em cada fase.", "Na introdução, flexibilidade; no crescimento, capacidade; na maturidade, custo; no declínio, racionalização.", "**Propriedade intelectual no Brasil (INPI):** patente de invenção (vigência de 20 anos do depósito), modelo de utilidade (15 anos), desenho industrial, marca.", "Prototipagem (inclusive impressão 3D) e testes com usuários reduzem risco.", "Ecodesign: pensar desde o projeto na reciclagem e no descarte."],
        formulas: [],
        producao: "O tipo de processo e o PCP adequados mudam ao longo do ciclo de vida; planejar a capacidade para a fase de crescimento evita faltas.",
        exemplo: "Bombom lançado em edição limitada (introdução): produção em lotes pequenos. Se virar sucesso (crescimento), migra para a linha dedicada." }
    ],
    glossario: [["PDP", "Processo de desenvolvimento de produto."], ["Stage-gate", "Desenvolvimento em etapas com portões de decisão."], ["Engenharia simultânea", "Trabalho integrado das áreas desde o início do projeto."], ["QFD", "Desdobramento da função qualidade."], ["Casa da qualidade", "Matriz do QFD que relaciona requisitos do cliente e características técnicas."], ["Modelo de Kano", "Classificação dos requisitos: obrigatórios, desempenho, encantamento."], ["DFM", "Projeto para manufatura."], ["DFA", "Projeto para montagem."], ["DFMEA", "FMEA de projeto."], ["Ciclo de vida do produto", "Introdução, crescimento, maturidade e declínio."], ["Patente", "Direito de exclusividade sobre uma invenção por prazo determinado."]],
    questoes: [
      { t: 0, id: "g-pprod-q01", tipo: "ordenar", pergunta: "Ordene as fases do desenvolvimento de produto:", itens: ["Planejamento do projeto", "Projeto informacional (requisitos)", "Projeto conceitual", "Projeto detalhado", "Preparação da produção", "Lançamento"], explicacao: "Modelo de referência do PDP." },
      { t: 0, id: "g-pprod-q02", tipo: "vf", pergunta: "Grande parte do custo final de um produto é definida nas fases iniciais do projeto.", correta: true, explicacao: "Mudar depois custa muito mais." },
      { t: 0, id: "g-pprod-q03", tipo: "multipla", pergunta: "O que é engenharia simultânea?", opcoes: ["Fazer vários produtos ao mesmo tempo", "Integrar projeto, manufatura, qualidade, compras e marketing desde o início", "Trabalhar em dois turnos", "Terceirizar o projeto"], correta: 1, explicacao: "Reduz retrabalho e prazo." },
      { t: 1, id: "g-pprod-t01", tipo: "calculo", variaveis: { w1: { min: 1, max: 5 }, w2: { min: 1, max: 5 }, w3: { min: 1, max: 5 }, r1: { valores: [0, 1, 3, 9] }, r2: { valores: [0, 1, 3, 9] }, r3: { valores: [0, 1, 3, 9] } }, resposta: "w1*r1+w2*r2+w3*r3", tolerancia: 0, unidade: "",
        pergunta: "Casa da qualidade: requisitos com pesos {w1}, {w2} e {w3}; relações com uma característica técnica: {r1}, {r2} e {r3}. Qual a importância técnica?", resolucao: "{w1}×{r1} + {w2}×{r2} + {w3}×{r3} = {=w1*r1+w2*r2+w3*r3}", explicacao: "Prioriza as características técnicas." },
      { t: 1, id: "g-pprod-q04", tipo: "ligar", pergunta: "Classifique pelo modelo de Kano (para uma caixa de bombons):", pares: [["Bombons inteiros, sem quebrar", "Obrigatório"], ["Mais sabores na caixa", "Desempenho"], ["Mensagem personalizada inesperada", "Encantamento"]], explicacao: "Obrigatórios não encantam, mas sua falta decepciona muito." },
      { t: 1, id: "g-pprod-q05", tipo: "vf", pergunta: "O QFD traduz a voz do cliente em características técnicas mensuráveis.", correta: true, explicacao: "Casa da qualidade." },
      { t: 2, id: "g-pprod-q06", tipo: "multipla", pergunta: "Qual mudança é típica de DFA (projeto para montagem)?", opcoes: ["Aumentar o número de parafusos", "Substituir parafusos por encaixes e reduzir o número de peças", "Exigir tolerâncias mais apertadas", "Usar mais materiais diferentes"], correta: 1, explicacao: "Menos peças, montagem mais simples." },
      { t: 2, id: "g-pprod-t02", tipo: "calculo", variaveis: { s: { min: 1, max: 10 }, o: { min: 1, max: 10 }, d: { min: 1, max: 10 } }, resposta: "s*o*d", tolerancia: 0, unidade: "",
        pergunta: "DFMEA: severidade {s}, ocorrência {o} e detecção {d}. Qual o NPR?", resolucao: "NPR = {s} × {o} × {d} = {=s*o*d}", explicacao: "Severidade alta merece atenção mesmo com NPR moderado." },
      { t: 2, id: "g-pprod-q07", tipo: "vf", pergunta: "Usar componentes padronizados e módulos comuns a vários produtos reduz estoques e simplifica a produção.", correta: true, explicacao: "Base da estratégia ATO." },
      { t: 3, id: "g-pprod-q08", tipo: "ordenar", pergunta: "Ordene as fases do ciclo de vida do produto:", itens: ["Introdução", "Crescimento", "Maturidade", "Declínio"], explicacao: "Estratégia de operações muda em cada fase." },
      { t: 3, id: "g-pprod-q09", tipo: "multipla", pergunta: "No Brasil, qual a vigência de uma patente de invenção, contada do depósito?", opcoes: ["5 anos", "10 anos", "15 anos", "20 anos"], correta: 3, explicacao: "Modelo de utilidade: 15 anos (INPI)." },
      { t: 3, id: "g-pprod-q10", tipo: "multipla", pergunta: "Na fase de maturidade do produto, a prioridade das operações costuma ser:", opcoes: ["Flexibilidade para mudanças de projeto", "Redução de custo e eficiência", "Criar capacidade urgentemente", "Descontinuar"], correta: 1, explicacao: "Volume estável e concorrência por preço." }
    ]
  },

  {
    id: "g-gproj", codigo: "GPRO-7803", nome: "Gestão de Projetos", periodo: 8, area: "producao", icone: "📅", creditos: "(3-0-0) 3 créditos", prereq: ["g-inteco", "g-custos"], relacionado: ["m02"],
    intro: "Projetos entregam mudanças: nova linha, implantação de ERP, lançamento de produto. A disciplina cobre **escopo e EAP**, **cronograma e caminho crítico**, **PERT**, **custos e valor agregado**, **riscos** e **métodos ágeis**. O Módulo 2 do curso aprofunda em 3 níveis.",
    topicos: [
      { t: "Projeto, escopo e EAP", icone: "🧱",
        pontos: ["**Projeto:** esforço temporário para criar um resultado único; **operação:** contínua e repetitiva.", "**Termo de abertura (TAP):** autoriza o projeto; objetivos, premissas, restrições, patrocinador.", "**EAP (estrutura analítica do projeto):** decomposição do escopo em entregas e pacotes de trabalho.", "Restrição tripla: **escopo, prazo e custo** (com qualidade no centro)."],
        formulas: [],
        producao: "Implantar uma nova linha de bombons é um projeto; a produção diária é operação.",
        exemplo: "EAP da nova linha: 1. Projeto do layout; 2. Compra de equipamentos; 3. Instalação; 4. Treinamento; 5. Partida (ramp-up)." },
      { t: "Cronograma, caminho crítico e PERT", icone: "🗓️",
        pontos: ["Atividades, durações e **precedências** formam a rede do projeto.", "**Caminho crítico:** maior caminho da rede; atividades com **folga zero**; qualquer atraso atrasa o projeto.", "**Folga total** = LS − ES (início mais tarde − início mais cedo).", "**PERT:** tₑ = (a + 4m + b) ÷ 6; σ = (b − a) ÷ 6.", "**Compressão:** crashing (mais recursos) e fast tracking (atividades em paralelo)."],
        formulas: [["tₑ = (a + 4m + b) ÷ 6", "duração esperada (PERT)"], ["σ = (b − a) ÷ 6", "desvio-padrão da atividade"], ["Folga = LS − ES", "folga total"]],
        producao: "Saber o caminho crítico mostra onde concentrar esforço para não atrasar a partida da linha.",
        exemplo: "a = 4, m = 6, b = 14 dias: tₑ = (4 + 24 + 14) ÷ 6 = **7 dias**; σ = 10 ÷ 6 ≈ **1,67 dia**." },
      { t: "Custos e valor agregado (EVM)", icone: "💵",
        pontos: ["**PV** (valor planejado), **EV** (valor agregado = orçamento do que foi feito), **AC** (custo real).", "**CPI** = EV ÷ AC (< 1: acima do orçamento); **SPI** = EV ÷ PV (< 1: atrasado).", "**EAC** (estimativa no término) ≈ BAC ÷ CPI (se o desempenho continuar igual).", "Curva S de custos acumulados."],
        formulas: [["CPI = EV ÷ AC", "desempenho de custo"], ["SPI = EV ÷ PV", "desempenho de prazo"], ["EAC = BAC ÷ CPI", "estimativa no término"]],
        producao: "Acompanhar o projeto da nova linha com números objetivos, não com “está quase pronto”.",
        exemplo: "PV = 100, EV = 80, AC = 100: CPI = **0,8** e SPI = **0,8** ⇒ acima do custo e atrasado." },
      { t: "Riscos e métodos ágeis", icone: "⚡",
        pontos: ["**Risco:** evento incerto que afeta objetivos (ameaça ou oportunidade).", "Identificar → analisar (probabilidade × impacto) → planejar respostas (evitar, transferir, mitigar, aceitar) → monitorar.", "**Valor monetário esperado** do risco = probabilidade × impacto.", "**Ágil (Manifesto, 2001):** entregas incrementais e adaptação a mudanças; **Scrum** (sprints, product owner, scrum master, time) e **Kanban** (limite de WIP, fluxo).", "Híbrido: planejamento preditivo para obras e equipamentos, ágil para software e melhorias."],
        formulas: [["VME do risco = probabilidade × impacto", "priorização e reserva de contingência"]],
        producao: "Atraso do fornecedor da banhadeira é risco de alto impacto: mitigar com cláusulas, acompanhamento e plano B.",
        exemplo: "Risco com 20% de chance e impacto de R$ 50 mil: VME = **R$ 10 mil** (considerar na reserva de contingência)." }
    ],
    glossario: [["Projeto", "Esforço temporário para criar um resultado único."], ["TAP", "Termo de abertura do projeto."], ["EAP", "Estrutura analítica do projeto."], ["Caminho crítico", "Sequência de atividades com folga zero que define a duração."], ["Folga total", "Quanto uma atividade pode atrasar sem atrasar o projeto."], ["PERT", "Técnica de estimativa com três durações."], ["EVM", "Gerenciamento do valor agregado."], ["CPI", "Índice de desempenho de custo."], ["SPI", "Índice de desempenho de prazo."], ["Scrum", "Framework ágil com sprints e papéis definidos."]],
    questoes: [
      { t: 0, id: "g-gpro-q01", tipo: "ligar", pergunta: "Classifique:", pares: [["Implantar uma nova linha de produção", "Projeto"], ["Produzir bombons todos os dias", "Operação"], ["Implantar um ERP", "Projeto"]], explicacao: "Temporário e único × contínuo e repetitivo." },
      { t: 0, id: "g-gpro-q02", tipo: "multipla", pergunta: "Qual documento autoriza formalmente o início do projeto?", opcoes: ["EAP", "Termo de abertura (TAP)", "Cronograma", "Ata de encerramento"], correta: 1, explicacao: "Com objetivos, premissas e patrocinador." },
      { t: 0, id: "g-gpro-q03", tipo: "vf", pergunta: "A EAP decompõe o escopo do projeto em entregas e pacotes de trabalho.", correta: true, explicacao: "Base para cronograma e custos." },
      { t: 1, id: "g-gpro-t01", tipo: "calculo", variaveis: { a: { min: 2, max: 6 }, m: { min: 6, max: 10 }, b: { min: 11, max: 20 } }, resposta: "(a+4*m+b)/6", tolerancia: 0.01, unidade: "dias",
        pergunta: "PERT: otimista {a}, mais provável {m}, pessimista {b} dias. Qual a duração esperada? (2 casas)", resolucao: "tₑ = ({a} + 4×{m} + {b}) ÷ 6 = {=(a+4*m+b)/6:2} dias (σ = {=(b-a)/6:2})", explicacao: "Média ponderada da distribuição beta." },
      { t: 1, id: "g-gpro-q04", tipo: "vf", pergunta: "Atividades do caminho crítico têm folga total zero.", correta: true, explicacao: "Qualquer atraso atrasa o projeto." },
      { t: 1, id: "g-gpro-q05", tipo: "ligar", pergunta: "Ligue a técnica de compressão à descrição:", pares: [["Crashing", "Acrescentar recursos para reduzir a duração"], ["Fast tracking", "Fazer atividades em paralelo"]], explicacao: "Crashing aumenta custo; fast tracking aumenta risco." },
      { t: 2, id: "g-gpro-t02", tipo: "calculo", variaveis: { pv: { min: 80, max: 200, passo: 10 }, evp: { valores: [0.7, 0.8, 0.9, 1, 1.1] }, acp: { valores: [0.8, 0.9, 1, 1.1, 1.25] } }, calc: { ev: "round(pv*evp)", ac: "round(pv*evp*acp)" }, resposta: "ev/ac", tolerancia: 0.01, unidade: "",
        pergunta: "PV = {pv}, EV = {ev}, AC = {ac} (R$ mil). Qual o CPI? (2 casas)", resolucao: "CPI = {ev} ÷ {ac} = {=ev/ac:2} (SPI = {=ev/pv:2})", explicacao: "CPI < 1: gastando mais do que o planejado para o que foi feito." },
      { t: 2, id: "g-gpro-q06", tipo: "multipla", pergunta: "SPI = 0,85 indica que o projeto está:", opcoes: ["Adiantado", "Atrasado", "Abaixo do custo", "Encerrado"], correta: 1, explicacao: "Entregou 85% do que deveria até agora." },
      { t: 2, id: "g-gpro-q07", tipo: "vf", pergunta: "Se o CPI se mantiver, a estimativa no término é o orçamento total dividido pelo CPI.", correta: true, explicacao: "EAC = BAC ÷ CPI." },
      { t: 3, id: "g-gpro-t03", tipo: "calculo", variaveis: { p: { valores: [5, 10, 20, 30, 40, 50] }, imp: { min: 10, max: 200, passo: 10 } }, resposta: "p/100*imp", tolerancia: 0.01, unidade: "R$ mil",
        pergunta: "Risco com probabilidade de {p}% e impacto de R$ {imp} mil. Qual o valor monetário esperado (R$ mil)?", resolucao: "{=p/100} × {imp} = {=p/100*imp:2}", explicacao: "Soma dos VME ajuda a dimensionar a reserva de contingência." },
      { t: 3, id: "g-gpro-q08", tipo: "ligar", pergunta: "Ligue a resposta ao risco ao exemplo:", pares: [["Evitar", "Mudar o plano para eliminar a causa"], ["Transferir", "Contratar seguro ou cláusula contratual"], ["Mitigar", "Reduzir probabilidade ou impacto"], ["Aceitar", "Conviver com o risco, com contingência"]], explicacao: "Respostas a ameaças." },
      { t: 3, id: "g-gpro-q09", tipo: "multipla", pergunta: "No Scrum, quem prioriza o backlog do produto?", opcoes: ["Scrum master", "Product owner", "Time de desenvolvimento", "Cliente final diretamente"], correta: 1, explicacao: "O scrum master facilita o processo." }
    ]
  }
);
