/* =====================================================================
   GRADE CURRICULAR — 9º E 10º PERÍODOS (formato: veja grade/p01.js)
   Exemplos numéricos são ILUSTRATIVOS (criados para ensino).
   ===================================================================== */
(window.DISCIPLINAS = window.DISCIPLINAS || []).push(
  {
    id: "g-pcp2", codigo: "GPRO-7822", nome: "Planejamento e Controle da Produção II", periodo: 9, area: "producao", icone: "🎛️", creditos: "(4-0-0) 4 créditos", prereq: ["g-pcp1"], relacionado: ["m03", "m06"],
    intro: "A segunda parte do PCP vai do plano ao chão de fábrica: **capacidade** (RCCP e CRP), **sequenciamento e programação**, **controle da produção** e os **sistemas de coordenação** (MRP, kanban, CONWIP, tambor-pulmão-corda, APS). Módulos 3 e 6 do curso aprofundam os temas.",
    topicos: [
      { t: "Capacidade: RCCP e CRP", icone: "🏋️",
        pontos: ["Capacidade **projetada, efetiva e realizada**; utilização = realizada ÷ projetada; eficiência = realizada ÷ efetiva (definições de Slack).", "**Carga** = Σ (quantidade × tempo padrão); ocupação = carga ÷ capacidade.", "**RCCP:** verificação grosseira do PMP nos recursos críticos.", "**CRP:** verificação detalhada das ordens do MRP por centro de trabalho e período.", "Ajustes: capacidade (hora extra, turno, terceirização) ou carga (antecipar, adiar, mudar o mix)."],
        formulas: [["Carga = Σ qᵢ × tpᵢ", "horas necessárias"], ["Ocupação = carga ÷ capacidade × 100%", "acima de 100% = sobrecarga"]],
        producao: "Um plano que não cabe na capacidade vira atraso e urgência; verificar antes de liberar as ordens evita isso.",
        exemplo: "500 × 0,3 h + 200 × 0,5 h = 250 h de carga para 240 h de capacidade: ocupação ≈ **104%**." },
      { t: "Sequenciamento e programação", icone: "🔢",
        pontos: ["Regras de prioridade: **PEPS**, **MTP (SPT)**, **DD (EDD)**, razão crítica.", "Numa máquina: MTP minimiza o **tempo médio de fluxo**; DD minimiza o **maior atraso**.", "**Johnson** (duas máquinas em série): minimiza o makespan.", "**Gráfico de Gantt** para visualizar a programação.", "Setups dependentes da sequência (ex.: chocolate branco antes do amargo) mudam a melhor ordem."],
        formulas: [["Tempo de fluxo = término − liberação", "tempo no sistema"], ["Atraso = máx(0; término − data de entrega)", "tardiness"]],
        producao: "Mudar só a sequência reduz atrasos e WIP sem investimento; na indústria de alimentos, a ordem de sabores reduz limpezas.",
        exemplo: "Ordens com tempos 2, 3, 6 e 8 h pela regra MTP: términos 2, 5, 11, 19 ⇒ fluxo médio = **9,25 h**." },
      { t: "Controle da produção", icone: "📊",
        pontos: ["Controlar = medir, comparar com o plano, analisar causas e agir.", "Indicadores: **aderência ao programa**, **OTIF**, **WIP**, **lead time**, ocupação do gargalo, acuracidade de estoque.", "**Lei de Little:** WIP = taxa × lead time.", "Apontamento confiável (MES, coletores) é pré-requisito.", "Rotina: reunião diária de produção, reunião semanal de PCP, S&OP mensal."],
        formulas: [["Aderência = ordens concluídas no prazo ÷ ordens programadas", "cumprimento do programa"], ["OTIF = pedidos no prazo e completos ÷ total", "nível de serviço"], ["Lead time = WIP ÷ taxa", "lei de Little"]],
        producao: "Sem controle, o plano vira intenção; indicadores mostram onde o sistema falha (material, máquina, prioridade).",
        exemplo: "180 ordens no prazo de 200 programadas: aderência de **90%**." },
      { t: "Sistemas de coordenação da produção", icone: "🔀",
        pontos: ["**MRP/MRP II:** empurra pelo plano; bom para estruturas complexas e demanda irregular.", "**Kanban:** puxa pelo consumo; bom para itens repetitivos e demanda estável.", "**CONWIP:** limita o WIP total da linha; simples para alta variedade.", "**Tambor-pulmão-corda (TOC):** o gargalo (tambor) dita o ritmo, um pulmão de tempo o protege e a corda controla a liberação de material.", "**APS:** programação com capacidade finita e otimização, integrada ao ERP/MES."],
        formulas: [["N = D × L × (1 + α) ÷ C", "número de kanbans"]],
        producao: "Muitas fábricas usam híbridos: MRP para compras de longo prazo, kanban no chão de fábrica e DBR no gargalo.",
        exemplo: "Demanda de 400 peças/h, reposição em 0,5 h, margem de 10%, 20 por caixa ⇒ **11 kanbans**." }
    ],
    glossario: [["RCCP", "Verificação grosseira de capacidade do PMP."], ["CRP", "Verificação detalhada de capacidade das ordens do MRP."], ["Carga", "Horas necessárias para cumprir o plano."], ["MTP (SPT)", "Menor tempo de processamento primeiro."], ["DD (EDD)", "Menor data de entrega primeiro."], ["Regra de Johnson", "Sequenciamento ótimo para duas máquinas em série."], ["Aderência ao programa", "Proporção das ordens concluídas conforme o programado."], ["OTIF", "Entregas no prazo e completas."], ["CONWIP", "Sistema puxado com WIP total constante."], ["Tambor-pulmão-corda", "Programação pela Teoria das Restrições."], ["APS", "Sistema avançado de planejamento e programação."]],
    questoes: [
      { t: 0, id: "g-pcp2-t01", tipo: "calculo", variaveis: { qx: { min: 200, max: 600, passo: 20 }, tx: { valores: [0.2, 0.25, 0.3, 0.4] }, qy: { min: 100, max: 400, passo: 20 }, ty: { valores: [0.4, 0.5, 0.6] }, cap: { valores: [160, 200, 240, 280] } }, condicao: "(qx*tx+qy*ty)/cap >= 0.7 && (qx*tx+qy*ty)/cap <= 1.3",
        resposta: "(qx*tx+qy*ty)/cap*100", tolerancia: 0.1, unidade: "%", pergunta: "Plano: {qx} × {tx} h e {qy} × {ty} h; capacidade de {cap} h. Qual a ocupação (%)? (1 casa)", resolucao: "Carga = {=qx*tx+qy*ty:2} h; ocupação = {=(qx*tx+qy*ty)/cap*100:1}%", explicacao: "Acima de 100%: ajuste carga ou capacidade." },
      { t: 0, id: "g-pcp2-q01", tipo: "ligar", pergunta: "Ligue a verificação ao nível de detalhe:", pares: [["RCCP", "Grosseira, sobre o PMP, recursos críticos"], ["CRP", "Detalhada, sobre as ordens do MRP, por centro de trabalho"]], explicacao: "Primeiro o grosseiro, depois o detalhado." },
      { t: 0, id: "g-pcp2-q02", tipo: "vf", pergunta: "Adiar ordens para períodos com folga é uma forma de ajustar a carga à capacidade.", correta: true, explicacao: "Assim como antecipar (gerando estoque)." },
      { t: 1, id: "g-pcp2-t02", tipo: "calculo", variaveis: { pt: { lista: 4, min: 1, max: 9 } }, calc: { o: "ordenar(pt)" }, resposta: "(4*o[0]+3*o[1]+2*o[2]+o[3])/4", tolerancia: 0.01, unidade: "h",
        pergunta: "Quatro ordens (tempos {pt} h), todas disponíveis em t = 0. Pela regra MTP, qual o tempo médio de fluxo (h)? (2 casas)", resolucao: "Ordem MTP: {o}\nMédia = {=(4*o[0]+3*o[1]+2*o[2]+o[3])/4:2} h", explicacao: "MTP minimiza o fluxo médio numa máquina." },
      { t: 1, id: "g-pcp2-q03", tipo: "multipla", pergunta: "Qual regra minimiza o maior atraso numa única máquina?", opcoes: ["PEPS", "MTP", "DD (menor data de entrega)", "Maior tempo primeiro"], correta: 2, explicacao: "Regra de Jackson." },
      { t: 1, id: "g-pcp2-q04", tipo: "vf", pergunta: "A regra de Johnson se aplica a duas máquinas em série com todas as ordens passando na mesma sequência.", correta: true, explicacao: "Minimiza o makespan." },
      { t: 2, id: "g-pcp2-t03", tipo: "calculo", variaveis: { prog: { valores: [100, 150, 200, 250] }, ader: { min: 70, max: 99 } }, calc: { ok: "round(prog*ader/100)" }, resposta: "ok/prog*100", tolerancia: 0.1, unidade: "%",
        pergunta: "{ok} de {prog} ordens programadas foram concluídas no prazo. Qual a aderência ao programa (%)? (1 casa)", resolucao: "{ok} ÷ {prog} × 100 = {=ok/prog*100:1}%", explicacao: "Analise as causas das ordens não cumpridas (Pareto)." },
      { t: 2, id: "g-pcp2-q05", tipo: "multipla", pergunta: "Pela lei de Little, com a mesma taxa de produção, reduzir o WIP pela metade:", opcoes: ["Dobra o lead time", "Reduz o lead time pela metade", "Não muda nada", "Zera a produção"], correta: 1, explicacao: "Lead time = WIP ÷ taxa." },
      { t: 2, id: "g-pcp2-q06", tipo: "vf", pergunta: "OTIF mede a proporção de pedidos entregues no prazo e completos.", correta: true, explicacao: "On time, in full." },
      { t: 3, id: "g-pcp2-q07", tipo: "ligar", pergunta: "Ligue o sistema à lógica:", pares: [["MRP", "Empurra pelo plano"], ["Kanban", "Puxa pelo consumo"], ["CONWIP", "Limita o WIP total da linha"], ["Tambor-pulmão-corda", "O gargalo dita o ritmo"]], explicacao: "Sistemas de coordenação da produção." },
      { t: 3, id: "g-pcp2-t04", tipo: "calculo", variaveis: { dem: { min: 100, max: 600, passo: 20 }, lt: { valores: [0.25, 0.5, 1, 2] }, mg: { valores: [0, 0.1, 0.2] }, cx: { valores: [10, 20, 25, 50] } }, resposta: "ceil(dem*lt*(1+mg)/cx)", tolerancia: 0, unidade: "kanbans",
        pergunta: "Demanda de {dem} peças/h, reposição em {lt} h, margem de {=mg*100}%, {cx} peças por contêiner. Quantos kanbans?", resolucao: "N = {dem} × {lt} × {=1+mg} ÷ {cx} = {=dem*lt*(1+mg)/cx:2} → {=ceil(dem*lt*(1+mg)/cx)}", explicacao: "Arredonde para cima." },
      { t: 3, id: "g-pcp2-q08", tipo: "multipla", pergunta: "No tambor-pulmão-corda, o que é o “pulmão”?", opcoes: ["O estoque de produto acabado", "Uma proteção de tempo/material antes do gargalo", "O próprio gargalo", "O sistema ERP"], correta: 1, explicacao: "Evita que o gargalo pare por falta de material." }
    ]
  },

  {
    id: "g-gestr", codigo: "GPRO-7741", nome: "Gestão Estratégica", periodo: 9, area: "gestao", icone: "♟️", creditos: "(3-0-0) 3 créditos", prereq: ["g-projorg"],
    intro: "Estratégia é escolher **onde competir e como vencer**. A disciplina cobre missão e visão, **análise externa** (PESTEL, 5 forças de Porter), **análise interna** (cadeia de valor, VRIO), **SWOT**, **estratégias genéricas**, **estratégia de operações** e a execução com **BSC e OKR**.",
    topicos: [
      { t: "Direção estratégica e análise externa", icone: "🌍",
        pontos: ["**Missão** (razão de existir), **visão** (aonde chegar), **valores** (como agir).", "**PESTEL:** fatores políticos, econômicos, sociais, tecnológicos, ecológicos (ambientais) e legais.", "**Cinco forças de Porter:** rivalidade entre concorrentes, ameaça de novos entrantes, ameaça de substitutos, poder de barganha dos fornecedores e dos compradores.", "Quanto mais fortes as forças, menor a rentabilidade média do setor."],
        formulas: [],
        producao: "Fornecedores concentrados (cacau, embalagens) têm poder de barganha: afeta custos e exige estratégias de suprimento.",
        exemplo: "Chocolates: rivalidade alta, substitutos (outros doces), grandes redes de varejo com forte poder de compra → pressão sobre preço e prazos." },
      { t: "Análise interna, SWOT e estratégias genéricas", icone: "🧭",
        pontos: ["**Cadeia de valor (Porter):** atividades primárias (logística de entrada, operações, logística de saída, marketing e vendas, serviços) e de apoio.", "**VRIO:** recursos valiosos, raros, difíceis de imitar e organizados geram vantagem sustentável.", "**SWOT:** forças e fraquezas (internas) × oportunidades e ameaças (externas); cruzamentos geram estratégias.", "**Estratégias genéricas (Porter):** liderança em custo, diferenciação e foco (em custo ou em diferenciação).", "“Meio-termo” sem posicionamento claro tende a ter desempenho fraco."],
        formulas: [],
        producao: "Liderança em custo exige operações muito eficientes; diferenciação exige qualidade, flexibilidade e inovação — a estratégia define o que as operações priorizam.",
        exemplo: "Doces Serra: força = receita artesanal; oportunidade = mercado de presentes premium ⇒ estratégia de **foco com diferenciação**." },
      { t: "Estratégia de operações", icone: "🏭",
        pontos: ["**Skinner (1969):** a manufatura pode ser arma competitiva ou um peso; há **trade-offs** (fábrica focada).", "**Objetivos de desempenho:** qualidade, rapidez, confiabilidade, flexibilidade e custo.", "**Critérios ganhadores de pedido × qualificadores** (Hill): qualificadores são o mínimo para competir; ganhadores fazem o cliente escolher você.", "Áreas de decisão: capacidade, instalações, tecnologia, integração vertical, organização, qualidade, PCP.", "Alinhamento: decisões de operações coerentes com a estratégia do negócio."],
        formulas: [],
        producao: "O engenheiro de produção traduz a estratégia em decisões de capacidade, processo, estoques e tecnologia.",
        exemplo: "Para presentes premium, qualidade e aparência são **ganhadores**; prazo de entrega confiável no Natal é **qualificador**." },
      { t: "Execução: BSC, OKR e indicadores", icone: "🎯",
        pontos: ["**Balanced Scorecard (Kaplan e Norton):** quatro perspectivas — financeira, clientes, processos internos, aprendizado e crescimento.", "**Mapa estratégico:** relações de causa e efeito entre objetivos das perspectivas.", "**OKR:** objetivos qualitativos + resultados-chave mensuráveis, ciclos curtos (ex.: trimestrais).", "**KPIs SMART:** específicos, mensuráveis, atingíveis, relevantes e com prazo.", "Desdobramento (hoshin): da estratégia às metas das áreas."],
        formulas: [["Atingimento do KR = (valor atual − inicial) ÷ (meta − inicial)", "progresso de um resultado-chave"]],
        producao: "Indicadores de operações (OEE, OTIF, custo por unidade, acidentes) aparecem na perspectiva de processos internos e sustentam os resultados financeiros.",
        exemplo: "Objetivo: “ser referência em entrega no Natal”. KR: OTIF de 88% → 97% até dezembro. Hoje em 94%: progresso = 6 ÷ 9 ≈ **67%**." }
    ],
    glossario: [["Missão", "Razão de existir da organização."], ["Visão", "Situação futura desejada."], ["PESTEL", "Análise de fatores políticos, econômicos, sociais, tecnológicos, ecológicos e legais."], ["Cinco forças", "Modelo de Porter da atratividade do setor."], ["Cadeia de valor", "Atividades que criam valor na empresa (Porter)."], ["VRIO", "Valor, raridade, imitabilidade, organização."], ["SWOT", "Forças, fraquezas, oportunidades e ameaças."], ["Estratégias genéricas", "Custo, diferenciação e foco."], ["Critério ganhador de pedido", "Fator que faz o cliente escolher a empresa."], ["Critério qualificador", "Requisito mínimo para ser considerado pelo cliente."], ["BSC", "Balanced Scorecard."], ["OKR", "Objetivos e resultados-chave."]],
    questoes: [
      { t: 0, id: "g-gest-q01", tipo: "ligar", pergunta: "Ligue a força de Porter ao exemplo:", pares: [["Poder dos compradores", "Grandes redes de supermercado negociando preço"], ["Poder dos fornecedores", "Poucos fornecedores de cacau"], ["Ameaça de substitutos", "Consumidores trocando chocolate por outros doces"], ["Novos entrantes", "Marca estrangeira entrando no país"]], explicacao: "Mais a rivalidade entre concorrentes." },
      { t: 0, id: "g-gest-q02", tipo: "multipla", pergunta: "Uma nova lei de rotulagem de alimentos entra em qual fator do PESTEL?", opcoes: ["Econômico", "Legal", "Tecnológico", "Social"], correta: 1, explicacao: "Também tem componente político." },
      { t: 0, id: "g-gest-q03", tipo: "vf", pergunta: "Quanto mais intensas as cinco forças num setor, menor tende a ser a rentabilidade média das empresas desse setor.", correta: true, explicacao: "Pressão sobre preços e custos." },
      { t: 1, id: "g-gest-q04", tipo: "ligar", pergunta: "Classifique no SWOT da Doces Serra:", pares: [["Receita artesanal reconhecida", "Força"], ["Linha antiga com muitas paradas", "Fraqueza"], ["Crescimento do mercado de presentes premium", "Oportunidade"], ["Alta do preço do cacau", "Ameaça"]], explicacao: "Forças e fraquezas são internas; oportunidades e ameaças, externas." },
      { t: 1, id: "g-gest-q05", tipo: "multipla", pergunta: "Qual estratégia genérica exige operações extremamente eficientes e grande escala?", opcoes: ["Diferenciação", "Liderança em custo", "Foco em diferenciação", "Nenhuma"], correta: 1, explicacao: "Custos menores que os concorrentes." },
      { t: 1, id: "g-gest-q06", tipo: "vf", pergunta: "Pelo VRIO, um recurso valioso mas fácil de imitar gera vantagem competitiva sustentável.", correta: false, explicacao: "Gera, no máximo, vantagem temporária." },
      { t: 2, id: "g-gest-q07", tipo: "ligar", pergunta: "Classifique (mercado de presentes premium):", pares: [["Aparência e qualidade excepcionais", "Ganhador de pedido"], ["Segurança do alimento e rotulagem correta", "Qualificador"], ["Entrega confiável antes do Natal", "Qualificador"]], explicacao: "Qualificadores não vencem sozinhos, mas sua falta elimina a empresa." },
      { t: 2, id: "g-gest-q08", tipo: "multipla", pergunta: "A ideia de “fábrica focada” (Skinner) se baseia em:", opcoes: ["Fazer tudo muito bem ao mesmo tempo", "Trade-offs: concentrar a fábrica em poucos objetivos de desempenho", "Aumentar a variedade sem limite", "Terceirizar tudo"], correta: 1, explicacao: "Uma fábrica não é a melhor em tudo." },
      { t: 2, id: "g-gest-q09", tipo: "vf", pergunta: "As decisões de capacidade, tecnologia e estoques devem ser coerentes com a estratégia competitiva da empresa.", correta: true, explicacao: "Alinhamento estratégico das operações." },
      { t: 3, id: "g-gest-q10", tipo: "ordenar", pergunta: "Ordene as perspectivas do BSC da base (causas) para o topo (resultados):", itens: ["Aprendizado e crescimento", "Processos internos", "Clientes", "Financeira"], explicacao: "Pessoas e sistemas → processos → clientes → finanças." },
      { t: 3, id: "g-gest-t01", tipo: "calculo", variaveis: { ini: { valores: [80, 85, 88] }, meta: { valores: [95, 97, 98] }, prog: { valores: [0.2, 0.4, 0.5, 0.6, 0.75] } }, calc: { atual: "arred(ini+(meta-ini)*prog,1)" }, resposta: "(atual-ini)/(meta-ini)*100", tolerancia: 0.5, unidade: "%",
        pergunta: "KR: OTIF de {ini}% para {meta}%. Hoje está em {atual}%. Qual o progresso do KR (%)? (inteiro)", resolucao: "({atual} − {ini}) ÷ ({meta} − {ini}) × 100 = {=(atual-ini)/(meta-ini)*100:0}%", explicacao: "OKRs medem o avanço em relação à meta." },
      { t: 3, id: "g-gest-q11", tipo: "multipla", pergunta: "Qual é um KPI SMART?", opcoes: ["Melhorar a qualidade", "Reduzir o refugo da linha 2 de 4% para 2% até junho", "Ser o melhor", "Trabalhar mais"], correta: 1, explicacao: "Específico, mensurável, atingível, relevante e com prazo." }
    ]
  },

  {
    id: "g-logist", codigo: "GPRO-7814", nome: "Logística", periodo: 9, area: "producao", icone: "🚛", creditos: "(4-0-0) 4 créditos", prereq: ["g-po2", "g-pcp1"],
    intro: "Logística leva o produto certo, na quantidade certa, ao lugar certo, no tempo certo, com o menor custo total. A disciplina trata da **cadeia de suprimentos**, **gestão de estoques** (ABC, lote econômico, ponto de pedido, estoque de segurança), **armazenagem**, **transporte** e **nível de serviço**.",
    topicos: [
      { t: "Cadeia de suprimentos", icone: "🔗",
        pontos: ["Fluxos de **materiais** (fornecedor → cliente), **informação** e **dinheiro** (em sentido contrário).", "**Efeito chicote:** a variação da demanda se amplifica a montante (causas: previsões isoladas, lotes grandes, promoções, racionamento).", "Mitigação: compartilhar dados de demanda real, reduzir lotes e lead times, preços estáveis, VMI (estoque gerenciado pelo fornecedor).", "**Custo total** logístico: transporte + estoque + armazenagem + processamento de pedidos + falta.", "Trade-offs: menos estoque × mais transporte rápido, e assim por diante."],
        formulas: [["Amplificação = variância dos pedidos ÷ variância da demanda", "medida do efeito chicote"]],
        producao: "O PCP depende dos fornecedores; compartilhar a demanda real com eles reduz faltas e estoques em toda a cadeia.",
        exemplo: "O varejo vende 100 ± 10 caixas/semana, mas pede à fábrica entre 50 e 200: a fábrica enxerga uma demanda muito mais variável do que a real." },
      { t: "Gestão de estoques", icone: "📦",
        pontos: ["Funções do estoque: proteger contra incertezas, desacoplar etapas, aproveitar lotes e sazonalidade.", "**Curva ABC:** poucos itens (A) concentram a maior parte do valor; controle mais rigoroso neles.", "**Lote econômico (LEC):** Q* = √(2DS/H) equilibra custo de pedir e de manter.", "**Ponto de pedido:** PP = demanda média no lead time + estoque de segurança.", "**Estoque de segurança:** ES = z·σ_d·√LT (demanda variável, lead time fixo)."],
        formulas: [["Q* = √(2·D·S ÷ H)", "lote econômico"], ["PP = d̄ · LT + ES", "ponto de pedido"], ["ES = z · σ_d · √LT", "estoque de segurança"]],
        producao: "Dimensionar estoques de matéria-prima e embalagens para não parar a linha, sem imobilizar capital demais.",
        exemplo: "d̄ = 200 caixas/dia, σ_d = 40, LT = 4 dias, 95% (z = 1,65): ES = 1,65 × 40 × 2 = **132**; PP = 800 + 132 = **932 caixas**." },
      { t: "Armazenagem e movimentação", icone: "🏬",
        pontos: ["Atividades: recebimento, conferência, endereçamento, armazenagem, separação (picking), expedição.", "**WMS** controla endereços e movimentos; **código de barras** e **RFID** aumentam acuracidade.", "Regras de saída: **PEPS/FIFO** (primeiro que entra) e **FEFO** (primeiro que vence — essencial em alimentos).", "**Endereçamento por giro:** itens de alta saída perto da expedição (curva ABC de movimentação).", "Estruturas: porta-paletes, drive-in, flow rack; equipamentos: empilhadeiras, paleteiras, transelevadores."],
        formulas: [["Taxa de ocupação = posições ocupadas ÷ posições totais", "uso do armazém"], ["Produtividade de picking = linhas separadas ÷ hora", "desempenho da separação"]],
        producao: "Em alimentos, FEFO evita vencimentos; endereçar por giro reduz deslocamentos na separação.",
        exemplo: "Bombons com validade: sai primeiro o lote que vence antes (**FEFO**), mesmo que tenha entrado depois." },
      { t: "Transporte e nível de serviço", icone: "🚚",
        pontos: ["Modais: **rodoviário** (flexível, dominante no Brasil), **ferroviário** e **aquaviário** (grandes volumes, baixo custo por t·km), **aéreo** (rápido e caro), **dutoviário**.", "Custos: fixos (veículo, motorista) e variáveis (combustível, pedágio); **consolidação** de cargas reduz o custo por unidade.", "**Roteirização:** sequência de entregas que minimiza distância/tempo (problemas de roteamento de veículos).", "**Nível de serviço:** OTIF, prazo, taxa de atendimento (fill rate), avarias.", "**Logística reversa:** retorno de embalagens, produtos e resíduos."],
        formulas: [["Custo por unidade = custo da viagem ÷ unidades transportadas", "efeito da consolidação"], ["Fill rate = quantidade atendida ÷ quantidade pedida", "nível de serviço"]],
        producao: "Programar a produção pensando nas janelas de coleta e na formação de cargas completas reduz o custo logístico.",
        exemplo: "Viagem de R$ 1.800: com 600 caixas, R$ 3,00/caixa; com 1.200 caixas (carga completa), **R$ 1,50/caixa**." }
    ],
    glossario: [["Cadeia de suprimentos", "Rede de empresas do fornecedor ao cliente final."], ["Efeito chicote", "Amplificação da variação da demanda ao longo da cadeia."], ["VMI", "Estoque gerenciado pelo fornecedor."], ["Curva ABC", "Classificação de itens pela importância (valor)."], ["Lote econômico", "Quantidade que minimiza custos de pedir e manter."], ["Ponto de pedido", "Nível de estoque que dispara a reposição."], ["Estoque de segurança", "Proteção contra variações da demanda e do lead time."], ["FEFO", "Primeiro que vence, primeiro que sai."], ["WMS", "Sistema de gestão de armazém."], ["Picking", "Separação de itens para os pedidos."], ["Fill rate", "Proporção da quantidade pedida que foi atendida."], ["Logística reversa", "Fluxo de retorno de produtos, embalagens e resíduos."]],
    questoes: [
      { t: 0, id: "g-log-q01", tipo: "multipla", pergunta: "Qual é uma causa do efeito chicote?", opcoes: ["Compartilhar dados de venda real", "Pedidos em lotes grandes e promoções frequentes", "Lotes pequenos e frequentes", "Preços estáveis"], correta: 1, explicacao: "Distorcem o sinal da demanda." },
      { t: 0, id: "g-log-q02", tipo: "vf", pergunta: "O custo logístico total deve ser analisado em conjunto, pois reduzir um custo (ex.: estoque) pode aumentar outro (ex.: transporte urgente).", correta: true, explicacao: "Trade-offs logísticos." },
      { t: 0, id: "g-log-q03", tipo: "multipla", pergunta: "No VMI (vendor managed inventory), quem decide a reposição do estoque do cliente?", opcoes: ["O cliente", "O fornecedor, com base nos dados de consumo do cliente", "O transportador", "O banco"], correta: 1, explicacao: "Reduz o efeito chicote." },
      { t: 1, id: "g-log-t01", tipo: "calculo", variaveis: { d: { min: 50, max: 400, passo: 10 }, sd: { min: 10, max: 80, passo: 5 }, lt: { valores: [1, 4, 9] }, z: { valores: [1.28, 1.65, 2.05, 2.33] } }, resposta: "d*lt+z*sd*sqrt(lt)", tolerancia: 0.5, unidade: "unidades",
        pergunta: "Demanda média de {d}/dia, desvio-padrão diário de {sd}, lead time de {lt} dia(s), z = {z}. Qual o ponto de pedido? (inteiro)", resolucao: "ES = {z} × {sd} × √{lt} = {=z*sd*sqrt(lt):0}\nPP = {d} × {lt} + {=z*sd*sqrt(lt):0} = {=d*lt+z*sd*sqrt(lt):0}", explicacao: "z maior = nível de serviço maior = mais estoque de segurança." },
      { t: 1, id: "g-log-t02", tipo: "calculo", variaveis: { d: { min: 5000, max: 50000, passo: 1000 }, s: { valores: [50, 100, 150, 200] }, h: { valores: [1, 2, 2.5, 4, 5] } }, resposta: "sqrt(2*d*s/h)", tolerancia: 1, unidade: "unidades",
        pergunta: "D = {d}/ano; custo por pedido S = R$ {s}; custo de manter H = R$ {h}/unidade·ano. Qual o lote econômico? (inteiro)", resolucao: "Q* = √(2 × {d} × {s} ÷ {h}) = {=sqrt(2*d*s/h):0}", explicacao: "No ótimo, custo de pedir = custo de manter." },
      { t: 1, id: "g-log-q04", tipo: "vf", pergunta: "Na curva ABC, os itens A são poucos, mas concentram a maior parte do valor e merecem controle mais rigoroso.", correta: true, explicacao: "Princípio de Pareto." },
      { t: 2, id: "g-log-q05", tipo: "multipla", pergunta: "Para produtos perecíveis como bombons, qual regra de saída do estoque é mais adequada?", opcoes: ["UEPS", "FEFO (primeiro que vence)", "Aleatória", "Maior lote primeiro"], correta: 1, explicacao: "Evita vencimentos." },
      { t: 2, id: "g-log-q06", tipo: "multipla", pergunta: "Onde endereçar os itens de maior giro no armazém?", opcoes: ["No fundo, longe da expedição", "Perto da expedição e em alturas de fácil acesso", "No nível mais alto", "Tanto faz"], correta: 1, explicacao: "Reduz deslocamentos no picking." },
      { t: 2, id: "g-log-q07", tipo: "vf", pergunta: "Código de barras e RFID ajudam a aumentar a acuracidade do estoque.", correta: true, explicacao: "Reduzem erros de digitação e conferência." },
      { t: 3, id: "g-log-t03", tipo: "calculo", variaveis: { v: { min: 800, max: 3000, passo: 100 }, u: { valores: [300, 400, 600, 800, 1200] } }, resposta: "v/u", tolerancia: 0.01, unidade: "R$/caixa",
        pergunta: "Uma viagem custa R$ {v} e leva {u} caixas. Qual o custo de frete por caixa? (2 casas)", resolucao: "{v} ÷ {u} = R$ {=v/u:2}", explicacao: "Consolidar cargas reduz o custo por unidade." },
      { t: 3, id: "g-log-q08", tipo: "ligar", pergunta: "Ligue o modal à característica:", pares: [["Rodoviário", "Flexível, porta a porta"], ["Ferroviário", "Grandes volumes, baixo custo por t·km"], ["Aéreo", "Muito rápido e caro"], ["Dutoviário", "Fluxo contínuo de líquidos e gases"]], explicacao: "Escolha pelo produto, volume, prazo e custo." },
      { t: 3, id: "g-log-q09", tipo: "multipla", pergunta: "Um cliente pediu 1.000 caixas e recebeu 950. Qual o fill rate?", opcoes: ["50%", "95%", "105%", "100%"], correta: 1, explicacao: "950 ÷ 1.000." }
    ]
  },

  {
    id: "g-tcc", codigo: "GPRO-7808 / GPRO-7809", nome: "Projeto Final I e II (TCC)", periodo: 9, area: "producao", icone: "🎓", creditos: "(0-4-0) 2 + (0-4-0) 2 créditos", prereq: ["g-metcie"],
    intro: "O projeto final integra o curso num trabalho autoral: um **problema real de Engenharia de Produção**, resolvido com **método**, **dados** e **ferramentas** das disciplinas, documentado e defendido. Projeto Final I costuma focar no problema, na revisão e no método; o II, na execução, nos resultados e na defesa.",
    topicos: [
      { t: "Escolha do tema e do problema", icone: "🎯",
        pontos: ["Bom tema: **relevante**, **viável** (acesso a dados e empresa, prazo), com **interesse pessoal** e ligado às áreas da Engenharia de Produção.", "Transformar tema em **problema de pesquisa** (pergunta) e **objetivos** (geral e específicos).", "Delimitar: onde, quando, qual processo, qual indicador.", "Fontes de temas: estágio, empresa júnior, iniciação científica, problemas da comunidade.", "Alinhar com o orientador desde o início."],
        formulas: [],
        producao: "Temas típicos: redução de setup (SMED), balanceamento de linha, previsão de demanda, layout, OEE, simulação, gestão de estoques, ergonomia, custos.",
        exemplo: "Tema amplo “Lean na indústria” → problema: “Como reduzir o tempo de setup da banhadeira da empresa X em pelo menos 40%?”" },
      { t: "Revisão da literatura e método", icone: "📚",
        pontos: ["**Revisão da literatura:** o que já se sabe; conceitos e trabalhos semelhantes; bases como Portal CAPES, SciELO, Scopus.", "Escolher o **método de pesquisa**: estudo de caso, pesquisa-ação, modelagem e simulação, survey, experimento.", "Planejar a **coleta de dados**: o quê, como, quando, quanto (amostra), com que instrumento.", "Considerar ética (consentimento, confidencialidade da empresa, LGPD).", "Normas ABNT para citações e referências."],
        formulas: [],
        producao: "O método do TCC é o mesmo raciocínio dos projetos de melhoria: medir a situação atual, analisar causas, propor, testar e medir o resultado.",
        exemplo: "Pesquisa-ação: filmar e cronometrar 10 setups (antes), aplicar SMED com a equipe, medir mais 10 setups (depois)." },
      { t: "Execução, análise e escrita", icone: "✍️",
        pontos: ["Cronograma com marcos e entregas parciais ao orientador (evite deixar tudo para o fim).", "Analisar os dados com as ferramentas adequadas (estatística, simulação, indicadores).", "**Resultados e discussão:** comparar com os objetivos e com a literatura; reconhecer limitações.", "Estrutura: introdução, referencial, método, resultados e discussão, conclusão, referências.", "Escrita clara e objetiva: frases curtas, figuras e tabelas numeradas e citadas no texto."],
        formulas: [["Ganho (%) = (antes − depois) ÷ antes × 100", "forma comum de apresentar resultados de melhoria"]],
        producao: "Resultados quantificados (antes × depois) e discutidos com honestidade fortalecem o trabalho e o currículo.",
        exemplo: "Setup médio de 62 min antes e 34 min depois ⇒ redução de **45%**, com a limitação de apenas 3 semanas de acompanhamento." },
      { t: "Apresentação e defesa", icone: "🎤",
        pontos: ["Slides limpos: problema, objetivo, método, principais resultados, conclusão.", "Tempo: ensaie; em geral cerca de 1 slide por minuto.", "Antecipe perguntas da banca: limitações, generalização, escolha do método, confiabilidade dos dados.", "Responda com calma; reconheça o que não foi feito e sugira trabalhos futuros.", "Depois da aprovação: versão final com correções e entrega nos prazos da instituição."],
        formulas: [],
        producao: "Saber apresentar resultados para uma banca é a mesma habilidade de apresentar um projeto para a diretoria.",
        exemplo: "Uma apresentação de 20 minutos com cerca de 15 a 20 slides, focada no que foi feito e nos números." }
    ],
    glossario: [["Problema de pesquisa", "Pergunta que o trabalho pretende responder."], ["Objetivo geral", "O que o trabalho pretende alcançar como um todo."], ["Objetivos específicos", "Etapas mensuráveis para atingir o objetivo geral."], ["Revisão da literatura", "Síntese do conhecimento existente sobre o tema."], ["Estudo de caso", "Investigação aprofundada de um caso no seu contexto."], ["Pesquisa-ação", "Pesquisa em que o pesquisador participa da intervenção."], ["Limitações", "Restrições do estudo que afetam as conclusões."], ["Banca", "Comissão que avalia o trabalho."]],
    questoes: [
      { t: 0, id: "g-tcc-q01", tipo: "multipla", pergunta: "Qual destes é um problema de pesquisa bem delimitado?", opcoes: ["Estudar o Lean", "Como reduzir em 40% o tempo de setup da banhadeira da empresa X até dezembro?", "Melhorar a indústria brasileira", "Qualidade"], correta: 1, explicacao: "Específico, mensurável e com contexto." },
      { t: 0, id: "g-tcc-q02", tipo: "vf", pergunta: "A viabilidade (acesso a dados e prazo) é um critério importante na escolha do tema.", correta: true, explicacao: "Tema ótimo sem dados não vira TCC." },
      { t: 0, id: "g-tcc-q03", tipo: "ligar", pergunta: "Ligue o tema de TCC à área da Engenharia de Produção:", pares: [["Balanceamento de linha", "Engenharia de operações/métodos"], ["Previsão de demanda", "PCP"], ["Análise ergonômica de posto", "Engenharia do trabalho"], ["Viabilidade de um investimento", "Engenharia econômica"]], explicacao: "Os temas conectam as áreas da ABEPRO." },
      { t: 1, id: "g-tcc-q04", tipo: "multipla", pergunta: "O pesquisador participa da implantação do SMED na empresa e mede os resultados. Qual o método?", opcoes: ["Survey", "Pesquisa-ação", "Revisão bibliográfica", "Experimento em laboratório"], correta: 1, explicacao: "Participação na mudança estudada." },
      { t: 1, id: "g-tcc-q05", tipo: "vf", pergunta: "Dados de uma empresa podem exigir cuidados de confidencialidade e, se envolverem pessoas, de proteção de dados pessoais.", correta: true, explicacao: "Ética e LGPD." },
      { t: 1, id: "g-tcc-q06", tipo: "multipla", pergunta: "Para que serve a revisão da literatura?", opcoes: ["Aumentar o número de páginas", "Mostrar o que já se sabe, fundamentar conceitos e posicionar o trabalho", "Copiar trabalhos anteriores", "Substituir a coleta de dados"], correta: 1, explicacao: "Base teórica e comparação dos resultados." },
      { t: 2, id: "g-tcc-t01", tipo: "calculo", variaveis: { antes: { min: 40, max: 120, passo: 2 }, red: { min: 15, max: 60 } }, calc: { depois: "round(antes*(1-red/100))" }, resposta: "(antes-depois)/antes*100", tolerancia: 0.1, unidade: "%",
        pergunta: "Setup médio antes: {antes} min; depois: {depois} min. Qual a redução (%)? (1 casa)", resolucao: "({antes} − {depois}) ÷ {antes} × 100 = {=(antes-depois)/antes*100:1}%", explicacao: "Apresente também as limitações da medição." },
      { t: 2, id: "g-tcc-q07", tipo: "vf", pergunta: "Reconhecer as limitações do estudo enfraquece o TCC e deve ser evitado.", correta: false, explicacao: "Mostra rigor e honestidade intelectual." },
      { t: 2, id: "g-tcc-q08", tipo: "ordenar", pergunta: "Ordene a estrutura textual do TCC:", itens: ["Introdução", "Referencial teórico", "Método", "Resultados e discussão", "Conclusão"], explicacao: "Seguida das referências." },
      { t: 3, id: "g-tcc-q09", tipo: "multipla", pergunta: "Numa apresentação de 20 minutos, o ideal é:", opcoes: ["60 slides cheios de texto", "Cerca de 15 a 20 slides objetivos, focados em problema, método e resultados", "Ler o trabalho inteiro", "Não usar slides"], correta: 1, explicacao: "Menos texto, mais resultados." },
      { t: 3, id: "g-tcc-q10", tipo: "vf", pergunta: "Diante de uma pergunta difícil da banca, é melhor reconhecer o limite do trabalho e sugerir estudos futuros do que inventar uma resposta.", correta: true, explicacao: "Honestidade acadêmica." }
    ]
  },

  {
    id: "g-anorg", codigo: "GPRO-7827", nome: "Análise Organizacional", periodo: 10, area: "gestao", icone: "🔬", creditos: "(3-0-0) 3 créditos",
    intro: "Como diagnosticar uma organização e conduzir mudanças: **modelos de diagnóstico**, **teorias organizacionais**, **cultura e poder**, **mudança organizacional** e **aprendizagem**. É a disciplina que fecha a visão de gestão do engenheiro de produção, útil para liderar transformações (Lean, ERP, reestruturações).",
    topicos: [
      { t: "Teorias organizacionais", icone: "📚",
        pontos: ["**Clássicas:** administração científica, teoria clássica, burocracia (eficiência, estrutura, regras).", "**Relações humanas e comportamental:** pessoas, grupos, motivação, decisão (racionalidade limitada — Simon).", "**Sistêmica:** organização como sistema aberto que troca com o ambiente.", "**Contingencial:** não há uma única melhor forma; a estrutura adequada depende do ambiente, da tecnologia e do tamanho.", "**Institucional:** organizações se parecem porque buscam legitimidade (isomorfismo); **visão baseada em recursos**."],
        formulas: [],
        producao: "Entender por que uma prática “de sucesso” numa empresa pode falhar em outra (contingência, cultura, legitimidade) evita copiar soluções sem adaptar.",
        exemplo: "Uma startup em mercado turbulento funciona melhor com estrutura orgânica; uma usina com processo estável e riscos altos, com estrutura mais mecanicista." },
      { t: "Diagnóstico organizacional", icone: "🩺",
        pontos: ["Objetivo: entender o funcionamento atual e as causas dos problemas antes de intervir.", "**Modelo 7S (McKinsey):** estratégia, estrutura, sistemas, valores compartilhados, estilo, pessoas (staff) e habilidades — precisam estar alinhados.", "**Seis caixas (Weisbord):** propósitos, estrutura, relacionamentos, recompensas, liderança e mecanismos de apoio.", "Fontes: entrevistas, questionários de clima, observação, documentos, indicadores.", "Diagnóstico participativo aumenta a adesão às mudanças."],
        formulas: [],
        producao: "Antes de implantar Lean ou um ERP, diagnosticar estrutura, sistemas de recompensa e liderança evita barreiras previsíveis.",
        exemplo: "A empresa quer trabalho em equipe (estratégia), mas remunera só o desempenho individual (sistemas): desalinhamento no 7S." },
      { t: "Cultura, poder e conflito", icone: "⚔️",
        pontos: ["**Cultura** (Schein): artefatos, valores declarados e pressupostos básicos; muda devagar.", "**Poder:** capacidade de influenciar; fontes como posição, especialização, recompensa, coerção, relacionamento.", "**Política organizacional:** negociação de interesses; parte normal da vida das organizações.", "**Conflito:** pode ser destrutivo ou produtivo; estilos de gestão de conflito (competir, colaborar, ceder, evitar, acomodar).", "Stakeholders internos com interesses diferentes (produção × vendas × finanças)."],
        formulas: [],
        producao: "O conflito clássico produção × vendas (prazos, mix) se resolve melhor com processos integrados (S&OP) e objetivos comuns do que com disputa de poder.",
        exemplo: "Vendas quer muitas variações de produto; produção quer lotes grandes. O S&OP transforma a disputa em decisão baseada em custo e serviço." },
      { t: "Mudança e aprendizagem organizacional", icone: "🔁",
        pontos: ["**Lewin:** descongelar → mudar → recongelar.", "**Kotter (8 passos):** senso de urgência, coalizão, visão, comunicação, remover obstáculos, vitórias rápidas, consolidar, ancorar na cultura.", "**Aprendizagem organizacional (Argyris):** circuito **simples** (corrige o erro) × **duplo** (questiona as premissas que geraram o erro).", "**Senge:** organização que aprende — pensamento sistêmico, domínio pessoal, modelos mentais, visão compartilhada e aprendizagem em equipe.", "Sustentar a mudança exige padrões, indicadores e liderança."],
        formulas: [],
        producao: "Programas de melhoria contínua (kaizen, A3) são mecanismos de aprendizagem organizacional; sem “recongelar” (padronizar), a mudança regride.",
        exemplo: "Circuito simples: refazer o lote com defeito. Circuito duplo: questionar por que a meta de volume incentiva liberar lotes sem inspeção." }
    ],
    glossario: [["Teoria contingencial", "A melhor estrutura depende do ambiente, tecnologia e tamanho."], ["Isomorfismo", "Tendência de organizações se tornarem semelhantes (teoria institucional)."], ["Racionalidade limitada", "Decisões com informação e capacidade cognitiva limitadas (Simon)."], ["Modelo 7S", "Estrutura de diagnóstico da McKinsey com 7 elementos."], ["Seis caixas", "Modelo de diagnóstico de Weisbord."], ["Cultura organizacional", "Pressupostos e valores compartilhados."], ["Poder", "Capacidade de influenciar comportamentos e decisões."], ["Modelo de Lewin", "Descongelar, mudar e recongelar."], ["Aprendizagem de circuito duplo", "Aprendizagem que questiona as premissas (Argyris)."], ["Organização que aprende", "Organização que desenvolve continuamente a capacidade de aprender (Senge)."]],
    questoes: [
      { t: 0, id: "g-anor-q01", tipo: "ligar", pergunta: "Ligue a abordagem à ideia central:", pares: [["Contingencial", "Não há uma única melhor forma de organizar"], ["Sistêmica", "Organização como sistema aberto"], ["Institucional", "Busca de legitimidade leva à semelhança entre organizações"], ["Comportamental", "Racionalidade limitada nas decisões"]], explicacao: "Teorias organizacionais." },
      { t: 0, id: "g-anor-q02", tipo: "vf", pergunta: "Pela teoria contingencial, uma estrutura mais orgânica tende a funcionar melhor em ambientes instáveis.", correta: true, explicacao: "Ambientes estáveis favorecem estruturas mais mecanicistas." },
      { t: 0, id: "g-anor-q03", tipo: "multipla", pergunta: "Copiar uma prática de gestão só porque “as grandes empresas usam” é explicado por qual teoria?", opcoes: ["Administração científica", "Teoria institucional (isomorfismo)", "Teoria das filas", "Relações humanas"], correta: 1, explicacao: "Busca de legitimidade." },
      { t: 1, id: "g-anor-q04", tipo: "multipla", pergunta: "Qual modelo de diagnóstico usa estratégia, estrutura, sistemas, valores compartilhados, estilo, pessoas e habilidades?", opcoes: ["Seis caixas de Weisbord", "7S da McKinsey", "Cinco forças", "BSC"], correta: 1, explicacao: "Os 7 elementos precisam estar alinhados." },
      { t: 1, id: "g-anor-q05", tipo: "caso", contexto: "A diretoria lançou um programa de trabalho em equipe, mas o bônus continua baseado apenas no desempenho individual.", pergunta: "Qual o diagnóstico?", opcoes: ["Tudo alinhado", "Desalinhamento entre estratégia e sistemas de recompensa", "Falta de tecnologia", "Excesso de treinamento"], correta: 1, explicacao: "As pessoas seguem o que é recompensado." },
      { t: 1, id: "g-anor-q06", tipo: "vf", pergunta: "Diagnosticar a organização antes de intervir ajuda a identificar causas dos problemas e barreiras à mudança.", correta: true, explicacao: "Evita soluções que não atacam a causa." },
      { t: 2, id: "g-anor-q07", tipo: "ligar", pergunta: "Ligue a fonte de poder ao exemplo:", pares: [["Posição (legítimo)", "Cargo de gerente"], ["Especialização", "Técnico que domina a máquina crítica"], ["Recompensa", "Quem decide bônus e promoções"], ["Relacionamento (referência)", "Colega admirado e ouvido por todos"]], explicacao: "O poder não vem só do cargo." },
      { t: 2, id: "g-anor-q08", tipo: "multipla", pergunta: "O conflito entre vendas (mais variedade) e produção (lotes grandes) é melhor tratado por:", opcoes: ["Decisão unilateral de quem tem mais poder", "Processo integrado com critérios comuns, como o S&OP", "Evitar o assunto", "Demitir um dos gerentes"], correta: 1, explicacao: "Transforma disputa em decisão baseada em dados." },
      { t: 2, id: "g-anor-q09", tipo: "vf", pergunta: "A cultura organizacional costuma mudar rapidamente com um único comunicado da diretoria.", correta: false, explicacao: "Pressupostos básicos mudam devagar, com práticas consistentes." },
      { t: 3, id: "g-anor-q10", tipo: "ordenar", pergunta: "Ordene as etapas do modelo de Lewin:", itens: ["Descongelar", "Mudar", "Recongelar"], explicacao: "Recongelar = padronizar e sustentar." },
      { t: 3, id: "g-anor-q11", tipo: "multipla", pergunta: "Questionar as metas e premissas que levaram ao erro, e não só corrigi-lo, é aprendizagem de:", opcoes: ["Circuito simples", "Circuito duplo", "Memorização", "Nenhuma"], correta: 1, explicacao: "Argyris." },
      { t: 3, id: "g-anor-q12", tipo: "multipla", pergunta: "Qual é o primeiro passo do modelo de mudança de Kotter?", opcoes: ["Ancorar na cultura", "Criar senso de urgência", "Celebrar vitórias", "Comprar tecnologia"], correta: 1, explicacao: "Depois: coalizão, visão, comunicação…" }
    ]
  }
);
